### ISSUE TITLE
FFplay to RTMP

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#1000]
From this [demo](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/WebRTCtoFfplay) application we can view the stream using FFplay (`ffplay -probesize 32 -protocol_whitelist "file,rtp,udp" -i ffplay.sdp`). Is it possible to redirect the stream to RTMP url?

**Comment by sipsorcery** [comment]
Not with ffplay but possibly with ffmpeg.

Here's what ChatGPT gave me:

`ffmpeg -i [input_stream] -c copy -f flv rtmp://[RTMP_endpoint]`
