### ISSUE TITLE
Simulcast Video Display Issue with SipSorcery in Janus Media Server Setup

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#1006]
We are currently encountering an issue with our video setup using the Janus media server, and I'd appreciate your expertise in helping us resolve it.

Here's a breakdown of our scenario:

1. Client A: An iOS device equipped with simulcast support. This device publishes video to Janus, making decisions based on simulcast.
2. Client B: An Android device, which does not support simulcast.
3. Client C: A Windows desktop device running SipSorcery, also without simulcast support.

When all these clients join a video room:
- Client A is able to view video feeds from both Client B and Client C.
- Client B can also display videos from Client A and Client C.
- However, Client C only manages to display the video from Client B and fails to show the video from Client A.

For your reference, all participants are utilizing the VP8 video codec.

Could you provide some insights into what might be causing this issue? Your assistance will be greatly appreciated.

**Comment by mail2mhossain** [comment]
Feedback from Janus Regarding Video Stream Issues:

I wanted to share some feedback we received from the Janus team regarding the video stream issue we discussed.

After running their tests using the same process (text2pcap, pcap2mjr, janus-pp-rec), they were able to obtain a playable video, indicating that the video stream is in good condition. However, they did point out that the playback speed is notably fast, reminiscent of the comedic "Benny Hill" speed. They're uncertain if this speed is due to the encoding from the publisher's end.

Nevertheless, the key takeaway is that the RTP video stream is functioning correctly. This suggests that the underlying issue might lie with SipSorcery.

**Comment by sipsorcery** [comment]
We never got to the lofty heights of [supporting mutliple audio](https://github.com/sipsorcery-org/sipsorcery/blob/f157b072c059c9d1bff17cd979facdc08419fdf5/src/net/RTP/RTPSession.cs#L229) or video streams.
