### ISSUE TITLE
RTCPeerConnection Reconnection Mechanism in a SipSorcery

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#1014]
We are currently utilizing SipSorcery in conjunction with a Janus server to manage our communications. We have observed that in instances where the internet connection is interrupted, the WebSocket connection with the Janus server is consequently lost. Fortunately, a reconnection mechanism is in place which effectively attempts to re-establish the connection to the Janus server, and has been performing optimally. It has been noted that reconnection is successful even if the internet connectivity is restored within a 25-second timeframe.

We are now turning our attention to the RTCPeerConnection and are keen to understand if a similar reconnection mechanism is implemented within it. Your insights on whether there is a connection retry system embedded in RTCPeerConnection, and any additional information on how it operates would be immensely valuable.

**Comment by sipsorcery** [comment]
Do you get any [DTLS alert log messages](https://github.com/sipsorcery-org/sipsorcery/blob/f157b072c059c9d1bff17cd979facdc08419fdf5/src/net/WebRTC/RTCPeerConnection.cs#L1717C9-L1717C9) in the application using the sipsorcery library?

By the time the DTLS alert gets from the BouncyCastle DTLS client/server to the sipsorcery RTCPeerConnection the DTLS session has already been closed and the state (encryption keys etc.) cleared. There's no way to restore a session after that.

**Comment by sipsorcery** [comment]
Answer is no, there is no reconnectino mechanism in the library but you could always catch the close event in your app and retry.
