### ISSUE TITLE
Implement nack for SipSorcery

### ISSUE THREAD

**Issue by 29654761** [sipsorcery-org/sipsorcery#1018]
I want to try to Implement nack by myself,  but I encountered a problem
My current approach is

For receiver:
1. Call MediaStream.UseBuffer 
2. Handle the OnRtpPacketReceived event
3. Check the rtp sequence number to determine if packets was lost
4. Call SendRtcpFeedback
This seems feasible

But for sender:
1. Handle the OnReceiveReport event
2. Received feedback nack packet
3. Problem is no temporary sent packets queue, I can't resend the lost packet

Solution：
MediaStream.SendRtpRaw can raise a event so we can save the sent packets
Because people usually use eg. MediaStream.SendH264Frame to send data

**Comment by sipsorcery** [comment]
> Problem is no temporary sent packets queue, I can't resend the lost packet

Yes, there's a LOT of work to do. The queue would need to be implemented as well.

This library was originally written for SIP signalling. The additional bits to do with RTP, RTCP, devices, encoding, codecs etc. have been bolted on afterwards and there are still lots of gaps.
