### ISSUE TITLE
Mic not working in debian

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#1020]
@sipsorcery 
In FFmpegFileAndDevicesTest, I tried to capture mic. With this basic ffmpeg command `ffmpeg -f alsa -i hw:0,1 output.wav` I was able to capture the audio. But when I used the same `hw:0,1` in the FFmpegFileAndDevicesTest at this line `static private string MicrophoneDevicePath = "hw:0,1"; ` I get error as **Segmentation fault**. I also tried with **default, hw:0**. Nothing works.

What causes this error? Is there a way to solve it.

**Comment by nodminger** [comment]
I get this at the beginning of the program
![image](https://github.com/sipsorcery-org/sipsorcery/assets/128209987/bc61f628-a51e-4de8-81eb-bdaaa82cc8e1)
But still I get error as Segmentation Fault.

**Comment by nodminger** [comment]
I am working on Debian in VirtualBox. Can this be a reason for this issue?

**Comment by sipsorcery** [comment]
That's likely to be an ffmpeg issue rather than a sipsorcery one. If it's still a problem I'd suggest trying a basic ffmpeg console app to access the audio device and if/when that works wire it up to sipsorcery.
