### ISSUE TITLE
Send video to SIPUserAgent

### ISSUE THREAD

**Issue by deus82ex** [sipsorcery-org/sipsorcery#1021]
Hi,

I have a windows service establishing a call to a SIPUserAgent. Voice call is working fine.
But I need to send a Video/Image which I have in form of a byte array.
How can I accomplish this task?

regards
Mario

**Comment by sipsorcery** [comment]
The SIP softphone example can send/receive video. [This](https://github.com/sipsorcery-org/sipsorcery/blob/401ce75b3c7d0187e851c4466811acffe194b332/examples/Softphone/Softphone.xaml.cs#L608C9-L608C9) might ehlp you get started.
