### ISSUE TITLE
Suggestion to reduce observability concerns from using a shared static logger

### ISSUE THREAD

**Issue by grondinjc** [sipsorcery-org/sipsorcery#1023]
Hello, 

As most of the loggers of the lib are built using [the static logger](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/sys/Log.cs#L33C9-L33C39), I currently have problems enabling some sections of logs using debug severity while not being flooded by all the other logs from the lib...

My current choise is to either enable "sipsorcery" globally in debug, or to enable a log severity a little bit less verbose.

I was curious on what you would think about introducing an alternate way to get loggers, involving something similar to : 
```c#
        public static ILogger GetLogger<T>() => SIPSorcery.LogFactory.CreateLogger<T>();
```
```c#
        public static ILogger<T> GetLogger<T>() => SIPSorcery.LogFactory.CreateLogger<T>();
```

Key differences : 
- Loggers could be per-instance instead of static.
- Associated source would vary according to the class namespaces (such as "SIPSorcery.Net" for the RTCPeerConnection") instead of "sipsorcery".
![image](https://github.com/sipsorcery-org/sipsorcery/assets/5757055/3c001bfc-8371-492b-8f11-eabbcf9a9261)
- This could introduce usage of type-specific loggers, such as `ILogger<RTCPeerConnection>` instead of a plain `ILogger`
- (biggest value) This would allow to enable logs from the lib to be enable with a more tight control based on namespaces.

What do you think ?
Would you accept such transitive change in the library ?

**Comment by ChristopheI** [comment]
It's a good idea and it's very valuable.
It will be appreciate to have this kind of PR.

**Comment by grondinjc** [comment]
Good news 😁

Here are some follow up questions regarding the upcoming change : 
- Some classes define their `ILogger` as a `static`. I would see value into gradually changing those into per-instance loggers. Such change would allow to be a bit more resilient to Static logger being defined I some classes followed by the static LoggerFactory being set. It would make the impact of having a global shared mutable variable (the static `ILoggerFactory`) a bit less cumbersome.
- Namespace-wise, I observed inconsistencies across the lib. Given the RtpIceChannel under filepath `src/net/ICE/RtpIceChannel.cs` has namespace `SIPSorcery.Net`, I would see value in more segmentation in namespaces such as having `SIPSorcery.Net.ICE` (or `SIPSorcery.net.ICE`). Along with my initial suggestion, it would allow to enable some logs in specific parts of the Lib. This would allow to responds to usecases like : I want debug logs on all ICE and DtlsSrtp related code, Info on all SCTP, Warning on all the rest. However, this namespace change would be a break. 

What do you think ?

**Comment by ChristopheI** [comment]
> * Some classes define their `ILogger` as a `static`. I would see value into gradually changing those into per-instance loggers.
Seems good. 
How do you configure the logger to have log entries of the first instance of SIPSorcery in one file / config , and the second instance in another one ?

> * Namespace-wise, I observed inconsistencies across the lib. 
It's a good point too but as you said it will break the way to use this package. So please avoid it as much as possible

**Comment by grondinjc** [comment]
> How do you configure the logger to have log entries of the first instance of SIPSorcery in one file / config , and the second instance in another one ?

Since there is a mutable `ILoggerFactory`, we can leverage tools such as NLog or Serilog to provide such loggerFactory. From those respective tools, specific configuration could tell to do : 
- Write logs under targets "SIPSorcery.net" having warning or error in file app.errors.logs.
- Write logs under targets "SIPSorcery.core" having warning or error in file app.sip.errors.logs 
- ... and so on.

It becomes consumer specific.

The biggest improvement of my suggestion is that all logs will NOT be emitted from the same logger, meaning that they will be generated from different source contexts. Having such in place will allow consumer to define more flexible nlog/serilog configuration to isolate the logs they want.

The first part requires to be able to build typed loggers 😊
https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/pull/6

**Comment by sipsorcery** [comment]
PR merged.
