### ISSUE TITLE
How to view content of RTCPeerConnection?

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#1029]
I am using this to create Peer Connection `var pc = new RTCPeerConnection(config);`. On printing this using `Console.WriteLine(pc)` I get **SIPSorcery.Net.RTCPeerConnection** instead of getting the actual content of Peer Connection. I also tried using **.ToString()**. Is there a way to print content of **pc**?

**Comment by sipsorcery** [comment]
You could use `JsonSerializer.Serialize` if you just want to dump all the properties to the console/log output.
