### ISSUE TITLE
Video lags after few minutes and high memory consumption

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#1042]
I am using [FFmpeg File and Device Test](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/tree/master/test/FFmpegFileAndDevicesTest) to share my screen. It works perfectly fine initially, but after a few minutes, there is some lag—between 1-3 seconds, and very rarely, it becomes 5 seconds. Also, the application consumes a significant amount of memory, always hovering around 180 MB or more(200 MB+ some times). I am using .NET v6. Is there a way to solve these issues? Is anyone else facing the same issues as me?

**Comment by sbarrac** [comment]
I've had a very similar experience with both issues.

The memory usage is due to some non ideal memory management in the RTPPeerconnection.SendView & SendAudio methods. The byte arrays are being copied many times per call, due to byte arrays not being resizable.

I'm having the same issue with latency in video streams. As far as I can tell, it's due to the chrome jitter buffer detecting that the video stream is unstable so it starts to buffer it, however this is even happening on Localhost. I believe this is due to some issues with exceptions being thrown on a background thread somehow causing some jitter in the stream. When the latency starts increasing, check the output window in visual studio, look for either an exception being thrown or a thread exiting.

**Comment by nodminger** [comment]
> I've had a very similar experience with both issues.
> 
> The memory usage is due to some non ideal memory management in the RTPPeerconnection.SendView & SendAudio methods. The byte arrays are being copied many times per call, due to byte arrays not being resizable.
> 
> I'm having the same issue with latency in video streams. As far as I can tell, it's due to the chrome jitter buffer detecting that the video stream is unstable so it starts to buffer it, however this is even happening on Localhost. I believe this is due to some issues with exceptions being thrown on a background thread somehow causing some jitter in the stream. When the latency starts increasing, check the output window in visual studio, look for either an exception being thrown or a thread exiting.

Yes, I am getting "Exceptions" and some "threads are exiting"

```
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
The thread 0x2434 has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
The thread 0x2cbc has exited with code 0 (0x0).
The thread 0x1d64 has exited with code 0 (0x0).
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
The thread 0x5a54 has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
The thread 0x6344 has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
The thread 0x5944 has exited with code 0 (0x0).
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
The thread 0x3da0 has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
The thread 0x4af0 has exited with code 0 (0x0).
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
The thread 0x4d7c has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
The thread 0x5410 has exited with code 0 (0x0).
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
Exception thrown: 'System.ApplicationException' in SIPSorcery.dll
The thread 0x1b00 has exited with code 0 (0x0).
```

**Comment by sipsorcery** [comment]
There is unoubtedly some optimisation that can be done in the video frame buffers but depending on the throughput requirements it still may not get anywhere near what's required.

The biggest problem is anywhere the native-to-managed boundary is crossed, e.g. Win32 to .NET, there's a big performance hit. The sipsorcery library is an attempt to implement as much of the WebRTC stack as possible in .NET. AFAIK there's still no direct .NET API for video/audio devices on Windows and I've never seen anything from M$ in the last 23 years of .Net Framewrok/.NET that indicates this is likely to change.

Ao long story short if you need performance your best option is to use C++ & libwebrtc. The next best option would to try and finds a .NET libwebrtc wrapper and hope that it has an option to keep the media->srtp pipeline fully native. I don't know if the latter option exists.
