### ISSUE TITLE
WebRtc MediaStreamTrack `Stop & Mute` feature

### ISSUE THREAD

**Issue by MrAliSalehi** [sipsorcery-org/sipsorcery#1046]
Hi There
I'm looking for a way to simulate the `Mute` and `Stop` options in my MediaStream, something like this:

```csharp
public class MediaStreamTrack : IObserverInterface
{
    private bool _ended;
    private bool _enabled;
    private readonly IMediaStreamTrackInterface _track;
    private MediaStreamTrack(IMediaStreamTrackInterface track)
    {
        _track = track;
        _track.RegisterObserver(this);
    }
    public static MediaStreamTrack Create(IMediaStreamTrackInterface track) => new(track);

    public void OnChanged()
    {
        if (_track.State == IMediaStreamTrackInterface.TrackState.Ended)
            Stop();
    }

    public bool IsMuted() => _ended ? !_enabled : !_track.Enabled;

    public void Mute(bool muted)
    {
        if (_ended)
            _enabled = !muted;
        else
            _track.Enabled = !muted;
    }
    public IMediaStreamTrackInterface Track() => _track;

    public void OnPeerConnectionClosed() => Stop();
    private void Stop()
    {
        _track.UnregisterObserver(this);
        _ended = true;
        _enabled = _track.Enabled;
    }
}
```
_this code was taken from a similar implementation of WebRtc in CPP and was translated into C#, as a simple prototype_

any Ideas? Thanks!

**Comment by sipsorcery** [comment]
The sofphone sample has examples of putting audi and video streams on and off hold see [here](https://github.com/sipsorcery-org/sipsorcery/blob/1a2c2f675ed7d7bc4886c6144cd7ecb1808fe87a/examples/Softphone/Signalling/SIPClient.cs#L217C11-L217C11).

**Comment by MrAliSalehi** [comment]
is there any way to do it from the MediaStreamTrack? and I thought SIPAgent wasn't for webrtc stuff, interesting

**Comment by sipsorcery** [comment]
Whoops, you're correct. Disregard the softphone & SIP agent angle.

You can't do if from the MediaStreamTrack, instead you can do if from the IVideoSource or IAudioSource, that get connected to the MediaStreamTrack, using their Pause and Resume methods. See [here](https://github.com/sipsorcery-org/sipsorcery/blob/1a2c2f675ed7d7bc4886c6144cd7ecb1808fe87a/examples/WebRTCExamples/WebRTCGetStarted/Program.cs#L85) for how that connection is made.

Only works for your locally added streams. For remote streams it is theoretically possible to send a new SDP offer with the sendrecv attribute set to sendonly but that behaviour has not been extensively tested with this library.
