### ISSUE TITLE
Getting distorted image after converting RawImage to System.Drawing.Bitmap

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#1049]
We are currently utilizing SipSorcery in conjunction with a Janus server to manage our communications.

When I am converting the RawImage of Publisher's Camera feed (Directly from SIPSorceryMedia.FFmpeg) got from event OnVideoSourceRawSampleFaster to System.Drawing.Bitmap image = new Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, rawImage.Sample), converted image is OK. 

But when I am converting the RawImage of Subscriber's feed (From Janus Server) got from event OnVideoSinkDecodedSampleFaster to System.Drawing.Bitmap image = new Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, rawImage.Sample), converted image is distorted.

Please provide me some clue to solve the issue.

**Comment by sipsorcery** [comment]
Duplciate of https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/issues/69.
