### ISSUE TITLE
When installing the package SipSorceryMedia.Windows, an error occurs windows-x64, .Net7.0 AvaloniaUI

### ISSUE THREAD

**Issue by TheBestWorldProgrammer** [sipsorcery-org/sipsorcery#1053]
![Screenshot_30](https://github.com/sipsorcery-org/sipsorcery/assets/61782172/bdd9d58d-8549-4e15-bd83-d10bbc5b3d56)

**Comment by TheBestWorldProgrammer** [comment]
NuGet\Install-Package : NU1202: Пакет SIPSorceryMedia.Windows 6.0.5 несовместим с net7.0 (.NETCoreApp,Version=v7.0). Пакет SIPSorceryMedia.Windows 6.0.5 поддерживает:
  - net6.0-windows10.0.17763 (.NETCoreApp,Version=v6.0)
  - net8.0-windows10.0.17763 (.NETCoreApp,Version=v8.0)
строка:1 знак:1
+ NuGet\Install-Package SIPSorceryMedia.Windows -Version 6.0.5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by sipsorcery** [comment]
Any idea what [target framework moniker](https://learn.microsoft.com/en-us/dotnet/standard/frameworks) would work?

TBH I've lost track of how to properly target nuget packages that need to use Windows OS functions. It's probably still something to do with WinRT but I've "given up keeping up".

**Comment by thicsilva** [comment]
Maybe changing to .netx.x-windows [here](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/5b2367169cdffb1d870f025f2c5336b93bf59f63/src/SIPSorceryMedia.Windows.csproj#L12) (removing platform version) solve the problem.

**Comment by sipsorcery** [comment]
> Maybe changing to .netx.x-windows [here](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/5b2367169cdffb1d870f025f2c5336b93bf59f63/src/SIPSorceryMedia.Windows.csproj#L12) (removing platform version) solve the problem.

The WinRT API's don't seem to be supported with just a `*-windows`, e.g. `net8.0-windows`, tfm.

Attempting it gives errors that the Windows.Graphics, Winows.Media etc namespaces cannot be found.

**Comment by TheBestWorldProgrammer** [comment]
Here is Example Naudio .cproj    <TargetFrameworks>net472;netcoreapp3.1;net6.0-windows;net6.0</TargetFrameworks> 
But I do not know if it will help

**Comment by sipsorcery** [comment]
You're welcome to test this out yourself. The code is right [here](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows).
