### ISSUE TITLE
How to get the current connection type of WebRTC

### ISSUE THREAD

**Issue by Hu-Said** [sipsorcery-org/sipsorcery#1054]
I want to know when the WebRTC connection is successful, how do I know what the current connection mode is? Where can I get this information?
![image](https://github.com/sipsorcery-org/sipsorcery/assets/63393002/02fe21d8-48ed-4380-baaf-dffce3a7c9d1)

**Comment by sipsorcery** [comment]
[onconnectionstatechange](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/WebRTC/RTCPeerConnection.cs#L366) sounds like what you need.

**Comment by Hu-Said** [comment]
> [onconnectionstatechange](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/WebRTC/RTCPeerConnection.cs#L366) sounds like what you need.

No, this can only know his connection status. I want to know his connection mode, such as relay or host, or something else.

> I want to know when the WebRTC connection is successful, how do I know what the current connection mode is? Where can I get this information? ![image](https://private-user-images.githubusercontent.com/63393002/298535712-02fe21d8-48ed-4380-baaf-dffce3a7c9d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzQ5NjIsIm5iZiI6MTcwNTk3NDY2MiwicGF0aCI6Ii82MzM5MzAwMi8yOTg1MzU3MTItMDJmZTIxZDgtNDhlZC00MzgwLWJhYWYtZGZmY2UzYTdjOWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAxNTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTU5ZmMwNzVlNTM1ZGI3ZGQyOGQ3ZmE0ZGUzMjUxZDE5ZTAxNjE1ZDYwNzI1NDJhYzk2MWQ0NTdkYzkxZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14Og4-HdJvAik1RNd1Pmqy5V40AangUzfNtRvjnJvh8)

Just like the four in this screenshot, I want to know which mode is used after the connection is successful.

**Comment by Hu-Said** [comment]
I know there is a type in RTCIceCandidate to know this mode, but this is a collection, and I hope to accurately find the RTCIceCandidate type being used by the current connection.

**Comment by sipsorcery** [comment]
The [RtpIceChannel](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/WebRTC/RTCPeerConnection.cs#L1038) has a [NominatedEntry](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/ICE/RtpIceChannel.cs#L509) property that contains the local and remote ICE candidates that were used.

**Comment by Hu-Said** [comment]
> The [RtpIceChannel](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/WebRTC/RTCPeerConnection.cs#L1038) has a [NominatedEntry](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/ICE/RtpIceChannel.cs#L509) property that contains the local and remote ICE candidates that were used.

Yes I see that and this does what I need, thanks for the reply!

**Comment by Hu-Said** [comment]
> The [RtpIceChannel](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/WebRTC/RTCPeerConnection.cs#L1038) has a [NominatedEntry](https://github.com/sipsorcery-org/sipsorcery/blob/e5edf3db43cf98aae95543cd3b205266f181ab9e/src/net/ICE/RtpIceChannel.cs#L509) property that contains the local and remote ICE candidates that were used.

Yes I see that and this does what I need, thanks for the reply!
