### ISSUE TITLE
How To Add RTP Header Extension?

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#1066]
Is there any procedure to add multiple RTP header extension when sending RTP packets from Sipsorcery WebRTC to WebRTC Web Applications? I was checking Sipsorcery source code, and I am not able to understand it completely. Can anyone who is already familiar with RTP packetization guide me with this?

**Comment by ChristopheI** [comment]
Perhaps if you describe your use case, it will help

**Comment by nodminger** [comment]
@ChristopheI I want to add this extension to reduce video delay ([https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/playout-delay](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/playout-delay)). I found out when streaming using Sipsorcery, JitterBufferDelay/JitterBufferEmittedCount and other JitterBuffer stats increases quickly. I also found out KeyFrames are being sent very often. How to set KeyFrame to be sent only in the first frame and stop it? Because even KeyFrames can cause the receiving end to use more resources, right?

**Comment by nodminger** [comment]
@ChristopheI @sipsorcery is there any way to add RTP Headers?

**Comment by sipsorcery** [comment]
There's no hook to add a custom RTP header. You'll need to go into the source directly.
