### ISSUE TITLE
Line 231 from FFmpegVideoDecoder.cs consumes high CPU

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#1068]
The line 231 from FFmpegVideoDecoder.cs in SipsorceryMedia.FFmpeg consumes more CPU usage while video streaming. Is there any way to reduce this?
![image](https://github.com/sipsorcery-org/sipsorcery/assets/128209987/44aeb3c8-2cc9-44c6-bd80-5ec311a45b5e)

**Comment by ChristopheI** [comment]
I suppose you can ask FFmpeg community about this
