### ISSUE TITLE
Call failed Call attempt was answered with INVITE 200 OK (Error) but an error occurred setting the remote description..

### ISSUE THREAD

**Issue by fcltd** [sipsorcery-org/sipsorcery#1075]
Trying to test the "examples/SIPExamples/PlaySounds", but keep getting this error:

SIPSorcery Play Sounds Demo
press ctrl-c to exit...
Call failed Call attempt was answered with INVITE 200 OK (Error) but an error occurred setting the remote description..
Call to ********* failed.
Exiting...

The target gets the call Ok, but once answered it immediately hangs up, and that error is thrown.

The only thing that was changed in the code was this:

            ` // Place the call and wait for the result.` 
           `  var dstUri = $"sip:{DESTINATION}@{SIP_SERVER}";` 

            ` var callTask = userAgent.Call(dstUri, SIP_USERNAME, SIP_PASSWORD, voipMediaSession); `

to be able to specify the SIP server username/password. 

Any help would be immensely appreciated, thank you!

**Comment by sipsorcery** [comment]
The PlaySounds example works with the UserAgentServer example and also with the [MicroSIP](https://www.microsip.org/) softphone.

If you're able to provide the console log files from your app to show the SIP failure response that would help a lot. Please feel free to re-open if there is anymore info,
