### ISSUE TITLE
TLS client side

### ISSUE THREAD

**Issue by maddinthegreat** [sipsorcery-org/sipsorcery#1076]
Hi,

is there any setting (code) i must use to enable/support TLS? I didn't found an example how to use TLS on client side!
Is TLS handled internally by SIPSorcery?

Thx in advance

**Comment by DavidMartynWood** [comment]
If you add SIPTLSChannel (instead of SIPUDPChannel or SIPTCPChannel) to your SIPTransport it should work fine.
