### ISSUE TITLE
Contact header IP rewrite

### ISSUE THREAD

**Issue by Chali-Anne** [sipsorcery-org/sipsorcery#1078]
Free softphones such as MicroSIP support IP rewrite, which sets the Contact header to be the public facing address instead of the internal one on subsequent SIP calls. I would like to introduce this concept to SIPSorcery's user agents.

**Comment by DavidMartynWood** [comment]
It's possible to customise the outgoing request/reply header by implementing the callbacks CustomiseRequestHeader and CustomiseResponseHeader on the SIPTransport class.
This should allow you to carefully rewrite the contact header.

**Comment by DavidMartynWood** [comment]
Are you happy to close this issue?

**Comment by Chali-Anne** [comment]
Sorry for the delay, yes in the end I've turned to the transport to rewrite the contact header.
Thank you 🌸
