### ISSUE TITLE
Latest version (6.2..1) introduced a bug

### ISSUE THREAD

**Issue by nganju98** [sipsorcery-org/sipsorcery#1079]
src/net/RTP/RTPSession.cs has a bug where lower case codecs won't map with Enum.Parse, because all the enums are upper case (PCMU vs pcmu).  This bug was introduced by line 1032 in RTPSession.cs, where it says
`currentMediaStream.LocalTrack.Capabilities = capabilities;`

Steps to reproduce: just run the SIPCallServer example, and call the server with a SIP Invite that wants pcmu (lower case) as the audio codec.  You'll get a bunch of errors that say "Can't encode to unknown codec" because the AudioFormat is unknown because it failed to map "pcmu" to the enum PCMU.

**Comment by ChristopheI** [comment]
I don't think the line 1032 in RTPSession.cs is the cause. 
But the way to check codec is somewhere incorrect. 
I don't use SIP neither PCMU ... So could you try to find where the test is incorrect ?

By the way SDPAudioVideoMediaFormat.AreMatch() is correct.

**Comment by sipsorcery** [comment]
I don't believe anything has changed in this area. The issue is likely why you are seeing "pcmu" when it should be "PCMU".

SDP is case-sensitive see [RFC 4566](https://www.rfc-editor.org/rfc/rfc4566.html) section 5. The relevant text is included below.

````
   An SDP session description consists of a number of lines of text of
   the form:

      <type>=<value>

   where <type> MUST be exactly one case-significant character and
   <value> is structured text whose format depends on <type>.  In
   general, <value> is either a number of fields delimited by a single
   space character or a free format string, and is case-significant
   unless a specific field defines otherwise.  Whitespace MUST NOT be
   used on either side of the "=" sign.
