### ISSUE TITLE
SIP Proxy example didn't implement INVITE

### ISSUE THREAD

**Issue by nganju98** [sipsorcery-org/sipsorcery#1082]
Hi, I'm trying to implement a dirt simple SIP Proxy with this library.  I looked at the SIP Proxy example where it allows clients to register, but it doesn't implement a response to an inbound SIP Invite request.  Is there a simple example I can use to make a SIP Invite response that builds up all the appropriate headers?  Like it should fill out the Contact and RecordRoutes headers and the body should be from the registered client, and send that response back to the inbound caller.  

Really, I want the same server to be both the Proxy for client lookups, and the answering UserAgent Server as well, that answers as like an IVR to the caller.  Inbound callers (Twilio's implementation in particular) expect the SIP Invite redirect with the Contact header first.  If I just send 200 OK back on the first SIP Request, the client never sends back an ACK.  I think I need to send the Invite response with Contact/RecordRoutes header first, then I'll get another incoming INVITE from the same client, then answer it normally.

**Comment by DavidMartynWood** [comment]
You're trying to build something really complicated, and I think trying to use this library to do something like that is unlikely to lead to success.
As I understand it you want to answer a call, do some IVR, and the forward the call to to something.
There are products like asterisk/freeswitch and kamailio that exist to do stuff like this. Those are not simple solution either. But if you want to comply with standards it's probably worth looking into it.

**Comment by nganju98** [comment]
No, I don't want to do some IVR and then forward the call.  I just want to forward the call immediately, in other words just act exactly like a Proxy Server by using the Contact headers.  This is not a complex use case, I feel like it's 15 lines of code on top of the massive standards-compliant library you guys have already built.

The next server that I forward it to is the one that has the IVR.  The IVR destination server is also based on this library, it would be great if I could make the Proxy Server based on this library too, then I would have less variety of products to support and it would all be in .Net.

**Comment by DavidMartynWood** [comment]
Thanks for the explanation, that makes more sense now. Just to clarify, I'm a minor contributor to this project, and by no means a sip expert like there maintainers.

I'm not sure if sipsorcery respects record-route headers when sending an ACK, or if it replies to the contact in the sip invite ok. And indeed I'm not actually sure what it's supposed to do according to the standard. I recently had a similar problem in this area and couldn't bottom it out so implemented a workaround for my scenario.

To try to understand what it's doing I would use wireshark on the client and see where it's trying to send the ack to. That might give you some clues.

Then if you can include the full sip messages for your flow somebody more knowledgeable might be able to help you out with what eitherinyou are doing wrong, or what might need implementing in sipsorcery.

I'll be watching this in the hope somebody else jumps in with an answer. Routing in sip is hard to get your head around.

**Comment by sipsorcery** [comment]
Sounds like you're attempting to build a Stateful Proxy (like OpenSER, Kamailio) or a B2BUA Server (like Asterisk and FreeSWITCH w/o media). 

Both options are feasible with this library but definitely not in 15 lines of code, probably closer to 1500.

There is an example of a B2BUA [here](https://github.com/sipsorcery-org/signalrtc/blob/master/src/SIPServers/SIPB2BUserAgentCore.cs).
