### ISSUE TITLE
SipRegistrationUserAgent not responding to OPTIONS requests from server

### ISSUE THREAD

**Issue by mnik17** [sipsorcery-org/sipsorcery#1089]
Hello @sipsorcery,

I noticed that after the initial registration Asterisk is sending (by default) OPTIONS requests to check if the endpoint is still there. However, the `SIPRegistrationUserAgent` is not responding to these requests. Consequently, the extension in Asterisk is marked as unavailable and it is not possible to call it.

I checked the Wireshark capture and the port seems to be correct. I don't know if it's a problem, but I'm using the same `SIPTransport` for the `SIPUserAgent` and the `SIPRegistrationUserAgent`.

Then I checked the documentation and the code of the `SIPRegistrationUserAgent` and I didn't notice any method taking care of that. Is this really the case or am I missing something?

**Comment by sipsorcery** [comment]
The registration agent isn't designed to handle anything other than REGISTER requests. Instead you should handle the OPTIONS request on your SIPTransport, see the [SIPProxy example](https://github.com/sipsorcery-org/sipsorcery/blob/2f59115b2c4d49ded9bc5cd3a6734bb10e5c4bb8/examples/SIPExamples/SIPProxy/Program.cs#L158).
