### ISSUE TITLE
c# .net framework 4.7.2 make call to sip

### ISSUE THREAD

**Issue by Desync3** [sipsorcery-org/sipsorcery#1092]
c# .net framework 4.7.2 make call to sip doesnt work. I get error and theres no example codes as i see it and I'm not able to compile the project without error so I'm just using nuget manager.

This my code:
`       var sipTransport = new SIPUDPChannel();
        var sipAccount = new SIPAccount(sipUser, sipServer, sipUser, sipPassword);
        var sipCall = new SIPClient(sipTransport);

        var callRequest = sipCall.Call(unescape(sipUser), unescape(destination), unescape(callid), sipAccount, null);

        if (callRequest == null)
        {
            Console.WriteLine("Call failed.");
        }
        else
        {
            Console.WriteLine("Call successful.");
        }
`
But as i see it i get 
The type or namespace name 'SIPAccount' could not be found
and much more errors and yes I'm using latest verison SIPSorcery.SIP;

**Comment by Desync3** [comment]
still need help

**Comment by sipsorcery** [comment]
Can you provide the full text for the compiler error.

**Comment by sipsorcery** [comment]
Feel free to re-opwn if any further info.
