### ISSUE TITLE
Signed Nuget package

### ISSUE THREAD

**Issue by FredeJ** [sipsorcery-org/sipsorcery#1103]
Hey!

First of all, thanks for all the work you've done on sipsorcery.

We're looking at using it in one of our projects. We however have rules about requiring signed Nuget packages.

This strikes me like the kind of work I couldn't just implement myself. Is there any chance you could get around to looking at it?

If there's any way I can contribute to that effort, let me know!

**Comment by helu-milestone** [comment]
We are using it in our solution as well. We have had to suppress warnings about it. It would be really nice if the packages could be signed.

**Comment by sipsorcery** [comment]
Code signing certs have a substantial cost. It's not a requirement for me to fork out for one at this point. OFC you're welcome to fork the repo and sign with your own cert.
