### ISSUE TITLE
Possible Null pointer exception if using MdnsResolve

### ISSUE THREAD

**Issue by helu-milestone** [sipsorcery-org/sipsorcery#1116]
In RtpIceChannel.cs line 2645 returns null in case the MdnsResolve fails to resolve the mDNS address. I think null should be changed into an Empty.Array<IPAddress>() to avoid null pointer exception in line 1376.

I would like to make a pull request with this small fix, but I have no branch. How do I contribute to the project?

**Comment by helu-milestone** [comment]
For anyone else new to OpenSource you can make a fork of the repository. Create a fix in your own repository and after that github will show that you are ahead of SipSorcery repostory and you can make a pull request

**Comment by sipsorcery** [comment]
Resolved in #1119.
