### ISSUE TITLE
Unhandled exception at WebSocketSharp.WebSocket.Send(String data) if websocket client connect and immediately close it

### ISSUE THREAD

**Issue by programatix** [sipsorcery-org/sipsorcery#1120]
Hi,

I'm testing the SIPToWebRTCBridge example project. I have updated it `net8.0` with `SIPSorcery` version `6.2.4` and `SIPSorcery.WebSocketSharp` version `0.0.1`.

Using webrtcsip.html, if I click Start button and immediately click the Close button to close the websocket, before it complete establishing the connection, I get an unhandled exception.
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The current state of the connection is not Open.
  Source=websocket-sharp
  StackTrace:
   at WebSocketSharp.WebSocket.Send(String data) in WebSocketSharp\WebSocket.cs:line 2373
   at SIPSorcery.Net.WebRTCWebSocketPeer.<OnOpen>d__19.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

I tried tracing back the call and it should be initiated from the `open()` function in `websocket-sharp.dll` which is encapsulated by a try...catch routine, but somehow it crashed the main app.

Steps to reproduce:

1. Run the updated SIPToWebRtcBridge.
2. Open webrtcsip.html.
3. Click Start button.
4. Click Allow on permission prompt.
5. Immediately clock Close button before the connection established.
6. Exception Unhandled will occur.

![image](https://github.com/sipsorcery-org/sipsorcery/assets/3293865/d993d628-ec4f-4900-8cb6-d6b835965bac)
![image](https://github.com/sipsorcery-org/sipsorcery/assets/3293865/01af2856-26a4-4490-9799-541f19b5a025)

**Comment by programatix** [comment]
It seems that the issue is caused by `OnOpen()` function in `WebRTCWebSocketPeer` class. It's an `async` which runs on a thread but doesn't return any Task, so exception raised inside it will not be caught by the original `Try..Catch` in `WebSocket` `open()`.

The easiest way out is to catch the exception in `OnOpen()` function for `WebRTCWebSocketPeer` class and log the error there. Any suggestion?

**Comment by sipsorcery** [comment]
Resovled by #1121.
