### ISSUE TITLE
Issue with Audio Level RTP Extension in Janus-Gateway

### ISSUE THREAD

**Issue by Touhid9814** [sipsorcery-org/sipsorcery#1122]
I'm currently working with Janus-Gateway and I’ve encountered an issue where I’m not receiving any talking events. After some troubleshooting, I was asked whether the audio level RTP extension is being negotiated in my library.
Upon inspecting the SDP string, I noticed that there is no audio level RTP extension included.
I’m seeking assistance to understand how to properly negotiate the audio level RTP extension in my setup. Could someone guide me on how to include the audio level RTP extension in the SDP negotiation?

**Comment by ChristopheI** [comment]
Could you provide a SDP as an example about this ?
Do you have a reference about this RTP Extension ?

**Comment by ChristopheI** [comment]
I suppose your are talking about this RFC: https://datatracker.ietf.org/doc/rfc6464/

Today it's not possible to add RTP extension without modifying the code itself - see https://github.com/sipsorcery-org/sipsorcery/issues/1066

I'm also interested by this RTP Extension (Audio Level - urn:ietf:params:rtp-hdrext:ssrc-audio-level)  and Video Orientation (urn:3gpp:video-orientation)

**Comment by Touhid9814** [comment]
"sdp": "v=0\r\r\no=- 59218 0 IN IP4 127.0.0.1\r\r\ns=sipsorcery\r\r\nt=0 0\r\r\na=group:BUNDLE 0\r\r\nm=audio 9 UDP/TLS/RTP/SAVP 111 0 8 9 18 101\r\r\nc=IN IP4 0.0.0.0\r\r\na=ice-ufrag:LPRY\r\r\na=ice-pwd:LVSJDZMVPHNGSMZLLNKXAWUZ\r\r\na=fingerprint:sha-256 E3:3C:D5:F9:AA:33:43:57:E1:87:C9:6D:8B:03:7A:2B:2B:58:8F:A9:9A:AF:63:66:97:A8:B7:C6:51:C4:B4:50\r\r\na=setup:actpass\r\r\na=candidate:1440154887 1 udp 2113937663 192.168.104.207 50590 typ host generation 0\r\r\na=ice-options:ice2,trickle\r\r\na=mid:0\r\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\r\na=rtpmap:111 opus/48000/2\r\r\na=fmtp:111 a=fmtp:111 minptime=10;useinbandfec=1\r\r\na=rtpmap:0 PCMU/8000\r\r\na=rtpmap:8 PCMA/8000\r\r\na=rtpmap:9 G722/8000\r\r\na=rtpmap:18 G729/8000\r\r\na=rtpmap:101 telephone-event/8000\r\r\na=fmtp:101 0-16\r\r\na=rtcp-mux\r\r\na=rtcp:9 IN IP4 0.0.0.0\r\r\na=sendrecv\r\r\na=s
