### ISSUE TITLE
Windows, .NET Framework4.8 console app 

### ISSUE THREAD

**Issue by Hanning-Liu** [sipsorcery-org/sipsorcery#1123]
Following this tutorial :
https://github.com/sipsorcery-org/sipsorcery?tab=readme-ov-file#getting-started-webrtc
Using .NET 6 follow this tutorial is fine. I can see the final test image.
But Visual Studio threw an exception when I use .NET Framework4.8 console app to test it.

![image](https://github.com/sipsorcery-org/sipsorcery/assets/42676581/b2e6ba3f-291a-4f5a-8581-452a5364895e)

Code File:
https://drive.google.com/drive/folders/1BYC3VyXbUfzXBMsleo4p06E-0XN89aH7?usp=drive_link

**Comment by Terricide** [comment]
You probably need to uncheck 32-bit in your project and make sure it is running as 64-bit

**Comment by ChristopheI** [comment]
I guess you have all necessary information.
I close the issue. Re-open it if necessary
