### ISSUE TITLE
Display video WebRTC

### ISSUE THREAD

**Issue by hossam14102010** [sipsorcery-org/sipsorcery#1137]
How can I display `peerConnection.RemoteVideoTrack` in Maui, Wpf or UWP

**Comment by ha-ves** [comment]
https://github.com/sipsorcery-org/SIPSorceryMedia.Windows

**Comment by hossam14102010** [comment]
@ha-ves can you provide an example to use this, looks like it contains only video sources and video sinks I mean if I have a video track how can I display (how can I make a video call using WebRTC)

**Comment by ha-ves** [comment]
There are many examples in [examples/WebRTCExamples/](https://github.com/sipsorcery-org/sipsorcery/tree/a92c57441b8fb9aa5add38f58f71232c35ec3284/examples/WebRTCExamples).

Currently, there are 2 ways, using VP8 and FFmpeg. Both are abstracted so you only need to get an object handle in 2 lines, the rest are the same.

excerpts:
https://github.com/sipsorcery-org/sipsorcery/blob/a92c57441b8fb9aa5add38f58f71232c35ec3284/examples/WebRTCExamples/WebRTCClientVP8Net/Program.cs#L94-L112
https://github.com/sipsorcery-org/sipsorcery/blob/a92c57441b8fb9aa5add38f58f71232c35ec3284/examples/WebRTCExamples/WebRTCClient/Program.cs#L85-L103

Essentially you'd get a decoded frame (pixel bytes) with which you'd put into a `Bitmap` or something else, then you can use for the `Source` of an `Image` control in WPF/UWP.
