### ISSUE TITLE
Incoming requests are discarted while I'm in call

### ISSUE THREAD

**Issue by FerranPalmada** [sipsorcery-org/sipsorcery#1138]
I am using a SIPUserAgent to handle incoming calls, like this example:

https://sipsorcery-org.github.io/sipsorcery/articles/sipuseragent.html

When I answer a call, any incoming request which is not from this call is discarted, since it does not belong to the same sipDialogue.

I think that the library should allow to keep receiving requests, as even if I am in call, i should know if someone else is calling me, for example. Is there any way to handle this situation?

**Comment by sipsorcery** [comment]
That's by design. Each SIPUserAgent instance is designed to handle a single call. If you want to handle simultaneous calls you simply create another SIPUserAgent instance.
