### ISSUE TITLE
Proxy auth with BlindTransfer

### ISSUE THREAD

**Issue by marcinborecki** [sipsorcery-org/sipsorcery#1139]
How to implement auto-send Auth Proxy to BlindTransfer.
I do not know why but PBX do not send info that it is required (but is) and after invoke BlindTransfer (REFER) it's hung up.

I saw that ZOIPIER do it some how.
During session in WireShark I saw that in both cases (also ZOIPIER) there is no info from server that PROXY Auth header should be send - but ZOIPIER do it and it works - but I could not force for it - this library.

Could you help?

**Comment by sipsorcery** [comment]
The [BlindTransfer](https://github.com/sipsorcery-org/sipsorcery/blob/2f59115b2c4d49ded9bc5cd3a6734bb10e5c4bb8/src/app/SIPUserAgents/SIPUserAgent.cs#L811) method does take a username and password. Is that what you need?

**Comment by sipsorcery** [comment]
Feel free to re-open if any further info.
