### ISSUE TITLE
Broken stream with h264 format

### ISSUE THREAD

**Issue by KishanDasani** [sipsorcery-org/sipsorcery#1148]
I am working on a WebRTC sender application using .NET Core, SIPSorcery, and idb video-stream to stream video from an iOS device. My signaling server uses WebSocket (Socket.IO). The peer connection is successfully established, and ICE candidates and SDP offers/answers are exchanged correctly. However, the video is not appearing correctly on the receiver side. The frames seem to be incomplete or corrupted despite continuous logs indicating that video frames are being sent from the sender side.

Environment:

WebRTC Library: SIPSorcery
Signaling Server: WebSocket (Socket.IO)
Video Stream Source: idb video-stream with H264 format
Platform: .NET Core 5
Steps Implemented:

- Set up signaling server to exchange SDP offers/answers and ICE candidates.
- Establish WebRTC peer connection using SIPSorcery.
- Stream video from iOS device using idb video-stream --format h264.

Code Snippets:
Here is a simplified version of my current implementation:

- Function to get iOS Stream

```
private static async Task<Stream> GetVideoStream()
    {
        string idbCmd = $"video-stream --udid {IOS_DEVICE_UDID} --format h264";

        ProcessStartInfo idbStartInfo = new ProcessStartInfo
        {
            FileName = "idb",
            Arguments = idbCmd,
            RedirectStandardOutput = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        var idbProcess = new Process
        {
            StartInfo = idbStartInfo
        };

        idbProcess.Start();

        return idbProcess.StandardOutput.BaseStream;
    }
```

- Getting video stream and convert stream data to frames which are being sent to peerConnection

```
var videoStream = await GetVideoStream();
var rawFramesSource = new RawFramesSource(videoStream);

var h264Format = new VideoFormat(VideoCodecsEnum.H264, 96);
MediaStreamTrack videoTrack = new MediaStreamTrack(new List<VideoFormat> { h264Format }, MediaStreamStatusEnum.SendRecv);
pc.addTrack(videoTrack);

rawFramesSource.OnVideoSourceEncodedSample += (uint timestamp, VideoFormat format, byte[] sample) =>
{
    pc.SendVideo(timestamp, sample);
};
```

- RawFramesSource class to convert stream data to frames

```
public class RawFramesSource
    {
        private readonly Stream _videoStream;
        public VideoFormat VideoFormat { get; set; }

        public delegate void EncodedSampleDelegate(uint timestamp, VideoFormat format, byte[] sample);
        public event EncodedSampleDelegate OnVideoSourceEncodedSample;

        public RawFramesSource(Stream videoStream)
        {
            _videoStream = videoStream;
        }

        public void Start()
        {
            Task.Run(ReadFrames);
        }

        private async Task ReadFrames()
        {
            byte[] buffer = new byte[65536];
            while (true)
            {
                int bytesRead = await _videoStream.ReadAsync(buffer, 0, buffer.Length);
                if (bytesRead <= 0)
                    break;

                var sample = buffer.Take(bytesRead).ToArray();
                uint timestamp = (uint)DateTimeOffset.Now.ToUnixTimeMilliseconds(); // Example timestamp
                OnVideoSourceEncodedSample?.Invoke(timestamp, VideoFormat, sample);
            }
        }

        public void Stop()
        {
            _videoStream.Close();
        }
    }
```

- Below is the snapshot of stream I get on my browser.
![image](https://github.com/user-attachments/assets/f08b2e32-7375-434a-9a1a-80c4cbbb57f8)

**Comment by sipsorcery** [comment]
Typivally the corrupted video indicates a missing key frame. You could try requesting the remote peer to send a new key frame using the mechansim shonw in this [example](https://github.com/sipsorcery-org/sipsorcery/blob/2f59115b2c4d49ded9bc5cd3a6734bb10e5c4bb8/examples/WebRTCExamples/WebRTCtoFfplay/Program.cs#L129).
