### ISSUE TITLE
Add support for RFC3311-UPDATE method

### ISSUE THREAD

**Issue by fanshuxian** [sipsorcery-org/sipsorcery#1150]
I have a voice call, and the call will be automatically disconnected 10 minutes after it is answered.

By checking the signaling, I found that the third-party PBX（freeswitch、VOS3000 etc） will send an `UPDATE` request when the call lasts 600 seconds. 

`Sipsorcery` does not support `UPDATE` method, and it is forced to hang up after 30 seconds because there is no media.

**Comment by ChristopheI** [comment]
Please don't hesitate to create a PR.
Thx
