### ISSUE TITLE
Can't set the caller id?

### ISSUE THREAD

**Issue by babawarrior** [sipsorcery-org/sipsorcery#1152]
Hello, I'm trying out sipsorcery but i can't manage to set the caller id, it always calls as "No Caller ID", my sip doesn't require caller id registration. 

If anyone can help me set the caller id, I would be very happy.

This is my code:

```
using System;
using SIPSorcery.SIP.App;
using SIPSorcery.Media;
using SIPSorceryMedia.Abstractions;

const string DESTINATION = "sip:4670000000@sip.9sip.net";
Console.WriteLine("SIP Get Started");

var userAgent = new SIPUserAgent();

var voipMediaSession = new VoIPMediaSession();
voipMediaSession.AcceptRtpFromAny = true;
voipMediaSession.AudioExtrasSource.SetSource(AudioSourcesEnum.Silence);

// Place the call and wait for the result.
bool callResult = await userAgent.Call(DESTINATION, "8511", "25228", voipMediaSession);
Console.WriteLine($"Call result {(callResult ? "success" : "failure")}.");
//voipMediaSession.Close("idgaf");
if(callResult == true)
{
    voipMediaSession.AudioExtrasSource.StartAudio();
    voipMediaSession.AudioExtrasSource.SendAudioFromStream(new FileStream("hello.raw", FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);

}


Thread.Sleep(10000);
userAgent.Hangup();

```

**Comment by babawarrior** [comment]
still need help

**Comment by babawarrior** [comment]
Still need help

**Comment by sipsorcery** [comment]
Most SIP Providers use the From header to set the callerID. The From header can be tricky to customise as it's also often used for authentication.

Try switching to the SIPUserAgent.Call overload that takes a SIPCallDescriptor. Set the From header to something like:

"Your Desired Caller ID" <username@siprovider,com>

As mentioned you may have to iterate a bit to get it in the form reqd by your SIP Provider. 

There are also lots of other similar issues in this repo. If you search for "callerid" you should get some useful suggestions.

**Comment by sipsorcery** [comment]
Feel free to re-open if any further info.

**Comment by babawarrior** [comment]
> Feel free to re-open if any further info.

I'm having a issue where I just receive "Call Result Failure" when using SIPCallDescriptor.
`
        const string DESTINATION = "sip:46735000000@sip.diamondcard.us";
        const string from = "46735000000<480000@sip.diamondcard.us>";
        SIPCallDescriptor callDescriptor = new SIPCallDescriptor("314444", "438800000", DESTINATION, from, null, null, null, null, 
       SIPCallDirection.Out, "application/sdp", null, null);

`

**Comment by sipsorcery** [comment]
Seems more like a SIP Provider issue than a library issue.

Only suggestion i have is to add a space between the From name and URI:

`const string from = "46735000000 <480000@sip.diamondcard.us>";`

**Comment by babawarrior** [comment]
> Seems more like a SIP Provider issue than a library issue.
> 
> Only suggestion i have is to add a space between the From name and URI:
> 
> `const string from = "46735000000 <480000@sip.diamondcard.us>";`

I dont think its a SIP Provider issue because ozeki sdk worked but its expensive and I dont got that money.

**Comment by babawarrior** [comment]
If i privre

> Seems more like a SIP Provider issue than a library issue.
> 
> Only suggestion i have is to add a space between the From name and URI:
> 
> `const string from = "46735000000 <480000@sip.diamondcard.us>";`

If I privately give you my sip credentials from diamondcard.us, you think you can try debug it? I've had this issue for months.

**Comment by sipsorcery** [comment]
I won't troubleshoot it for you but you hvae options. Use Wireshark to capture the SIP request with ozeki and compare it with the one you are sending with this library. It will most likely be something to with the From header or a P-Asserted header.

**Comment by babawarrior** [comment]
> I won't troubleshoot it for you but you hvae options. Use Wireshark to capture the SIP request with ozeki and compare it with the one you are sending with this library. It will most likely be something to with the From header or a P-Asserted header.

I didn't solve it, but i found a work around, different sip providers have so you can in the dest choose the callerid so i switched to a different sip. Btw I tried on like 5 different sip providers, it never worked with SIPCallDescriptor. But atleast I found a work around.
