### ISSUE TITLE
How to know incoming call has been cancel?

### ISSUE THREAD

**Issue by TMT25** [sipsorcery-org/sipsorcery#1153]
I am building an C# app  with SIPSorcery using SIP to work with third-party VoIP server. I don't know which method to use when an incoming call has been cancel by other client. Can someone please help me about it?

**Comment by sipsorcery** [comment]
The [CallCancelled](https://github.com/sipsorcery-org/sipsorcery/blob/97d2a35fc0a579ab1062719ad1808f19221a17e3/src/app/SIPUserAgents/SIPServerUserAgent.cs#L96) event will inform you when an incoming call attempt is cancelled.
