### ISSUE TITLE
How to implement Low Latency, 60 fps video encoding in WebRTC.

### ISSUE THREAD

**Issue by DigitalSerpant** [sipsorcery-org/sipsorcery#1154]
Hi, Does anyone know how to encode the video stream for webRTC at 60 fps? This might be a big ask but it's worth a shot. I'm trying to make a screen share application with high fps at 1080p. The compression does not matter to much so it can be VP8 or VP9 but I'm not sure how to make it go above 20 fps. My code is basically from the following issue but I changed the screenshot method to use direct x with SharpDX to do the screenshots.

https://github.com/sipsorcery-org/sipsorcery/issues/320
[VideoEncoding.zip](https://github.com/user-attachments/files/16434224/VideoEncoding.zip)

Thanks in advanced for any help at all!

**Comment by hossam14102010** [comment]
`FFmpegScreenSource` constructor has a `frameRate` paramater which is set to 20 by default. did you try to change it?

**Comment by DigitalSerpant** [comment]
Yes, I had changed it. Turns out I just needed to set the preset to low latency and that did the trick. Thanks though!

**Comment by sipsorcery** [comment]
Issue seems resovled. Please feel free to re-open if any further questions.

**Comment by Butcher-vj** [comment]
> Yes, I had changed it. Turns out I just needed to set the preset to low latency and that did the trick. Thanks though!

Hey, Could you explain about that ?
