### ISSUE TITLE
How to know which STUN.TURN server is used in PeerConnection

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#1160]
We are providing a list of STUN and TURN servers url. Now we want to know which one is used in a PeerConnection.

**Comment by ha-ves** [comment]
In case of relay server.
You can subscribe to the `onicecandidate` event and get the `DestinationEndPoint`.

```c#
pc.onicecandidate += (ice) =>
{
    if(ice.type == RTCIceCandidateType.relay)
        _relayServer = ice.DestinationEndPoint;
}
```

**Comment by sipsorcery** [comment]
Is this solved?
