### ISSUE TITLE
OnRtpPacketReceived stops being called for video during session

### ISSUE THREAD

**Issue by thiggins09** [sipsorcery-org/sipsorcery#1162]
For an audio/video stream, we've observed that occasionally, after a seemingly random duration, OnRtpPacketReceived will only notify of audio data.

Has anyone else encountered this?

**Comment by ChristopheI** [comment]
Using WebRTC, I never noticed this.
Even using one Audio Stream (both direction) with two video streams (both direction) in the same Peer Connection.

Check your network to ensure your device receives well video packets

**Comment by sipsorcery** [comment]
Please re-open if there's any more info.
