### ISSUE TITLE
RTP event payload type can be set incorrectly when sending DTMF on an incoming call

### ISSUE THREAD

**Issue by CNH01** [sipsorcery-org/sipsorcery#1164]
Suggested PR: 
https://github.com/sipsorcery-org/sipsorcery/pull/1165

Scenario: 

* SIP transport receives an INVITE request with SDP containing the capability `96 telephone-event 0-15`
* Invite is accepted (by creating a SIPUserAgent and `calling AcceptCall(SIPRequest inviteRequest)`) 

Result:
The SIPUserAgent's media session's local track's capabilities are changed to support 
`96 telephone-event 0-15`
rather than
`101 telephone-event 0-16`

So the SDP in the 200 OK when answering the call contains `96 telephone-event 0-15`. 

This becomes an issue when calling `SendDtmf(byte tone)` on the SIPUserAgent, as this calls `SendDtmf(byte key, CancellationToken ct)` on the AudioStream which, in turn, defaults to using `101 telephone-event 0-16` (RTPSession.DTMF_EVENT_PAYLOAD_ID). 

So we end up sending DTMF with payload type 101, despite advertising that we will send payload type 96 when answering the call.

**Comment by sipsorcery** [comment]
#1165 merged.
