### ISSUE TITLE
OnVideoSinkDecodedSampleFaster  invalid

### ISSUE THREAD

**Issue by weikezhi** [sipsorcery-org/sipsorcery#1174]
OnVideoSinkDecodedSample  able to fetch data successfully.
OnVideoSinkDecodedSampleFaster   it hasn't been triggered.

My second question is, how can I scale the data acquired from source OnVideoSinkDecodedSample? I've tried stretching it, but the image flickers.

Thank you all for your generous advice and guidance.

**Comment by ha-ves** [comment]
> OnVideoSinkDecodedSample able to fetch data successfully. OnVideoSinkDecodedSampleFaster it hasn't been triggered.

If you use `VideoEncoderEndPoint` from [SIPSorceryMedia.Encoders](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/), it doesn't support `OnVideoSinkDecodedSampleFaster`, it will only invoke `OnVideoSinkDecodedSample`

> My second question is, how can I scale the data acquired from source OnVideoSinkDecodedSample? I've tried stretching it, but the image flickers.

you can use ImageSharp, SkiaSharp, OpenCVSharp, EmguCV, or any other image manipulation library.

**Comment by weikezhi** [comment]
> > OnVideoSinkDecodedSample 能够成功获取数据。OnVideoSinkDecodedSampleFaster 尚未触发。
> 
> 如果使用 [from SIPSorceryMedia.Encoders](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/)，则它不支持，它只会调用`VideoEncoderEndPoint``OnVideoSinkDecodedSampleFaster``OnVideoSinkDecodedSample`
> 
> > 我的第二个问题是，如何缩放从源 OnVideoSinkDecodedSample 获取的数据？我尝试拉伸它，但图像闪烁。
> 
> 您可以使用 ImageSharp、SkiaSharp、OpenCVSharp、EmguCV 或任何其他图像处理库。

Thank you for your answer. It's very helpful to me. Have a happy weekend.
