### ISSUE TITLE
WebRTC丢包处理

### ISSUE THREAD

**Issue by Forever-OnLine** [sipsorcery-org/sipsorcery#1176]
你好 sipsorcery团队：
我在使用sipsorcery进行webrtc通讯，整个过程非常顺利，但是放在公网上测试视频通讯时，发现丢包情况很严重，但是经过我测试，通过H264编码，和设置了比特率。视频流已经处理到很小（约20kb）。尽管这样，丢包的情况依然很严重。我该如何操作和设置呢？我相信我的网络是可以支撑20kb数据的传输。

**Comment by Forever-OnLine** [comment]
Hello sipsorcery Team:
I used sipsorcery for webrtc communication, the whole process was very smooth, but when testing video communication on the public network, I found that the packet loss was very serious, but after my test, through H264 encoding, and set the bit rate. The video stream has been processed to a small size (about 20kb). Despite this, the situation of packet loss is still very serious. How do I operate and set it up? I believe my network can support the transfer of 20kb of data.

**Comment by ChristopheI** [comment]
Could you test with VP8 only ?
I notice a lot of problem using H264 - which I no more use.

**Comment by Forever-OnLine** [comment]
> Could you test with VP8 only ? I notice a lot of problem using H264 - which I no more use.

Thank you very much for your reply. I have used VP8 format according to your suggestion,and the effect is very good. The problem has been  solved.

**Comment by ChristopheI** [comment]
Good news. 
Perhaps someone in the community can help with H264
