### ISSUE TITLE
Initiate a call ,Return 401 404 error

### ISSUE THREAD

**Issue by xhhaha** [sipsorcery-org/sipsorcery#1195]
string USERNAME = "1006";
 string PASSWORD = "Ab123456";
 string DOMAIN = "192.168.1.28";
 int EXPIRY = 120;

 SIPTransport sipTransport = new SIPTransport();
 SIPRegistrationUserAgent regUserAgent;// = new SIPRegistrationUserAgent(sipTransport, USERNAME, PASSWORD, DOMAIN, EXPIRY);
 SIPUserAgent userAgent;
 IMediaSession IPMediaSession = null;
 public Form1()
 {
     InitializeComponent();
     userAgent = new SIPUserAgent(sipTransport, null);
     regUserAgent = new SIPRegistrationUserAgent(sipTransport, USERNAME, PASSWORD, DOMAIN, EXPIRY);
     regUserAgent.Start();
     regUserAgent.RegistrationFailed += (uri, err, s) => Console.WriteLine($"{uri.ToString()}: {err}");
     regUserAgent.RegistrationTemporaryFailure += (uri, msg, s) => Console.WriteLine($"{uri.ToString()}: {msg}");
     regUserAgent.RegistrationRemoved += (uri, s) => Console.WriteLine($"{uri.ToString()} registration failed.");
     regUserAgent.RegistrationSuccessful += (uri, s) =>
     {
         Debug.WriteLine(uri);
         Debug.WriteLine(s);
     };
     
     IPMediaSession = new VoIPMediaSession();
 }
 VoIPMediaSession session = new VoIPMediaSession();

 private async void button1_Click(object sender, EventArgs e)
 {
     
     bool callResult = await userAgent.Call("150***12342@192.168.1.28", USERNAME, PASSWORD, session);
     if (callResult)
     {

     }
 }

regUserAgent.RegistrationSuccessful   
Successful registration returns the following message

SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.11.111.153:60613;rport=60613;received=10.11.111.153;branch=z9hG4bK9e74212d1b3149f5a7c5f11ba40a076a
To: <sip:1006@192.168.1.28>;tag=z9hG4bK9e74212d1b3149f5a7c5f11ba40a076a
From: <sip:1006@192.168.1.28>;tag=PKUFRKFILI
Call-ID: d6f2e13e-d80d-431c-86b6-ac39e7745622
CSeq: 2 REGISTER
Contact: <sip:10.11.111.153:60613>;expires=119,<sip:10.11.111.153:54523>;expires=99,<sip:10.11.111.153:60695>;expires=105
Expires: 120
Date: Sat, 12 Oct 2024 06:34:39 GMT
Server: Yeastar S50-30.15.0.102
Content-Length: 0 

execute(bool callResult = await userAgent.Call("150***@192.168.1.28", USERNAME, PASSWORD, session);)
![image](https://github.com/user-attachments/assets/472f185e-3132-4d56-81a0-2d5df8df9fec)
solve

**Comment by xhhaha** [comment]
The code runs without any exceptions, but the call cannot be initiated correctly

**Comment by sipsorcery** [comment]
The issue is likely to be your Asterisk dialplan or Asterisk SIP config. I've used tested this library extensively with Asterisk.

Try turning on Asterisk debug logs.
