### ISSUE TITLE
Help please - SIP Proxy / B2BUA

### ISSUE THREAD

**Issue by Vrince1998** [sipsorcery-org/sipsorcery#1200]
Hello guys, i'm looking for some help...

I'm not an expert and i have literally 0 knowledge on how SIP or VoIP works.

What i'm trying to achieve is what an ignorant like me might call a Proxy (apparently is not a proxy).

We have a DoorBird device, which has SIP inside, or wants to talk via SIP, again, i'm not an expert.

We also have a raspberry pi which will run on the same LAN as the DoorBird device. And we also have a mobile app, which we'd really like to use as client for the incoming doorbird calls.

The idea is when somebody rings your doorbell to be able to answer the call. That's it, very simple. (not so simple apparently)

We first tried installing Asterisk on the raspberry and it worked, we achieved the wanted result but asterisk is too heavy and it's kind of killing the raspy since we also run some services on it.

What i did with Asterisk (FreePBX actually) is set up 2 extensions with id 1001 and 1002.

Let's suppose the Raspy IP with Asterisk running on it is 10.0.1.249.

I've set the SIP settings inside the DoorBird using the raspy ip as domain/server and with the username and pass of user 1001.

Using MicroSIP i've set up a client using the 1002 user.

I've created an Inbound rule to route everything to 1001.

When doorbell rings, it makes a sip call towards asterisk like this: sip:1001@10.0.1.249 which then is being routed to the MicroSIP client --> Lovely, everything works.

As i mentioned before having Asterisk on the raspy is not doing it for us, so we started looking for a lighter approach and since we are C# developers we stumbled upon your library.

That's what i'm trying to achieve but its been a few days now and i feel like i'm not achieving anything, i've tried looking at the example codes, especially SIPProxy but it's not working (or better, i don't know how to make it work). I've tried searching for documentation or more examples, even with ChatGPT but nothing.

What i achieved so far is having a client make the call towards the server, but no forwarding is happening whatsoever. If somebody could please take a look and hopefully point me towards the right direction i'd really apreciate it.

Below is my current code, that's the result of arguing with ChatGPT and what i've found in some of the examples. I'm pretty sure it may look simple to you but for somebody who doesn't know anything about this topic is getting really complicated and overwhelming... Help please :(

`    public class SIPProxyService : IHostedService, ISIPProxyService, IDisposable
    {
        private readonly ILogger<SIPProxyService> _logger;
        private readonly SIPEventService _eventService;
        private SIPTransport _sipTransport;
        private IPAddress _proxyIPAddress;
        private readonly int _listenPort = SIPConstants.DEFAULT_SIP_PORT;

        // Dictionary to track registered SIP accounts: [Username, Binding]
        private readonly ConcurrentDictionary<string, SIPAccountBinding> _sipRegistrations = new ConcurrentDictionary<string, SIPAccountBinding>();

        // Concurrent dictionary to map Call-ID to the original caller's endpoint
        private readonly ConcurrentDictionary<string, SIPEndPoint> _callIdToCallerEndPoint = new ConcurrentDictionary<string, SIPEndPoint>();

        // Concurrent dictionary to store active INVITE transactions to prevent garbage collection
        private readonly ConcurrentDictionary<string, UACInviteTransaction> _activeInviteTransactions = new ConcurrentDictionary<string, UACInviteTransaction>();

        public SIPProxyService(ILogger<SIPProxyService> logger, SIPEventService eventService)
        {
            _logger = logger;
            _eventService = eventService;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Starting SIP Proxy Service.");

            // Determine the Proxy's IP address
            _proxyIPAddress = GetLocalIPAddress();
            if (_proxyIPAddress == null)
            {
                _logger.LogError("Unable to determine the local IP address. SIP Proxy Service cannot start.");
                throw new InvalidOperationException("Local IP Address not found.");
            }
            _logger.LogInformation($"SIP Proxy is using IP Address: {_proxyIPAddress}");

            // Configure SIP Transport
            _sipTransport = new SIPTransport();

            // Add UDP SIP channels for IPv4 with the correct IP address
            var udpChannel = new SIPUDPChannel(new IPEndPoint(_proxyIPAddress, _listenPort));
            _sipTransport.AddSIPChannel(udpChannel);

            // Optionally add IPv6 channel if needed
            // var ipv6UdpChannel = new SIPUDPChannel(new IPEndPoint(IPAddress.IPv6Any, _listenPort));
            // _sipTransport.AddSIPChannel(ipv6UdpChannel);

            // Register event handlers for SIP Transport
            _sipTransport.SIPTransportRequestReceived += SIPTransportRequestReceived;
            _sipTransport.SIPTransportResponseReceived += SIPTransportResponseReceived;

            // Optional: Trace all incoming SIP requests and responses
            _sipTransport.SIPRequestInTraceEvent += SIPRequestInTraceEvent;
            _sipTransport.SIPResponseOutTraceEvent += SIPResponseOutTraceEvent;

            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Stopping SIP Proxy Service.");

            _sipTransport?.Shutdown();

            return Task.CompletedTask;
        }

        public void Dispose()
        {
            _sipTransport?.Dispose();
        }

        /// <summary>
        /// Retrieves the local IP address that the SIP Proxy should use.
        /// </summary>
        /// <returns>The local IPAddress or null if not found.</returns>
        private IPAddress GetLocalIPAddress()
        {
            IEnumerable<NetworkInterface> networkInterfaces = NetworkInterface.GetAllNetworkInterfaces();

            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
            {
                networkInterfaces = networkInterfaces
                .Where(n => n.OperationalStatus == OperationalStatus.Up &&
                            (n.NetworkInterfaceType != NetworkInterfaceType.Loopback) &&
                            (n.NetworkInterfaceType != NetworkInterfaceType.Tunnel) &&
                            n.Name.Contains("External", StringComparison.OrdinalIgnoreCase));
            }
            else
            {
                networkInterfaces = networkInterfaces
              .Where(n => n.OperationalStatus == OperationalStatus.Up &&
                          (n.NetworkInterfaceType != NetworkInterfaceType.Loopback) &&
                          (n.NetworkInterfaceType != NetworkInterfaceType.Tunnel));
            }

            foreach (var ni in networkInterfaces)
            {
                var ipProps = ni.GetIPProperties();
                foreach (var addr in ipProps.UnicastAddresses)
                {
                    if (addr.Address.AddressFamily == AddressFamily.InterNetwork)
                    {
                        return addr.Address;
                    }
                }
            }

            return null;
        }

        /// <summary>
        /// Handles incoming SIP requests.
        /// </summary>
        private async Task SIPTransportRequestReceived(
            SIPEndPoint localEndPoint,
            SIPEndPoint remoteEndPoint,
            SIPRequest sipRequest)
        {
            try
            {
                switch (sipRequest.Method)
                {
                    case SIPMethodsEnum.REGISTER:
                        await HandleRegisterRequest(sipRequest, remoteEndPoint, localEndPoint);
                        break;

                    case SIPMethodsEnum.INVITE:
                        await HandleInviteRequest(sipRequest, remoteEndPoint, localEndPoint);
                        break;

                    case SIPMethodsEnum.OPTIONS:
                        await HandleOptionsRequest(sipRequest, remoteEndPoint, localEndPoint);
                        break;

                    case SIPMethodsEnum.ACK:
                        await HandleAckRequest(sipRequest, remoteEndPoint, localEndPoint);
                        break;

                    case SIPMethodsEnum.BYE:
                        await HandleByeRequest(sipRequest, remoteEndPoint, localEndPoint);
                        break;

                    default:
                        _logger.LogDebug($"Received unhandled SIP method: {sipRequest.Method}. Sending 501 Not Implemented.");
                        SIPResponse notImplemented = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.NotImplemented, null);
                        await _sipTransport.SendResponseAsync(notImplemented);
                        break;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error processing SIP request: {ex.Message}");
                SIPResponse serverError = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.InternalServerError, null);
                await _sipTransport.SendResponseAsync(serverError);
            }
        }

        /// <summary>
        /// Handles incoming SIP responses.
        /// </summary>
        private async Task SIPTransportResponseReceived(
            SIPEndPoint localEndPoint,
            SIPEndPoint remoteEndPoint,
            SIPResponse sipResponse)
        {
            try
            {
                _logger.LogDebug($"Received SIP Response: {sipResponse.StatusCode} {sipResponse.ReasonPhrase} for {sipResponse.Header.CSeqMethod} from {remoteEndPoint}.");

                // Log the entire SIP Response for inspection
                _logger.LogDebug($"Full SIP Response:\n{sipResponse}");

                if (sipResponse.Header.CSeqMethod == SIPMethodsEnum.INVITE)
                {
                    // Correctly extract the Call-ID value
                    string callId = sipResponse.Header.CallId;

                    _logger.LogDebug($"Extracted Call-ID: {callId}");

                    if (_callIdToCallerEndPoint.TryGetValue(callId, out SIPEndPoint originalCallerEndPoint))
                    {
                        _logger.LogDebug($"Original caller endpoint found: {originalCallerEndPoint}");

                        // Remove top Via header for correct forwarding
                        SIPResponse forwardedResponse = sipResponse.Copy();
                        forwardedResponse.Header.Vias.PopTopViaHeader();

                        // Log the forwarded response and its Via headers
                        _logger.LogDebug($"Forwarded SIP Response after popping Via:\n{forwardedResponse}");
                        foreach (var via in forwardedResponse.Header.Vias.Via)
                        {
                            _logger.LogDebug($"Via Header: {via}");
                        }

                        _logger.LogDebug($"Forwarding SIP Response {sipResponse.StatusCode} to {originalCallerEndPoint}.");

                        // Forward the response back to the caller
                        var sendResult = await _sipTransport.SendResponseAsync(forwardedResponse);

                        // Log the result of SendResponseAsync
                        _logger.LogDebug($"SendResponseAsync result: {sendResult}");

                        // Trigger event for the SIP response
                        _eventService.TriggerSIPResponseEvent(sipResponse);

                        // Remove the Call-ID mapping and active transaction
                        _callIdToCallerEndPoint.TryRemove(callId, out _);
                        _activeInviteTransactions.TryRemove(callId, out _);
                    }
                    else
                    {
                        _logger.LogWarning($"No mapping found for Call-ID: {callId}. Cannot forward response.");
                    }
                }
                else
                {
                    // Handle other SIP responses if necessary
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error processing SIP response: {ex.Message}");
            }
        }

        /// <summary>
        /// Handles REGISTER SIP requests.
        /// </summary>
        private async Task HandleRegisterRequest(
            SIPRequest sipRequest,
            SIPEndPoint remoteEndPoint,
            SIPEndPoint localEndPoint)
        {
            _logger.LogDebug($"Processing REGISTER request from {remoteEndPoint}.");

            // Always respond with '100 Trying' first
            SIPResponse trying = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Trying, null);
            await _sipTransport.SendResponseAsync(trying);

            // Check for Contact header
            if (sipRequest.Header.Contact != null && sipRequest.Header.Contact.Count > 0)
            {
                SIPContactHeader contact = sipRequest.Header.Contact[0];

                // Determine the actual IP and port from the remote endpoint
                IPAddress actualIP = remoteEndPoint.Address;
                int actualPort = remoteEndPoint.Port;

                // **Create a new Contact URI without ';ob'**
                string uriStr = $"sip:{sipRequest.Header.From.FromURI.User}@{actualIP}:{actualPort}";
                SIPURI actualContactURI = SIPURI.ParseSIPURI(uriStr);

                // Create a new Contact header with the updated URI
                SIPContactHeader actualContact = new SIPContactHeader(null, actualContactURI);

                // Determine expiry
                long expiry = contact.Expires > 0 ? contact.Expires : sipRequest.Header.Expires;

                string username = sipRequest.Header.From.FromURI.User.ToLowerInvariant();
                string domain = sipRequest.Header.From.FromURI.Host;

                // Update or add the SIPAccountBinding
                if (_sipRegistrations.TryGetValue(username, out SIPAccountBinding existingBinding))
                {
                    if (existingBinding.RegisteredContact.ToString() == actualContact.ToString())
                    {
                        _logger.LogDebug($"User '{username}' is already registered with the same contact. Updating expiry.");
                        // Update expiry
                        existingBinding.Expiry = (int)expiry;
                        _sipRegistrations[username] = existingBinding;

                        // Trigger event for updated registration
                        _eventService.TriggerSIPRegistrationEvent(existingBinding);
                    }
                    else
                    {
                        _logger.LogDebug($"User '{username}' re-registering with a new contact URI.");
                        // Update the binding with new contact
                        SIPAccountBinding newBinding = new SIPAccountBinding(
                            existingBinding.SIPAccount,
                            actualContactURI,
                            remoteEndPoint,
                            localEndPoint,
                            (int)expiry
                        );
                        _sipRegistrations[username] = newBinding;

                        // Trigger event for new registration
                        _eventService.TriggerSIPRegistrationEvent(newBinding);
                    }
                }
                else
                {
                    // Create SIPAccount and SIPAccountBinding
                    SIPAccount sipAccount = new SIPAccount(username, domain);
                    SIPAccountBinding binding = new SIPAccountBinding(
                        sipAccount,
                        actualContactURI,
                        remoteEndPoint,
                        localEndPoint,
                        (int)expiry
                    );

                    // Register the binding
                    _sipRegistrations[username] = binding;

                    _logger.LogDebug($"Registered user '{username}' with contact '{actualContactURI}' from '{remoteEndPoint}'.");

                    // Trigger event for the registration
                    _eventService.TriggerSIPRegistrationEvent(binding);
                }

                // Respond with '200 OK' including the new Contact header
                SIPResponse ok = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Ok, null);
                ok.Header.Contact = new List<SIPContactHeader> { actualContact };
                await _sipTransport.SendResponseAsync(ok);
            }
            else
            {
                _logger.LogWarning("REGISTER request missing Contact header. Sending 400 Bad Request.");
                SIPResponse badRequest = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.BadRequest, null);
                await _sipTransport.SendResponseAsync(badRequest);
            }
        }

        /// <summary>
        /// Handles OPTIONS SIP requests.
        /// </summary>
        private async Task HandleOptionsRequest(
            SIPRequest sipRequest,
            SIPEndPoint remoteEndPoint,
            SIPEndPoint localEndPoint)
        {
            _logger.LogDebug($"Processing OPTIONS request from {remoteEndPoint}.");

            // Respond with '200 OK' including allowed methods and supported SDP
            SIPResponse ok = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Ok, null);
            ok.Header.Allow = "INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, INFO, MESSAGE, PRACK, UPDATE";
            ok.Header.Accept = "application/sdp";
            await _sipTransport.SendResponseAsync(ok);
        }

        /// <summary>
        /// Handles INVITE SIP requests by forwarding them to the target user.
        /// </summary>
        private async Task HandleInviteRequest(
            SIPRequest sipRequest,
            SIPEndPoint remoteEndPoint,
            SIPEndPoint localEndPoint)
        {
            _logger.LogDebug($"Processing INVITE request from {remoteEndPoint}.");

            // Extract target username from SIP URI (e.g., sip:1003@10.0.1.249)
            string targetUsername = sipRequest.URI.User.ToLowerInvariant();

            // Lookup the target user's contact binding
            if (!_sipRegistrations.TryGetValue(targetUsername, out SIPAccountBinding targetBinding))
            {
                _logger.LogWarning($"Target user '{targetUsername}' not found. Sending 404 Not Found.");
                SIPResponse notFound = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.NotFound, null);
                await _sipTransport.SendResponseAsync(notFound);
                return;
            }

            // Create a copy of the INVITE request to forward
            SIPRequest forwardedInvite = sipRequest.Copy();

            //// Strip ';ob' parameter from Contact headers if present
            //if (forwardedInvite.Header.Contact != null && forwardedInvite.Header.Contact.Count > 0)
            //{
            //    foreach (var contact in forwardedInvite.Header.Contact)
            //    {
            //        if (contact.Uri.Parameters.Contains("ob"))
            //        {
            //            contact.Uri.Parameters.Remove("ob");
            //            _logger.LogDebug($"Removed 'ob' parameter from Contact header: {contact.Uri}");
            //        }
            //    }
            //}

            // Ensure we preserve the correct contact information and port for the target
            forwardedInvite.URI = targetBinding.RegisteredContact;

            // Update the Via header to include the proxy's information
            forwardedInvite.Header.Vias.PushViaHeader(new SIPViaHeader(
                _proxyIPAddress.ToString(), // Use proxy IP
                _listenPort, // Use proxy listening port
                SIPConstants.SIP_BRANCH_MAGICCOOKIE + CallProperties.CreateBranchId()
            ));

            // Set the correct "From" tag if not already set
            forwardedInvite.Header.From.FromTag = sipRequest.Header.From.FromTag ?? CallProperties.CreateNewTag();

            // Clear the Route headers to prevent routing loops
            forwardedInvite.Header.Routes = new SIPRouteSet();

            // Map Call-ID to the original caller's endpoint for response routing
            string callId = sipRequest.Header.CallId;
            _callIdToCallerEndPoint[callId] = remoteEndPoint;

            // Forward the INVITE to the target endpoint
            SIPEndPoint destinationEndPoint = targetBinding.RemoteEndPoint;
            _logger.LogDebug($"Forwarding INVITE to {destinationEndPoint.Address}:{destinationEndPoint.Port}");

            // Trigger event for INVITE forwarding
            _eventService.TriggerSIPInviteEvent(forwardedInvite);

            // Forward the INVITE using UACInviteTransaction
            UACInviteTransaction inviteTransaction = new UACInviteTransaction(_sipTransport, forwardedInvite, null);

            // Store the transaction to prevent garbage collection
            _activeInviteTransactions[callId] = inviteTransaction;

            // Handle final responses from the target
            inviteTransaction.UACInviteTransactionFinalResponseReceived += async (localSIPEndPoint, remoteEndPointResponse, sipTransaction, sipResponse) =>
            {
                _logger.LogDebug($"Received SIP Response: {sipResponse.StatusCode} {sipResponse.ReasonPhrase} from {destinationEndPoint}.");

                if (_callIdToCallerEndPoint.TryGetValue(callId, out SIPEndPoint originalCallerEndPoint))
                {
                    // Remove top Via header before forwarding
                    SIPResponse forwardedResponse = sipResponse.Copy();
                    forwardedResponse.Header.Vias.PopTopViaHeader();

                    // Forward the response back to the caller
                    _logger.LogDebug($"Forwarding SIP Response {sipResponse.StatusCode} to {originalCallerEndPoint}");
                    await _sipTransport.SendResponseAsync(forwardedResponse);

                    // Cleanup after forwarding
                    _callIdToCallerEndPoint.TryRemove(callId, out _);
                    _activeInviteTransactions.TryRemove(callId, out _);

                }

                return SocketError.Success;
            };

            // Handle transaction failures
            inviteTransaction.UACInviteTransactionFailed += async (sipTransaction, failureReason) =>
            {
                _logger.LogError($"INVITE transaction failed: {failureReason}");

                if (_callIdToCallerEndPoint.TryGetValue(callId, out SIPEndPoint originalCallerEndPoint))
                {
                    // Respond with '500 Server Error' to the caller
                    SIPResponse serverError = SIPResponse.GetResponse(forwardedInvite, SIPResponseStatusCodesEnum.InternalServerError, null);
                    await _sipTransport.SendResponseAsync(serverError);

                    // Cleanup after failure
                    _callIdToCallerEndPoint.TryRemove(callId, out _);
                    _activeInviteTransactions.TryRemove(callId, out _);
                }
            };
        }

        /// <summary>
        /// Handles ACK SIP requests.
        /// </summary>
        private async Task HandleAckRequest(
            SIPRequest sipRequest,
            SIPEndPoint remoteEndPoint,
            SIPEndPoint localEndPoint)
        {
            _logger.LogDebug($"Processing ACK request from {remoteEndPoint}.");

            // In a Proxy, ACKs typically do not require forwarding.
            // However, you can log them or perform additional actions if necessary.

            // Trigger event for ACK
            _eventService.TriggerSIPAckEvent(sipRequest);

            await Task.CompletedTask;
        }

        /// <summary>
        /// Handles BYE SIP requests by forwarding them to the target user.
        /// </summary>
        private async Task HandleByeRequest(
            SIPRequest sipRequest,
            SIPEndPoint remoteEndPoint,
            SIPEndPoint localEndPoint)
        {
            _logger.LogDebug($"Processing BYE request from {remoteEndPoint}.");

            // Extract Call-ID to find the associated call
            string callId = sipRequest.Header.CallId;

            _logger.LogDebug($"Extracted Call-ID: {callId}");

            if (_callIdToCallerEndPoint.TryGetValue(callId, out SIPEndPoint originalCallerEndPoint))
            {
                _logger.LogDebug($"Original caller endpoint found: {originalCallerEndPoint}");

                // Identify the target user based on SIP URI in BYE
                string targetUsername = sipRequest.URI.User.ToLowerInvariant();

                if (_sipRegistrations.TryGetValue(targetUsername, out SIPAccountBinding targetBinding))
                {
                    // Create a copy of the BYE request to forward
                    SIPRequest forwardedBye = sipRequest.Copy();

                    // **Strip ';ob' parameter from Contact headers if present**
                    if (forwardedBye.Header.Contact != null && forwardedBye.Header.Contact.Count > 0)
                    {
                        foreach (var contact in forwardedBye.Header.Contact)
                        {
                            if (contact.ContactURI.Parameters.Has("ob"))
                            {
                                contact.ContactURI.Parameters.Remove("ob");
                                _logger.LogDebug($"Removed 'ob' parameter from Contact header: {contact.ContactURI}");
                            }
                        }
                    }

                    // Update SIP headers for forwarding
                    forwardedBye.Header.Vias.PushViaHeader(new SIPViaHeader(
                        _proxyIPAddress.ToString(), // Use the actual Proxy IP
                        _listenPort,
                        SIPConstants.SIP_BRANCH_MAGICCOOKIE + CallProperties.CreateBranchId()
                    ));

                    // Update From and To tags
                    forwardedBye.Header.From.FromTag = sipRequest.Header.From.FromTag ?? CallProperties.CreateNewTag();
                    forwardedBye.Header.To.ToTag = sipRequest.Header.To.ToTag; // Preserve To tag

                    // Clear Route headers to prevent routing loops
                    forwardedBye.Header.Routes = new SIPRouteSet();

                    // Determine the destination endpoint
                    SIPEndPoint destinationEndPoint = targetBinding.RemoteEndPoint;

                    _logger.LogDebug($"Forwarding BYE to {destinationEndPoint}.");

                    // Trigger event for BYE forwarding
                    _eventService.TriggerSIPByeEvent(forwardedBye);

                    // Forward the BYE using SIPNonInviteTransaction
                    SIPNonInviteTransaction byeTransaction = new SIPNonInviteTransaction(_sipTransport, forwardedBye, null);

                    // Store the transaction if needed (optional)

                    // Log the forwarded BYE
                    _logger.LogDebug($"Forwarded BYE:\n{forwardedBye}");
                    foreach (var via in forwardedBye.Header.Vias.Via)
                    {
                        _logger.LogDebug($"Via Header: {via}");
                    }

                    // Handle final responses from the target
                    byeTransaction.NonInviteTransactionFinalResponseReceived += async (localSIPEndPoint, remoteEndPointResponse, sipTransaction, sipResponse) =>
                    {
                        _logger.LogDebug($"Received SIP Response: {sipResponse.StatusCode} {sipResponse.ReasonPhrase} from {destinationEndPoint}.");

                        // Log the entire SIP Response from target
                        _logger.LogDebug($"Full SIP Response from target:\n{sipResponse}");

                        // Remove top Via header before forwarding
                        SIPResponse forwardedResponse = sipResponse.Copy();
                        forwardedResponse.Header.Vias.PopTopViaHeader();

                        // Log the forwarded response and its Via headers
                        _logger.LogDebug($"Forwarded SIP Response after popping Via:\n{forwardedResponse}");
                        foreach (var via in forwardedResponse.Header.Vias.Via)
                        {
                            _logger.LogDebug($"Via Header: {via}");
                        }

                        _logger.LogDebug($"Forwarding SIP Response {sipResponse.StatusCode} to {originalCallerEndPoint}.");

                        // Forward the response back to the caller
                        var sendResult = await _sipTransport.SendResponseAsync(forwardedResponse);

                        // Log the result of SendResponseAsync
                        _logger.LogDebug($"SendResponseAsync result: {sendResult}");

                        // Trigger event for the SIP response
                        _eventService.TriggerSIPResponseEvent(sipResponse);

                        // Remove the Call-ID mapping as the call is terminated
                        _callIdToCallerEndPoint.TryRemove(callId, out _);

                        return SocketError.Success;
                    };

                    // Handle transaction failures
                    byeTransaction.NonInviteTransactionFailed += (sipTransaction, failureReason) =>
                    {
                        _logger.LogError($"BYE transaction failed: {failureReason}");

                        // Optionally, trigger an event for BYE failure
                        _eventService.TriggerSIPFailureEvent(callId, failureReason);
                    };
                }
                else
                {
                    _logger.LogWarning($"Target user '{targetUsername}' not found. Cannot forward BYE. Sending 404 Not Found.");
                    SIPResponse notFound = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.NotFound, null);
                    await _sipTransport.SendResponseAsync(notFound);
                }
            }
            else
            {
                _logger.LogWarning($"No Call-ID mapping found for Call-ID: {callId}. Cannot forward BYE. Sending 400 Bad Request.");
                SIPResponse badRequest = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.BadRequest, null);
                await _sipTransport.SendResponseAsync(badRequest);
            }
        }

        /// <summary>
        /// Logs incoming SIP requests.
        /// </summary>
        private void SIPRequestInTraceEvent(
            SIPEndPoint localEndPoint,
            SIPEndPoint remoteEndPoint,
            SIPRequest sipRequest)
        {
            _logger.LogDebug($"REQUEST IN {remoteEndPoint} -> {localEndPoint}: {sipRequest.Method} {sipRequest.URI}");
            // Uncomment below to log full SIP messages
            // _logger.LogDebug(sipRequest.ToString());
        }

        /// <summary>
        /// Logs outgoing SIP responses.
        /// </summary>
        private void SIPResponseOutTraceEvent(
            SIPEndPoint localEndPoint,
            SIPEndPoint remoteEndPoint,
            SIPResponse sipResponse)
        {
            _logger.LogDebug($"RESPONSE OUT {localEndPoint} -> {remoteEndPoint}: {sipResponse.StatusCode} {sipResponse.ReasonPhrase}");
            // Uncomment below to log full SIP messages
            // _logger.LogDebug(sipResponse.ToString());
        }

        public List<SIPAccountBinding> GetRegisteredAccounts()
        {
            return _sipRegistrations.Values.ToList();
        }
    }`

**Comment by sipsorcery** [comment]
Ouch, that looks nasty. ChatGPT is definitely struggling there. You can throw that code away.

Before you try again you should consider using an existing SIP Proxy such as https://github.com/kamailio/kamailio. Something like that should work fine on your Pi and be lighter on resources than Asterisk.

You might even be able to connect to MicroSIP directly. When I test with MicroSIP I create an account called local, put in some arbitrary username and a local IP address for the domain and that's it. You can then call MicroSIP by username@<microsip ipaddress> and it should answer.

**Comment by sipsorcery** [comment]
Feel free to re-open if any further questions.
