### ISSUE TITLE
Unused argument on `VoIPMediaSession` Class

### ISSUE THREAD

**Issue by alexander-zerpa** [sipsorcery-org/sipsorcery#1219]
Here you set `musicFilePath` in order to load audio to the media session, but then don't do anything with it.

https://github.com/sipsorcery-org/sipsorcery/blob/88339ba9e5bb8e0020b75467571937587e378854/src/app/Media/VoIPMediaSession.cs#L72-L90

**Comment by sipsorcery** [comment]
That snuck in under the radar somehow. Fixed in #1220.
