### ISSUE TITLE
Determine if Call Was Answered by Person or Voicemail System

### ISSUE THREAD

**Issue by babawarrior** [sipsorcery-org/sipsorcery#1228]
How can I detect if a call went to voicemail or was picked up by a person? I noticed that callResult still shows success, and IsCallActive remains true even when no one actually picks up. I considered adding a system that counts up to 30 seconds—if the call is answered after that, it would be counted as going to voicemail. However, this feels like a workaround and could lead to false positives. Is there a better way to accurately detect if a call was answered by a person or went to voicemail?

**Comment by sipsorcery** [comment]
There's no way to tell at the SIP signalling level. The SIP traffic is identical no matter who or what picks up the call.

The only option that occurs to me is some kind of analysis of the audio stream and detect whether the speech matches known phrases. That type of audio processing capability does not exist in this library.
