### ISSUE TITLE
Ffmpeg 'Specific method is not supported'

### ISSUE THREAD

**Issue by HighOnLemonz** [sipsorcery-org/sipsorcery#1237]
Hi,

Running the WebRTCMp4Source example I hit a block at the FFmpegInit.Initialize line where I always get 'Specific method is not supported' and nothing else.

I am using ffmpeg.exe Windows build and its the version from 21.10.2024.
Also if this information is useful I'll just paste is here
libavutil      59. 44.100 / 59. 44.100
libavcodec     61. 22.100 / 61. 22.100
libavformat    61.  9.100 / 61.  9.100
libavdevice    61.  4.100 / 61.  4.100
libavfilter    10.  6.100 / 10.  6.100
libswscale      8.  6.100 /  8.  6.100
libswresample   5.  4.100 /  5.  4.100
libpostproc    58.  4.100 / 58.  4.100

Any hints on how to get pass this?

Thank you

**Comment by sipsorcery** [comment]
It's usually a mismatch in the FFmpeg version and the C# wrapper library. Unfortunately that's a very fragile mechanism.

If you install FFMpeg as per the instructions [here](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg?tab=readme-ov-file#for-windows) and use the latest code, or nuget packages, it should work.

**Comment by HighOnLemonz** [comment]
Thanks, it works now. Have a good one.
