### ISSUE TITLE
Example "SIPToWebRtcBridgeVideo" not working

### ISSUE THREAD

**Issue by mawiedemann** [sipsorcery-org/sipsorcery#1239]
Hi, 
I set up a local FreeSwitch with just the default Settings and tested the SIPToWebRtcBridgeVideo example by adding a SIPRegistrationUserAgent and calling it with MicroSIP. The audio works but the video does not and the console puts out the warning "Discarding RTP packet, VP8 header Start bit not set.". However if you dont add the audiotracks to the peer connection and the rtpSession the video works just fine but obviously there is no audio anymore. Videocalling from MicroSIP to MicroSIP via the Freeswitch works so FreeSwitch should not be the problem? 

Does anyone know if I am doing something wrong or is this example just outdated?

**Comment by sipsorcery** [comment]
It's outdated, hasn't been tested in a while. It didn't work properly for me either. I'll see if I can get it working over the next few days.

**Comment by sipsorcery** [comment]
I was able to get the example working successfully with the [VideoPhoneCmdLine](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/VideoPhoneCmdLine/Program.cs) example.

Steps:
1. Start the SIPToWebRtcBridgeVideo example: `sipsorcery\examples\WebRTCExamples\SIPToWebRtcBridgeVideo>dotnet run`
2. Call it with the VideoPhoneCmdLine: `sipsorcery\examples\SIPExamples\VideoPhoneCmdLine>dotnet run -- --dst=127.0.0.1 --tp`
3. Open the `webrtcsipvideo.html` example is a browser and press connect.
