### ISSUE TITLE
Add ability to prefer H264

### ISSUE THREAD

**Issue by ispysoftware** [sipsorcery-org/sipsorcery#1247]
My web clients  vary in their SDP over whether they prefer VP8 (firefox) or H264 (chrome) but they support both. The server side app performance is much (much) better with H264. 

Unfortunately the sdp negotiation chooses the first option.

I've kind of hacked it by modifying GetCompatibleFormats in SDPAudioVideoMediaFormat.cs so it looks like

 ```
public static List<SDPAudioVideoMediaFormat> GetCompatibleFormats(List<SDPAudioVideoMediaFormat> a, List<SDPAudioVideoMediaFormat> b, bool preferH264 = true)
 {
     List<SDPAudioVideoMediaFormat> compatible = new List<SDPAudioVideoMediaFormat>();

     if (a == null || a.Count == 0)
     {
         // Preferable to return an empty list.
         //throw new ArgumentNullException("a", "The first media format list supplied was empty.");
     }
     else if (b == null || b.Count == 0)
     {
         // Preferable to return an empty list.
         //throw new ArgumentNullException("b", "The second media format list supplied was empty.");
     }
     else
     {
         foreach (var format in a)
         {
             if (b.Any(x => AreMatch(format, x)))
             {
                 if (preferH264 && (format.Rtpmap ?? "").StartsWith("H264"))
                 {
                     return new List<SDPAudioVideoMediaFormat> { format };
                 }
                 compatible.Add(format);
             }
         }
     }
     
     return compatible;
 }
```

This results in both firefox and chrome using H264 and anything that doesn't support H264 drops back to VP8. It'd be good to be able to provide this as a flag or option when creating the media tracks, like a preferH264 flag.

Also, I dont think we need to call GetSendingFormat() on every call to SendVideo (and SendAudio), seems like a bit of a waste of CPU cycles..

```
 private SDPAudioVideoMediaFormat sendingFormat;
 private bool sendingFormatFound = false;
 public void SendVideo(uint durationRtpUnits, byte[] sample)
 {
     if (!sendingFormatFound)
     {
         sendingFormat = GetSendingFormat();
         sendingFormatFound = true;
     }

     int payloadID = Convert.ToInt32(sendingFormat.ID);
```

I'd do this as a pull request but my version is in a bit of a mess at the moment

**Comment by sipsorcery** [comment]
You can do that already when you create the IAudioSource and/or iVideoSource.

```
 SIPSorceryMedia.FFmpeg.FFmpegInit.Initialise(SIPSorceryMedia.FFmpeg.FfmpegLogLevelEnum.AV_LOG_VERBOSE, null, logger);
 var mediaFileSource = new SIPSorceryMedia.FFmpeg.FFmpegFileSource(MP4_PATH, false, new AudioEncoder());
 mediaFileSource.RestrictFormats(x => x.Codec == VideoCodecsEnum.VP8);
 mediaFileSource.RestrictFormats(x => x.Codec == AudioCodecsEnum.PCMU);
```

**Comment by ispysoftware** [comment]
Right but won't that fail if the client doesn't support h264?

**Comment by sipsorcery** [comment]
> Right but won't that fail if the client doesn't support h264?

Yes, that's correct. If you do want to offer both VP8 and H264 with a preference for H264 you should add H264 as the first supported format when adding your MediaStreamTrack. SDP negotiation rules specify that the first common format "should" be used so if you put H264 first you should have a good chance it will get selected.

Your note about GetSendingFormat being inefficient also seems correct. If you do get a chance to submit a PR for that when you're able it would be appreciated.

**Comment by ispysoftware** [comment]
Yeah I'm doing that, I have

   ```
 internal static List<VideoFormat> GetSupportedVideoFormats() => new List<VideoFormat>
{
    new VideoFormat(
        VideoCodecsEnum.H264,
        H264_FORMATID_BASELINE,
        VideoFormat.DEFAULT_CLOCK_RATE,
        "packetization-mode=1"
    ),
    new VideoFormat(
        VideoCodecsEnum.VP8,
        VP8_FORMATID,
        VideoFormat.DEFAULT_CLOCK_RATE
    )
};
```

... but in the sdp that comes in from firefox, the first format is VP8 which is what SipSorcery selects as it's the first match. My code changes above will look for H264 and force that instead if it's available.

It might be better to use the sipsorcery order preference instead of the web browser preferences but i got in a bit of a tangle trying that with it selecting H264 and sending VP8 frames and vice versa.

**Comment by sipsorcery** [comment]
I don't think there's going to be a default way to solve that. The choice being made is inline with the SDP spec. The other peer, FireFox in this case, will apply the same rules which allows both peers to use a common video format.

**Comment by ispysoftware** [comment]
well.. i mean, i did solve it up the top there ^^
VP8 on my computer uses about 11% CPU, H264 uses around 0.2% CPU so it's quite important to use H264 if at all possible

**Comment by sipsorcery** [comment]
Was it a one way stream with you sending? If not what format did FireFox send?

While SDP does specify both peers should use the same format there's nothing that prevents different ones. The RTP payload ID indicates the fromat so it's feasible to send and receive different streams. I suspect the intent of the spec is that a single format is more efficient as it measn a peer only has to intiailise one codec for sending/receiving.

I recently fixed a bug where there the sipsorcery codec selection was wrong and chose PCMU instead of PCMA. The sipsorcery peer sent PCMU (payload id 0) and the remote peer also swtiched to using payload id 0 but kept sending PCMA resulting in corrupted audio.

The above was for a VoIP call though not WebRTC. It's possible there's been an update to SDP for WebRTC.

**Comment by ispysoftware** [comment]
Also, and it might be related, I think there's some weirdness going on with the matching of the streams.
If I edit the SDP offer before it gets sent by Firefox to put H264 first (using codecshelper js) it still selects VP8 in sipsorcery.
I found out that it's because the H264 int in GetSupportedVideoFormats is 100 and the H264 int in Firefox is 97 - if i change the int in GetSupportedVideoFormats to 97 then it uses H264. I don't think these ints should have to match for SipSorcery to choose them as they're arbitrary.

I'm streaming video and audio one way server to browser.

**Comment by ispysoftware** [comment]
This AreMatch method in  \net\SDP\SDPAudioVideoMediaFormat.cs shouldn't be comparing the ID's
```
if (format1.ID < DYNAMIC_ID_MIN
                && format1.ID == format2.ID
                && string.Equals(format1.Name(), format2.Name(), StringComparison.OrdinalIgnoreCase))
```
A format with ID 98 from the browser may match perfectly with ID 101 in SipSorcery.
Also the fmtp parameter does matter - it needs to configure the encoder with packetization and profile level ids

**Comment by sipsorcery** [comment]
I think you could be right about the SDP format matching. I recall in the past issues when non-well known format IDs were used. If you're not in a position to create a PR (another one) for it I can add it to the enhancements list.

**Comment by ispysoftware** [comment]
OK I've been looking into this some more - the code to select the profile definitely needs to be expanded beyond first match.
When it's using VP8 it works ok as VP8 is very forgiving but uses a lot of CPU. H264 is much better performance but it's much more complicated to setup.
We need to add a bunch of levels to the local encoders list (I think using baseline profile is fine) and then have it select the matching H264 encoder based on the resolution of the video stream. The first one is usually level 3.1 which isn't good at high resolution streaming. It needs to be much more intelligent about selecting matching formats.

**Comment by ispysoftware** [comment]
@sipsorcery Is SetVideoEncoderBitrate supposed to be called automagically via some feedback/ stream monitoring/ webrtc mechanism?

**Comment by ispysoftware** [comment]
I've resolved the performance issues with VP8 (It was my sws flags using a high quality color matching flag). It is using H264 when VP8 isn't available (on IOS).
There does need to be an update though to choose the most appropriate encoding profile/ level for the stream resolution and framerate. I'll get to that at some point unless you do first :)
