### ISSUE TITLE
Optimisations required for 1080p

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery-org/sipsorcery#384]
Attempting to receive a VP8 encoded video stream at 1080p (1920x1080) will quickly degrade to become very laggy and then corrupted. The sipsorcery library is not able to decode the video stream fast enough which results in the network buffer filling up and then dropping packets. The library is able to keep up with 720p (1280x720) on a Win10 i7 CPU.

The main bottleneck is the [I420toBGR](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions/blob/a786969f05f8d086fb47f1ef94f6f31d1a99d3d5/src/PixelConverter.cs#L237) function.

![1080p_hotpath](https://user-images.githubusercontent.com/197660/102776218-42c7c880-4386-11eb-9f31-4ef2bca04c5f.png)

![1080p_hotpath_diags](https://user-images.githubusercontent.com/197660/102776316-70ad0d00-4386-11eb-8303-a8d648526cf6.png)

**Comment by jvakos** [comment]
I don't have any expirance in video enc/dec but in past I had to do some image proccecing (pixel by pixel proccecing). Back then, I gave a performance boost by using `unsafe ` code block.

**Comment by 4hera** [comment]
Hi Aaron,
Is there any current development on the issue?

**Comment by sipsorcery** [comment]
@4hera ran out of steam on this one. No further developments have occurred.

**Comment by 4hera** [comment]
> [@4hera](https://github.com/4hera) ran out of steam on this one. No further developments have occurred.

Normally, I capture the Windows Desktop image via DirectX and create an encoder. And I send it via webrtc. However, the quality is still low. Even though I stream the mp4 source via webrtc with ffmpeg, the quality is still low. Do you have any suggestions to increase the quality?

**Comment by sipsorcery** [comment]
> Do you have any suggestions to increase the quality?

TBH if you need good video performance this library is not going to cut it. Even with hooks into the native [Windows Media Foundation](https://github.com/sipsorcery/mediafoundationsamples) the overhead of backwards and forwards across the managed to native boundary is a killer. Same with FFmpeg that boundary is the biggest problem.

If you need performant video encoding you'll most likely have to go C++. Here is my very crude [libwebrtc demo app](https://github.com/sipsorcery/webrtc-interop/tree/master/libwebrtc) in case it's of any use.

**Comment by 4hera** [comment]
Thank you very much for your interest.
