### ISSUE TITLE
Add proper RTCP feedback support as per RFC4585

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery-org/sipsorcery#385]
[RTCP Feedback](https://tools.ietf.org/html/rfc4585) provides a way to deal with dropped or missing RTP packets. 

For voice a dropped RTP packet is not worth taking any action over. Each voice packet is independent and if a packet is dropped it does not affect the decoding of subsequent packets.

For video a single dropped RTP packet can render the video stream unusable. For example VP8 requires all video frames since the previous key frame in order to be able to decode the current frame. The RTCP feedback mechanism provides a way to request that a dropped packet be re-transmitted or that a new key frame is desired.

An example of what occurs to a VP8 stream when one or more packets are dropped is shown below.

![720p_corruption](https://user-images.githubusercontent.com/197660/102777729-1792a880-4389-11eb-8c79-fb02c19eed3f.png)

**Comment by rafcsoares** [comment]
Hello @sipsorcery any improvement in congestioning control and FEC support?

**Comment by sipsorcery** [comment]
Sadly no. It took me a month to redo SCTP and now I've got to do some real work for a while.

**Comment by funnyrick01** [comment]
Hey @sipsorcery, 
after looking through the code, I have a feeling a solution for packet loss is still not implemented right?
With only ~0.1% packet loss rate it's making the video nearly unusable is some my cases.

Are there any plans to improve this in the near future with either FEC or NACK PLI support?
If not how difficult would it be for me to implement a temporary dirty version of this myself?

**Comment by sipsorcery** [comment]
> after looking through the code, I have a feeling a solution for packet loss is still not implemented right?

Yes, that's still the case.

> Are there any plans to improve this in the near future with either FEC or NACK PLI support?

It's not something I'll be able to put any time into in the near future.

> If not how difficult would it be for me to implement a temporary dirty version of this myself?

Good question.

I would think the NACK PLI support wouldn't be a huge amount of effort. It should be a matter of catching the picture loss event from the video decoder and sending an RTCP packet to the remote peer.

I'm not familiar enough with forward error correction to guess how hard it would be. If it can be accomplished by setting parameters on the video codecs, which I suspect, then it "could" be easy.

**Comment by rafcsoares** [comment]
Hello @funnyrick01 ... a simple solution for you.

Register OnReceiveReport from RTCPeerConnection.

And implement a function that sends a keyframe from your encoder when receiving PLI.

For Example

`pc.OnReceiveReport += HandleOnReceiveReport;`

and

```
protected virtual void HandleOnReceiveReport(IPEndPoint endpoint, SDPMediaTypesEnum mediaType, RTCPCompoundPacket packet)
        {
            //When receive Feedback about missing frame, force keyframe
            if (packet != null &&
                (packet.ReceiverReport != null || packet.SenderReport != null))
            {
                if (mediaType == SDPMediaTypesEnum.video)
                {
                    //Pick Header Report
                    var header = packet.ReceiverReport != null ? packet.ReceiverReport.Header :
                        (packet.SenderReport != null ? packet.SenderReport.Header : null);

                    //Estimate KeyFrame Lost
                    if (header != null &&
                        header.PayloadFeedbackMessageType == PSFBFeedbackTypesEnum.PLI)
                    {
                        //TODO you need to implement this function
                        SendKeyFrameFromEncoder();
                    }
                }
            }
        }
```

**Comment by kuleshov-aleksei** [comment]
Hello! Is there any progress for this issue? I've noticed, there is commit https://github.com/sipsorcery-org/sipsorcery/commit/4db5d1ab70139a090166f1c1d600f23ec56424fe that allows sending raw RTCP packets, but data for this packets should be calculated externally. Are there any plans for implementing outgoing RTCP packets inside SIPSorcery?

**Comment by leo0104** [comment]
Hi @rafcsoares 
Thank you for your solution for sending PLI report :)

I also testet you suggestion on how to handle receive reports and it is not working.
I'm streaming video from server to chrome browser and simulate packet loss. Thereby I receive RTCP packets of type PSFB (Payload-specific feedback). The [PSFB message type](https://github.com/sipsorcery-org/sipsorcery/blob/37b5b6ceb2efd0a2c23b8701564a29bd68f1c655/src/net/RTCP/RTCPFeedback.cs#L61) in the [RTCP Header](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTCP/RTCPHeader.cs) is then always set to AFB (Application layer FB message).

In my opinion your solution is not working because you only check the ReceiverReport and SenderReport. But only feedback packets (with type RTPFB and PSFB) include feedback information (see [here](https://github.com/sipsorcery-org/sipsorcery/blob/37b5b6ceb2efd0a2c23b8701564a29bd68f1c655/src/net/RTCP/RTCPHeader.cs#L158)).

Are there any solution how to notice that the browser needs a new keyframe?

**Comment by 29654761** [comment]
I can't known when I need to send nack as a sender
