### ISSUE TITLE
AWS Kinesis Video Stream with WebRTC

### ISSUE THREAD

**Issue by tribaud** [sipsorcery-org/sipsorcery#396]
Hello, I wonder if the SIPsorcery Library can be used to connect to the AWS Kinesis Video Stream with WebRTC ?
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/what-is-kvswebrtc.html

I need to share a video from a Dot net application and I don't know where to start to configure AWS WebRTC in SIPSorcery.
Can you just tell me if the AWS Kinesis WebRTC is enough open to connect with SIPSorcery or If the AWS SDK is mandatory ?

Thanks for the answer

**Comment by sipsorcery** [comment]
I've wondered the same thing myself. It's on my list to see if this library can connect to AWS Kinesis but I don't know when I'll get to it. There's a chance someone else might have already attempted it, if so hopefully they'll spot this question.

**Comment by sipsorcery** [comment]
I did end up having a quick look at Amazon Kinesis. To get to the point where a WebRTC connection can be negotiated some specific set up is required with an Amazon service somewhere. While it's almost certainly possible to do the set up with the AWS .NET SDK it's not currently something I plan on implementing.
