### ISSUE TITLE
Using ArrayPool、Memory<byte> and Span<byte> at network layer.

### ISSUE THREAD

**Issue by xljiulang** [sipsorcery-org/sipsorcery#398]
### byte[] -> `Span<byte>`
eg `buffer = buffer.Take(outBufLen).ToArray()`, it will create a new array, but 0 alloced `span = span.Slice(outBufLen)`

### byte[] -> `Memory<byte>`
eg `PacketReceivedDelegate(UdpReceiver, int, IPEndPoint, byte[])`, maybe can delegate as `PacketReceivedDelegate(UdpReceiver, int, IPEndPoint, Memory<byte>[])`

###  Udp recv buffer -> `ArrayPool<byte>`
There's a Buffer.BlockCopy at udp EndReceiveFrom(IAsyncResult), we can `ArrayPool<byte>.Shared` to rent a buffer for recv buffer, and slice  it at EndReceiveFrom, after a packet process, return the rent buffer to pool.

**Comment by sipsorcery** [comment]
All good tips, thanks.

The problem is the library still supports the .NET Framework, specifically version 4.6.1, and those three classes are not available.

I have made at least one [note](https://github.com/sipsorcery/sipsorcery/blob/f912319891ef387e166b7682605dc7a1bfd4dc69/src/core/SIP/SIPTransport.cs#L868) about where such improvements can be made when .NET Framework support is deprecated.

**Comment by xljiulang** [comment]
Well, [System.Memory](https://www.nuget.org/packages/System.Memory/) library supports net461 and .NETStandard 2.0，so  those three classes are available at `sipsorcery`.
There are high performance buffer types such as ArrayPool,IArrayOwner,BufferWriter,and Slice extension for IMemoryOwner in my project [MemoryExtensions](https://github.com/xljiulang/MemoryExtensions)

**Comment by xljiulang** [comment]
And we can use BinaryPrimitives class to ReverseEndian and read/write number/bytes instead of BitConverter/BitConverter, a recyclable `BufferWriter<byte>`  to build Packet.
```
Buffer.BlockCopy(BitConverter.GetBytes(NetConvert.DoReverseEndian(firstWord)), 0, header, 0, 2);
Buffer.BlockCopy(BitConverter.GetBytes(NetConvert.DoReverseEndian(SequenceNumber)), 0, header, 2, 2);
Buffer.BlockCopy(BitConverter.GetBytes(NetConvert.DoReverseEndian(Timestamp)), 0, header, 4, 4);
Buffer.BlockCopy(BitConverter.GetBytes(NetConvert.DoReverseEndian(SyncSource)), 0, header, 8, 4);
```

I found to many ArrayCopy code，but actually it don't need to copy if use `ArraySegment<byte>` or `Span<bye>`
```
public void Send(byte[] buffer, int offset, int length)
{
     base.Send(buffer.Skip(offset).Take(length).ToArray());
}
```

**Comment by sipsorcery** [comment]
Yes you're definitely correct there are now superior approaches for a lot of the buffer management and conversion methods (a large chunk of the code was written around 2008 to 2010, well before such niceties).

I see what you're saying now. I hadn't spotted that there is a `System.Memory` nuget package which holds those classes. I made the assumption they were in the runtime libraries and not available separately.

Adding `System.Memory` as a dependency shouldn't be an issue so PR's for the improvements you've mentioned would be welcome.

**Comment by rafcsoares** [comment]
Just a note: System.Memory can only optimize performance while working with Net.Core 3+ as this platform can use SIMD commands to perform high optimized vector operations.

In other platforms, System.Memory is only an abstraction layer for compatibility purposes.

**Comment by sipsorcery** [comment]
> Adding System.Memory as a dependency shouldn't be an issue so PR's for the improvements you've mentioned would be welcome.

I did take a look at doing this for some new code and decided not to proceed at this point. Adding the nuget `System.Memory` package dependency does drag along quite a large dependency chain for .NET Framework. The improvements, while nice, aren't big enough to warrant the extra dependencies at this point.

**Comment by lostmsu** [comment]
@sipsorcery I understand the `Memory` is not an option for now. But how about adding overloads for all methods, that take `byte[]`, that would take a triple of `byte[] buffer, int offset, int length` instead? That would cover most of the performance benefits of a `Memory`, as it would be possible to reuse chunks of preallocated arrays. Right now every frame of different length in `SendVideo` has to be allocated separately.

Adding overloads that also take `IntPtr buffer, int length` would even allow clients to pass `Memory` and `Span` if they really need it.

**Comment by lostmsu** [comment]
@sipsorcery I just checked the cost of a "large dependency chain", and this it what it looks like (net461 console app with only System.Memory 4.5.5 dependency):

![image](https://github.com/sipsorcery-org/sipsorcery/assets/239520/eab958db-cb1f-4df1-8644-a5b831d2bd24)

E.g. 300KB total.

For comparison, this is SIPSorcery (net461 console app with SIPSorcery 6.0.12):
![image](https://github.com/sipsorcery-org/sipsorcery/assets/239520/615b1bd3-87f1-4b70-a3de-8270700a51a9)

E.g. 10MB+ total.

I think this needs to be reopened.

**Comment by lostmsu** [comment]
Additionally: in 1 minute of an app execution with intensive use of data channels I get 6 seconds spent in non-concurrent GCs, which does not even include time it take to allocate and zero memory, and copy data around.

**Comment by lostmsu** [comment]
Also, considering the update to BouncyCastle.Crypto 2.X would probably require a major version bump, I think it is a good time to rewrite a bunch of bits this way.
