### ISSUE TITLE
SIPNotifierClient not working

### ISSUE THREAD

**Issue by oetzy** [sipsorcery-org/sipsorcery#400]
Is there a bug in the Subscribe-Method of SIPNotifierClient?

```
                    SIPRequest subscribeRequest = SIPRequest.GetRequest(
                        SIPMethodsEnum.SUBSCRIBE,
                        m_resourceURI,
                        new SIPToHeader(null, subscribeURI, m_subscriptionToTag),
                        null);
```

The last Parameter (from) should not be null:

```
// SIPSorcery.SIP.SIPRequest
public static SIPRequest GetRequest(SIPMethodsEnum method, SIPURI uri, SIPToHeader to, SIPFromHeader from)
{
	SIPRequest sIPRequest = new SIPRequest(method, uri);
	SIPHeader sIPHeader = (sIPRequest.Header = new SIPHeader(from, to, 1, CallProperties.CreateNewCallId()));
	sIPHeader.CSeqMethod = method;
	sIPHeader.Allow = "ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, PRACK, REFER, REGISTER, SUBSCRIBE";
	sIPHeader.Vias.PushViaHeader(SIPViaHeader.GetDefaultSIPViaHeader(uri.Protocol));
	return sIPRequest;
}
```

The constructor of SIPHeader throws an exception. :-(

**Comment by sipsorcery** [comment]
That code is likely to be very broken, sorry. I probably should have left it out when I imported the source from the custom sipsorcery.com service. It probably hasn't been used for at least 5 or 6 years, if not longer.

It "might" be possible to fix it up. What are you trying to do? If it's subscribe for Message Waiting Indications or something simple it shouldn't take too long. If it's some kind of XML event payload maybe not.

**Comment by oetzy** [comment]
The goal is to implement a blf functionality.
