### ISSUE TITLE
Windows SIP Client using sipsorcery?

### ISSUE THREAD

**Issue by LukeOwlclaw** [sipsorcery-org/sipsorcery#405]
I am wondering if there are any ready-to-use Windows SIP Client using sipsorcery. I found the [SoftPhone example](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/Softphone). But there surely must be some active projects. I did not find any though. I'd appreciate any hints! Thanks.

**Comment by sipsorcery** [comment]
None that I know of. 

There are a few open source softphones around that use different SIP libraries, often [pjsip](https://github.com/pjsip/pjproject).

- [baresip](https://github.com/baresip/baresip)
- [csipsimple](https://github.com/r3gis3r/CSipSimple)
- and bound to be others as well.
