### ISSUE TITLE
How to use custom EventPackages?

### ISSUE THREAD

**Issue by amaguolo** [sipsorcery-org/sipsorcery#406]
Hello,

the SIPNotifierClient constructor requires a SIPEventPackage parameter but this structure only allow for standard event packages (Dialog, MessageSummary, Presence, ect.). 

How can I send a SUBSCRIBE request with a custom Event header value?

Thanks.

**Comment by sipsorcery** [comment]
You would need to:

- Implement a new class that inherits from [SIPEvent](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIPEvents/SIPEvent.cs),
- Register the the new event type in the [SIPEventPackage](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIPEvents/SIPEventPackages.cs) class.

Do you have a particular SIP event type you need to support? You'll notice from the headers that the code in this area is over 10 years old and it could probably do with a refactor.

**Comment by amaguolo** [comment]
OK, so I need to change the sources of the [SipEventPackage](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIPEvents/SIPEventPackages.cs) struct.

Thank you.

**Comment by sipsorcery** [comment]
I have just re-factored a lot of the SIP Event related code to make it more sensible. The latest nuget release should now be working better. Take a look at the [NotifierClient demo](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/NotifierClient/Program.cs) to see a working example.

**Comment by amaguolo** [comment]
Thanks a lot. 

This change simplify the customization of the SipEventPackage.
