### ISSUE TITLE
Watching movies together using webrtc

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [sipsorcery-org/sipsorcery#407]
Is it possible to grab a video from my server and share It via WebRTC in real-time?

**Comment by sipsorcery** [comment]
Yes it's possible to stream video files with WebRTC.

In this project the [WebRTC Daemon](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/WebRTCDaemon) demo can stream an `mp4` file to WebRTC peers.

The Janus WebRTC server also has a [streaming demo](https://janus.conf.meetecho.com/streamingtest.html).

**Comment by INTERNALINTERFERENCE** [comment]
ok, thanks. I'll try to use this on my blazor project
