### ISSUE TITLE
Subscribe to buddy list to receive presence notifications

### ISSUE THREAD

**Issue by ilogixxDE** [sipsorcery-org/sipsorcery#409]
I have a question on how I can use this library to subscribe a user to the presence of the others. So the user receives an event when the presence state changes for any of the users in the buddy list. 
Can you plese point me in the rigt direction?
I have tried with SIPNotifierClient, but i get always back a 407 and i would expect that the library will handle this and send a second request following what is in the 407. Am I wrong on this and how can I achieve my subsription?
Thank you

**Comment by sipsorcery** [comment]
You'll get back repeated 401 or 407 responses if you are using the wrong password. The [SIPNotifierClient](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/SIPUserAgents/SIPNotifierClient.cs) does attempt to authenticate if you give it a password. If you capture the `SubscriptionFailed` events you should get a good idea of what's going wrong.

I have just re-factored a lot of the SIP Event related code which is used by the `SIPNotifierClient`. The latest nuget release should now be working better. Take a look at the [NotifierClient demo](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/NotifierClient/Program.cs) to see a working example.

**Comment by ilogixxDE** [comment]
I get a successfull subscription to the sip,server. In the console trace I can see the messages coming in from the pbx, but the NotificationReceived is never raised. I can see the messages when handling the SIPTransportRequestReceived of the transport, but I would expect it in the NotificationReceived event. As an example I receive this from the PBX:

Request received: udp:0.0.0.0:65060<-udp:20.52.207.202:5060
NOTIFY sip:192.168.254.101:65060 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.4:5060;branch=z9hG4bK-524287-1---3f37d5744762072e;rport
To: <sip:200@ilogixx.de>;tag=OHCEXNXVJU
From: <sip:100@ilogixx.de>;tag=1bfe7f42
Call-ID: 98408675ece3405989d41ff0e93f5733
CSeq: 2 NOTIFY
Contact: <sip:100@20.52.207.202:5060;ob>
Max-Forwards: 70
User-Agent: PortSIP UC - Call Manager 12.3.1.0
Content-Length: 313
Content-Type: application/pidf+xml
Event: presence
Subscription-State: active;expires=3600

<?xml version="1.0" encoding="UTF-8"?>
<presence xmlns="urn:ietf:params:xml:ns:pidf"
        entity="sip:100@ilogixx.de">
  <tuple id="F224BB90">
    <status>
      <basic>open</basic>
    </status>
    <note>Do not disturb</note>
    <timestamp>2021-02-02T18:54:19Z</timestamp>
  </tuple>
</presence>

Where in the code is this message filtered and finaly can raise the event. Any hint for me?

**Comment by sipsorcery** [comment]
Ah yes that's a bit of a flaw. I guess the best option would be for the `SIPNotifierClient` to add the handler to the `SIPTransport` itself. I'll fix that up shortly. In the meantime you will need to do it manually as shown [here](https://github.com/sipsorcery-org/sipsorcery/blob/0dd45399ca0997ae2d1ceadefa6c98be8489b1aa/examples/SIPExamples/NotifierClient/Program.cs#L52).

````csharp
sipTransport.SIPTransportRequestReceived += async (lep, rep, req) =>
{
	if (req.Method == SIPMethodsEnum.NOTIFY)
	{
		await mwiSubscriber.GotNotificationRequest(lep, rep, req);
	}
	else
	{
		SIPResponse notSupported = SIPResponse.GetResponse(req, SIPResponseStatusCodesEnum.MethodNotAllowed, null);
		await sipTransport.SendResponseAsync(notSupported);
	}
};
````
