### ISSUE TITLE
Redundant parsing in ParseSIPUserField

### ISSUE THREAD

**Issue by jscarle** [sipsorcery-org/sipsorcery#411]
There is some redundant parsing in the [ParseSIPUserField](https://github.com/sipsorcery-org/sipsorcery/blob/1b6b44fdf16615b156965d260ec131ca00d1e478/src/core/SIP/SIPUserField.cs#L69) of the SIPUserField class.

Specifically, [line 109](https://github.com/sipsorcery-org/sipsorcery/blob/1b6b44fdf16615b156965d260ec131ca00d1e478/src/core/SIP/SIPUserField.cs#L109) is immediately overwritten by [line 112](https://github.com/sipsorcery-org/sipsorcery/blob/1b6b44fdf16615b156965d260ec131ca00d1e478/src/core/SIP/SIPUserField.cs#L112), and [line 110](https://github.com/sipsorcery-org/sipsorcery/blob/1b6b44fdf16615b156965d260ec131ca00d1e478/src/core/SIP/SIPUserField.cs#L110) will always be true because of [line 107](https://github.com/sipsorcery-org/sipsorcery/blob/1b6b44fdf16615b156965d260ec131ca00d1e478/src/core/SIP/SIPUserField.cs#L107).

**Comment by sipsorcery** [comment]
You're right, that's a weird bit of code. Will fix that up now, thanks.

**Comment by jscarle** [comment]
I think there's a mix up on which variable is supposed to be assigned where. Everything is correct up to line 105, between 105 and 120, there's some math that doesn't seem to add up quite right.

**Comment by jscarle** [comment]
`position = trimUserField.IndexOf('>');
if (position != -1)
{
	int addrSpecLen = position - 1;

	string paramStr = trimUserField.Substring(position + 1).Trim();
	userField.Parameters = new SIPParameters(paramStr, PARAM_TAG_DELIMITER);`

Replacing lines 105 to 116 with above would give the same result.
