### ISSUE TITLE
Question: Is there a way to convert the received Opus encoded RTP packages into something else?

### ISSUE THREAD

**Issue by cristianmad** [sipsorcery-org/sipsorcery#413]
Hi, 

I'm using the library in order to establish WebRTC connections and send/receive audio. The other party only supports opus so that is what is being negociated.
During a conversation, I'm capturing all the received RTPPackages (in a MemoryStream) by handling the OnRtpPacketReceived, however, once the conversation is completed, I would like to convert them into something more usable (maybe linear in a .wav container? - realy anything except raw opus).
I noticed there are a few encoders/decoders in the library, but nothing opus related. 

I would appreciate any help :)

Thank you!

**Comment by sipsorcery** [comment]
It's probably not a big job to wire up the OPUS codec, either a C# port or a wrapper around libopus, but it's one of those things that always seems to get bumped down the list.

In the meantime one option could be to forward RTP packets you get from your WebRTC connection to `ffplay`/`ffmpeg`, see this [demo](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/WebRTCtoFfplay). If you can get the RTP to `ffmpeg` then you should be able to convert and save it into just about any format you could possibly need.

**Comment by cristianmad** [comment]
Thank you for the promt reponse!

I will have a look at the provided link. Opus seems to become the predominant codec when using WebRTC so I think that having a coder/decoder part of the library would prove beneficial to more ppl.

Thanks again!

**Comment by Ali-Russell** [comment]
Hi there @cristianmad 

Did you have any success in wiring up the opus codecs? I'm looking at this and it would be nice to confirm before starting, I'm considering using the c# lib [Concentus](https://github.com/lostromb/concentus) to start with to keep things simpler.

Cheers,

Ali

**Comment by cristianmad** [comment]
Yes, I have! :)
I spent some time looking at various options and performing all kinds of tests and I ended up using OpusDotNet.
Even if it only officially works on Windows, I have found a way to make it work on Linux as well. Please see this post I opened
https://github.com/mrphil2105/OpusDotNet/issues/2

I hope this helps.
