### ISSUE TITLE
telekom.de interop - RequestUri for PRACK & Eearly Media

### ISSUE THREAD

**Issue by tstaehli** [sipsorcery-org/sipsorcery#414]
Hi,

I am trying to use sipsorcery to connect to a SIP Trunk provided by the German telecom provider telekom.de. After some trial and error and comparing wireshark-traces from PhonerLite I got basic incomming and outgoing calls to work. I needed to "fix" sipsorcery in two ways however:

First, telekom.de needs to have the RequestURI updated to whatever Contact-Uri it sends back in a 183 Session Progress response for the PRACK. If this is not updated, telekom.de responds with `SIP/2.0 503 Service Unavailable (R503_ALL_SYSTEMS_UNRESPONSIVE)` and no call is established.
I fixed this by copying the code from `UACInviteTransaction.Get2xxAckRequest()` which deals with adjusting RequestUri from the Contact to `UACInviteTransaction.GetPRackRequest()`, which fixed the problem and allowed for proper call establishment. https://github.com/tstaehli/sipsorcery/commit/7acff821e56468750091a4781e8509751a4f96a4

Second, telekom.de sends the SDP in a 183 and does not send an SDP in the 200 OK Respnse to the INVITE. This caused an exception "The session description cannot be null for SetRemoteDescription", so I tried to fix this: https://github.com/tstaehli/sipsorcery/commit/643184907af83e761bbd3af2fc5ca6de0e55c59a

I tried to find the relevant section in the SIP RFC which deals with when the Reuqets URI needs to be adjusted but did not find it. I actually think that there is a problem in the SIP-Stack/Infrastructure of telekom.de, because the Contact they send is really cryptic and clearly internal. For example: `Contact: <sip:n+afFG245FSFF434+THgsd346FDER43HNy5GOc35q/m@th1>`

What is your preferred way for integrating patches? 
Should I just submit a Pull Request and we can continue discussion there on details?
For the first problem, maybe there needs to be some kind of switch to avoid breaking other SIP-Trunk providers?

Please let me know, if you need any further information.

Regards,
Tobias

**Comment by sipsorcery** [comment]
Nice work tracking the integration issue down. Over the years I have found that it's typically the big telcos that don't care too much about keeping things close to the core standard. In a lot of cases they only officially support their own client devices so they can get away with it.

> First, telekom.de needs to have the RequestURI updated to whatever Contact-Uri it sends back in a 183 Session Progress response for the PRACK. 

This approach seems a bit precarious to me.

 - The 183 Session Progress is 1xx informational response and to the best of my knowledge the `Contact` header from a 1xx response should not be used to update the session target. Maybe there's a [SIP RFC](https://tools.ietf.org/wg/sip/) somewhere that describes some new behaviour for 183 responses but I couldn't find it.
 - If the new `Contact` header is in the `PRACK` that's acknowledging the 183 response that also seems wrong. There's nothing in the [PRACK RFC](https://tools.ietf.org/html/rfc3262) that explicitly mentions that behaviour. The `PRACK` is meant to be treated the same as an `ACK` for 1xx responses. The `ACK` can update the session target but only when it's for a 2xx response.

> What is your preferred way for integrating patches?

PR's are the preferred way and the problem can be discussed there as well. If you're able to include the fill SIP trace from PhonerLite that would be very useful.

**Comment by tstaehli** [comment]
Thank you for your quick response. I will open that PR then.

In the mean time, here is a debug-trace of phonerLite. I had to remove some of the credential-information, but the main information should still be present. around line 260 is the interesting part.

[trace_PhonerLite.txt](https://github.com/sipsorcery-org/sipsorcery/files/5918342/trace_PhonerLite.txt)

**Comment by sipsorcery** [comment]
Thanks for the trace.

The first problem is in the sipsorcery library. At the moment the `PRACK` request is created too simplistically. It's not taking into account `Route` & `Contact` headers. It should be using the same logic as for generating a 2xx `ACK` but instead it's using the non-2xx `ACK`. It's an easy fix. The [Get2xxAckRequest](https://github.com/sipsorcery-org/sipsorcery/blob/b9103ea2a2a3321f5cd315dd939c7ef03c7b6470/src/core/SIPTransactions/UACInviteTransaction.cs#L190) just needs to be refactored to accommodate `PRACK` requests.

The second problem is the the SIP server seems to be answering the call in the `183 Session Progress` response and not the `200 Ok` response. It's probably correct behaviour according a SIP RFC somewhere but again I haven't seen it. I'll need to look into this one a bit more.

**Comment by tstaehli** [comment]
Thank you for your time. Please let me know if I can run some tests on the telekom sip trunk.
