### ISSUE TITLE
Chrome Error

### ISSUE THREAD

**Issue by NHodgesVFX** [sipsorcery-org/sipsorcery#419]
Im trying to run the examples but no matter what example I pick in google chrome I always get 

```
DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=ssrc:1492337403 Expects 2 fields.
    at WebSocket.ws.onmessage
```
the above is from webrtcsendaudio which does work in firefox. as a side note the getting started webrtc project doesnt seem to work on firefox or chrome. chrome has the above issue and on fire fox the server crashes because the format wasn't set.

**Comment by sipsorcery** [comment]
Thanks for the bug report.

I most likely broke that with this [commit](https://github.com/sipsorcery-org/sipsorcery/commit/a791edf020b3d5435e079162a18a93f41f635b3e) a few days ago. Will fix shortly.
