### ISSUE TITLE
Stream Audio Content Play Problem.

### ISSUE THREAD

**Issue by HarunDurmus** [sipsorcery-org/sipsorcery#424]
I am converting the audio content that I call from google text to speech service in this way.

string audioContent = "aaaaaaa............."
 byte[] file = Convert.FromBase64String(audioContent); 
 MemoryStream memStream = new MemoryStream();
 memStream.Write(file, 0, file.Length);

 await voipMediaSession.AudioExtrasSource.SendAudioFromStream(memStream, AudioSamplingRatesEnum.Rate16KHz);

When I call the target, I transmit this sound but the sound plays very slowly. What is the problem?

**Comment by sipsorcery** [comment]
Maybe the sample you're getting from the text-to-speech service is at a higher sampling rate than 16KHz.

Do you have a demo program for the text to speech service? I'd be happy to try it out.

**Comment by HarunDurmus** [comment]
Google tts test API website: [](https://cloud.google.com/text-to-speech/docs/reference/rest/v1/text/synthesize)

example request body:
 {
  "input": {
    "text": "Google Cloud Text-to-Speech enables developers to synthesize natural-sounding speech with 100+ voices, available in multiple languages and variants."
  },
  "voice": {
    "languageCode": "en-US",
    "name": "en-US-Wavenet-D"
  },
  "audioConfig": {
    "audioEncoding": "LINEAR16",
    "pitch": 0,
    "speakingRate": 1
  }
}

**Comment by sipsorcery** [comment]
Thanks.

Are you setting the `sampleRateHertz` to `16000` in your [AudioConfig](https://cloud.google.com/text-to-speech/docs/reference/rest/v1/text/synthesize)?

**Comment by HarunDurmus** [comment]
I did not set sample Rate 16000 before. i tried it now and the problem is solved. Thank you so much for your help.
