### ISSUE TITLE
How to set DEFAULT_FROM_URI

### ISSUE THREAD

**Issue by dv8inpp** [sipsorcery-org/sipsorcery#425]
I am trying the SIPCallServer example with FusionPBX. I can see a call being placed to the correct extension but in SNGREP on the server it is being referenced as thisis@anonymous.invalid which is the DEFAULT_FROM_URI.

The extension I'm trying to call from is 1000@mypbx.fusion.local.

How can I resolve this?

Console output

[01:09:57 DBG] Information response 100 Trying for sip:2000@mypbx.fusion.local:5060.
[01:09:57 INF] sip:2000@mypbx.fusion.local:5060 Trying: 100 Trying.

sngrep
[ ] 11   INVITE     thisis@anonymous.invalid  2000@mypbx.fusion.local:5 4     192.168.1.114:5060     192.168.1.13:5060      BUSY
[ ] 12   INVITE     thisis@anonymous.invalid  2000@mypbx.fusion.local:5 4     192.168.1.114:5060     192.168.1.13:5060      BUSY

fs_cli
EXECUTE [depth=0] sofia/internal/thisis@anonymous.invalid export(call_direction=inbound)
2021-02-17 06:00:22.732686 [DEBUG] switch_channel.c:1310 EXPORT (export_vars) [call_direction]=[inbound]
Dialplan: sofia/internal/thisis@anonymous.invalid Action set(call_direction=inbound) INLINE
EXECUTE [depth=0] sofia/internal/thisis@anonymous.invalid set(call_direction=inbound)

sngrep - detail
INVITE sip:2000@mypbx.fusion.local:5060 SIP/2.0
192.168.1.114:5060            192.168.1.13:5060 xVia: SIP/2.0/UDP 192.168.1.114:5060;branch=z9hG4bKd13b638e6c6148f4b71bca28fb951c8f;rport
To: <sip:2000@mypbx.fusion.local:5060>
From: <sip:thisis@anonymous.invalid>;tag=UMBBMCWAPX
Call-ID: 2205dad458254dc2b4e2818c2775bf2b
CSeq: 1 INVITE
Contact: <sip:Anonymous@192.168.1.114:5060>
Max-Forwards: 70
User-Agent: sipsorcery_v5.0.27.0
Supported: replaces, norefersub, 100rel

**Comment by sipsorcery** [comment]
You can set the username and password for outgoing calls when calling [ua.Call](https://github.com/sipsorcery-org/sipsorcery/blob/fb70e323d94c722e80b415e444e4b4ca12b073c5/examples/SIPExamples/SIPCallServer/Program.cs#L163).

The SIPCallServer example may not be the best one to start with if all you want to do is place calls to a PBX. You may be better off with the much simpler GetStarted example.

**Comment by dv8inpp** [comment]
Thanks for that , I started with the GetStarted then moved on to registration then making a call examples. I got stuck on the how to place a call example in the documentation as I couldn't find RtpAVSession.

So to place a call to an extension on the same server I need to define outgoing credentials?

**Comment by sipsorcery** [comment]
Oops sorry I must have missed updating the documentation somewhere, I'll track that down. `RtpAVSession` was renamed as `VoIPMediaSession`.

> So to place a call to an extension on the same server I need to define outgoing credentials as well as register?

Normally you only need to register to receive an incoming call. Sometimes a certain SIP Provider will also require a current registration for an outgoing call but that's a policy decision and not part of the SIP specification. As far as SIP goes registrations and calls are separate transactions.

Credentials can also be set in the GetStarted example on the [userAgent.Call](https://github.com/sipsorcery-org/sipsorcery/blob/fb70e323d94c722e80b415e444e4b4ca12b073c5/examples/SIPExamples/GetStarted/Program.cs#L42) line.
