### ISSUE TITLE
DnsClient release question

### ISSUE THREAD

**Issue by LADSoft** [sipsorcery-org/sipsorcery#426]
DnsClient seems to have been released a couple of days ago, I was wondering when we might see a version of SipSorcery without the beta of DnsClient?

**Comment by sipsorcery** [comment]
Yes. I spotted the DnsClient release as well. Working on a stable release of sipsorcery now.

**Comment by sipsorcery** [comment]
Done [SIPSorcery v5.1.0](https://www.nuget.org/packages/SIPSorcery/5.1.0).

**Comment by LADSoft** [comment]
thanks much for your help!
