### ISSUE TITLE
Sipsorcery run error on ubuntu 20.04 

### ISSUE THREAD

**Issue by HarunDurmus** [sipsorcery-org/sipsorcery#427]
I want to run sipsorcery on ubuntu 20.04 but I get an error like this.

**sipsorcery/examples/SIPExamples/PlaySounds:** gives this error while working on this project

```
WindowsAudioEndPoint failed to initialise playback device.
System.DllNotFoundException: Unable to load shared library 'winmm.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwinmm.dll: cannot open shared object file: No such file or directory
   at NAudio.Wave.WaveInterop.waveOutOpenWindow(IntPtr& hWaveOut, IntPtr uDeviceID, WaveFormat lpFormat, IntPtr callbackWindowHandle, IntPtr dwInstance, WaveInOutOpenFlags dwFlags)
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
```

**Comment by sipsorcery** [comment]
That's because that particular example use [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows) which is Windows specific.

The alternative for Linux is the [GetStartedPortAudio](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/SIPExamples/GetStartedPortAudio) demo. But be aware it's not very polished and it's definitely worth reading the readme for that demo.

.NET Core does not provide any cross platform way to access audio or video devices and it would be a mammoth task to come up with a library that does.

**Comment by HarunDurmus** [comment]
I did all the steps in program.cs, installed vcpkg and installed portaudio with "./vcpkg install portaudio". When I run the application, I get an error like this.

```
SIPSorcery Getting Started Demo
Unhandled exception. System.TypeInitializationException: The type initializer for 'ProjectCeilidh.PortAudio.Native.PortAudio' threw an exception.
 ---> System.DllNotFoundException: Could not find library "portaudio.2.0.0"
```

**Comment by sipsorcery** [comment]
What do you get if you search for the PortAudio library?

````
sudo find / -name libportaudio.so.2*
/home/aaron/src/portaudio/lib/.libs/libportaudio.so.2.0.0
/home/aaron/src/portaudio/lib/.libs/libportaudio.so.2
/usr/local/lib/libportaudio.so.2
/usr/local/lib/libportaudio.so.2.0.0
````

**Comment by HarunDurmus** [comment]
When I search with "`sudo find / -name libportaudio.so.2 *`" command, it outputs like this.

```
$ sudo find / -name libportaudio.so.2*
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied

```

**Comment by HarunDurmus** [comment]
> When I search with "`sudo find / -name libportaudio.so.2 *`" command, it outputs like this.
> 
> ```
> $ sudo find / -name libportaudio.so.2*
> find: ‘/run/user/1000/doc’: Permission denied
> find: ‘/run/user/1000/gvfs’: Permission denied
> ```

Now it finds the portaudio library I solved this problem

**Comment by HarunDurmus** [comment]
The application gives an error like this while running.

```
SIPSorcery Getting Started Demo
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

**Comment by HarunDurmus** [comment]
> The application gives an error like this while running.
> 
> ```
> SIPSorcery Getting Started Demo
> ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
> ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
> ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> ```

how can i solve this problem

**Comment by sipsorcery** [comment]
I can't help much with that one, sorry. My knowledge of PortAudio is minimal and anecdotally sorting out audio issues on Linux can get very tricky.

**Comment by HarunDurmus** [comment]
Can this library be used with sipsorcery https://scientificprogrammer.net/2019/08/18/playing-audio-on-net-core-with-netcoreaudio/

**Comment by sipsorcery** [comment]
I doubt it. Looks like that library is only for playing back media files and to do it shells out to an external application.

I do feel your pain. The Microsoft .NET Framework had notoriously poor support for Windows audio and video. Nothing has with .NET Core/.NET5 in that regard except that now the poor support is cross platform.

**Comment by HarunDurmus** [comment]
finally worked. but the sound is not clear why?

**Comment by sipsorcery** [comment]
Popped up on my twitter feed just now (completely unhelpful for this issue but does go to show how challenging audio on Linux can be).

![pulseaudio](https://user-images.githubusercontent.com/197660/109281357-1f048100-7814-11eb-8ec2-2da22de248d6.png)

**Comment by HarunDurmus** [comment]
I am running ubuntu virtual. Could the problems be due to this?

**Comment by sipsorcery** [comment]
How have you wired up your virtual machine to your real audio devices? I've never even attempted that.

If you don't actually to test an audio device, or even if you do, a better starting point might be one of the demo apps that doesn't require a physical device. And upon looking for such a demo I realise there isn't one...

If you let me know what you're looking to try out I can tell you if I can give you a demo app or not.

**Comment by HarunDurmus** [comment]
I actually want to make a small virtual pbx running on docker, using the sipsorcery library.

**Comment by sipsorcery** [comment]
> I actually want to make a small virtual pbx running on docker, using the sipsorcery library.

That's potentially a lot easier than getting audio working reliably on Linux.

The [SIPCallServer](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/SIPCallServer/Program.cs) demo is probably the best starting point. It's not a PBX but it is a very minimal SIP server that can give you a feel for the sipsorcery API.

You might also be interested in [signalrtc](https://github.com/sipsorcery-org/signalrtc) it's a demo SIP server. I use it to test things out on Azure where it runs on a Linux VM (and therefore is easily transplantable to Docker). You can test it out at [sipsorcery.cloud](https://sipsorcery.cloud). It contains various different [SIP server classes](https://github.com/sipsorcery-org/signalrtc/tree/master/src/SIPServers). You might find one that does close to what you're after.
