### ISSUE TITLE
AssocRcv{n} threads running forever even if I close RTCPeerConnection

### ISSUE THREAD

**Issue by gabesznagy** [sipsorcery-org/sipsorcery#428]
I've created a small application that can receive audio data through RTCPeerConnection. I've created a data channel as well in order to be able to send back textual information. Once a client connects to the application, a new thread (AssocRcv{n}) will be created. This thread never ends and eats the CPU. Every new connection results a new never ending thread.

I've checked the source and it seems to be related to this: #338. The following line in the Association's thread method always returns with -1:
`var length = _transp.Receive(buf, 0, buf.Length, TICK);`
And because of this, we never break the while loop. Maybe the method closeStream in the class Association should set the _rcv variable's value to null.

**Comment by sipsorcery** [comment]
Unfortunately the data channels implementation has proven to be a bit like a leaky bucket. We fix one thing and another thing breaks. It's not totally unexpected given the SCTP implementation it's based on is a retrofit of an old C# project that was a port of a Java project. Ultimately I think the SCTP implementation will need to be rewritten from scratch but I don't have a timeframe for that.

If you'd like to experiment this [PR](https://github.com/sipsorcery-org/sipsorcery/pull/402) contains a different SCTP version and may work better. The PR is waiting on additional testing so if you are able try it out and report any findings it would be very helpful.

**Comment by sipsorcery** [comment]
@gabesznagy the SCTP stack that underpins data channels has now been re-written. If you're still interested in giving it a spin either master or nuget package v5.1.6-pre onwards have the new SCTP implementation.
