### ISSUE TITLE
WebRTC Client not generated di ICE and che connection not start.

### ISSUE THREAD

**Issue by michferrero** [sipsorcery-org/sipsorcery#429]
Hi, 

I am trying to use SipSorcery as a client in a WebRTC connection (the server is on a NODEJS server).
I create the new WebRTC connection and the offer SDP, I send everything to the server that answers me correctly. 
I also receive the ICEs from the server, and on the client I listen to the event "_onicecandidate_". The event starts but the ICE generated is NULL. 

Below is an excerpt of my code: 
```
peerConnection = new RTCPeerConnection(config);
...
peerConnection.onicecandidate += PeerConnection_onicecandidate;
...
private void PeerConnection_onicecandidate(RTCIceCandidate iceCandidate)
        {
            WebRtcIceCandidatePeer iceCandidatePeer = new WebRtcIceCandidatePeer();
            iceCandidatePeer.candidate = iceCandidate.candidate;
            iceCandidatePeer.mittente = "BRIDGE_COM4";
         ...
        }
```
The "_**iceCandidate.candidate**_" is NULL and the connection not start.
Can you help me? There is something wrong?

Thanks so much.

**Comment by sipsorcery** [comment]
If you're sending the ICE candidate to another peer the best thing to do is call the [toJSON](https://github.com/sipsorcery-org/sipsorcery/blob/5f3d1c8ba4948d5c61ab855cf8b129e5b0b348d4/src/net/ICE/RTCIceCandidate.cs#L293). The JSON encoded string should then be suitable for the remote Peer's `addIceCandidate` method.

**Comment by michferrero** [comment]
I have no problem converting the ICE as JSON and sending it with WebSocket.
The ICE that is generated by the library has the field candidate as NULL. 

Also, the response I get from the server is not loaded by my client. Is it possible to log the library error? 
Thanks.

**Comment by sipsorcery** [comment]
I've had another look at the code and that does look like a bug after all. The `RTCIceCandidate.candidate` property is never set (or used) so it's always going to be `null`.

It should be returning the same thing as `RTCIceCandidate.ToString()`. I'll fix that up now but in the meantime you can call that method instead of accessing the `RTCIceCandidate.candidate` property.

**Comment by michferrero** [comment]
I tried to use the `RTCIceCandidate.ToString()` but I get the following value:
`"2324 1 udp 659136 172.16.22.253 57558 typ host generation 0"`

I don't think it's a valid Ice SDP. 


I have another problem with the answer. This is the answer that receive from the server:
"v=0\r\no=- 6872009176290654765 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:kySk\r\na=ice-pwd:r3T20KvuTmFSg3KFPNK3hhro\r\na=ice-options:trickle\r\na=fingerprint:sha-256 CF:EC:BE:19:96:D8:26:5B:6C:5D:1C:C9:8E:5F:17:C1:D7:65:3A:FA:76:BA:71:66:74:00:D6:89:0C:3F:95:CE\r\na=setup:active\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"

When I try to upload it to the RTCPeerConnection with the code,
```
       WebRtcSdpAnswer sdpAnswer = LitJson.JsonMapper.ToObject<WebRtcSdpAnswer>(message);
                if (sdpAnswer != null)
                {
                    RTCSessionDescriptionInit rtcSessioneDescription = new RTCSessionDescriptionInit();
                    rtcSessioneDescription.sdp = sdpAnswer.sdp;
                    rtcSessioneDescription.type = RTCSdpType.answer;

                    SetDescriptionResultEnum value = peerConnection.setRemoteDescription(rtcSessioneDescription);
                } 
```
The value of the variable "value" is "ERROR".
Is my SDP wrong?

Thanks.

**Comment by sipsorcery** [comment]
It's not intended to be valid SDP. The `RTCIceCandidate` knows nothing about SDP. See [here](https://github.com/sipsorcery-org/sipsorcery/blob/4faa5b58516b098cfe244763f45dc2c2acbbeaa1/src/net/SDP/SDP.cs#L732) for how it gets included in SDP (which in this case is just an `a=candidate:` prefix).

> The value of the variable "value" is "ERROR".

An exception occurred. You can turn on logging by adding a log provider and wiring it up to `SIPSorcery.LogFactory`. All the demos in the `examples\WebRTCExamples` demonstrate how to use a logger. For example with `Serilog`:

````
/// <summary>
///  Adds a console logger. Can be omitted if internal SIPSorcery debug and warning messages are not required.
/// </summary>
private static Microsoft.Extensions.Logging.ILogger AddConsoleLogger()
{
	var seriLogger = new LoggerConfiguration()
		.Enrich.FromLogContext()
		.MinimumLevel.Is(Serilog.Events.LogEventLevel.Debug)
		.WriteTo.Console()
		.CreateLogger();
	var factory = new SerilogLoggerFactory(seriLogger);
	SIPSorcery.LogFactory.Set(factory);
	return factory.CreateLogger<Program>();
}
````
