### ISSUE TITLE
Memory leak on multipart NOTIFY?

### ISSUE THREAD

**Issue by amaguolo** [sipsorcery-org/sipsorcery#431]
Hello,

I'm using the NotifierClient to get notifications from a SIP server sending notifications with content type `multipart/related;boundary="Boundary106a67_401fa3e2_4ade7df_2c94fcc";type=application/rlmi+xml`, and the memory footprint of the application keeps growing at each received NOTIFY.

At first I thought it was my application's fault, but also the NotifierClient demo shows the same behaviour when it's receiving the same notification body.

I'm using the latest 5.1.0 version of the library.

What can I check to try to resolve this problem?

Thanks.

Alessandro

**Comment by sipsorcery** [comment]
I left the Notifier Client demo running for a while with the MWI subscription and didn't seem to get a memory leak unless it's a very slow one (SUBSCRIBE requests were getting sent every 30s).

How big and fast is the memory leak you are getting?

**Comment by amaguolo** [comment]
The NotifierClient memory grows about 250 KB for every notification received.

This is a example of the NOTIFY message.

NOTIFY sip:192.168.9.4:50827;transport=TCP SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port]
To: <sip:testrc@alceo.com>;tag=LKMUHGSEPT
From: <sip:testrc@alceo.com>;tag=664c8c0-408a8c0-1b94-55013-105ede-6fb7afd7-105ede
Call-ID: 8236d967573e4502ae789bd867b4b1cb
CSeq: 30 NOTIFY
Contact: <sip:HAL@192.168.8.4:7060;transport=TCP>
Max-Forwards: 69
User-Agent: Hal 6.0.1.2
Allow: INVITE,ACK,CANCEL,BYE,NOTIFY,REFER,MESSAGE
Date: 23 Feb 2021 11:23:02 GMT
Supported: join,replaces,timer,100rel
Content-Length: 1514
Content-Type: multipart/related;boundary="Boundary106a67_401fa3e2_4ade7df_2c94fcc";type=application/rlmi+xml
Event: presence-ccsuperv
Subscription-State: active

--Boundary106a67_401fa3e2_4ade7df_2c94fcc
Content-Type: application/rlmi+xml

<?xml version="1.0"?>
<list xmlns="urn:ietf:params:xml:ns:rlmi" xmlns:r="http://www.alceo.com/schema/rlist" uri="sip:testrc@alceo.com" version="262" fullState="true" cid="cid:0000">
  <resource uri="sip:amaguolo@alceo.com" r:rank="regular">
    <instance id="i1" state="pending"/>
  </resource>
  <resource uri="sip:operatore1@alceo.com" r:rank="regular">
    <instance id="i1" state="pending"/>
  </resource>
  <resource uri="sip:operatore2@alceo.com" r:rank="regular">
    <instance id="i1" state="pending"/>
  </resource>
</list>

--Boundary106a67_401fa3e2_4ade7df_2c94fcc
Content-Type: application/pidf+xml
Content-ID: <cid:0000>

<?xml version="1.0"?>
<presence xmlns="urn:ietf:params:xml:ns:pidf" entity="sip:testrc@alceo.com" xmlns:a="http://www.alceo.com/schema/presence">
  <tuple id="h1">
    <status>
      <basic>open</basic>
      <a:requestClass priority="1" algorithm="0" queueLengthAlert="0" queueExpectedSecsAlert="0" queueAdvancingRate="213.52" dailyTimedOutRequestCount="1">
        <a:serviceRate value="0.2" mostRecentRequestServedDt="2021-02-22T14:49:48Z"/>
        <a:oprCounter unknown="0" not-logged="3" ready="0" pause="0" reserved="0" on-session="0" after-work="0"/>
        <a:dailyAbandon reqCount="12" averageSecs="9"/>
      </a:requestClass>
    </status>
    <contact>sip:testrc@alceo.com</contact>
  </tuple>
</presence>

--Boundary106a67_401fa3e2_4ade7df_2c94fcc--

**Comment by sipsorcery** [comment]
If you comment out your code processing the NOTIFY request body do you still get the leak?

Are you using the [SIPEventPresence](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIPEvents/Presence/SIPEventPresence.cs) class? If not it's hard to see how the leak could be in the sipsorcery SIP event processing given there essentially isn't any other than an attempt to identify the event type. And event the logic in that class is very minimal so it's unlikely, although not impossible, that it's leaking.

If you have a demo program I'd be happy to run it and see if I can spot anything.

**Comment by amaguolo** [comment]
I'm not using the [SIPEventPresence](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIPEvents/Presence/SIPEventPresence.cs) but I made a modification to the [SIPEventPackages](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIPEvents/SIPEventPackages.cs) to handle my custom event package (see attached file)
[SIPEventPackages.zip](https://github.com/sipsorcery-org/sipsorcery/files/6035740/SIPEventPackages.zip)

I also attached my modified version of the NotifierClient demo 
[Program.zip](https://github.com/sipsorcery-org/sipsorcery/files/6035749/Program.zip)

I'm trying to create a sipp test scenario to reproduce the behaviour.

**Comment by sipsorcery** [comment]
Can't see anything in those two classes that's likely to cause a leak. If you find a way to re-produce the behaviour I'm happy to check it out.

**Comment by amaguolo** [comment]
After further investigation I think the problem lies on the TCP transport when the connection is closed from the remote endpoint.

Our notification server was closing the TCP connection after every NOTIFY sent, switching to UDP transport does not show the problem.

So I'm now using the UDP transport and the system works perfectly.

Regards.
