### ISSUE TITLE
Problem with send DataChannel Message to server

### ISSUE THREAD

**Issue by michferrero** [sipsorcery-org/sipsorcery#432]
Hi, I have a problem with the DataChannel module. My application is a client that connects with WebRTC to a remote server. 
The connection is established correctly and the DataChannel is active ('Onopen' event is called correctly).

This is the code to open my dataChannel:
```
RTCDataChannelInit rtcDataChannelOption = new RTCDataChannelInit();
rtcDataChannelOption.ordered = false;
rtcDataChannelOption.maxRetransmits = 5;
rtcDataChannelOption.negotiated = false;
peerConnection.createDataChannel("dataChannelMessage", rtcDataChannelOption);
```

I receive messages from the server correctly, but I can't send them. 
This is the code to send the messages to server:
```
if (dataChannel.IsOpened)
{
     WebRtcDataChannelMessage webRtcMsg = new WebRtcDataChannelMessage();
     webRtcMsg.type = typeMsg;
     webRtcMsg.idDest = idDest;
     webRtcMsg.value = value;
     string msg = LitJson.JsonMapper.ToJson(webRtcMsg);
     ...
     dataChannel.send(msg);
     ...
}
```

When the instruction _dataChannel.send(msg)_ is executed, the WebRTC connection change the state to DISCONNECTED.
Is there any problem in sending messages on the DataChannel? 
Do I need to configure anything? 

Thanks a lot.
Michele

**Comment by sipsorcery** [comment]
There have been a few issues with the data channel implementation in this library. The SCTP stack was ported from another library and it hasn't worked out so well.

Are you able to test out this [PR](https://github.com/sipsorcery-org/sipsorcery/pull/402) with your application? It's an attempt at improving the data channels by using a different port.

**Comment by michferrero** [comment]
Thanks for the quick response...I can try to test it in my application.
Only a question: how can i download the correct version of the code? Is there an example of how this code can be used?

Thanks.

**Comment by sipsorcery** [comment]
To use the PR you need to use the sipsorcery project directly in your application instead of the nuget package.

If you're able to do that you can checkout the PR using:

````
git fetch origin refs/pull/402/head:402
git checkout 402
````

You shouldn't need to make any changes to your application. The PR changes the data channel code within the sipsorcery library so it's all under the hood.

**Comment by michferrero** [comment]
I downloaded the SipSorcery version from GitHub and got the implementation from the branch 402 with the changes for the DataChannel. I try it in my application and it doesn't work correctly.

The WebRTC connection is established. 
The event "OnOpen" in my application is activated and the event "OnOpen" on the server is called. 
After a few seconds, for no reason, the "onClose" event of the DataChannel is called on the server and, in the same time, in my application, the "OnOpen" event of the DataChannel is called again (for three times). Then, an error is returned:
```
File: DtlsSrtpTransport.cs - Row: 542

else if (!_isClosed) { **--> True** 
	return Read(buf, off, len, waitMillis);
} else {
	throw new SocketException(DTLS_RECEIVE_ERROR_CODE); **--> Generated error**
}

System.Net.Sockets.SocketException
  HResult=0x80004005
  Messaggio=Unknown error (0xfffffffe)
  Origine=SIPSorcery
  Analisi dello stack:
   at SIPSorcery.Net.DtlsSrtpTransport.Receive(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in ...BridgeCOM4\SipSorcery\net\DtlsSrtp\DtlsSrtpTransport.cs:line 544
   at Org.BouncyCastle.Crypto.Tls.DtlsRecordLayer.ReceiveDatagram(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsRecordLayer.cs:line 331
```

Why is the DataChannel connection dropped? With the master version of the library, the connection remained active.
Is there any way to resolve this? 

Thanks a lot.
Michele

**Comment by Terricide** [comment]
You could enable logging and set the logging to Trace, it might show what the issue is.

        /// <summary>
        /// Adds a console logger. Can be omitted if internal SIPSorcery debug and warning messages are not required.
        /// </summary>
        private static void AddConsoleLogger()
        {
            var seriLogger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Is(Serilog.Events.LogEventLevel.Trace)
                .WriteTo.Console()
                .CreateLogger();
            var factory = new SerilogLoggerFactory(seriLogger);
            SIPSorcery.LogFactory.Set(factory);
            logger = factory.CreateLogger<Program>();
        }

**Comment by sipsorcery** [comment]
@michferrero the SCTP stack that underpins data channels has now been re-written. If you're still interested in giving it a spin either `master` or nuget package `v5.1.6-pre` onwards have the new SCTP implementation.

**Comment by sipsorcery** [comment]
Feel free to re-open if required.
