### ISSUE TITLE
mediaendpoint

### ISSUE THREAD

**Issue by a71sa** [sipsorcery-org/sipsorcery#435]
hi 
i'm trying to run portaudio example on linux but it seems that the example is old and can't compile it.
i searched and did'nt find anything usefull 
it says that must implement some interface with ProjectCeilidh.PortAudio, IAudioSource, IAudioSink but i can't find good DOC to start 
so anyone have something to help ? or any work that make this part of the project better ?

(sorry for my week english and ...)

**Comment by sipsorcery** [comment]
I've fixed up the main project to use the latest main library package.

As far as getting the PortAudio part of the demo to work on your Linux machine you may or may not get lucky. It took me a while to be successful on my Ubuntu 20.04 machine (I'm no PortAudio expert). Also see #427 for someone else facing similar challenges.

**Comment by a71sa** [comment]
thank u very much.
it kinda worked but still has some issu (on rasp) but i'm working on it and if it worked i will share it.
 
this link help with alsa (https://www.raspberrypi.org/forums/viewtopic.php?t=136974)

**Comment by sipsorcery** [comment]
Please do share if you find a better way.
