### ISSUE TITLE
event ServerCallCancelled not fired

### ISSUE THREAD

**Issue by bpg-software** [sipsorcery-org/sipsorcery#444]
Good morning, I try to use you example SoftPhone in order to develop my own application.
I find a problem when the remote party ends an incoming call (not yet answered). Using version 5.0.11-pre (referenced on last source version downloaded) all works fine but if I update to last version (5.1.1) no event was received. In SIpClient.cs the method IncomingCallCancelled is never called.
Have you any suggestion?
Thank you very much

**Comment by sipsorcery** [comment]
I can re-produce. Shouldn't take too long to fix.

**Comment by bpg-software** [comment]
Now the event works. Thank you very much
