### ISSUE TITLE
Softphone problems

### ISSUE THREAD

**Issue by bpg-software** [sipsorcery-org/sipsorcery#445]
Hi, I am trying to use Softphone demo with a Yeastar PBX and a GrandStream Android Phone.
I have 2 problems:
1) when I answer an incoming call arrived on Softphone I receive the exception:
No capture device available
   at SIPSorceryMedia.Windows.WindowsVideoEndPoint.InitialiseDevice(UInt32 width, UInt32 height, UInt32 fps)
   at SIPSorceryMedia.Windows.WindowsVideoEndPoint.StartVideo()
   at SIPSorcery.Media.VoIPMediaSession.Start()
   at SIPSorcery.SIP.App.SIPUserAgent.Answer(SIPServerUserAgent uas, IMediaSession mediaSession, String[] customHeaders)
   at SIPSorcery.SoftPhone.SIPClient.Answer() in C:\temp\sipsorcery\sipsorcery-master\sipsorcery-master\examples\Softphone\Signalling\SIPClient.cs:line 199
   at SIPSorcery.SoftPhone.SoftPhone.AnswerCallAsync(SIPClient client) in C:\temp\sipsorcery\sipsorcery-master\sipsorcery-master\examples\Softphone\Softphone.xaml.cs:line 420
   at SIPSorcery.SoftPhone.SoftPhone.AnswerButton_Click(Object sender, RoutedEventArgs e) in C:\temp\sipsorcery\sipsorcery-master\sipsorcery-master\examples\Softphone\Softphone.xaml.cs:line 410
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SIPSorcery.SoftPhone.App.Main()
I have a mic connected, I try to changes AudioOutDeviceIndex in app.config but I have no success.

2) All outgoing call seems fail and the remote phone doesn't ring, on textbox I write number or sip:number or sip:number@ip_pbx but never works.

Have you suggestions for my problems.
Thank you very much

**Comment by sipsorcery** [comment]
Try the [Get Started](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/GetStarted/Program.cs) console application. It uses the same audio device logic as the softphone and is easier to troubleshoot without the GUI stuff.

The source for the Windows audio logic is [here](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/master/src/WindowsAudioEndPoint.cs). You may need to checkout the source and step through it to find what's going wrong.

**Comment by bpg-software** [comment]
Hi,
I used source code and Visual Studio Debug and I discover some things:

1) if udp port 5060 is already used, the app crashes on SIPTransportManager "udpChannel = new SIPUDPChannel(new IPEndPoint(IPAddress.Any, SIP_DEFAULT_PORT));"; this occours because arrives an ApplicationException and not a SocketException. I replace the catch instruction from SocketException to Exception and it works

2) In SIPSorceryMedia.Windows.WindowsVideoEndPoint "await _mediaCapture.InitializeAsync(mediaCaptureSettings).AsTask().ConfigureAwait(false);" I receive the exception: "No capture device available". I think this occour because my pc hasn't a webcam. Which is the best way to disable video? For now I comment every usage of video (windowsVideoEndPoint, VideoSink, VideoSource and testPatternSource) in SIPClient.CreateMediaSession and it works, but I don't know if there are a best solution.

3) I see that using a PBX and SIPRegistrationUserAgent, my application seems not correctly registered and when I try to make a call I receive "SIP 404 Not Found". Using wireshark I see that in REGISTER message the field Contact is sip:ip:port instead of sip:user@ip:port (saw with other sip clients). To try to correct this in SIPRegistrationUserAgent constructor after "m_contactURI = new SIPURI(m_sipAccountAOR.Scheme, IPAddress.Any, 0);" I add "m_contactURI.User = username;".
After this, my registration works fine and my calls work. This is the correct solution or there is a best one?


I need also a suggestion. My goal is to use the library to send pre-recorded audio (from wave file created by a text to speech application) and waiting DTMF from user. I suppose that a solution can be to modify CreateMediaSession in SIPClient and build my own implementation of IAudioSource and IAudioSink, it is the correct way or do you have a best solution?

Thank you very much

**Comment by sipsorcery** [comment]
Thanks for the points.

>  this occours because arrives an ApplicationException and not a SocketException. 

I've fixed that now.

>  For now I comment every usage of video (windowsVideoEndPoint, VideoSink, VideoSource and testPatternSource) in SIPClient.CreateMediaSession and it works, but I don't know if there are a best solution.

The best solution would be to add a new application setting called `DisableVideo` and when it gets set to true exclude all the video related functionality.

>  I add "m_contactURI.User = username;". After this, my registration works fine and my calls work. This is the correct solution or there is a best one?

Yes that's correct. There's often variation between different SIP providers around registration requirements.

>  My goal is to use the library to send pre-recorded audio (from wave file created by a text to speech application) and waiting DTMF from user. I suppose that a solution can be to modify CreateMediaSession in SIPClient and build my own implementation of IAudioSource and IAudioSink, it is the correct way or do you have a best solution?

Do you need a user interface? It not it would be much easier to use a console application instead. Could you use the [PlaySounds](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/PlaySounds/Program.cs) demo, to send audio from a file, and add the ability to receive DTMF to it? Receiving DTMF is just a matter of adding a handler for the `SIPUserAgent.OnDtmfTone` event. There are no specific demos to receive DTMF but if you want to see it being used take a look at this [program](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPScenarios/BlindTransferScenario/Transferor/Program.cs).

**Comment by bpg-software** [comment]
Thank you very much for your reply.

> The best solution would be to add a new application setting called DisableVideo and when it gets set to true exclude all the video related functionality.

Do you mean a parameter of SipClient used to call a different version of CreateMediaSession without video references ?

> Yes that's correct. There's often variation between different SIP providers around registration requirements.

Since my modification is in SIPRegistrationUserAgent code and in order to use directly nuget package without source code I see that the second constructor of SIPRegistrationUserAgent has the Contact field. So in SoftPhone.xaml.cs I replace 
```
_sipRegistrationClient = new SIPRegistrationUserAgent(
                _sipTransportManager.SIPTransport,
                m_sipUsername,
                m_sipPassword,
                m_sipServer,
                REGISTRATION_EXPIRY);
```
with
```
            SIPURI m_sipAccountAOR, m_contactURI;
            if (SIPURI.TryParse(m_sipServer, out var serverUri))
            {
                m_sipAccountAOR = serverUri;
                m_sipAccountAOR.User = m_sipUsername;
            }
            else
            {
                m_sipAccountAOR = new SIPURI(m_sipUsername, m_sipServer, null, SIPSchemesEnum.sip, SIPProtocolsEnum.udp);
            }
            m_contactURI = new SIPURI(m_sipAccountAOR.Scheme, System.Net.IPAddress.Any, 0);
            m_contactURI.User = m_sipUsername;
            _sipRegistrationClient = new SIPRegistrationUserAgent(
                _sipTransportManager.SIPTransport,
                null,
                m_sipAccountAOR,
                m_sipUsername,
                m_sipPassword,
                null,
                m_sipServer,
                m_contactURI,
                REGISTRATION_EXPIRY,
                null);
```
and it seems working without problems.

Thank you also for the suggestions about PlaySounds and DTMF, I will try in next days.

**Comment by sipsorcery** [comment]
> Do you mean a parameter of SipClient used to call a different version of CreateMediaSession without video references ?

No, I was thinking of an application setting for the softphone.

**Comment by bpg-software** [comment]
Ok, an application settings of Softphone, but this parameter must be sent to SipClient (maybe in constructor) and used to call a CreateMediaSession without video references, correct?
Thanks

**Comment by sipsorcery** [comment]
Yes that's correct.

The `SIPClient` is already using app settings so the [same approach](https://github.com/sipsorcery-org/sipsorcery/blob/6d82635ce5ebcaf197bd4361152326b87df66af8/examples/Softphone/Signalling/SIPClient.cs#L37) can be used.

**Comment by bpg-software** [comment]
Ok, perfect.
I hope to try in the next days audio from wave file.
Now I have a little doubt about SIPRegistrationUserAgent.Stop. I try demo UserAgentRegister but I see (with wireshark) that deregistration message is not sent. Watching the source code I understand that registration and deregistration are sent using a specific a Task/Thread. So I think the solution to send deregistration correctly is to insert a Sleep after "regUserAgent.Stop();".
Do you think is a correct solution?
Thanks

**Comment by sipsorcery** [comment]
Yes you generally need to wait 0.5 to 1s between the last SIP operation you want and shutting down the SIP transport. Without the delay situations such as you describe might not work. It's not something that will be enforced by the sipsorcery library. Some apps will not care about waiting and some will.

**Comment by bpg-software** [comment]
Hi, I took a look to PlaySounds example and I tried to integrate it in my application.
I have 2 doubts:
1) my pre-recorder audio is quite long so I cannot wait the end of SendAudioFromStream, but I need to know when audio is ended, so I try to use event voipMediaSession.AudioExtrasSource.OnSendFromAudioStreamComplete. It seems that this event is fired at start and at end of stream, why is fired also at start?
Maybe an alternative solution is not to use OnSendFromAudioStreamComplete but use SendAudioFromStream in another thread with await and to fire my event after await.

2) since that for now I don't need mic audio but only prerecorder audio I replace the original of SoftPhone (where I remove only video reference)

```
private VoIPMediaSession CreateMediaSessionAudio()
        {
            var windowsAudioEndPoint = new WindowsAudioEndPoint(new AudioEncoder(), m_audioOutDeviceIndex);
            MediaEndPoints mediaEndPoints = new MediaEndPoints
            {
                AudioSink = windowsAudioEndPoint,
                AudioSource = windowsAudioEndPoint,
            };
            var voipMediaSession = new VoIPMediaSession(mediaEndPoints);
            voipMediaSession.AcceptRtpFromAny = true;
            return voipMediaSession;
        }
```

with

```
private VoIPMediaSession CreateMediaSessionRTP()
        {
            var audioOptions = new AudioSourceOptions { AudioSource = AudioSourcesEnum.SineWave };
            AudioExtrasSource audioExtrasSource = new AudioExtrasSource(new AudioEncoder(), audioOptions);
            var voipMediaSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = audioExtrasSource });
            voipMediaSession.AcceptRtpFromAny = true;
            voipMediaSession.AudioExtrasSource.OnSendFromAudioStreamComplete += AudioExtrasSource_OnSendFromAudioStreamComplete;
            return voipMediaSession;
        }
```

In this way I see that mic audio is not captured and a sine wave is sent in call. When I want to send my audio I replace AudioSourcesEnum.SineWave with AudioSourcesEnum.None. It works but the audio is not perfect, this is because I see with wireshark that the delta of packets is about 30ms and not 20ms (also if AudioSamplePeriodMilliseconds is 20). I don't understant what is the problem. The sine wave is quite good but the prerecorder audio is very slow and shredded.
If I use the original CreateMediaSessionAudio all works fine so I think the problem is in use of VoIPMediaSession without WindowsAudioEndPoint.
Can you help me?

Thank you very much

**Comment by bpg-software** [comment]
> Are you using .NET Framework or Core? The framework cannot provide timer resolutions less that 30ms and can also be erratic.

I am using .NET Framework.

> You have to ensure the sampling rate you record the audio at is the same as the one you set in the audio sample format.

I tried with wave files in PlaySounds example, so sampling rate is correct

I knew about Timing problems in .net framework, and in the past, with other applications, I solved problems of Thread.Sleep using DllImport (of winmm.dll) and timeBeginPeriod. This approch doesn't works in my application that uses SipSorcery, I didn't understand why, maybe because it use Timer and not Sleep.
I also tried to replace System.Threading.Timer with System.Timers.Timer in AudioExtrasSource but nothing changed.
I saw the example HighPrecisionTimerExample (with HighPrecisionAudioSource and HighPrecisionVoipMediaSession) in issue #404 and this solve all my audio problems (with 2/3 fix in suggested code).
In the future do you think you will integrate the MicroTimer in your AudioExtrasSource?

About the SendFromAudioStreamComplete fired at start and at end of stream, I think the problem is that in AudioExtrasSource StopSendFromAudioStream (and therefore the event OnSendFromAudioStreamComplete) is called also at beginning of SendAudioFromStream. Will there be a fix in the future?

Thank you very much

**Comment by sipsorcery** [comment]
I'm happy to take Pull Requests for the addition of the `MicroTimer` and/or bug fixes.

**Comment by bpg-software** [comment]
Sorry for my late response but I am very busy in this period.
So for MicroTimer and AudioStreamComplete event, I will add on Pull requests. Mine are just suggestions, your project is wonderful.
Just another question: When I make a call I need a timer (example ring only for 30 seconds) and this timer maybe can change between different call. Is there already a build-in feature in your project?
Thank you

**Comment by sipsorcery** [comment]
> When I make a call I need a timer (example ring only for 30 seconds) and this timer maybe can change between different call. Is there already a build-in feature in your project?

I thought there was a ring timeout but it turns out there isn't. 

There was a [mechanism](https://github.com/sipsorcery-org/sipsorcery/blob/9ecaafb996a9d5ab4deccb22fa241c8acf5f0ab5/sipsorcery-core/SIPSorcery.AppServer.DialPlan/DialPlanFacades/DialPlanScriptFacade.cs#L563) in the previous version of the code but that relied on the caller of `SIPClientUserAgent.Call` to create a timer and then call `SIPClientUserAgent.Cancel` when it expired.

It should be trivial to add a timer to `SIPClientUserAgent` and I've created #468 for it. I should be able to come up with something in the near future.

**Comment by bpg-software** [comment]
Perfect, I think the ringing timeout will be a great feature.
As referred above I also added issue #470 and #471 also as reminder.
Thank you very much for your great support
