### ISSUE TITLE
Permance

### ISSUE THREAD

**Issue by PauloTroguilho** [sipsorcery-org/sipsorcery#446]
Dear,

what are the application limitations? how many simultaneous calls? how much processor and memory is recommended for a sip server doing automatic answering? what performance tips would you give?

**Comment by sipsorcery** [comment]
Impossible questions without knowing how calls will be processed. Signaling and media or just one or the other? Will the application do any other processing for each call? Record CDR's to a database? Run a dialplan script etc etc.

> what performance tips would you give?

The hardest problem for VoIP applications isn't scalability, a big enough server can probably do 1000's of calls, it's fault tolerance. For fault tolerance the two biggest problems are:

 - How do you build a reliable signaling server set up, such as load balanced SIP Proxy's? A master-slave set up with IP address failover is about as good as you can get.
 - For media servers how can you transfer media sessions of 1000's of calls if a server goes down?
