### ISSUE TITLE
Played Audio is not heared on recording

### ISSUE THREAD

**Issue by javjim** [sipsorcery-org/sipsorcery#450]
I have been able to play audio properly and the other party in call hears it. but on the recording I do of the call, the audio that is being played is not recorded.

Is there a way to record the audio that is being played?

         voipMediaSession = new VoIPMediaSession(windowsAudio.ToMediaEndPoints());
            voipMediaSession.AcceptRtpFromAny = true;
            voipMediaSession.OnRtpPacketReceived += OnRtpPacketReceived;
            userAgent.OnCallHungup += (dialog) => _waveFile?.Close();
            await windowsAudio.PauseAudio();

                    await voipMediaSession.AudioExtrasSource.StartAudio();
                    await Task.Delay(5000);
                    Console.WriteLine("Sending welcome message from 16KHz sample.");
                    await voipMediaSession.AudioExtrasSource.SendAudioFromStream(new FileStream(ring, FileMode.Open), AudioSamplingRatesEnum.Rate16KHz);
                    await Task.Delay(200, exitCts.Token);
                    Console.WriteLine("Sent message");
                    voipMediaSession.AudioExtrasSource.SetSource(AudioSourcesEnum.None);
                    await voipMediaSession.AudioExtrasSource.PauseAudio();
                    await windowsAudio.ResumeAudio();`

The recording event is this:

           private void OnRtpPacketReceived(IPEndPoint remoteEndPoint, SDPMediaTypesEnum mediaType, RTPPacket rtpPacket)
          {
            
            if (mediaType == SDPMediaTypesEnum.audio)
            {
                var sample = rtpPacket.Payload;

                for (int index = 0; index < sample.Length; index++)
                {
                    if (rtpPacket.Header.PayloadType == (int)SDPWellKnownMediaFormatsEnum.PCMA)
                    {
                        short pcm = NAudio.Codecs.ALawDecoder.ALawToLinearSample(sample[index]);
                        byte[] pcmSample = new byte[] { (byte)(pcm & 0xFF), (byte)(pcm >> 8) };
                        _waveFile.Write(pcmSample, 0, 2);
                    }
                    else
                    {
                        short pcm = NAudio.Codecs.MuLawDecoder.MuLawToLinearSample(sample[index]);
                        byte[] pcmSample = new byte[] { (byte)(pcm & 0xFF), (byte)(pcm >> 8) };
                        _waveFile.Write(pcmSample, 0, 2);
                    }
                }
            }
        }

**Comment by sipsorcery** [comment]
There's no in-built in this library way to record two audio streams. To do so you need an audio mixer that can combine two audio signals into one and then record that. I have not looked into it but I'd be surprised is NAudio did not have some kind of mixing capability.

**Comment by javjim** [comment]
TY for your help, will check NAudio
