### ISSUE TITLE
udp rtp from helloworld@sipsorcery.cloud

### ISSUE THREAD

**Issue by nick-grange** [sipsorcery-org/sipsorcery#454]
Hi,

I tried your 'Getting Started' sip example and since the 26th of March we have been receiving a udp rtp media stream from 20.73.112.13 and it's not stopping, please can you check you sip server 20.71.77.154 and see it you still has a open call and disconnect it?

Thanks
Nick

**Comment by sipsorcery** [comment]
Whoops looks like I need to add some timeouts to the Asterisk dialplan for the echo and music on hold numbers.

All active calls have been terminated now.

**Comment by nick-grange** [comment]
Great, thanks for sorting so quickly

Thanks
Nick
