### ISSUE TITLE
Stream sender

### ISSUE THREAD

**Issue by pazicb** [sipsorcery-org/sipsorcery#455]
Hello,
is it possible to use Sipsorcery to create an application that will receive 1 WebRTC stream and send it to other users?

**Comment by sipsorcery** [comment]
Yes.

**Comment by pazicb** [comment]
Can you please give an example of how to proceed?

**Comment by sipsorcery** [comment]
The closest thing is probably the [WebRTCEchoServer](https://github.com/sipsorcery-org/sipsorcery/blob/5dfcc9bd1666da96e5b7b4caec47f50666a837f8/examples/WebRTCExamples/WebRTCEchoServer/WebRTCEchoServer.cs#L27) demo class. 

You would need to do something like handle the [OnRtpPacketReceived](https://github.com/sipsorcery-org/sipsorcery/blob/5dfcc9bd1666da96e5b7b4caec47f50666a837f8/examples/WebRTCExamples/WebRTCEchoServer/WebRTCEchoServer.cs#L79) from two different peer connections and forward the RTP packets to the other connection.
