### ISSUE TITLE
Huge spike to create new RTCPeerConnection

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery-org/sipsorcery#456]
Hello @sipsorcery , the current version of RTCPeerConnection creates a huge spike while trying to create new instance (around 200~600ms)

This is probably related to method that try bind to socket.

Maybe need some reafactors to try perform some slow actions in multi-thread context?

**Comment by sipsorcery** [comment]
That's interesting. I was encountering some longer than expected time running some unit tests and suspected it may have been down to creating the UDP sockets. It seemed to be sporadic and I blamed the OS and didn't look into it.

The only likely recent change to the NetServices.CreateBoundUdpSocket looks to be this [one](https://github.com/sipsorcery-org/sipsorcery/commit/5335837b96522088bf162f48bf20d69e2d947bf3#diff-da726b4fc5881d36688bbedc6777747afb077d829e1d82a6117860d9cebceb7b). But I left that deliberately turned off and the new logic shouldn't be getting called.

I'm stuck in the middle of the [rewrite](https://github.com/sipsorcery-org/sipsorcery/pull/447) at the moment so it might be a little while before I look into this properly. If you spot anything that could be a likely cause it would be very helpful.

**Comment by rafcsoares** [comment]
@sipsorcery Okey, after some investigations i found 2 major bottlenecks.

1) First bottleneck is related to create RTCPeerConnection without Certificate.

Without certificate the constructor of PeerConnection will call 
`(_dtlsCertificate, _dtlsPrivateKey) = DtlsUtils.CreateSelfSignedTlsCert();` and this will generate around 600ms delay in my notebook. Maybe should try to create a static selfsigned certificate to be used when parameter is null instead create new selfsigned certificate everytime? 

Another minor improvement is related to
```
_dtlsCertificate = DtlsUtils.LoadCertificateChain(usableCert.Certificate);
_dtlsPrivateKey = DtlsUtils.LoadPrivateKeyResource(usableCert.Certificate);
.
.
.
DtlsCertificateFingerprint = DtlsUtils.Fingerprint(_dtlsCertificate);
```

seems that you will always call LoadCertificateChain/LoadPrivateKeyResource/DtlsUtils.Fingerprint from certificate... maybe we should change RTCCertificate to cache this values? (this will prevent 4ms of delay while creating peerconnection with certificate setted)

```
public class RTCCertificate
    {
        private X509Certificate2 _certificate;

        /// <summary>
        /// The expires attribute indicates the date and time in milliseconds relative to 1970-01-01T00:00:00Z 
        /// after which the certificate will be considered invalid by the browser.
        /// </summary>
        public long expires
        {
            get
            {
                if (Certificate == null)
                {
                    return 0;
                }
                else
                {
                    return Certificate.NotAfter.GetEpoch();
                }
            }
        }

        public X509Certificate2 Certificate
        {
            get
            {
                return _certificate;
            }
            set
            {
                if (_certificate == value)
                    return;
                _certificate = value;
                CertificateChain = DtlsUtils.LoadCertificateChain(_certificate);
                PrivateKey = DtlsUtils.LoadPrivateKeyResource(_certificate);
                Fingerprint = DtlsUtils.Fingerprint(Certificate);
            }
        }

        public Org.BouncyCastle.Crypto.Tls.Certificate CertificateChain 
        {
            get;
            private set;
        }

        public Org.BouncyCastle.Crypto.AsymmetricKeyParameter PrivateKey
        {
            get;
            private set;
        }

        public RTCDtlsFingerprint Fingerprint
        {
            get;
            private set;
        }

        public List<RTCDtlsFingerprint> getFingerprints()
        {
            return new List<RTCDtlsFingerprint> { Fingerprint };
        }
    }
```

2)  addSingleTrack(); seems to generate around 100ms of delay in constructor (i must investigate this futher as i don't know which part is generating this lag).

**Comment by rafcsoares** [comment]
With this improvements RTCPeerConnection can be created without any delay (0 ms)... i can send a pull request if you think this changes make sense.

**Comment by sipsorcery** [comment]
@rafcsoares thanks a lot for tracking those down! Looks like it wasn't the UDP socket binding after all.

As far as your suggested change go:

 - Adjusting `RtcIceChannel.StartGathering` to be an `async` task: I think this is a good idea. That method does query the OS interface table and touch DNS code (once `InitialiseIceServers` is included). There are no DNS lookups done at this point. The delay incurred is currently small but there is a chance a different OS could make it longer.

 - Making the self signed certificate static and caching the fingerprint: This one I'm not so sure about. It's good to have a new certificate & key generated for each connection. My suggestion would be for the application to create a static certificate and then it can pass it to `RTCPeerConnection` in the config options. Caching the fingerprint for a certificate may be useful but I'm not adding and managing the lookup dictionary is worth it for 4ms.

What do you think? I'm happy to go ahead and do the `RtcIceChannel.StartGathering` and save the need for you to do a PR.

**Comment by rafcsoares** [comment]
@sipsorcery agreed. For sure this can solve the problems by now

**Comment by rafcsoares** [comment]
@sipsorcery i saw in yout commit that you don't changed the contructor of RTCIceChannel to create DnsCllientLookupClient as a task too

_dnsLookupClient = new DnsClient.LookupClient(defaultServers.ToArray())

LookupClient instance generate huge spike too so without this changes below we will have another 60ms delay for 1 server to create RTCPeerConnection.

public RtpIceChannel(
            IPAddress bindAddress,
            RTCIceComponent component,
            List<RTCIceServer> iceServers = null,
            RTCIceTransportPolicy policy = RTCIceTransportPolicy.all,
            bool includeAllInterfaceAddresses = false) :
            base(false, bindAddress)
        {
            _bindAddress = bindAddress;
            Component = component;
            _iceServers = iceServers;
            _policy = policy;
            _includeAllInterfaceAddresses = includeAllInterfaceAddresses;

            LocalIceUser = Crypto.GetRandomString(ICE_UFRAG_LENGTH);
            LocalIcePassword = Crypto.GetRandomString(ICE_PASSWORD_LENGTH);

            _localChecklistCandidate = new RTCIceCandidate(new RTCIceCandidateInit
            {
                sdpMid = SDP_MID,
                sdpMLineIndex = SDP_MLINE_INDEX,
                usernameFragment = LocalIceUser
            });

            _localChecklistCandidate.SetAddressProperties(
                RTCIceProtocol.udp,
                base.RTPLocalEndPoint.Address,
                (ushort)base.RTPLocalEndPoint.Port,
                RTCIceCandidateType.host,
                null,
                0);

            if (iceServers != null)
            {
                InitialiseIceServers(_iceServers);

                // DNS is only needed if there are ICE server hostnames to lookup.
                if (_dnsLookupClient == null && _iceServerConnections.Any(x => !IPAddress.TryParse(x.Key.Host, out _)))
                {
                    var defaultServers = DefaultNameServers;
                    _dnsLookupResolverTask = Task.Run(() =>
                    {
                        if (defaultServers != null)
                        {
                            _dnsLookupClient = new DnsClient.LookupClient(defaultServers.ToArray()); ;
                        }
                        else
                        {
                            _dnsLookupClient = new DnsClient.LookupClient();
                        }
                    });
                }

**Comment by sipsorcery** [comment]
> i saw in yout commit that you don't changed the contructor of RTCIceChannel to create DnsCllientLookupClient as a task too
> _dnsLookupClient = new DnsClient.LookupClient(defaultServers.ToArray())

I moved the `new DnsClientLookup` from the `RtpIceChannel` constructor and into the `StartGathering` method. The `RTCPeerConnection` constructor now calls `StartGathering` on a background thread, see [here](https://github.com/sipsorcery-org/sipsorcery/blob/6d57981b0d061496fa452d44d00f41b4a87ada32/src/net/WebRTC/RTCPeerConnection.cs#L441).

**Comment by rafcsoares** [comment]
@sipsorcery my bad.. thanks in advance!
