### ISSUE TITLE
NRE in ClientCallAnsweredHandler

### ISSUE THREAD

**Issue by RomanPlekhanov** [sipsorcery-org/sipsorcery#457]
Hi! I got this error one time. But I'm unable to reproduce this error again and I don’t know why this error occurred.

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в SIPSorcery.SIP.App.SIPUserAgent.<ClientCallAnsweredHandler>d__119.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by sipsorcery** [comment]
Thanks for the bug report but that's not enough to track it down unfortunately. It is happens again and you can provide the steps I'd be happy to try and replicate it.
