### ISSUE TITLE
Latest code on nuget

### ISSUE THREAD

**Issue by royben** [sipsorcery-org/sipsorcery#460]
Hi,
Thanks for the great work you've done on this library.
Great to see a **real** WebRTC porting to C#.

My initial experiments were done with the WebRTC API found on the latest nuget package.
But, after a while I found my self more satisficed with the latest code on the main branch.

My question is, when do you plan on releasing the latest code to a nuget.
I really prefer to reference the nuget package.

**Comment by sipsorcery** [comment]
The latest nuget package was released just over 12 hours ago and at the time of writing is synchronised with the `main` branch. Make sure you select the `pre-release` option and the nuget version is `5.1.6-pre`.

**Comment by royben** [comment]
Thanks!
