### ISSUE TITLE
PlaySound lag problem.

### ISSUE THREAD

**Issue by farhanjavid** [sipsorcery-org/sipsorcery#462]
I am using your playsound example code in my project and streaming .wav file. there are massive lags in the audio when it reaches the end destination user cell phone.

here is my code:

                var windowsAudio = new WindowsAudioEndPoint(new AudioEncoder());
                var voipMediaSession = new VoIPMediaSession(windowsAudio.ToMediaEndPoints());
                voipMediaSession.AcceptRtpFromAny = true;

                var callTask = m_userAgent.Call(callDescriptor, voipMediaSession);
                bool callResult = await callTask;

                if (callResult)
                {
                    const string inform_16  = "inform-16.wav";
                    await windowsAudio.PauseAudio();

                    try
                    {
                        await voipMediaSession.AudioExtrasSource.StartAudio();

                        //Console.WriteLine("Sending welcome message from 8KHz sample.");
                        await voipMediaSession.AudioExtrasSource.SendAudioFromStream(new FileStream(inform_16, FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);

                        Console.WriteLine("Sending inform-16.wav.");
                        voipMediaSession.AudioExtrasSource.SetSource(AudioSourcesEnum.SineWave);

                    }
                    catch (TaskCanceledException)
                    { }
                }

**Comment by sipsorcery** [comment]
Is there any lag if you listen to it on the same computer or network your application is running on?

If not then the lag is due to something on the network or the app at the other end.

**Comment by farhanjavid** [comment]
No there is no lag Sent from Mail for Windows 10 From: Aaron ClausonSent: Wednesday, April 14, 2021 4:34 PMTo: sipsorcery-org/sipsorceryCc: farhanjavid; AuthorSubject: Re: [sipsorcery-org/sipsorcery] PlaySound lag problem. (#462) Is there any lag if you listen to it on the same computer or network your application is running on?If not then the lag is due to something on the network or the app at the other end.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by farhanjavid** [comment]
There is no app on the user end I am directly call on there cell phones like cell network companies does.  Sent from Mail for Windows 10 From: Aaron ClausonSent: Wednesday, April 14, 2021 4:34 PMTo: sipsorcery-org/sipsorceryCc: farhanjavid; AuthorSubject: Re: [sipsorcery-org/sipsorcery] PlaySound lag problem. (#462) Is there any lag if you listen to it on the same computer or network your application is running on?If not then the lag is due to something on the network or the app at the other end.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sipsorcery** [comment]
There's nothing special about the PlaySounds demo or the sipsorcery library in general as far as VoIP goes. It puts RTP packets on the wire, every 20ms by [default](https://github.com/sipsorcery-org/sipsorcery/blob/9f3bf4f164a8258749d4523efd51ff0640acc9fb/src/app/Media/Sources/AudioExtrasSource.cs#L97). It's pretty much identical to a softphone such as MicroSIP, Bria, Zoiper etc. If you get laggy audio with the sipsorcery library then it's more than likely you'll have the same issue with any VoIP softphone.
