### ISSUE TITLE
Can we make multiple calls parallelly using single SIPClient ?

### ISSUE THREAD

**Issue by farhanjavid** [sipsorcery-org/sipsorcery#465]
I want to know that, Is that possible to make multiple calls at the same time using a single SIPClient? if there is any example available for guidance kindly provide it.

**Comment by sipsorcery** [comment]
No. One call per `SIPClient` is what you should do.

**Comment by farhanjavid** [comment]
Ok , thanks  Sent from Mail for Windows 10 From: Aaron ClausonSent: Saturday, April 17, 2021 4:14 PMTo: sipsorcery-org/sipsorceryCc: farhanjavid; AuthorSubject: Re: [sipsorcery-org/sipsorcery] Can we make multiple calls parallelly using single SIPClient ? (#465) No. One call per SIPClient is what you should do.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
