### ISSUE TITLE
How to specify audio codec G729

### ISSUE THREAD

**Issue by RomanPlekhanov** [sipsorcery-org/sipsorcery#472]
Hi! I try connect to Avaya telephony and have a problem. I can't connect to Avaya because it requires G729 audio codec. How can I specify this audio codec? Thanks!

**Comment by sipsorcery** [comment]
There is no `g729` codec included in this project.

Someone else did do something with `g729` a while ago if you want to search through the old issues.

**Comment by RomanPlekhanov** [comment]
It is sad. Thank you.
