### ISSUE TITLE
BYE is not re-sent upon 407 Proxy-Autentication request

### ISSUE THREAD

**Issue by Cheroukee** [sipsorcery-org/sipsorcery#477]
Hello! 

I'm currently working with a PBX that sends a 407 Proxy-Authentication request when trying to leave a call, but I've noticed my calls not actually hanging up on the other clients if I hang up from a SipSorcery SIPUserAgent. 

I've investigated and it seems like we simply do not re-send a BYE with the proper auth header. I've been able to kinda fix it by using the Server/Client User Agents to hangup, but it only partially fixes the problem (only when we made the call). It seems in the Server User Agent I'd need to have a non-null ISIPAccount for it to resend.

My fix currently, from SIPUserAgent
```
/// Old code
/*if (m_sipDialogue != null && m_sipDialogue.DialogueState != SIPDialogueStateEnum.Terminated)
{
  m_sipDialogue.Hangup(m_transport, m_outboundProxy);
  m_byeTransaction = m_sipDialogue.m_byeTransaction;
}*/

/// New code, use the UserAgents depending on which is available
if (m_uac != null)
{
  m_uac.Hangup();
}
else if (m_uas != null)
{
  m_uas.Hangup(false);
}
```

Is this an issue and can I help in any way to fix it ? 

Thanks in advance

**Comment by Cheroukee** [comment]
To add to this, I've did a patch fix on my side by supplying an ISIPAccount to the ServerUserAgent which lets it do the re-send and it seems to work. 

I just don't know if you'd want it fixed this way, if you want I'll be able to create a pull request and we can fix this properly

**Comment by sipsorcery** [comment]
Is the problem that the `BYE` request sent from the sipsorcery library does not have an expected the authentication header? Are you able to provide a SIP trace of the INVITE and BYE requests?

**Comment by Cheroukee** [comment]
I'll send you some traces shortly, but it's more that when the server sends a 407 because the initial BYE did not contain the authentication header, sipsorcery does not re-send a BYE with auth (the SIPDialogue.Hangup method does not have the hookups for that)

**Comment by sipsorcery** [comment]
> the SIPDialogue.Hangup method does not have the hookups for that

That's true, it doesn't. It's very rarely needed as most SIP Providers/Servers don't enforce authentication on `BYE` requests.

If you have a PR that adds the functionality I can't see any reason why it shouldn't be merged.

**Comment by Cheroukee** [comment]
I've seen this also on hold/unhold, where the invite that gets sent with the updated SDP will not be resent (the pbx I'm working with is pretty strict on this). I'll see what I can do on that front too. 

Do you still want the traces ? I can send them by email if you want.

**Comment by sipsorcery** [comment]
If you've got the traces send them to me at aaron@sipsorcery,com. They're always useful to verify what's going on. If you don't have them it's not important. The issue seems pretty clear.

**Comment by Cheroukee** [comment]
The PR for the BYE changes is up, I'll make a separate one for Hold/Unhold
