### ISSUE TITLE
Can I accept exists call parked in queue?

### ISSUE THREAD

**Issue by RomanPlekhanov** [sipsorcery-org/sipsorcery#482]
I use Asterisk. The call enters the queue and waits for an answer. I have a call id. Can I accept a parked call by ID or other descriptor?

**Comment by sipsorcery** [comment]
I'm not sure if you'll be able to pick up the call with only SIP signalling. You might need some kind of script integration, maybe Asterisk Gateway Interface (AGI).

Maybe @skrusty might be able to help?
