### ISSUE TITLE
How to use MusicMediaSession? Missing example.

### ISSUE THREAD

**Issue by jsiedentop** [sipsorcery-org/sipsorcery#483]
How to use MusicMediaSession with SIPUserAgent? 

My understanding is, that you get an RTP connection via SIPUserAgent. The SIPUserAgent:Call expects an IMediaSession object. 
MusicMediaSession implements IMediaSession, but requres an rtpEndPoint in the constructor (which is only known after the the sip connection is etablished).

@soitgoes, you created the pull request https://github.com/sipsorcery-org/sipsorcery/pull/368 for the MusicMediaSession (thanks for contributing 👍), maybe you can can help here?

**Comment by sipsorcery** [comment]
> My understanding is, that you get an RTP connection via SIPUserAgent. The SIPUserAgent:Call expects an IMediaSession object.
> MusicMediaSession implements IMediaSession, but requres an rtpEndPoint in the constructor (which is only known after the the sip connection is etablished).

Yes, you're right the `MusicMediaSession` is attempting to set the RTP destination end point before the session has been negotiated. I didn't spot that before. @soitgoes is that the desired behaviour?

The `MusicMediaSession` is just a tiny wrapper around the `VoIPMediaSession` so if it doesn't suit your needs I'd recommend using the `VoIPMediaSession directly. The [PlaySounds](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/PlaySounds/Program.cs) example demonstrates how to [play music](https://github.com/sipsorcery-org/sipsorcery/blob/18d0e18737ed3897859922cb533a58be6c6c98a8/examples/SIPExamples/PlaySounds/Program.cs#L127) to the destination if that's what you're after.

**Comment by jsiedentop** [comment]
@sipsorcery Thank you very much for your time. I actually used VoIPMediaSession for my solution. I created this issue mainly because of the possible inconsistency.
