### ISSUE TITLE
RTP Seq is sometimes used twice when sending DTMF due to race condition

### ISSUE THREAD

**Issue by tstaehli** [sipsorcery-org/sipsorcery#484]
I encountered the following duplicate Seq Number for an RTP Event rsp. a skipped Seq Number when sending DTMF RTP-Events using the userAgend.SendDtmf Method.

![image](https://user-images.githubusercontent.com/3128725/118517442-7fca9800-b737-11eb-8fde-2192cf844026.png)

The cause is the non-synchronized increments of the audioTrack.SeqNum Property. Without DTMF, this is never a problem, because only one thread is ever incrementing the SeqNum. But if SendDTMF is called, another Thread is introduced, which introduces the observer Race-Condition (classic read, modify write problem).

To avoid having to use an expensive lock statement when incrementing the SeqNum, I propose the folowing solution:

Replace property `MediaStreamTrack.SeqNum` with a private field. Change all accesses to `MediaStreamTrack.SeqNum` to a Method call `GetNextSeqNum`, which increments and returns a `SeqNum` to use when creating a `RTPPacket`. `GetNextSeqNum` should increment the new field using `Interlocked.CompareExchange` using something like https://stackoverflow.com/a/8698560 to faciliate the integer overflow.

This would also remove all the lines 
`audioTrack.SeqNum = (audioTrack.SeqNum == UInt16.MaxValue) ? (ushort)0 : (ushort)(audioTrack.SeqNum + 1);` from RTPSession, and centralise the incrementing and overflow handling to the new method GetNextSeqNum.

If its okay with @sipsorcery , I will prepare a Pull Request with the before mentioned changes. Or do you have another preferred way to solve this?

Regards,
Tobias

**Comment by sipsorcery** [comment]
Thanks for the diagnosis and the solution sounds good to me. PR would be most welcome.
