### ISSUE TITLE
VoIPMediaSession async void .Close()

### ISSUE THREAD

**Issue by bvanbleyenbergh** [sipsorcery-org/sipsorcery#489]
I ran into the problem where my call keeps ringing for the receiver, even after I called `userAgent.Cancel()`.

I fixed the problem by adding a 1 second delay.
Is there a reason the `VoIPMediaSession.Close()` method is async void and can't be awaited?

[https://github.com/sipsorcery-org/sipsorcery/blob/d1a2f2bc18d3868ceefbd50ad4c1b076e0ed1392/src/app/Media/VoIPMediaSession.cs#L196](https://github.com/sipsorcery-org/sipsorcery/blob/d1a2f2bc18d3868ceefbd50ad4c1b076e0ed1392/src/app/Media/VoIPMediaSession.cs#L196)

**Comment by sipsorcery** [comment]
This seems like a reasonable question. Did you find something else?

**Comment by bvanbleyenbergh** [comment]
Closed the issue because my problem was caused by something else.
My SipTransport instance was cleaned up before it could send the Cancel() message.

**Comment by Yitzchok** [comment]
@sipsorcery 
It's used as an event handler in a lot of places so from one side it might be kind of legal to return void but it's public so I would say it should be changed to return a Task.

**Comment by sipsorcery** [comment]
@Yitzchok I agree that returning `Task` would be better. I did a quick experiment to that effect. The change does cascade a bit into event handlers and various Close calls. I'm not sure it's worth the disruption.

**Comment by Yitzchok** [comment]
Mark it as obsolete and move the code to a method ..Async returning a Task. Call that method from the obsolete method (and use .Results)
