### ISSUE TITLE
Rng breaking - results in incorrect ice candidates being chosen

### ISSUE THREAD

**Issue by moorecj** [sipsorcery-org/sipsorcery#492]
I have been load testing webrtc connections from Sipsorcery  to browser in parallel.  I was running into the issue that eventually the whole system would die and new connections were not being created. After investigation I found that the the wrong ice candidate pairs were being chosen. 

Looking deeper I have found that in the scenario all the ice candidate checklist entries all have the same transaction IDs "AAAAAAAAAAAA".  I also found that ice-ufrag and ice-pwd were all being set to all 'A's. 

The problem seems to stem from the fact the Random is not thread safe and its being initialized into a static variable. You can see the general issue described here:
https://stackoverflow.com/questions/20412155/random-next-always-returns-0 

The issue seems to be line 36 in Crypto.cs
private static Random _rng = new Random();

I was thinking something like this would be a nice solution to the problem: https://stackoverflow.com/a/19271062/14531044 
I can submit a pull request if you like that idea.

**Comment by sipsorcery** [comment]
> I was thinking something like this would be a nice solution to the problem: https://stackoverflow.com/a/19271062/14531044
> I can submit a pull request if you like that idea.

Sounds good, yes please.

**Comment by sipsorcery** [comment]
Resolved by #493.
