### ISSUE TITLE
The SIPSorcery.Net.SDP.ParseSDPDescription method does not parse SDP content if terminated with just a newline (i.e. '\n') character

### ISSUE THREAD

**Issue by jefft666** [sipsorcery-org/sipsorcery#496]
As stated in the [SDP: Session Description Protocol](https://datatracker.ietf.org/doc/html/rfc4566) RFC, _"The sequence CRLF (0x0d0a) is used to end a record, although parsers **SHOULD** be tolerant and also accept records terminated with a single newline character."_

The code should probably do a quick check for the existence of "\r\n" string and/or a '\n' character, and split the string as appropriate. Alternatively the code could simply split based on the '\n' character and strip any additional '\r' and/or '\n' characters from the split-result strings and it would still work with both "\r\n" and '\n' line endings.

**NOTE:** _If_ a workaround exists for altering the content of the SDP string (prior to the parsing) to "fix up" the SDP so that the existing parser works as expected, that would be helpful until this issue is resolved.

**Comment by sipsorcery** [comment]
An easy fix would be to so a replace any `\r` or `\n` chars that are not part of `\r\n` with `\r\n`.

I did do something [similar](https://github.com/sipsorcery-org/sipsorcery/blob/48c156ff5ce48d1369a598a2b8a3574263ac684b/src/core/SIP/SIPHeader.cs#L1452) when parsing SIP headers. I guess it didn't occur to me to do it for SDP.

**Comment by jefft666** [comment]
When/how would one intercept the SIP body prior to it being parsed by the SIPSorcery.Net.SDP.ParseSDPDescription? In other words, is there a way to modify this in the calling code via a event handler? I wasn't able to figure out a means of doing this.
