### ISSUE TITLE
Blind Transfer not working for me

### ISSUE THREAD

**Issue by jafarulla15** [sipsorcery-org/sipsorcery#497]
![image](https://user-images.githubusercontent.com/15998911/121058920-b51c5000-c7e2-11eb-8fd0-286ad63526b8.png)
,
I am sorry for bothering you. I am very beginner and try to test the call transfer and fail. Don't know why. Tried from softphone at example and also from the console. Would you please help me find out what are the wrong. 
Best Regards

_Originally posted by @jafarulla15 in https://github.com/sipsorcery-org/sipsorcery/issues/288#issuecomment-856101802_

**Comment by sipsorcery** [comment]
Looks like you could have multiple issues.

First one to solve is why the ACK request is not getting through to your Asterisk server.

In the INVITE response below note the `Contact` header:

`Contact: sip:182.163.113.209:5060`

The subsequent ACK request gets sent to that address but it does not get received. The way to know this is the server retransmits the same INVITE response up to 11 times while waiting for the ACK.

The REFER request, for the blind transfer, is getting sent to the same address. By solving why the ACK doesn't get through it may solve the blind transfer as well.

````
[22:36:07 DBG] Response received: udp:0.0.0.0:54441<-udp:192.168.0.4:5060
[22:36:07 DBG] SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.0.0.12:54441;rport=54441;received=10.0.0.12;branch=z9hG4bKbed7c30bcd0d4c2dafee7e1366bcab00
To: sip:408@192.168.0.4;tag=ad503475-7b4d-4603-b3b2-6da97c214f60
From: sip:1003@192.168.0.4;tag=ZNXMCHUTCL
Call-ID: 0cacb5c0fef64b7a9806cfde0a1ff152
CSeq: 2 INVITE
Contact: sip:182.163.113.209:5060
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Content-Length: 226
Content-Type: application/sdp
Server: FPBX-15.0.17.34(16.6.2)
P-Asserted-Identity: "408" sip:408@192.168.0.4

v=0
o=- 1570444482 2 IN IP4 192.168.0.4
s=Asterisk
c=IN IP4 192.168.0.4
t=0 0
m=audio 18860 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv

[22:36:07 DBG] Request sent: udp:10.0.0.12:54441->udp:182.163.113.209:5060
[22:36:07 DBG] ACK sip:182.163.113.209:5060 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.12:54441;branch=z9hG4bKbb3d6b2570c649769ea0b32ec5cebf77;rport
To: sip:408@192.168.0.4;tag=ad503475-7b4d-4603-b3b2-6da97c214f60
From: sip:1003@192.168.0.4:5060;tag=ZNXMCHUTCL
Call-ID: 0cacb5c0fef64b7a9806cfde0a1ff152
CSeq: 2 ACK
Max-Forwards: 70
Authorization: Digest username="1003",realm="asterisk",nonce="1623105487/ad4ce9328656f18733f88d1d0c030363",uri="sip:408@192.168.0.4:5060",response="860341cd5a8bc8b3e4601b99a1b723a5",cnonce="1090407593",nc=00000001,qop=auth,opaque="591ba7a7284f9cb5",algorithm=MD5
Content-Length: 0
````

**Comment by sipsorcery** [comment]
Closing, fee free to re-open if there are any further questions.
