### ISSUE TITLE
Outbound call over SIP registration

### ISSUE THREAD

**Issue by thenicnic** [sipsorcery-org/sipsorcery#498]
Probably the most stupid question here but I can't manage to find a solution:
How do I perform an outgoing call over existing SIP registrations? [Documentation](https://sipsorcery-org.github.io/sipsorcery/articles/intro.html) is pretty good but as often I read through the articles as often I didn't find the way to do this in a basic command line application.

As far as I understand:

- "SIPUserAgent" includes the functions I need (like call, hangup etc.) but is independent from an existing SIP registration to an existing SIP server.
- "SIPRegistrationUserAgent" can be used to register to an existing SIP server - which works well with the example program and my local SIP server - but it doesn't include the call handle features.

Do I have to use "SIPClientUserAgent" as I contains all the call handle features? But there's no reference to "SIPRegistrationUserAgent" so I do not know if they correspond.
Or is it neccessary to combine "SIPUserAgent" with "SIPRegistrationUserAgent", for example over a common "SIPTransport" instance?

A little hint or an example would help me as a beginner a lot.

**Comment by sipsorcery** [comment]
The SIP protocol does not link registrations and **outgoing** calls. The point of a SIP registration is to provide a contact address(es) for **incoming** calls. The `SIPUserAgent` and `SIPRegistrationUserAgent` are true to that approach.

But... some SIP Providers do include mechanisms in their call authorisation logic to check whether there is a current registration. It's pretty pointless and adds a negligible amount of extra protection.

First thing I'd double check is whether you can make an outgoing call without registering. More than likely you can. If you're having trouble with this library you can use any softphone, such as [CounterPath's Bria](https://www.counterpath.com/bria-solo/), that allow the registration option to be disabled, and see if you can place a call.

**Comment by thenicnic** [comment]
Thank you so much! Embarrassing - I need to learn more about SIP.

But yes, no persistent registration to my home PBX router neccessary for outgoing calls. Only thing that was needed were the call params `username` and `password` for the `userAgent.Call`. They need to be the valid credentials for an existing VoIP telephony device setup in my "Fritzbox". Suprisingly only username and password are obligatory; auth name and number are unneccessary to tell the client for outbound - also didn't know that. 
I really have fun with your outstanding work plus it will help me understanding SIP a bit more.

**Comment by sipsorcery** [comment]
Don't worry, SIP is obscure for everyone at the start. Lot so little quirks.

> Suprisingly only username and password are obligatory; auth name and number are unnecessary to tell the client for outbound - also didn't know that.

This is an example of one of those quirks. The username is typically what goes in the 'From' & 'To' headers. The auth username is for the authentication header. But if no auth username is specified, which is the normal case, the default is to use the username.

**Comment by thenicnic** [comment]
Is there a possibility to define a sperate auth name if neccessary?
And by the way, which audio library do you recommend? When using SIPSorceryMedia.Windows for a .NET 5 project, the compiler tells me: `SIPSorceryMedia.Windows.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.`
And PortAudio throws me an error at initalization at runtime although source is included.

**Comment by sipsorcery** [comment]
> Is there a possibility to define a sperate auth name if neccessary?

Yes. To do so you need to use the `SIPUserAgent.Call` overload that takes a `SIPCallDescriptor` parameter. It has an `AuthUsername` parameter.

> And by the way, which audio library do you recommend? When using SIPSorceryMedia.Windows for a .NET 5 project, the compiler tells me: `SIPSorceryMedia.Windows.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.`

See https://github.com/sipsorcery-org/sipsorcery/issues/499.

> And PortAudio throws me an error at initalization at runtime although source is included.

I did get PortAudio to work on Linux for a demo but it was very fragile. NAudio is by far the best .NET audio library for Windows. If you only want audio functionality you could strip the required classes out of `SIPSorceryMedia.Windows`. It's the video classes that are breaking the .NET5 compilation.

**Comment by sipsorcery** [comment]
Closing, feel free to re-open if any further questions.
