### ISSUE TITLE
.net 5  SIPSorceryMedia.Windows

### ISSUE THREAD

**Issue by fallingrust** [sipsorcery-org/sipsorcery#499]
SIPSorceryMedia.Windows.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher 
Is there a solution if i use .net 5？

**Comment by sipsorcery** [comment]
It should be possible to get the `SIPSorceryMedia.Windows` library building with .NET5. I need to look at how to replace the `Microsoft.Windows.SDK.Contracts` dependency, which is the way earlier versions of .NET Core were able to get access to the webcam WinRT APIs. The mechanism has changed but I'm pretty sure [.NET5 can still access WinRT APIs](https://blogs.windows.com/windowsdeveloper/2020/09/03/calling-windows-apis-in-net5/).

I'll try and find some time to look at it this weekend but if you, or anyone else, is able to work it out in the meantime PR's are always welcome.

**Comment by fallingrust** [comment]
Thanks

**Comment by sipsorcery** [comment]
I'm able to get the `SIPSorceryMedia.Windows` project to build with .NET5 by changing the two lines in the project file as shown below (see https://blogs.windows.com/windowsdeveloper/2020/09/03/calling-windows-apis-in-net5/):

````
 <ItemGroup>
 ...
  <PackageReference Condition="'$(TargetFramework)' == 'netcoreapp3.1'" Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
 ...
 <\ItemGroup>

 <PropertyGroup>
  ...
  <TargetFrameworks>netcoreapp3.1;net5.0-windows10.0.19041.0</TargetFrameworks>
  ...
 </PropertyGroup>
````

But after making those changes neither audio or video works with `NET5` apps and `netcoreapp3.1` apps won't even build.

It doesn't look to me like `NET5` is really ready for consuming WinRT APIs. Having to set a specific version of the Windows SDK in the framework moniker seems very fragile. I'm not keen to fight the framework and would rather wait and until November and set if `NET6` fixes the problem.

For anyone that does want to use the audio functionality of this assembly with `NET5` apps the recommend solution is to copy and paste the `WindowsAudioEndPoint.cs` file into your app. It's self contained.
