### ISSUE TITLE
Duplicate SIP Status code 580

### ISSUE THREAD

**Issue by RobThree** [sipsorcery-org/sipsorcery#500]
I was building a list of SIP status codes and comparing [Wikipedia](https://en.wikipedia.org/wiki/List_of_SIP_response_codes) and other sources and then I stumbled upon the [`/src/core/SIP/SIPConstants.cs`](https://github.com/sipsorcery-org/sipsorcery/blob/62fd4cd8e83071c83b29ccaf4983c56cfdf8df8f/src/core/SIP/SIPConstants.cs) file.

It appears that code 580 is defined twice:

1. [On line 460](https://github.com/sipsorcery-org/sipsorcery/blob/62fd4cd8e83071c83b29ccaf4983c56cfdf8df8f/src/core/SIP/SIPConstants.cs#L460) (in the 4xx block, where it shouldn't belong anyway).
2. [On line 470](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/core/SIP/SIPConstants.cs#L470)

Also I happened to notice you seem to be missing some codes I found in the wild; do with them what you wish:

* `199`: Early Dialog Terminated
* `380`: Alternative Service
* `409`: Conflict
* `411`: Length Required
* `424`: Bad Location Information
* `425`: Bad Alert Message
* `469`: Bad Info Package
* `494`: Security Agreement Required
* `555`: Push Notification Service Not Supported
* `607`: Unwanted
* `608`: Rejected

Then, finally, you have [`303`](https://github.com/sipsorcery-org/sipsorcery/blob/62fd4cd8e83071c83b29ccaf4983c56cfdf8df8f/src/core/SIP/SIPConstants.cs#L414): UseProxy, shouldn't this be `305` (according to [Wikipedia](https://en.wikipedia.org/wiki/List_of_SIP_response_codes#3xx%E2%80%94Redirection_Responses) and [other](https://www.3cx.com/pbx/sip-responses/) sources and [RFC](https://datatracker.ietf.org/doc/html/rfc3261#section-21.3.4))?

Just to be clear: I have little to no knowledge on the sipsorcery project; I just noticed the above and thought I would mention it for investigation. All of the above 'mistakes' may very well be intentional and I'm just missing context.

**Comment by sipsorcery** [comment]
Thanks for the heads up. I'll double check the codes against RFC3261.

SIP must had around 50 add-on RFC's last time I looked, probably closer to 100 now. A lot of those will add extra response codes or request types. They'll always be some that are only relevant for very specialised cases and no library or SIP server will ever cover every single SIP related specification.

**Comment by RobThree** [comment]
> They'll always be some that are only relevant for very specialised cases and no library or SIP server will ever cover every single SIP related specification.

Oh, I agree and I'm aware. I'm not saying you should add/support any of these. That's up to you. Main reason for the issue was the duplicate 580 code; the rest is sharing just my findings.
