### ISSUE TITLE
I'd like to ask for support noise-canceling

### ISSUE THREAD

**Issue by Jack-M-Code** [sipsorcery-org/sipsorcery#501]
SIP Call Is there noise-canceling?

**Comment by sipsorcery** [comment]
No, there's no echo cancelling logic in this library.

**Comment by Jack-M-Code** [comment]
http://adrianb.io/2014/08/09/perlinnoise.html

**Comment by sipsorcery** [comment]
PR's welcome :-)

**Comment by Jack-M-Code** [comment]
How to develop video conferencing

**Comment by Jack-M-Code** [comment]
Webcam Virtual Background can be supported
It's like Zoom

**Comment by sipsorcery** [comment]
> How to develop video conferencing

Doing that from scratch is an absolutely massive task that you almost certainly don't want to do.

There are lots of existing WebRTC products with APIs that you can hook into to tailor different aspects. Take a look at Jitsi, Janus, Kurento etc.

**Comment by Jack-M-Code** [comment]
Thank you
