### ISSUE TITLE
Build GetStartedNetFramework fails

### ISSUE THREAD

**Issue by oo-dev17** [sipsorcery-org/sipsorcery#503]
Dear Sipsorcery supporters,
I am trying my first steps with this lib and have downloaded the samples.

Trying in VS2019 on Win 10 the GetStartedNetFramework example (.NET 4.7.2) but getting weird errors, like:
"**_Reference to type 'IAudioEncoder' claims it is defined in 'SIPSorceryMedia.Abstractions', but it could not be found	GetStartedNetFramework_**

I have updated the nuget packages to
![image](https://user-images.githubusercontent.com/6067255/121869873-c396ca00-cd02-11eb-972a-81b2b3bdc981.png)

All 'references' in the project are fine (have no exclamation mark)
No matter if I compile as x86 or x64
![image](https://user-images.githubusercontent.com/6067255/121869607-82061f00-cd02-11eb-9ad7-e18d6f40d4a5.png)

Any help is appreciated, Thank you in advance
oo_dev17

**Comment by sipsorcery** [comment]
It should be fixed if you use:

SIPSorceryMedia.Windows v0.0.31-pre
NAudio v1.10.0

Or do a git pull to pickup the project fixes I just committed.

**Comment by oo-dev17** [comment]
I tried your first workaround and it runs fine now. Thank you a lot for the quick response 👍😊
