### ISSUE TITLE
Incoming call INVITE

### ISSUE THREAD

**Issue by mmjc23** [sipsorcery-org/sipsorcery#504]
Hi, I am sorry for bothering you. 
With my application, I would like to manage the reception of multiple calls at the same time.

So, for each INVITE Request related to each call received, I create a new SIPUserAgent and accept the call
```
Dim ua As New SIPUserAgent(epsSIP, Nothing)
Dim sua As SIPServerUserAgent = ua.AcceptCall(request)
```
But I would like to answer the call only when the user presses the "accept" button, so I add the SIPUserAgent to a collection

When the user presses the accept button, I retrieve the SIPUserAgent from the collection, but the Answer method of SIPUserAgent requires the SIPServerUserAgent and IMediaSession parameters.

Following the examples, I am able to create a VoIPMediaSession object but in no way can I get the SIPServerUserAgent returned by the AcceptCall method.

Do I have to save both the UserAgent and the SIPServerAgent in the collection, or is there a more practical way?
Thanks in advance
Best regards

**Comment by mmjc23** [comment]
Is there a way to get SIPServerUserAgent and SIPClientUserAgent objects from the SIP UserAgent?
Thank you

**Comment by sipsorcery** [comment]
> Do I have to save both the UserAgent and the SIPServerAgent in the collection, or is there a more practical way?

Yes you'll have to keep a track of both.

The reason the `SIPServerUserAgent` from the `AcceptCall` method isn't stored is because until it's answered it's not considered part of an active call. It can still be rejected, redirected or ignored.

**Comment by mmjc23** [comment]
Ok Aaron, thank you very much for your clarification.
Best regards
