### ISSUE TITLE
[Qustion] Why SIPTransport never call RequestTransaction.GotRequest method?

### ISSUE THREAD

**Issue by pedoc** [sipsorcery-org/sipsorcery#510]
Hi,thank you for your excellent work 

I want to delay you a little time to ask a question.  

When I inherited and implemented my own business logic from ```SIPTransaction```, I found that ```SIPTransaction.TransactionRequestReceived``` never triggered because its ```GotRequest``` function was not called.

It can be noticed that there is a call to ```SIPTransaction.GotResponse``` in ```SIPTransport``` so that ```SIPTransaction.TransactionFinalResponseReceived``` can be triggered correctly.

So I would like to ask, why not call ```SIPTransaction.GotRequest``` in ```SIPTransport```? Is this a design reason or a bug?

**Comment by sipsorcery** [comment]
I looked into this and it turns out the transaction request received and got request logic is never used. I've removed it in #511.

**Comment by pedoc** [comment]
Thank you for your reply.

In fact, I don't expect to delete this api, but should call it in the right place. The reason is as follows:

1.Not all transactions in business scenarios do not care about requests (such as the SIP-based sub-protocols I am implementing) 
2.Destroy api symmetry. I think that the encapsulation of the request and the encapsulation of the response processing in the transaction should appear in pairs

ps:If the processing of the request in the transaction is removed, I will have to directly handle the event on the SIPTransport, which I think adds complexity

**Comment by sipsorcery** [comment]
> 1.Not all transactions in business scenarios do not care about requests (such as the SIP-based sub-protocols I am implementing)

Can you provide an example? As mentioned in the PR a SIP transaction instance is only ever created from a SIP Request. Firing an additional event to inform the app the SIP Request has been received is redundant; it already has access to it from the SIP transaction object.

If there is a genuine need I'm happy to accommodate. I did add this fix into a PR in case there were additional things to consider.

**Comment by pedoc** [comment]
Maybe I didn’t express it clearly enough, sorry.

If a transaction has only one request + response mode, then the existing scheme is indeed sufficient. 

Let us consider another situation. After we create a transaction with a certain request and send a ```SIPRequest```, we expect other servers to return ```SIPResponse```, but what if other domain servers also reply to us with ```SIPRequest```? 

The specific business scenario is:
Suppose we now have 2 SIP servers that need to communicate，they are called
```
SIPServer：A
SIPServer：B
```

steps:
1.A sent a query request（content over SIPRequest.Body）
2.B receives this request and starts to reply, but it will not pass SIPResponse, but reply to multiple SIPResquests to transmit data （content over SIPRequest.Body）

In the above case, unless B uses SIPResponse to reply, it is impossible for us to complete it using SIPTransaction. 
Of course ,At this point of course we can directly use SIPTransport.SIPTransportRequestReceived to complete this task, but this separates the specific logic,so I will consider using transactions to accomplish it.

Let me use code to express a minimal example:


Send query request
![image](https://user-images.githubusercontent.com/6604230/123421636-aeb61280-d5ef-11eb-831e-b3d6d2f6dde2.png)


Receive the SIPRequest from the other party in the transaction and reorganize it into business data 
![image](https://user-images.githubusercontent.com/6604230/123421664-b7a6e400-d5ef-11eb-8dec-f130a00930ea.png)


At this time, if SIPTransaction cannot receive SIPRequest on SIPTransport, this code will not work.

PS:
This SIP-based sub-protocol is called GB28181. This is not an international protocol, it is only suitable for security scenarios.

**Comment by sipsorcery** [comment]
> This SIP-based sub-protocol is called GB28181. This is not an international protocol, it is only suitable for security scenarios.

Do you have a good link for the protocol? I found a few, including the one below, but they're incomplete.

https://www.chinesestandard.net/PDF/English.aspx/GBT28181-2016?Redirect=YES

I suspect you might be trying to use a SIP Transaction where you should be using a SIP Dialogue. The SIP specification uses SIP transactions for single request/response exchanges. A SIP extension that attempts to send different requests within a single SIP transaction is going to get rejected by a lot of SIP implementations.

**Comment by pedoc** [comment]
Yes, maybe I should self reimplement GB28181 transactions based on SIPTransport. But my starting point is also very simple. As I said in my previous comment, to be compatible with GB28181 transactions, only one line of code needs to be added, and this does not conflict with the standard SIP specification.
For my scenario, I will handle the OnTransactionRequestReceived event. For other people who use the standard SIP protocol, they can ignore this event completely, which does not change the behavior of this library.

I do have the GB28181 specification document, but it is in Chinese. A copy of the document can be obtained [here](https://github.com/pedoc/public).

**Comment by sipsorcery** [comment]
You're definitely going down the wrong path. Each of the MESSAGE request/responses in your capture are separate SIP transactions. A SIP transaction must have the same `branch` parameter on the `Via` header. You'll end up running into difficulties with this library if you try and treat multiple SIP MESSAGE requests as belonging to the same SIP transaction.

Take a look at the [SIPNotifierClient](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/SIPUserAgents/SIPNotifierClient.cs). It's the closest thing to what you're trying to do. It matches new SIP requests with an existing subscription (same thing as a session etc). Matching multiple requests based on some field is not what a SIP transaction is meant for. In your case it looks like you actually need to go into the XML body to match each request to the session.

**Comment by pedoc** [comment]
Yes you are right, thanks for your opinion.

Conceptually, SIPTransaction is indeed different from GB28181 Transaction.
Here, because many of the definitions in the GB28181 protocol use the MESSAGE type, the GB28181 Transaction spans multiple SIP MESSAGE requests. It is up to the developer to parse the content of SIPRequest.Body to determine which SIPRequest belongs to the same transaction.

Although I still think that allowing SIPTransaction to receive SIPRequests from SIPTransport will not bring about break changes, I respect your decision. This will cause me to need to encapsulate GB28181 Transaction based on SIPTransport, but this is feasible. 

Now you can decide whether to close this question. :)

**Comment by sipsorcery** [comment]
Fixed.
