### ISSUE TITLE
Does sipsorcery sip server accept multiple incoming calls ?

### ISSUE THREAD

**Issue by HarunDurmus** [sipsorcery-org/sipsorcery#515]
Does sipsorcery accept multiple calls to the sip server? if it accepts does it keep any session id to distinguish each incoming call

**Comment by sipsorcery** [comment]
The main sipsorcery library does not have a SIP server as such. It has the building blocks to build your own SIP server. There are lots of different permutations of what a SIP server can be.

There are some examples using the library that implement some basic SIP server type applications. The most sophisticated is currently [signalrtc](https://github.com/sipsorcery-org/signalrtc).

**Comment by HarunDurmus** [comment]
I found the solution to the problem I encountered in the SIPCallServer example. but in this example, I can't make multiple simultaneous calls

**Comment by sipsorcery** [comment]
Looks like this issue is resolved. Fee free to re-open if anything further.
