### ISSUE TITLE
No Incoming or Outgoing Audio

### ISSUE THREAD

**Issue by jpwkeeper** [sipsorcery-org/sipsorcery#516]
I am attempting to run the example code for recording an incoming call.  My carrier is CallCentric, so I added the code for the SipRegistrationUserAgent to the example, but that is all I changed.  This is using .NET Framework 4.8.

The incoming call is answered, but no audio is heard from either end.

I presume I'm doing something wrong, but I can't figure out what.

The "hello world" example works as expected, for reference.

**Comment by sipsorcery** [comment]
Are the audio packets being received from CallCentric? Can you do a WireShark trace to check they are getting through and not being blocked by a NAT or firewall?

**Comment by jpwkeeper** [comment]
OK, it turns out that this laptop I was using did have the firewall turned on (I didn't realize that).  My apologies.
