### ISSUE TITLE
Streaming Audio to Discord

### ISSUE THREAD

**Issue by SeaLife** [sipsorcery-org/sipsorcery#518]
Hey,

im currently building a proxy application to allow me to chat with my friends via a VoIP call.

I've build everything so far, now i want to stream the audio from the phone to discord.

Discord requires PCM 48khz Audio (according to the docs of Discord.Net https://docs.stillu.cc/guides/voice/sending-voice.html)

I cant use NAudio because im limited to Linux and therefore cant use the decoder/encoders from there..

Does someone know how i decode/encode the given G722 media to PCM 48khz ?

Simply writing the bytes onto the discord stream  did not work 🗡️ 

```csharp
    public class DiscordAudioSink : IAudioSink
    {
        private readonly IAudioClient   _audioClient;
        private readonly AudioOutStream _stream;

        private List<AudioFormat> _audioFormats = new();

        public DiscordAudioSink(IAudioClient audioClient)
        {
            _audioClient = audioClient;
            _stream      = audioClient.CreatePCMStream(AudioApplication.Mixed);
        }

        public List<AudioFormat> GetAudioSinkFormats()
        {
            Console.WriteLine("GetAudioSinkFormats");
            return _audioFormats;
        }

        public void SetAudioSinkFormat(AudioFormat audioFormat)
        {
            _audioFormats.Add(audioFormat);
        }

        public void GotAudioRtp(IPEndPoint remoteEndPoint, uint ssrc, uint seqnum, uint timestamp, int payloadID, bool marker, byte[] payload)
        {
            // requires encoding/decoding here, i guess :D
            _stream.Write(payload);
        }

        public void RestrictFormats(Func<AudioFormat, bool> filter)
        {
            Console.WriteLine("RestrictFormats: {0}", filter);
        }

        public Task PauseAudioSink()
        {
            Console.WriteLine("PauseAudioSink");
            return Task.CompletedTask;
        }

        public Task ResumeAudioSink()
        {
            Console.WriteLine("ResumeAudioSink");
            return Task.CompletedTask;
        }

        public Task StartAudioSink()
        {
            Console.WriteLine("StartAudioSink");
            return Task.CompletedTask;
        }

        public Task CloseAudioSink()
        {
            Console.WriteLine("CloseAudioSink");
            _stream.Close();
            return Task.CompletedTask;
        }

        public event SourceErrorDelegate OnAudioSinkError;
    }
```

Regards
SeaLife

**Comment by sipsorcery** [comment]
I think you're on the right track. Do you get any sound at all in Discord? If things are wired up correctly I'd expect you to get noise or at least some occasional clicks/cracks.

The step you're missing are in `GotAudioRtp` you need to decode the RTP packets from G722 to PCM 48KHz. Take a look at the [AudioEncoder class](https://github.com/sipsorcery-org/sipsorcery/blob/10ed1071dea626e3648f98bd19cb5d17f7b091e7/src/app/Media/Codecs/AudioEncoder.cs#L118) for an example of how to use the G722 codec class (Which was actually copied verbatim from NAudio).

**Comment by SeaLife** [comment]
Hey, thanks for the fast reply.

No, not even the blue-ring around the bot talking...

If i send a sound file throught FFMPEG like this:

```csharp
        public DiscordAudioSink(IAudioClient audioClient)
        {
            _audioClient = audioClient;
            _stream      = audioClient.CreatePCMStream(AudioApplication.Mixed);

            PlayWelcomeSound();
        }

        private void PlayWelcomeSound()
        {
            PlaySound("C:\\sound1.mp4");
        }

        private async void PlaySound(string path)
        {
            var stream = Process.Start(new ProcessStartInfo
            {
                FileName               = "ffmpeg",
                Arguments              = $"-hide_banner -loglevel panic -i \"{path}\" -ac 2 -f s16le -ar 48000 pipe:1",
                UseShellExecute        = false,
                RedirectStandardOutput = true,
            });

            using (var ffmpeg = stream)
            using (var output = ffmpeg.StandardOutput.BaseStream)
            using (var discord = _stream)
            {
                try
                {
                    await output.CopyToAsync(discord);
                }
                finally
                {
                    await discord.FlushAsync();
                }
            }
        }
```

The sound gets played on discord but it silences out instantly after this

**Comment by SeaLife** [comment]
After i added the welcome sound on discord, sending proper audio first, i get weird clicks and sounds in discord, probably from the phone-sound stream...

Now its the encoding, i guess.. 🗡️

**Comment by sipsorcery** [comment]
That's a good sign though, at least you're getting something through. The [AudioExtrasSource](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/Media/Sources/AudioExtrasSource.cs) class might also be useful. You can use it so send a PCM sine wave (and other audio signals). It's useful to test an audio path when troubleshooting.

**Comment by SeaLife** [comment]
The AudioEncoder class is not helping me, i dont know much about audio signals to troubleshoot this perfectly...
Can i simply use the AudioEncoder class or do i have to do something special?

With this code:

```csharp
        public void GotAudioRtp(IPEndPoint remoteEndPoint, uint ssrc, uint seqnum, uint timestamp, int payloadID, bool marker, byte[] payload)
        {
            // if disabled, we ignore every package.
            if (!_enabled) return;

            var audioEncoder = new AudioEncoder();
            var decoded = audioEncoder.DecodeAudio(payload, new AudioFormat()
            {
                Codec = AudioCodecsEnum.G722,
            });

            //decoded = audioEncoder.Resample(decoded, 16000, 48000);

            var encoded = audioEncoder.EncodeAudio(decoded, new AudioFormat()
            {
                Codec = AudioCodecsEnum.PCM_S16LE
            });

            // requires encoding/decoding here, i guess :D
            _stream.Write(encoded);
        }
´´´

I dont hear myself speaking but you can clearly hear the difference between speaking and not speaking  on the phone..

The audio send by FFmpeg used `-ac 2`, `-f s16le` and `-ar 48000`, i guess, its the target encoding i need?

**Comment by SeaLife** [comment]
After resampling the audio source from 8k to 48k, i can actually hear myself.. Its awful, but i can actually hear myself... 🎇

**Comment by sipsorcery** [comment]
I was just about to say that G722 uses a 16KHz sampling rate so you'll need to upsample it to 48KHz. You've worked that out. Impressive work!

I'm sure you spotted my [comment](https://github.com/sipsorcery-org/sipsorcery/blob/10ed1071dea626e3648f98bd19cb5d17f7b091e7/src/app/Media/Codecs/AudioEncoder.cs#L179) in the Resample method:

````
else if (inRate == 16000 && outRate == 48000)
{
    // Crude up-sample to 48Khz by 3x each sample. This sounds bad, use for testing only.
    return pcm.SelectMany(x => new short[] { x, x, x }).ToArray();
}
````

To improve things from here you'll need to dig around and find a better audio algorithm to upsample form 16KHz to 48KHz. It will probably never sound that great but you should be able to improve it.

There are codecs, such as OPUS, that support 48KHz, but I never found the time to find and add a C# implementation into this library.

**Comment by SeaLife** [comment]
Okay, thanks, i'll probably find a solution to this problem...
I can share my code when im done. I hope i can get this done with .NET Core. :D

**Comment by SeaLife** [comment]
Okay, my progress is at this point now:

I've written the payload onto my disk, raw..

I used ffmpeg to "resample" it to 48khz and it sounds delicious...

```
.\ffmpeg.exe -hide_banner -loglevel panic -f g722 -i G:\output.wav -ac 2 -f s16le -ar 48000 pipe:1
```

Now i tried to just use ffmpeg in between, just like i did for the audio file...

But i think, its probably to slow to just call ffmpeg for every rtp package...

```csharp
        private Stream resample(byte[] samples)
        {
            var stream = Process.Start(new ProcessStartInfo
            {
                FileName               = "ffmpeg",
                Arguments              = "-hide_banner -loglevel panic -f g722 -i pipe:0 -ac 2 -f s16le -ar 48000 pipe:1",
                UseShellExecute        = false,
                RedirectStandardInput  = true,
                RedirectStandardOutput = true
            });

            var inputStream  = stream.StandardInput;
            var outputStream = stream.StandardOutput.BaseStream;

            Console.WriteLine("Writing to ffmpeg: " + samples.Length);

            inputStream.Write(samples);
            inputStream.Close();

            return outputStream;
        }
```

```csharp
        public void GotAudioRtp(IPEndPoint remoteEndPoint, uint ssrc, uint seqnum, uint timestamp, int payloadID, bool marker, byte[] payload)
        {
            // if disabled, we ignore every package.
            if (!_enabled)
            {
                Console.WriteLine("Skipping Frame {0}", seqnum);
                return;
            }

            MemoryStream memoryStream = new MemoryStream();
            resample(payload).CopyTo(memoryStream);
            var data = memoryStream.ToArray();

            _stream.Write(data);
        }
```

Probably too slow? At least, im only hearing "meeps" on discord, no actual sound/voice coming through

**Comment by sipsorcery** [comment]
FFmpeg can be used in process with .NET, for example https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg. You have to juggle the binaries but with Linux it's generally not too bad. It will also be a bit of a learning curve to get used to the C-centric FFmpeg API but you seem to be a fast learner ;).

**Comment by SeaLife** [comment]
Mh, the ffmpeg api seems complex af....

I tried to process-calling approach again and i probably found the issue...

So, if i run `.\ffmpeg.exe -y -hide_banner -loglevel panic -f g722 -i G:\output.wav -acodec pcm_s16le -ar 48000 test2.wav` it works just fine.

The test2.wav contains good quality sound...

But if i change the output to `-` or `pipe:1` the output sizes changes from 323kb to 0kb

```
.\ffmpeg.exe -y -hide_banner -loglevel panic -f g722 -i G:\output.wav -acodec pcm_s16le -ar 48000 - >test2.wav
```

Im kinda lost atm...

**Comment by sipsorcery** [comment]
> Mh, the ffmpeg api seems complex af....

Yep it takes some getting used to. You'll find FFmpeg in use just about everywhere audio/video are involved. The browser you are using right now is using one or more of the FFmpeg libraries. It's become a fundamental building block. The point is that it's worth spending the time to learn it as you'll come across it again and again.

In your second FFmpeg command line example are you attempting to accept input from `STDIN`? Don't you need to remove the `-i G:\output.wav` option?

Other than that I can think of a few options for you to get the audio from your VoIP call, upsample it and stream to Discord:

 - The option already discussed above where you use the FFMpeg libraries in process. The best .NET wrapper project I found was https://github.com/Ruslan-B/FFmpeg.AutoGen. Using the FFMpeg API to [resample audio](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/resampling_audio.c) does look a bit scary, but as with most C/C++ programs there's a lot of initialisation code.

 - If you can control the VoIP call and change the codec to OPUS then you could avoid the need to upsample. The big problem with that is you'd need to integrate an OPUS decoder. There are a few .NET implementations around on GitHub.

 - A very clunky option would be to use an FFmpeg command line process as an RTP listener and sender. This would be roughly the equivalent of what you're attempting above. An advantage would be that you could let FFmpeg do the G722 decode. There is a [WebRTC example](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/FfmpegToWebRTC) doing something similar that you may be able to leverage.

**Comment by SeaLife** [comment]
The last approach, using ffmpeg as "server" worked...
The voice is delayed by like 1-2 seconds, but it works...
Code for this:

```csharp
    public class DiscordAudioSink : TCPAudioSink
    {
        private readonly IAudioClient   _audioClient;
        private readonly AudioOutStream _stream;

        private bool _enabled = false;

        public DiscordAudioSink(IAudioClient audioClient) : base(5060)
        {
            _audioClient = audioClient;
            _stream      = audioClient.CreatePCMStream(AudioApplication.Mixed);
        }

        public override void GotEncodedAudioRtp(IPEndPoint remoteEndPoint, byte[] payload)
        {
            _stream.Write(payload);
        }
    }

    public abstract class TCPAudioSink : BasicAudioSink
    {
        private readonly NetworkStream _outgoingStream;

        protected TCPAudioSink(int port = 5060)
        {
            Task.Run(() =>
            {
                UdpClient udpServer = new UdpClient(new IPEndPoint(IPAddress.Any, port + 1));

                while (true)
                {
                    IPEndPoint sender = new IPEndPoint(IPAddress.Any, 0);

                    var data = udpServer.Receive(ref sender);

                    GotEncodedAudioRtp(sender, data);
                }
            });

            Task.Run(() =>
                Process.Start(new ProcessStartInfo()
                {
                    FileName = "ffmpeg",
                    //Arguments = $"-hide_banner -loglevel panic -f g722 -listen 1 -i tcp://127.0.0.1:{port} -acodec pcm_s16le -ar 48000 -f wav udp://127.0.0.1:{port + 1}",
                    Arguments = $"-hide_banner -loglevel panic -f g722 -listen 1 -i tcp://127.0.0.1:{port} -ac 2 -acodec pcm_s16le -ar 48000 -f wav udp://127.0.0.1:{port + 1}",
                }));

            Console.WriteLine("Connect to ffmpeg ...");
            var _tcpClient = new TcpClient("127.0.0.1", port);
            _outgoingStream = _tcpClient.GetStream();
            Console.WriteLine("Connected.");
        }

        public abstract void GotEncodedAudioRtp(IPEndPoint remoteEndPoint, byte[] payload);

        public override void GotAudioRtp(IPEndPoint remoteEndPoint, uint ssrc, uint seqnum, uint timestamp, int payloadID, bool marker, byte[] payload)
        {
            _outgoingStream.Write(payload, 0, payload.Length);
        }
    }
```

Probably the best solution i can get with my knowledge 🗡️ 

Regards
SeaLife

**Comment by rafcsoares** [comment]
https://github.com/lostromb/concentus

Its possível to use this Pure C# lib to use Opus inside SipSorcery

**Comment by sipsorcery** [comment]
Is it definitely C# only?

There's some binary dll's here: https://github.com/lostromb/concentus/tree/master/CSharp/TestConsole

**Comment by rafcsoares** [comment]
@sipsorcery yes, its a full c# port (without CELT and FEC support... only SILK) 

The main code is inside path below

https://github.com/lostromb/concentus/tree/master/CSharp/Concentus

**Comment by sipsorcery** [comment]
Ok. In answer to your original question, yes it's entirely possible to be able to use additional audio codecs with the sipsorcery library.

The two main tasks are:

 1. Write a class to consume the code by implementing the [IAudioEncoder](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/386e60a60c2a8318d5d19433a5d50f4850898bc2/src/MediaEndPoints.cs#L419) interface.  Alternatively it could be added to the [AudioEncoder](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/Media/Codecs/AudioEncoder.cs) class, which already contains G711 and G722.

 2. Check, and if required add, the RTP packetisation logic for OPUS. Hopefully there isn't anything special here, i.e. if OPUS is just sent as raw payloads, the same as G711, G722 etc.

**Comment by rafcsoares** [comment]
just to complete your informations @sipsorcery 

Any RTP Packetisation logic required.

Just use MediaFormat below inside peerConnection.addTrack

```
//Chrome use in SDP two audio channels, but only send one, so we must pass it as 2 channels in SDP but create a decoder with only one channel
public static readonly AudioFormat MEDIA_FORMAT_OPUS = new AudioFormat(111, "opus", 48000, 48000, 2, "a=fmtp:111 minptime=10;useinbandfec=1");```

And build a new AudioEncoder/AudioDecoder with this plugin

Example Decoding Package:

```
const int FRAME_SIZE_MILLISECONDS = 20;
const int MAX_DECODED_FRAME_SIZE_MULT = 6;
const int MAX_FRAME_SIZE = 5760; // 6*960
short[] _shortBuffer = null;
int _channels = 1;
int _sampleRate = 48000;

OpusFrameDecoder _opusDecoder = OpusFrameDecoder.Create(_sampleRate, _channels);

public byte[] DecodeFrame(ArraySegment<byte> encodedFrame)
{
                    if (packetData.Count < 1)
                        return null;

                    if (_shortBuffer == null)
                    {
                        // on the first call we don't know frame size, use temporal buffer of maximal length
                        _shortBuffer = new short[MAX_FRAME_SIZE * _channels];
                    }
                    int numSamplesDecoded;
                    try
                    {
                        numSamplesDecoded = _opusDecoder.Decode(packetData.Array, packetData.Offset, packetData.Count, shortBuffer, 0, shortBuffer.Length, false);
                    }
                    catch
                    {
                        //Failed to Decode
                        numSamplesDecoded = 0;
                    }

                    if (numSamplesDecoded == 0)
                        return null;

                    var buffer = new byte[numSamplesDecoded * _channels * 2];
                    Buffer.BlockCopy(shortBuffer, 0, buffer, 0, numSamplesDecoded * 2);
                    return buffer;
}
```

**Comment by sipsorcery** [comment]
Closing this issue. Feel free to re-open if anything further crops up.

**Comment by ChristopheI** [comment]
Hi @rafcsoares,

I'm trying to create an **OpusAudioEncoder** using **Concentus** plugin. 
But I didn't succeed and since I am not at all a specialist about this subject, could you help me ?

Based on your suggestion I created this class but the sound is totally awfull.

I assume that when I call **EncodeAudio** I must have a raw with:
- frequency = 48000
- using 1 channel
- encoded in 16 bit

Is it correct ?

Thanks in advance !

```
    public class OpusAudioEncoder : IAudioEncoder
    {
        public static readonly AudioFormat MEDIA_FORMAT_OPUS = new AudioFormat(111, "opus", SAMPLE_RATE, SAMPLE_RATE, 2, "a=fmtp:111 minptime=10;useinbandfec=1");
        
        private AudioEncoder _audioEncoder; // The AudioEncoder available in SIPSorcery
        private List<AudioFormat> _supportedFormats;

        private const int FRAME_SIZE_MILLISECONDS = 16;
        private const int MAX_DECODED_FRAME_SIZE_MULT = 6;
        private const int MAX_PACKET_SIZE = 4000;
        private const int MAX_FRAME_SIZE = MAX_DECODED_FRAME_SIZE_MULT * 960;
        private const int SAMPLE_RATE = 48000;

        private int _channels = 1;
        private int _frameSizeWithChannels;

        private short[] _shortBuffer = null;
        private byte[] _byteBuffer = null;

        private OpusEncoder _opusEncoder = null;
        private OpusDecoder _opusDecoder = null;

        public OpusAudioEncoder()
        {
            _audioEncoder = new AudioEncoder();

            // Add OPUS in the list of AudioFormat
            _supportedFormats = new List<AudioFormat>();
            _supportedFormats.Add(MEDIA_FORMAT_OPUS);

            // Add also list available from SIPSorcery.Media.AudioEncoder 
            _supportedFormats.AddRange(_audioEncoder.SupportedFormats);
        }

        public List<AudioFormat> SupportedFormats => _supportedFormats;

        public short[] DecodeAudio(byte[] encodedSample, AudioFormat format)
        {
            if (format.FormatName == "opus")
            {
                if (_opusDecoder == null)
                {
                    _opusDecoder =  OpusDecoder.Create(SAMPLE_RATE, _channels);
                    _shortBuffer = new short[MAX_FRAME_SIZE * _channels];
                }

                try
                {
                    int numSamplesDecoded = _opusDecoder.Decode(encodedSample, 0, encodedSample.Length, _shortBuffer, 0, _shortBuffer.Length, false);
                    if (numSamplesDecoded > 1)
                    {
                        var buffer = new short[numSamplesDecoded];
                        Buffer.BlockCopy(_shortBuffer, 0, buffer, 0, numSamplesDecoded);
                        return buffer;
                    }
                }
                catch
                {
                    
                }
                return new short[0];
            }
            else
                return _audioEncoder.DecodeAudio(encodedSample, format);
        }

        public byte[] EncodeAudio(short[] pcm, AudioFormat format)
        {
            if (format.FormatName == "opus")
            {
                if(_opusEncoder == null)
                {
                    _opusEncoder = OpusEncoder.Create(SAMPLE_RATE, _channels, OpusApplication.OPUS_APPLICATION_VOIP);

                    _byteBuffer = new byte[MAX_PACKET_SIZE];
                    _frameSizeWithChannels = (SAMPLE_RATE / 1000) * FRAME_SIZE_MILLISECONDS * _channels;
                }

                try
                {
                    int size = _opusEncoder.Encode(pcm, 0, _frameSizeWithChannels, _byteBuffer, 0, _byteBuffer.Length);

                    if (size > 1)
                    {
                        byte[] result = new byte[size];
                        Buffer.BlockCopy(_byteBuffer, 0, result, 0, size);
                        return result;
                    }
                }
                catch
                {

                }
                return new byte[0];

            }
            else
                return _audioEncoder.EncodeAudio(pcm, format);
        }

        public short[] Resample(short[] pcm, int inRate, int outRate)
        {
            return _audioEncoder.Resample(pcm, inRate, outRate);
        }
    }
```

**Comment by ChristopheI** [comment]
I'm still stuck with encoding part ... :(

But decoding part is now working using this

```
        public short[] DecodeAudio(byte[] encodedSample, AudioFormat format)
        {
            if (format.FormatName == "opus")
            {
                if (_opusDecoder == null)
                {
                    _opusDecoder =  OpusDecoder.Create(SAMPLE_RATE, _channels);
                    _shortBuffer = new short[MAX_FRAME_SIZE * _channels];
                }

                try
                {
                    int numSamplesDecoded = _opusDecoder.Decode(encodedSample, 0, encodedSample.Length, _shortBuffer, 0, _shortBuffer.Length, false);
                    if (numSamplesDecoded >= 1)
                    {
                        var buffer = new short[numSamplesDecoded];
                        Array.Copy(_shortBuffer, 0, buffer, 0, numSamplesDecoded);
                        return buffer;
                    }
                }
                catch
                {
                    
                }
                return new short[0];
            }
            else
                return _audioEncoder.DecodeAudio(encodedSample, format);
        }
```

**Comment by ChristopheI** [comment]
@rafcsoares,

I have finally found the source of the pb.

[SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg) and [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2) are now both compatible with Opus Codec

In [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2) I have added a new example called **CheckCodec**:
- In this example there is an **C#** implementation of an **Opus Audio Encoder / Decoder** (using [Consentus](https://github.com/lostromb/concentus)) (based on your explanations - Thank you !)
- It permits to test all these Audio codecs: **PCMU (G711), PCMA (G711), G722, G729** and **Opus**
- Tests are using Microphone or Audio file (it could be a Video file with audio stream) for Audio Input  and play it back to the specified Audio Output after to be **encoded** and then **decoded**

These Audio codecs ( PCMU (G711), PCMA (G711), G722, G729 ) are supported using **SIPSorcery** itself

**Comment by SeaLife** [comment]
> @rafcsoares,
> 
> I have finally found the source of the pb.
> 
> [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg) and [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2) are now both compatible with Opus Codec
> 
> In [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2) I have added a new example called **CheckCodec**:
> 
> * In this example there is an **C#** implementation of an **Opus Audio Encoder / Decoder** (using [Consentus](https://github.com/lostromb/concentus)) (based on your explanations - Thank you !)
> * It permits to test all these Audio codecs: **PCMU (G711), PCMA (G711), G722, G729** and **Opus**
> * Tests are using Microphone or Audio file (it could be a Video file with audio stream) for Audio Input  and play it back to the specified Audio Output after to be **encoded** and then **decoded**
> 
> These Audio codecs ( PCMU (G711), PCMA (G711), G722, G729 ) are supported using **SIPSorcery** itself

Thanks for sharing this, i'll try that with my SIP to Discord Proxy.
If it works, i can finally call a number and be in a voice channel with my mates while driving a car.
