### ISSUE TITLE
CSeq with 0 zero help me 

### ISSUE THREAD

**Issue by PauloTroguilho** [sipsorcery-org/sipsorcery#522]
Dear, how are you? I'm finishing a project where I need to answer a 200 OK for the OPTIONS, but getresponse removes CSeq = 0 and CSeqMethod, I can only send if it is above 0 and I need to send a 0

Shipping with 1 ok
2021-07-13 13:30:38.0101|DEBUG|SIP/2.0 200 Ok
Via: SIP/2.0/UDP 10.192.80.108:5060;rport=5060;branch=z9hG4bK-17706a-5b8f2058-578e8192;received=10.192.80.108
To: <sip:202020@10.192.80.160:5060>;transport=udp
From: <sip:RSTUIPCORESEC@10.192.80.108>;tag=f9ec8e0-6c50c00a-13c4-55022-17706a-27a1e340-17706a
Call-ID: f9ec8e0-6c50c00a-13c4-55022-17706a-6d533133-17706a
CSeq: 1 OPTIONS
Accept: application/sdp
Allow: ACK, BYE, CANCEL, INFO, INVITE, OPTIONS, PRACK, REFER, REGISTER, UPDATE
Server: Plataforma Aspect Resolutte URA P
Supported: replaces,timer,100rel
Content-Length: 0

Submit with 0 error, it removes Cseq

2021-07-13 08:47:18.5988|DEBUG|SIP/2.0 200 Ok
Via: SIP/2.0/UDP 10.192.80.107:5060;rport=5060;branch=z9hG4bK-a9909-2965cc6d-3d8d41bd;received=10.192.80.107
To: <sip:202020@10.192.80.160:5060>;transport=udp
From: <sip:RSTUIPCOREPRI@10.192.80.107>;tag=f76f3a0-6b50c00a-13c4-55022-a9909-21413784-a9909
Call-ID: f76f3a0-6b50c00a-13c4-55022-a9909-400ad1ba-a9909
Accept: application/sdp
Allow: ACK, BYE, CANCEL, INFO, INVITE, OPTIONS, PRACK, REFER, REGISTER, UPDATE
Server: Plataforma Aspect Resolutte URA
Supported: replaces,timer,100rel
Content-Length: 0

=========================================

To add the 1 I made the following code:
 response.Header = new SIPHeader(from, to, cSeq, callId);
                response.Header.CSeqMethod = SIPMethodsEnum.OPTIONS;
                response.Header.CSeq = 1;

to add the zero I changed the response.Header.CSeq = 1 to 0 and also changed the Initialise to
if (cseq >= 0 && cseq < Int32.MaxValue)
            {
                CSeq = cseq;
            }
            else
            {
                CSeq = DEFAULT_CSEQ;
            }
please help me, i just need to send the

CSeq: 0 OPTIONS

**Comment by sipsorcery** [comment]
I've pushed a fix for this.
