### ISSUE TITLE
multiple media audio tracks?

### ISSUE THREAD

**Issue by roozbehid** [sipsorcery-org/sipsorcery#524]
Hi,

It seems multiple audio tracks in SDP is not supported.
I am wondering how hard do you think it is to add this support? ( I mean I try to work on adding it...)
Or would just ignoring sipsorcery RTP support and having my own udp ports open and listening easier?

**Comment by sipsorcery** [comment]
No multiple audio/video tracks aren't supported, see #423.

> I am wondering how hard do you think it is to add this support?

 - SDP changes: difficulty = relatively easy
 - RTP session changes (replace the audio/video track fields with lists etc.): difficulty = medium
 - Side effects: difficulty = medium

I'd estimate it at a 1 to 2 week job for me, who knows the code base well.

**Comment by sipsorcery** [comment]
Closed as enhancement already captured in #423.
