### ISSUE TITLE
Quiestion: WebRTC How to convert from RTCSessionDescription to RTCSessionDescriptionInit?

### ISSUE THREAD

**Issue by dc-ucw** [sipsorcery-org/sipsorcery#529]
I have one WebRTC peer using SipSorcery, and the other WebRTC peer is javascript.  When I send SDP answers from SS to the javascript, I serialize JSON the localDescription.  Unfortunately this causes each field of the SDP to be serialized as JSON.  I would like to have it as an SDP name/value pair string.

I see that you have RTCSessionDescriptionInit which corresponds to the WebRTC/javascript type format.  Is there a way to convert from RTCSessionDescription localDescription to RTCSessionDescriptionInit? Then I can JSON serialize it and send to my javascript peer.

thanks

**Comment by dc-ucw** [comment]
I ended up doing the following.  I am not sure if this is the preferred method:
```
        private static string Serialize(RTCSessionDescription sessionDescription)
        {
            var init = new RTCSessionDescriptionInit();
            init.type = sessionDescription.type;
            init.sdp = sessionDescription.sdp.ToString();

            var json = init.toJSON();

            return json;
        }
```

**Comment by sipsorcery** [comment]
> Is there a way to convert from RTCSessionDescription localDescription to RTCSessionDescriptionInit?

No, because the SDP doesn't tell you whether it's an offer or an answer.

````
var init = new RTCSessionDescriptionInit { type = RTCSdpType.offer, sdp = offer.ToString() };
return init.toJSON();
````

**Comment by dc-ucw** [comment]
great - thanks.
