### ISSUE TITLE
siprec mode

### ISSUE THREAD

**Issue by vovanb** [sipsorcery-org/sipsorcery#532]
Hello,
I have request to implement siprec server which will record audio from SIPREC call.
Can you please point to relevant place in library where audio received so I can to stream it to file or external source and how to configure sipsorcery server for SIPREC?
Thanks

**Comment by sipsorcery** [comment]
I had a very quick look at the SIPREC RFC (RFC7866) and it could be added to this library BUT it wouldn't be trivial. You would need a fairly good grasp of SIP, RTP and the way they work together.

One possible place to start would be the [B2BUserAgent](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/SIPUserAgents/SIPB2BUserAgent.cs). It seems to be the simplest model that SIP recordings can be captured with.

If you only need to record an incoming call and don't need the RFC you could use something like this [example](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/RecordIncomingCall/Program.cs).

**Comment by sipsorcery** [comment]
Closing this issue. Feel free to re-open if there are any further questions.
