### ISSUE TITLE
end call recording

### ISSUE THREAD

**Issue by HarunDurmus** [sipsorcery-org/sipsorcery#535]
While the call is being recorded, can I end the voice recording without ending the call?

**Comment by sipsorcery** [comment]
Yes, it should be straight forward to stop recording whenever you want and leave the call up.

If you're using something like this [example](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/RecordIncomingCall/Program.cs) then to stop recording you can remove the event handler:

````
voipMediaSession.OnRtpPacketReceived -= OnRtpPacketReceived;
````

**Comment by HarunDurmus** [comment]
thank you so much
