### ISSUE TITLE
sender.replaceTrack from chrome cause connection to drop.

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery-org/sipsorcery#536]
@sipsorcery 

looks like chrome send RTCP BYE event when replacing track using sender.replaceTrack  (switching camera to screen share)

In SipSorcery when RTCP BYE was received the connection was closed immediate

the reason of BYE is null when replacing from chrome so its possible to add extra checks instead close connection when reason is null.

I don't know if this connection should close immediately when receiving a BYE Event as chrome seems to keep using the same SSRC when replacing track.

                   ```
                   if (rtcpPkt.Bye != null && rtcpPkt.Bye.Reason != null)
                   {
                            logger.LogDebug($"RTCP BYE received for SSRC {rtcpPkt.Bye.SSRC}, reason {rtcpPkt.Bye.Reason}.");

                            OnRtcpBye?.Invoke(rtcpPkt.Bye.Reason);

                            // In some cases, such as a SIP re-INVITE, it's possible the RTP session
                            // will keep going with a new remote SSRC. 
                            if (AudioRemoteTrack != null && rtcpPkt.Bye.SSRC == AudioRemoteTrack.Ssrc)
                            {
                                AudioRtcpSession?.RemoveReceptionReport(rtcpPkt.Bye.SSRC);
                                //AudioDestinationEndPoint = null;
                                //AudioControlDestinationEndPoint = null;
                                AudioRemoteTrack.Ssrc = 0;
                            }
                            else if (VideoRemoteTrack != null && rtcpPkt.Bye.SSRC == VideoRemoteTrack.Ssrc)
                            {
                                VideoRtcpSession?.RemoveReceptionReport(rtcpPkt.Bye.SSRC);
                                //VideoDestinationEndPoint = null;
                                //VideoControlDestinationEndPoint = null;
                                VideoRemoteTrack.Ssrc = 0;
                            }
                   }
```

**Comment by sipsorcery** [comment]
It was my understanding that a RTCP BYE will only get sent to indicate a media stream is ending. I don't recall finding the required behaviour specified anywhere and applied common sense. It seems very strange that a WebRTC peer would send BYE on a stream and then keep sending on it. Do you have steps that can replicate the behaviour with Chrome?

**Comment by sipsorcery** [comment]
Suspect this is/was something to do with the need to support SDP re-negotiation which has not yet been implemented.
