### ISSUE TITLE
Remaining issues with DisableRetransmitSending

### ISSUE THREAD

**Issue by roadz99** [sipsorcery-org/sipsorcery#538]
I've been reviewing the changes we made to force SipTransport to wait for DNS lookups when retransmits were disabled. I see there are still quite a number of places in SipSorcery where we call SendRequestAsync/SendResponseAsync without specifying whether to wait for DNS (in fact SipTransport itself does this in the SIPMessageReceived method!).
I started looking into the best way to fix this, but I think that even if I fixed them all it is likely that anybody contributing to the SipSorcery code base wouldn't be aware of this niche use case and problems might creep in again.
I was going to propose that instead of having "waitForDns" as a method parameter, we add it as a property to SipTransport so that nothing else needs to worry about it. But then I realise that the consumer of the library should not need to know that waitForDns should be true when they have disabled retransmits.
Finally I came back to my initial solution. Since SipTransport already knows that retransmits are disabled, why should it not decide whether to wait to DNS?
I would appreciate your thoughts on this.

Many thanks for the great library!

**Comment by sipsorcery** [comment]
Sounds reasonable. Can you see if #539 is what you had in mind?

**Comment by roadz99** [comment]
That looks good to me. Thanks for the quick reply!
