### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by farazp** [sipsorcery-org/sipsorcery#540]
I try to implementing sipsorcery in UWP project but SIPSorceryMedia.Windows not supported for UWP and aslo problem with NAudio in UWP!

How can I using sipsorcery in UWP? anyone using this? any sample? not working?

**Comment by sipsorcery** [comment]
The main sipsorcery project should work fine when consumed from a UWP app since it doesn't use any OS specific calls.

After that UWP support is not something I've ever wanted or needed. I don't know what kind of audio functionality is available with UWP, I suspect not a lot. I guess you have a strong reason to use UWP instead of switching to WinRT or MAUI but the example OS specific libraries related to this project are unlikely to ever get any UWP support from me.

**Comment by farazp** [comment]
I using that but SIPSorceryMedia.Windows not working with UWP cause on some NAudio functions not working with UWP.
anyway the Implementation of SIPSorceryMedia.Abstractions is to hard!
I work with many library but the SIPSorcery is one of best of that.

Also can or how using SIPSorcery in Xamarin?

**Comment by sipsorcery** [comment]
> anyway the Implementation of SIPSorceryMedia.Abstractions is to hard!

If all you care about is audio there are only two interfaces you have to implement:

[IAudioSource](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/386e60a60c2a8318d5d19433a5d50f4850898bc2/src/MediaEndPoints.cs#L464) for your application to source audio, e.g. microphone.

[IAudioSink](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/386e60a60c2a8318d5d19433a5d50f4850898bc2/src/MediaEndPoints.cs#L493) for you application to be able to playback audio, e.g. speaker.

> Also can or how using SIPSorcery in Xamarin?

Only a[ WebRTC data channel](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/XamarinDataChannelTest) one which doesn't incorporate any audio/video devices.

If you search for Xamarin in the issues you will find some other cases where people have attempted to use this library in a Xamarin app on a mobile device. The sipsorcery library works fine but the tricky part, as always, is accessing audio/video devices with .NET. I haven't tried it myself but one user did report some success with [libvlcsharp](https://github.com/videolan/libvlcsharp) on a mobile device.
