### ISSUE TITLE
How to integrate Jitsi server

### ISSUE THREAD

**Issue by peteryang023** [sipsorcery-org/sipsorcery#543]
@sipsorcery I want to integrate Jitsi, I already set up a server with Jitsi, and share the video between 2 clients by Sipsorery APIs, but I don't know how to communicate with the clients via the Jitsi server, so that I can establish the connection between mobile and PC, is there a way for that?
Looking forward to you reply.

Thanks,
Peter

**Comment by rafcsoares** [comment]
@peteryang023 
Jitsi use XMPP instead websocket to send messages...

Because of this, integrate with this media server is far more complex than integrate with OpenVidu/Kurento

**Comment by sipsorcery** [comment]
No XMPP feature planned (did it once ages ago when the GoogleVoice service offered free calls but code long since rotted).
