### ISSUE TITLE
AudioExtrasSource - object disposed exception in SendStreamSample

### ISSUE THREAD

**Issue by sambrereton2** [sipsorcery-org/sipsorcery#550]
Running version 5.2.3 in a load test scenario.
We had an issue where the SIP switch (Freeswitch) was sending a BYE just after accepting a call, causing the media stream being played to be closed resulting in an object disposed exception in the SendStreamSample. Since this method is called from a timer - there was no way for our application to catch the exception. I put a try-catch in the code and have tested 1000's calls with no observed issue.

After EncodeAndSend completes, the _streamSourceReader.BaseStream was disposed.
To first ensure our problem was not file locking related, we provided the audio stream to play as a MemoryStream object.

/// <summary>
        /// Sends audio samples read from a file containing 16 bit PCM samples.
        /// </summary>
        private void SendStreamSample(object state)
        {
            if (!_isClosed)
            {
                lock (_streamSourceTimer)
                {
                    try
                    {
                        if (_streamSourceReader?.BaseStream?.CanRead == true)
                        {
                            var pcm = GetPcmSampleFromReader(_streamSourceReader, _streamSourceRate, out int samplesRead);

                            if (samplesRead > 0)
                            {
                                EncodeAndSend(pcm, (int)_streamSourceRate);

                                if (_streamSourceReader.BaseStream.Position >= _streamSourceReader.BaseStream.Length)
                                {
                                    Log.LogDebug("Send audio from stream completed.");
                                    StopSendFromAudioStream();
                                }
                            }
                            else
                            {
                                Log.LogWarning("Failed to read from audio stream source.");
                                StopSendFromAudioStream();
                            }
                        }
                        else
                        {
                            Log.LogWarning("Failed to read from audio stream source, stream null or closed.");
                            StopSendFromAudioStream();
                        }
                    }catch(Exception ex)
                    {
                        Log.LogError("Failure in send stream sample. " + ex.Message, ex);
                        StopSendFromAudioStream();
                    }
                }

                if(!_streamSendInProgress)
                {
                    // An error has occurred or a request has been made to stop the stream.
                    _streamSourceReader?.Close();
                }
            }
        }

**Comment by sipsorcery** [comment]
Thanks for logging these issues.

To fix his one I've put a lock in the `StopSendFromAudioStream` method rather than adding a new exception handler. If you're able to test the change and see whether that fixes the problem it'd be appreciated.
