### ISSUE TITLE
Crash with nauido.MMexception

### ISSUE THREAD

**Issue by mgsray** [sipsorcery-org/sipsorcery#551]
I use sipsorcery useragent to call a freeswith with sip. 
The program keeps running, waiting for a call command to start. Only one dialogue will be created, until a hangup command received. Call->hangup->call->hangup...loop. The process shall be quite clear and clean. 
However, The program works fine until around 25~35 loops, then it crashed with an windows error. It seems related to naudio on wavein device. I tried to close everything after hangup and initialize while starting call, the problem still exists.
Here is my main code.
public async void Call(String org_caller_num, Dictionary<string, string> paramMap)
      {

	sipTransport = new SIPTransport();
        sipTransport.EnableTraceLogs();
        userAgent = new SIPUserAgent(sipTransport, null);
        userAgent.OnCallHungup += OnHangup;
        winAudio = new WindowsAudioEndPoint(audioEncoder: new AudioEncoder(), audioOutDeviceIndex: audioOutDevIndex,
            audioInDeviceIndex: audioInDevIndex, disableSource: false, disableSink: false);
        voipMediaSession = new VoIPMediaSession(new MediaEndPoints { AudioSink = winAudio, AudioSource = winAudio });
        List<String> param = new List<String>();
        param.Add("X-org_num:" + org_caller_num);
        foreach (var i in paramMap ) {
            param.Add("X-Plugin-" +i.Key+ ":" + i.Value);
        }
        var desc = new SIPCallDescriptor(
           username, password, 
           "sip:"+ DESTINATION,
           "sip:" + HOST, 
           "sip:" +DESTINATION,
           null,
           param,
           null,
           SIPCallDirection.Out,
           SDP.SDP_MIME_CONTENTTYPE,
           null,
           null);
        bool callResult = await userAgent.Call(desc,voipMediaSession);
        }
  
  public void Hangup()
  {

        if (userAgent.IsCallActive) 
        { 
            isRobotHangup = false;
            userAgent.Hangup();
            System.Threading.Thread.Sleep(2000);
            winAudio.CloseAudio();
            voipMediaSession.Close(null);
            userAgent.Close();
            sipTransport.Shutdown();
            isRobotHangup = true;
        }
  }
        
  
  private void OnHangup(SIPDialogue dialogue)
  {

      winAudio.CloseAudio();
      voipMediaSession.Close(null);
      userAgent.Close();
      sipTransport.Shutdown();
   }

Here is the error screen. 
![image](https://user-images.githubusercontent.com/41770225/131946526-a2dd0bf6-154f-49d0-880d-8a2d6e199697.png)

**Comment by mgsray** [comment]
I found some clue.
The issue only happens on Windows7 sp1. The program works fine on windows 10.
Maybe related to the audio drivers on different windows version.

**Comment by sipsorcery** [comment]
The execption is likelt ot be caused by one of three things:

1. The sipsorcery logic isn't initialising or cleaning up the NAudio calls correctly.
2. The NAudio logic isn't initialising or cleaning up the calls to the Win32 API's correctly.
3. The Windows audio APIs are failing due to an audio device not being accessible. Perhaps your device takes a bit of time to close and re-open or something.

To test `1.` you could extract the NAudio logic from [WindowsAudioEndPoint](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/master/src/WindowsAudioEndPoint.cs) into a console app and see if it exhibits the same behaviour wehn one in your test loop.

Testign `2` and `3` is a lot harder.

**Comment by mgsray** [comment]
I close this issue as it may related to windows version or hardware. There are several workarounds to solve it, so don't wanna waste time on it.
