### ISSUE TITLE
SipTransport.SendTransaction changed to AddTransaction and made internal

### ISSUE THREAD

**Issue by grishinrv** [sipsorcery-org/sipsorcery#554]
public version of this method is needed (changes were made at revision b9cdc5f4001e1ec6edca176220bd25fa15de9680)

**Comment by sipsorcery** [comment]
PR's are always welcome.

**Comment by grishinrv** [comment]
> PR's are always welcome.

Sorry for offtopic. Could You explain how to contribute to the repo? I couldn't find the information in README. Command:
git push --set-upstream origin issue554  
returns error 403 (tried both password and access token) after successful authentication:
info: please complete authentication in your browser...
remote: Permission to sipsorcery-org/sipsorcery.git denied to grishinrv.
fatal: unable to access 'https://github.com/sipsorcery-org/sipsorcery/': The requested URL returned error: 403

**Comment by sipsorcery** [comment]
See [GitHub Collaborative Development]( https://docs.github.com/en/github/collaborating-with-pull-requests/getting-started/about-collaborative-development-models).

A very high level overview of the steps are:

1. Fork the rerpository you want to contribute to (in this case sipsorcery-org/sipsorcery).
2. Create a new branch on your forked repo and make the change.
3. Push the change to your forked repo.
4. This is the "magic" step. Now if you come back to the sipsorcery-org/sipsorcery and click on the `Pull Requests` tab it automagically gives you an option to create a PR based on the change you made on your fork.

**Comment by grishinrv** [comment]
created PR https://github.com/sipsorcery-org/sipsorcery/pull/556 (please, check description)

**Comment by grishinrv** [comment]
by @sipsorcery - The SIPTransport.AddTransaction method was deliberately made internal to make using SIP transactions slightly easier. I had a few cases when writing some of the examples where I forgot to call the method to add the transaction BUT had called SendReliable and then had to troubleshoot why nothing happened.

I judged that if SIPTansaction.SendReliable is called the intent is clear and the SIP transaction logic should be used. The need to make an additional call to add the transaction is no longer required.
