### ISSUE TITLE
Conversation couldn't be heard

### ISSUE THREAD

**Issue by grishinrv** [sipsorcery-org/sipsorcery#570]
Could you share the knowledge, please?

how may i collect incoming bynary data from MediaSession (to make some processing with them)?

this event from WindowsAudioEndpoint.cs tells it is not used:
```
        /// <summary>
        /// Not used by this audio source.
        /// </summary>
        public event EncodedSampleDelegate OnAudioSourceEncodedSample;
```

I'm using SipSorccery 5.3.0-pre,
SipSorcery.Media.Abstractions 1.1.0,
SipSorcery.Media.Windows 0.0.31-pre

Thank You

**Comment by sipsorcery** [comment]
Unlikely to be anything to do with the code. Almost certainly to do with NAT. See https://www.sipsorcery.com/mainsite/Help/SIPAudio.

**Comment by grishinrv** [comment]
Thanks, but what about getting data from MediaSession (or may be another class) for processing them, but not playing?
