### ISSUE TITLE
Collecting binary data, incoming from conversation

### ISSUE THREAD

**Issue by grishinrv** [sipsorcery-org/sipsorcery#571]
how may i collect incoming bynary data from MediaSession (to make some processing with them)?

this event from WindowsAudioEndpoint.cs tells it is not used:

        /// <summary>
        /// Not used by this audio source.
        /// </summary>
        public event EncodedSampleDelegate OnAudioSourceEncodedSample;
I'm using SipSorccery 5.3.0-pre,
SipSorcery.Media.Abstractions 1.1.0,
SipSorcery.Media.Windows 0.0.31-pre

Thank You

**Comment by sipsorcery** [comment]
Take a look at the [Record Incoming Call](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/RecordIncomingCall/Program.cs) example. It's taking the raw RTP packets, decoding and then storing them in a file. If you want to access the binary data that's how to do it.

**Comment by grishinrv** [comment]
Thanks

**Comment by grishinrv** [comment]
I've  tested [Record Incomig Call](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/RecordIncomingCall/Program.cs) example (Windows 10, NetCore3.1 runtime). It Creates an emty output.mp3 with 0 byte size, and VLCreports this
[VlcLog.txt](https://github.com/sipsorcery-org/sipsorcery/files/7185715/VlcLog.txt)
 log on attempt of playing it. (Example-Console -app returned no errors )
