### ISSUE TITLE
AudioSourceFormat: PCM 8khz 16 bit signed little endian 

### ISSUE THREAD

**Issue by grishinrv** [sipsorcery-org/sipsorcery#574]
Could You tell, which parameters should i pass to 
AudioFormat.cs constructor to get  PCM 8khz 16 bit signed little endian  ?

`DecodeAudio(byte[] encodedSample, AudioFormat format)` of AudioEncoder class?

Which id must be set with :
`endPoint.SetAudioSourceFormat(new AudioFormat(AudioCodecsEnum.PCM_S16LE,  ????));`

**Comment by sipsorcery** [comment]
> Could You tell, which parameters should i pass to
AudioFormat.cs constructor to get PCM 8khz 16 bit signed little endian ?

Yep, as you've mentioned [AudioCodecsEnum.PCM_S16LE](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/386e60a60c2a8318d5d19433a5d50f4850898bc2/src/MediaEndPoints.cs#L117).

> Which id must be set with :
endPoint.SetAudioSourceFormat(new AudioFormat(AudioCodecsEnum.PCM_S16LE, ????));

You need to se the ID to something between the [minimum dynamic ID](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/386e60a60c2a8318d5d19433a5d50f4850898bc2/src/MediaEndPoints.cs#L141) and the [maximum dynamic ID](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/386e60a60c2a8318d5d19433a5d50f4850898bc2/src/MediaEndPoints.cs#L142). But if you're planning on trying to send that audio format to another SIP or WebRTC peer it most likely will not understand that format.  The Azure Speech services are likely the only place that format will be useful. If you control both ends of the call you could make it work but then it's an inefficient format to be transmitting.
