### ISSUE TITLE
Pending transactions list is full

### ISSUE THREAD

**Issue by necheyhin-a-v** [sipsorcery-org/sipsorcery#580]
Is it possible to increase the amount of pending transactions, lets say up to 20000? What is the reason for the restrictions? Does anything depend on the value?
It would be even better to make the parameter customizable, because in some cases an ApplicationException occurs with "pending transactions list is full" message

**Comment by sipsorcery** [comment]
Yes, it's possible... but as with a lot of the constants the values are chosen with the goal or preventing devs from shooting themselves in the foot. The current limit of 5k transactions is a LOT when you consider each transaction requires frequent checks as well as potentially SIP request/response retransmits.

An easy fix would be to make `MAX_RELIABLETRANSMISSIONS_COUNT` a `public static const`. That would make it hard to find but easy to change, correspoding to no one else has asked to change it in the last 15 years. Does that work?

Out of interest what's your use case for such high tx volumes? I'd be surprised if you didn't start hitting a CPU bottleneck with 5k pending tx's.

**Comment by necheyhin-a-v** [comment]
There is no straight access to SIPTransactionEngine, so the suggested fix will not work (I mean there will be no possibility to adjust the parameter from api). Perhaps it would be better to move the parameter out of the engine and put it to the SIPTransport

The use case is to do up to 3000 simultaneous calls

**Comment by sipsorcery** [comment]
Added [SIPTransport.MaxPendingTransactionsCount](https://github.com/sipsorcery-org/sipsorcery/blob/748630a9155d867c592563baa1f1a41c48aeee05/src/core/SIP/SIPTransport.cs#L198).
