### ISSUE TITLE
Kamailio / Freeswitch connection with rooms

### ISSUE THREAD

**Issue by Kerugal** [sipsorcery-org/sipsorcery#591]
Hi Aaron Clauson,
we are currently trying the following UseCase: 
A user is supposed to connect to a Kamailo/Freeswitch on an iOS Unity client via WebRTC + SIP. The Freeswitch is working with the following descriptor. For Example:

````
SIPCallDescriptor callDescriptor = new SIPCallDescriptor(
            currentFSInfo.username,                                         // username
            currentFSInfo.password,                                         // password
            $"sip:{currentRoomNumber.ToString()}@{currentFSInfo.hostname}", // uri
            $"sip:{currentFSInfo.username}@{currentFSInfo.hostname}",       // from
            $"sip:{currentRoomNumber.ToString()}@{currentFSInfo.hostname}", // to   => room id 
            null, null, null,                                               // routeset, customHeaders, authUsername
            SIPCallDirection.Out,                                           // call direction
            "application/sdp",                                              // content type
            currentModifiedOffer,                                           // content
            null);
````

Unfortunately, the SIPClientUserAgent does not take the correct paramters that are needed. Should look something like this: 
`new SIPClientUserAgent(sipTransport, invalidUser, invalidHost, sipInstanceId, currentRoomNumber.ToString());`
Is such a scenario known, or is the library not designed for it at all?

By the way - Thanks for the great work

**Comment by Kerugal** [comment]
Small addendum:

Furthermore, we currently connect via JSSip in our WebApp.
Unfortunately I don't see a way to work with sockets in the registration - like:
https://jssip.net/documentation/3.2.x/api/ua_configuration_parameters/#parameter_sockets

**Comment by cagedh1** [comment]
Hi, how to finally connect to WebSocket？
