### ISSUE TITLE
Debugging symbols not available

### ISSUE THREAD

**Issue by grondinjc** [sipsorcery-org/sipsorcery#598]
Hello,

While trying to debug a component referencing sipsorcery via nuget, I cannot get the pdb.
![image](https://user-images.githubusercontent.com/5757055/138129259-35513e45-b429-4e15-a3ec-0f8765f5f671.png)

While trying to figure out the issue, which I have not yet found, I used a blogpost (a bit old, I agree) to understand the steps : https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/

Looking at the repo, the symbol package appear to be build. However, looking at nuget.org, I don't have a link to download the symbols. For comparison, here is a nuget for which the symbols are properly published : 
- When a download symbol link is available : https://www.nuget.org/packages/Newtonsoft.Json/
- When a download symbol link is not available : https://www.nuget.org/packages/SIPSorcery/5.3.3-pre

Both projects appear to see the following csproj attributes just fine.
```
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

The lib seems to generate Portable PDB as the DebugType is not specified to override the default value : https://github.com/sipsorcery-org/sipsorcery/search?q=DebugType

Do you have an idea ?

**Comment by grondinjc** [comment]
I made a PR to experiment a fix about that.
I would be curious to know if you had some else in mind to verify about the config.

**Comment by grondinjc** [comment]
Will wait on the next nuget version to be publish to close the issue. Thanks

**Comment by sipsorcery** [comment]
Closing, feel free to re-open if there are still symbol problems.
