### ISSUE TITLE
Calls on web server

### ISSUE THREAD

**Issue by artemavrin** [sipsorcery-org/sipsorcery#604]
Hey!
I want to run app as web server, and there is no audio device. I synthesys voice and send it through stream on my machine, but it is not working on remote server, just no audio. How to send audio to call without audio device? Is it possible?

**Comment by sipsorcery** [comment]
The [PlaySounds](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/SIPExamples/PlaySounds) example generates audio from a .NET console application. You could retrofit that into an ASP.NET Core application. By doing that you're effectively building a media server which is arguably not an ideal use case for a request/reponse web framework such as ASP.NET Core.
