### ISSUE TITLE
SIPUserAgent cannot hang up incoming call

### ISSUE THREAD

**Issue by RySchmitt** [sipsorcery-org/sipsorcery#605]
SIPUserAgent::Hangup triggers a NullReferenceException when answering an incoming call, but it works correctly when the agent initiated the call. This seems to be caused by src/app/SIPUserAgents/SIPUserAgent.cs:588 where m_callDescriptor is (intentionally) null during incoming calls.

**Comment by sipsorcery** [comment]
Thanks for the bug report!
