### ISSUE TITLE
Screen Share and Unknown Decoder

### ISSUE THREAD

**Issue by sanalpencere** [sipsorcery-org/sipsorcery#606]
Hello everyone. I am not sure this is a bug or not. But I really wanna discuss this problem with you.

I am trying to implement `sipsorcery` for screen sharing. I checked your `TestPatternVideoExample` and I implemented it with my own encoder. (Nvidia  H264 Encoder Basically). Also, I implemented my own signaling server which is the rails action cable project.

I just add track like this without source and encoder parts. Cuz I have my own encoder as i said before.
```csharp
MediaStreamTrack track = new MediaStreamTrack(new List<VideoFormat>() {
                 new VideoFormat(VideoCodecsEnum.H264, 100, 90000, "packetization-mode=1")
            }, MediaStreamStatusEnum.SendOnly);

_peerConnection.addTrack(track);
```

When my encoded frame event triggered, I just send my h264 frames like this below.

```csharp
_peerConnection.SendH264Frame(90000 / 30, 100,frame.Data);
```

When I checked the chrome webrtc internal, I can able to get frame bytes.  But chrome I can not able to decode any frame.

<img width="2267" alt="Screen Shot 2021-11-05 at 16 44 50" src="https://user-images.githubusercontent.com/5247924/140520022-af4cab49-3029-4a3b-802d-b239a91eccae.png">

<img width="741" alt="Screen Shot 2021-11-05 at 16 46 16" src="https://user-images.githubusercontent.com/5247924/140520417-552d49ab-9620-48a1-b77f-01911c07f236.png">

And I don't know why when I checked the decoder implementation it says unknown. I guess I am missing a few things and chrome and my computer can not share the same codec information.

**Comment by sipsorcery** [comment]
Video encoding issues are the worst ones to track down.

My approach is to use the `ffplay` utility from FFmpeg to receive the video as raw RTP. That eliminates all the extra things that can go wrong with WebRTC (signalling, encryption etc). The problem with that approach is you need to be fairly comfortable operating FFmpeg...

**Comment by sanalpencere** [comment]
So sorry for the late response. But finally, we found the problem is with the SDP message. There is no `sprop-parameter-sets`. Because of that stream is not working. On the encoder side, I just add SPSPPS information to all frames. I can able to video. But I have some latency issues right now. I will keep updated here. Thanks again.

**Comment by sipsorcery** [comment]
Feel free to re-open if there's anything further to add.
