### ISSUE TITLE
Establishing early media on incoming calls to SIPUserAgent?

### ISSUE THREAD

**Issue by CMC01** [sipsorcery-org/sipsorcery#615]
I'm using SIPUserAgent to register and receive calls from another SIP client as part of an automation suite for said client. I'd like to test some early media scenarios, eg. sipsorcery posing as an IVR - The SIP client calls sipsorcery, sipsorcery answers 183 and plays media back, SIP client sends DTMF, sipsorcery validates DTMF sent during early media phase and returns success/failure test result.

From what I understand of the SIPUserAgent class, this isn't currently possible since MediaSession is read-only. My current approach is to accept the call and then send 183 with sdp constructed from a VoIPMediaSession object. However, since I have not answered the call, I haven't attached this object to the SIPUserAgent so the OnDtmfTone event would never fire.

Is there any way I could get my sipsorcery client to listen to DTMF during early media on an incoming call?

**Comment by sipsorcery** [comment]
> Is there any way I could get my sipsorcery client to listen to DTMF during early media on an incoming call?

The RTPSession [should start](https://github.com/sipsorcery-org/sipsorcery/blob/82a257ea11a6b7cf145b7fe292b78217bc63743d/src/app/SIPUserAgents/SIPUserAgent.cs#L1497) if an early media SIP response is received. Check whether you get the log message:

`logger.LogDebug($"Set remote description for early media result {setDescriptionResult}.");`

Once the RTPSession is started it [should also detect](https://github.com/sipsorcery-org/sipsorcery/blob/82a257ea11a6b7cf145b7fe292b78217bc63743d/src/net/RTP/RTPSession.cs#L2233) any RTP Event packets as long as the SDP in the early media response specified an RTP event payload.

Note the DTMF method has to be RTP Events, i.e. RFC2833. The sipsorcery library has very minimal audio processing capabilties and they don't include detecintg DTMF tones from an audio stream.

**Comment by CMC01** [comment]
Thanks for your response, I don't think I fully understand though. I want to set the remote description based on sdp from an Invite such that the media session is established before I answer the call from sipsorcery later on. Could I do this in response to OnIncomingCall? I can't find a method that allows me to set the MediaSession remote description without answering the call

**Comment by sipsorcery** [comment]
>  I want to set the remote description based on sdp from an Invite such that the media session is established before I answer the call from sipsorcery later on. 

If you're using the `SIPUserAgent` class you cant, and don't need to do this explcitly. If a 183 Session Progress response is received with an SDP response then it will be used to set the remote description. See the code link I mentioend above.

**Comment by CMC01** [comment]
![callflow drawio](https://user-images.githubusercontent.com/88338489/141964289-cca0f166-d18a-4bf7-aeaa-79bdbd2fddd0.png)

This is the call flow I am trying to replicate. There is no 183 received from the external client, instead I would like to set the remote description of the media session in response to the SDP contained within the initial Invite.

**Comment by sipsorcery** [comment]
>  I want to set the remote description based on sdp from an Invite such that the media session is established before I answer the call from sipsorcery later on. 

Ah OK, understood now. The `SIPUserAgent` class does not have any built in logic to send an early media response. It could be added but I'm up to my eyeballs at the moment.

The next best option is to use the `SIPUserAgentClient` class instead. It gives you more fine grained control but does take more wiring up.

**Comment by CMC01** [comment]
What I have at the minute, using the SIPServerUserAgent, is this handler for OnIncomingCall-


```
private async void UserAgent_OnIncomingCall(SIPUserAgent ua, SIPRequest req)
            {
                var uas = UserAgent.AcceptCall(req);
                var mediaSession = CreateMediaSession();
                PlayScenario(mediaSession);

                string sdp = null;
                var sipRequest = uas.ClientTransaction.TransactionRequest;

                if (!String.IsNullOrEmpty(sipRequest.Body))
                {
                    // The SDP offer was included in the INVITE request.
                    SDP remoteSdp = SDP.ParseSDPDescription(sipRequest.Body);
                    var setRemoteResult = mediaSession.SetRemoteDescription(SdpType.offer, remoteSdp);

                    if (setRemoteResult != SetDescriptionResultEnum.OK)
                    {
                        uas.Reject(SIPResponseStatusCodesEnum.NotAcceptable, setRemoteResult.ToString());
                        mediaSession.Close("sdp offer not acceptable");
                        UserAgent.Hangup();

                    }
                    else
                    {
                        var sdpAnswer = mediaSession.CreateAnswer(null);
                        sdp = sdpAnswer.ToString();
                    }
                }
                uas.Progress(SIPResponseStatusCodesEnum.SessionProgress, null, null, "application/sdp", sdp);

                // Wait before answering the call
                await Task.Delay(5000);

                await UserAgent.Answer(uas, mediaSession);
```
It's not the most clean since I'm using AcceptCall to generate the SIPServerUserAgent rather than doing something custom to prevent a 180 also being sent. This isn't a big problem for me though.

Since SIPUserAgent.MediaSession is read-only, I can't hook my mediaSession object- which is playing media intended for the client which made the inbound call- up to the user agent before I answer the call. I can't see a way of doing this using the current methods exposed by either SIPUserAgent or SIPServerUserAgent.

**Comment by sipsorcery** [comment]
> Since SIPUserAgent.MediaSession is read-only, I can't hook my mediaSession object- which is playing media intended for the client which made the inbound call- up to the user agent before I answer the call. 

Do you need to? The `SIPUserAgent` won't know what to do with it before the call is answered. If your approach is working you could stick with that and then use the same media session with `SIPUserAgent.Answer` at which point it will know what to do with it and use it for on/off hold, hangup etc.

**Comment by CMC01** [comment]
The intention of hooking up the media session during early media is to be able to act on OnDtmfTone events and verify them against expected results (ie. Did the external SIP client making the call to sipsorcery generate the correct tones).

The only solutions I can think of are
- OnIncomingCall, start the mediaSession without attaching to the user agent and then use mediaSession.OnRtpEvent to capture incoming DTMF
- Make SIPUserAgent.MediaSession writable
- Some custom method for SIPUserAgent to perform option 1

I'm going to give the first option a try. If that doesn't work, perhaps I should rephrase this question into a feature request for sipsorcery to be able to receive media before answering the call when acting as a server.

**Comment by CMC01** [comment]
The above approach worked nicely. I had some issues with receiving media due to local firewall protections meaning I needed to ensure I was sending media first. I also hooked OnRtpEvent straight into my handler for UserAgent.OnDtmfTone -

```
mediaSession.OnRtpEvent += (ep, evt, hdr) =>
{
  if (hdr.MarkerBit == 1)
  {
      UserAgent_OnDtmfTone(evt.EventID, evt.Duration);
   }
};
                   
await mediaSession.Start().ConfigureAwait(false);
PlayScenario(mediaSession);
```
