### ISSUE TITLE
Make a call using SIPWebSocketChannel towards a registered WebRTC client

### ISSUE THREAD

**Issue by franck-malka** [sipsorcery-org/sipsorcery#619]
How can we make an outbound call using the SIPWebSocketChannel towards a registered WebRTC client?

**Comment by sipsorcery** [comment]
WebRTC doesn't have any concept of signalling or registrations so it's not really clear what you're after.

Perhaps you mean a SIP client that's using a WebRTC media layer?

The closest example in the project is likely to be the [sipjs one](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/sipjs).

**Comment by franck-malka** [comment]
Yes
Once the sip.js client is registered.
How can i make a call to the registered client?

Franck.

Le mer. 24 nov. 2021 à 21:06, Aaron Clauson ***@***.***> a
écrit :

**Comment by franck-malka** [comment]
I don't understand how to get the transport layer to select the web socket associated with the SIP.js client so a call can be sent from the correct SIPWebSocketChannel  towards the registered SIP.js client.

SIP.js --> REGISTER --> SIPSorcery
SIP.js <-- OK <-- SIPSorcery

SIPSorcery --> INVITE --> SIP.js ???

**Comment by sipsorcery** [comment]
You can specify the type of transport to use in the SIP URI, for example:

`sip:127.0.0.1:8081;transport=ws`

The transport layer should take care of choosing which channel to use if you are setting the SIP URI correctly.

**Comment by franck-malka** [comment]
if this is the case then how would the transport select the right socket when i have many clients connected?

**Comment by sipsorcery** [comment]
It looks for an already connected web socket channel that has the same remote endpoint you're asking it to send to.

**Comment by franck-malka** [comment]
Thanks, got the event on the client now;
But it fails with this error
sip.SessionDescriptionHandler | SessionDescriptionHandler.setDescription failed - InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.

**Comment by franck-malka** [comment]
I sorted out the SDP issue.
The call gets connected now to the SIP.js client.
But i have no audio on the web page.
