### ISSUE TITLE
[Example] Send RTCP FIR to request a key frame

### ISSUE THREAD

**Issue by mikhaylo1** [sipsorcery-org/sipsorcery#620]
Hello,

Is there a way  to send RTCP FIR request for forcing remote h264 peer to produce a keyframe ? Or maybe a some way for setting up a keyframe interval in sipsorcery SDP answer ?

I am trying to do it this way, but not sure if I do it correctly:

```
var feedBack = new RTCPFeedback(connection.VideoRtcpSession.Ssrc, connection.VideoRemoteTrack.Ssrc, PSFBFeedbackTypesEnum.FIR);
 connection.SendRtcpFeedback(SDPMediaTypesEnum.video, feedBack);
```

Would appreciate an example or advise. I need this for reducing quality degradation issue when I receive h264 video with 
sipsorcery WebRtc from a browser

**Comment by sipsorcery** [comment]
You need to use the Picture Loss Inidication (PLI) feedback type, [crude example](https://github.com/sipsorcery-org/sipsorcery/blob/f220108a016fb1708e7a5608945f346f8bb47794/examples/WebRTCExamples/WebRTCtoFfplay/Program.cs#L128).

**Comment by mikhaylo1** [comment]
That works, Thank you !
