### ISSUE TITLE
'OPTIONS' not working during a call

### ISSUE THREAD

**Issue by LADSoft** [sipsorcery-org/sipsorcery#625]
I set up a simple SIP server which is easy to do with this library.    All I wanted to do is play audio out the PC speakers.

That works functionally, except that I found that while a call is in progress and audio is being played, the server will not respond to an 'OPTIONS' request, which I am using to ping that the server is still there.    I tried ensuring that SIPUserAgent.OnIncomingCall in the server returned immediately while the call was in progress, but it didn't seem to help the situation.   Apparently, the process of accepting and answering a call blocks responses to the OPTIONS request until the call is over.    But it does pick up again if I end the call.

Are there any tricks to making this work during a call?   Our client architecture has two separate programs, one for playing audio and the other for supervising the connection.   Because the two programs aren't synchronized, there is a need to send an OPTIONS and receive a response while a call is in progress...

**Comment by tstaehli** [comment]
Which SIPUserAgent are you using to make calls? And How are you creating/accepting the call?

I just tested this with my application and could not reproduce your issue where options are not answered during a call. However I am not using the SIPUserAgent class, maybe the issue is in there?

But I recently had a similar issue, where only one call could be in ringing at a time. The problem for me was, that I was blocking (awaiting) the Task returned in the event for SIPTransport.SIPTransportRequestReceived and SIPTransport.SIPTransportResponseReceived.

This is not ideal, because the Task/Thread which raises these event waits for the Task to be completed before the next SIP Message is dispatched.

My solution was to return a completed task in the event-handler and start a different task:
        ```
private Task HandleSIPTransportRequestReceived(SIPEndPoint localsipendpoint, SIPEndPoint remoteendpoint, SIPRequest siprequest)
        {
            Task.Run(async () =>
            {
                // Handle the siprequest
            })
            return Task.CompletedTask;
        }
```

**Comment by LADSoft** [comment]
yeah I'm using SIPUserAgent class.    I had previously tried to make OnIncomingCall not block because like you I thought that might be an issue... but it didn't help...   here is the code for the entire thing as it stands right now.   Where the OPTIONS work as long as a call isn't in progress.   I just made a new instance of this class and waited until control-c was pressed to exit the program, then used our applications to send VOIP data with an OPTIONS coming in at intervals...   wireshark showed there was no response to the OPTIONS during the call but it picked up again afterward.

Maybe the SIPUserAgent is blocking requests somehow?   Am I using the wrong UserAgent class?

```
    sealed class AudioSink : IDisposable
    {
        const int SIP_LISTENING_PORT = 5060;
        SIPTransport _sipTransport;
        SIPUserAgent _userAgent;
        WindowsAudioEndPoint _winAudioEP;
        VoIPMediaSession _voipMediaSession;
        public AudioSink()
        {
            _sipTransport = new SIPTransport();
            _sipTransport.AddSIPChannel(new SIPUDPChannel(new IPEndPoint(IPAddress.Any, SIP_LISTENING_PORT)));

            _userAgent = new SIPUserAgent(_sipTransport, null, true);
            _userAgent.ServerCallCancelled += (uas) => {
                _voipMediaSession.Dispose();
                _userAgent.Cancel();
            };
            _userAgent.OnCallHungup += (dialog) => {
                _voipMediaSession.Dispose();
                _userAgent.Cancel();
            };
            _userAgent.OnIncomingCall += (ua, req) =>
            {
                _ = Task.Run(async () =>
                {
                    _winAudioEP = new WindowsAudioEndPoint(new AudioEncoder());
                    _voipMediaSession = new VoIPMediaSession(_winAudioEP.ToMediaEndPoints());
                    _voipMediaSession.OnTimeout += (ste) =>
                    {
                        _userAgent.Hangup();
                    };
                    await _winAudioEP.CloseAudio();
                    _voipMediaSession.AcceptRtpFromAny = true;
                    var uas = _userAgent.AcceptCall(req);
                    await _userAgent.Answer(uas, _voipMediaSession);
                });
            };
        }

        public void Dispose()
        {
            // Clean up.
            _sipTransport.Shutdown();
        }
    }
```

**Comment by tstaehli** [comment]
As far as I can tell, SIPUserAgent is really only meant to handle one call at a time, and ignores other messages if there is a dialog, except for reinvites. Also, it does not handle OPTIONS Messages. 

There is one special case where a 415 response is sent as long as there is no sip_dialogue and the transport exclusive flag is set,  but a 200 OK response should never be sent by the SIPUserAgent.

Try something like this; should also send a 200 for the OPTIONS request:
_sipTransport.SIPTransportRequestReceived += (SIPEndPoint localsipendpoint, SIPEndPoint remoteendpoint, SIPRequest siprequest) => {
  if(siprequest.Method == SIPMethodsEnum.OPTIONS){
     _sipTransport.SendResponseAsync(SIPResponse.GetResponse(siprequest, SIPResponseStatusCodesEnum.Ok, null));
   }
};
_userAgent = new SIPUserAgent(_sipTransport, null, **false**); // Transport is not exclusively used by this SIPUserAgent

**Comment by LADSoft** [comment]
that seems to work...   Setting the parameter in the constructor false did turn out to be necessary, to get rid of '405 method not allowed'.

thank you!
