### ISSUE TITLE
Hold On/Off does not produce Hold events on remote party

### ISSUE THREAD

**Issue by nserj** [sipsorcery-org/sipsorcery#633]
SIPUserAgent, Call Hold On/Off disable voice. When it will be Off on remote party, music audible for caller, Off on caller side just disabling voice. However, events will not be received by other party, even request is sent, SIPMessageReceived will not be called respectively.

**Comment by sipsorcery** [comment]
Putting the SIPUserAgent on/off hold does not affect the SIPTransport. The only way to get back off hold is by sending a new SIP request.

The SIPUserAgent will [disregard](https://github.com/sipsorcery-org/sipsorcery/blob/95caae797eab2db0c430290f8715f5b973c868a2/src/app/SIPUserAgents/SIPUserAgent.cs#L1246) any requests it does not recognise. Perhaps that's the issue?
