### ISSUE TITLE
remote sys does not hear a ringing tone after local acceptance

### ISSUE THREAD

**Issue by YousefGhafouri** [sipsorcery-org/sipsorcery#634]
Hi
I've Developed a VoIP Application using SIPSorcery. I've Registered  an username at Server's PBX by it  and Although I accept an incoming call But I've not get any response from Application in Ringing or beep sound mode. can you help me solving this problem and make full two-way connection between VoIP and External Application?

**Comment by sipsorcery** [comment]
Do you mean there's no rining sound prior to answering the call? If so it's up to you to wire that up.

The [OnIncomingCall](https://github.com/sipsorcery-org/sipsorcery/blob/96ea5d7e81406a077c7571819f07f36ab39b7e89/src/app/SIPUserAgents/SIPUserAgent.cs#L364) event and [ClientCallRinging](https://github.com/sipsorcery-org/sipsorcery/blob/96ea5d7e81406a077c7571819f07f36ab39b7e89/src/app/SIPUserAgents/SIPUserAgent.cs#L262) events are typically where you could start playing a sound file, display a visual indication or do whatever other action your app may need.

**Comment by YousefGhafouri** [comment]
Thanks, but I didn't mean no ringing sound prior to answer the call . the main  problem is no hearing beep sound by caller. in other words the destination get the call but the caller doesn't hear any beep sound .

**Comment by sipsorcery** [comment]
Does the receviever get any audio at all? One way audio with VoIP is a [common problem](https://www.sipsorcery.com/mainsite/Help/SIPAudio) that's usually related to network conditions.
