### ISSUE TITLE
SIPTransaction.Expire not handled exception

### ISSUE THREAD

**Issue by jakubbukaj** [sipsorcery-org/sipsorcery#638]
Steps to reproduce:
1) On SIPTransport TransportRequestReceived event handler SIPUserAgent accepts call but do not answer it
2) After approx. 3 minutes of ringing internal Expire method in SIPTransaction is called

In Expire method following code TransactionTraceMessage?.Invoke(this, $"Transaction failed due to a timeout {this.TransactionFinalResponse.ShortDescription}"); will raise an exception due to TransactionFinalResponse is null.

Proposed fix (for code in methods Expire, Failed): Check TransactionFinalResponse is not null before accessing ShortDescription.

**Comment by sipsorcery** [comment]
Thanks for the bug report.
