### ISSUE TITLE
SIPHeader Expires field maximum value 2^31 instead of 2^32 -1

### ISSUE THREAD

**Issue by JanHyteraMobilfunk** [sipsorcery-org/sipsorcery#639]
Hi Aaron,
I've just made the observation that SIPSorcery can only handle the Expires header-field up to a value of 2^31.
According to [RFC3261 20.19](https://datatracker.ietf.org/doc/html/rfc3261#section-20.19) it is 2^32 -1.

A quick check in the code and the field is defined as an Int32 where -1 is used as default value.
It returns zero as parsing result in case 2^32 -1 is received in the SIP-Request message.

(Yeah, I do have a third-party client which is actually sending 2^32 -1 to my application. Though I have no clue which subscription should last 136 years.... )

As I am quite new to the SIP world and I haven't found any other statement so far where the value is limited.
Is it intended to use an Int32 there? 

If so, could you help me out why?
If not, I would be happy to provide a PR with a proposal on how to change it.

Best regards,
Jan

**Comment by sipsorcery** [comment]
Hi Jan,

> Is it intended to use an Int32 there?

I can't recall any reason that would have been the case other than convenience. Although it does seem a bit pointless to set a SIP expiry to anything approaching 2^31 or 2^32 (4000+ years in the future). Still if that's what the spec says then that's what we should support.

> If not, I would be happy to provide a PR with a proposal on how to change it.

Yes, please.

**Comment by sipsorcery** [comment]
Resolved by #640.
