### ISSUE TITLE
Creating a data-only RTP session

### ISSUE THREAD

**Issue by lowkay** [sipsorcery-org/sipsorcery#649]
Howdy,

I'm looking to implement file transfer over RTP that is compatible with legacy Skype for Business infrastructure.

I have a full understanding of the file transfer data protocol, but I need to be able to:
1. Negotiate an RTP transport that is data-only (no audio or video track)
2. Send/receive the raw RTP data

For the first part I note that RTPSession is the likely place to start, however it's not readily extensible:
- It doesn't support creating SDP when there are no audio/video tracks
- Trying to override this behaviour and create the SDP for the data track doesn't work because there's no access to manipulate the media track state (it's an internal setter) and there's no access to the other required fields to create the SDP (i.e. RTPSession sdp session ID and crypto settings)

So my question is, is it even possible to do this with the library?

If it is, some pointers would be great!

**Comment by sipsorcery** [comment]
> So my question is, is it even possible to do this with the library?

In theory it's possible to incorporate new media types to the `RTPSession`. The `RTCPeerConnection` class [does exactly that](https://github.com/sipsorcery-org/sipsorcery/blob/008087cf12a32594209594b47a0fd58894df8261/src/net/WebRTC/RTCPeerConnection.cs#L713) to support WebRTC data channels.

You are correct, though, that the `RTPSession` class is not that easy to extend. It wasn't originally designed with extensibility in mind and it's grown into probably the biggest class in the library. That being said the SDP related methods [CreateOffer](https://github.com/sipsorcery-org/sipsorcery/blob/008087cf12a32594209594b47a0fd58894df8261/src/net/RTP/RTPSession.cs#L560) and [CreateAnswer](https://github.com/sipsorcery-org/sipsorcery/blob/008087cf12a32594209594b47a0fd58894df8261/src/net/RTP/RTPSession.cs#L600) are overridable and if all you need to do is handle a single new media type in the SDP negotiation and then do your own RTP packetisation it may not be that much work.

**Comment by lowkay** [comment]
Hello, firstly, thank you for your response and taking the time to answer.

> In theory it's possible to incorporate new media types to the RTPSession. The RTCPeerConnection class does exactly that to support WebRTC data channels.

I can see the RtcPeerConnection essentially re-implements the offer/answer mechanics, including the crypto key session etc.
I think the only other thing stopping me from being able to easily do this is the use of internal classes that have internal setters (`MediaStreamTrack.StreamStatus`).

I'm happy to continue my research with a fork to expose the necessary bits as public, if all goes well I'll raise a pull request to better support extensibility, maybe even with an example. The project urgency has dropped, but I still plan on carrying out an investigation this year.

Closing as I have a better idea of how to proceed now.
