### ISSUE TITLE
DTLS Client throws TLSFatalError when X_DisableExtendedMasterSecretKey = true

### ISSUE THREAD

**Issue by Ali-Russell** [sipsorcery-org/sipsorcery#650]
Hi there,

I'm developing a Xamarin mobile app (iOS & Android) that uses SIPSorcery to make calls with webRTC and SIP signalling via a private backend.  

Making outgoing calls is working nicely, I have two-way audio to a web client, however I've hit a problem receiving calls via SIP.

For the DTLS negotiation I need to set `X_DisableExtendedMasterSecretKey = true` on the RTCConfiguration and this works fine when acting as a server, however when acting as a client this value appears to be ignored.

Ref: RTCPeerConnection Line 532
```
bool disableDtlsExtendedMasterSecret = _configuration != null && _configuration.X_DisableExtendedMasterSecretKey;
                    _dtlsHandle = new DtlsSrtpTransport(
                                IceRole == IceRolesEnum.active ?
                                new DtlsSrtpClient(_dtlsCertificate, _dtlsPrivateKey) :
                                (IDtlsSrtpPeer)new DtlsSrtpServer(_dtlsCertificate, _dtlsPrivateKey)
                                { ForceUseExtendedMasterSecret = !disableDtlsExtendedMasterSecret }
                                );

```

I was wondering if there's a reason that ForceUseExtendedMasterSecret is not set for the DtlsSrtpClient?  Apologies not very familiar with this part yet.

I can't see an easily accessible property to set or method to override to set this in customer code as everything looks private.  

I've tested modifying a copy of the source and the DTLS negotiation works but I'm looking for a better way.  Hoping you can suggest an approach. 

Cheers,

Ali

**Comment by sipsorcery** [comment]
> Making outgoing calls is working nicely, I have two-way audio to a web client,

That's very impressive. What are you using to access the speaker and/or microphone?

> I was wondering if there's a reason that ForceUseExtendedMasterSecret is not set for the DtlsSrtpClient?

There's no particular reason other than I did not come across a scenario where it was ever needed. The reason `X_DisableExtendedMasterSecretKey` was added was for athe single purpose of being able to connect to a Kurento WebRTC peer.

If you're able to confirm and/or submit a PR to use `ForceUseExtendedMasterSecret` for teh `DtlsSrtpClient` I'd be happy to merge it.

**Comment by Ali-Russell** [comment]
Great, thanks for the quick response!

I'm accessing the speakers through [libvlcsharp](https://github.com/videolan/libvlcsharp) and the microphone through [NateRickard/Plugin.AudioRecorder](https://github.com/NateRickard/Plugin.AudioRecorder). As you said in another issue somewhere it was a case of wiring up the media endpoints, and add a way to manage a stream with both accessing it.  It's still a work in progress of course. 

I did wonder if this was a specific case and will dig out more details why it's required. 

Cool, if there's no objections then I'd be happy to arrange a PR. 

Ali.

**Comment by sipsorcery** [comment]
> I'm accessing the speakers through libvlcsharp and the microphone through NateRickard/Plugin.AudioRecorder. As you said in another issue somewhere it was a case of wiring up the media endpoints, and add a way to manage a stream with both accessing it. It's still a work in progress of course.

It'd be awesome if you're able to provide an example at some point. So many people have asked about this and despite a few rumours I've never managed to get to see any working examples.

**Comment by Ali-Russell** [comment]
I hope to do that backlog dependent, and have everything related to the Xamarin media endpoints in a stand-alone library. 😄 Although it'll be interesting when MAUI comes along.

PR submitted, please let me know any comments.

**Comment by sipsorcery** [comment]
> Although it'll be interesting when MAUI comes along.

There won't be any audio interop in MAUI. Microsoft showed next to zero interest even when it was ,Net Framework and Windows only. No chance now .NET is x-platform. I suspect it's in the too hard basket.

> PR submitted, please let me know any comments.

Will do, thanks for the PR!
