### ISSUE TITLE
How to send DTMF key '#'

### ISSUE THREAD

**Issue by boskjoett** [sipsorcery-org/sipsorcery#658]
The documentation and example for the method 
`SIPUserAgent.SendDtmf(byte key)`
says that to send DTMF digit '1' you call
`SendDtmf(1)`
and not 
`SendDtmf('1')`

So how do you send the DTMF key '#'? What is the byte value for a hash key or an asterisk '*'?

**Comment by sipsorcery** [comment]
For `#` use `SentDtmf(11)`.

See https://datatracker.ietf.org/doc/html/rfc2833#section-3.10.
