### ISSUE TITLE
Regression: Bad audio since commit "a6bfce24"  (2022, 17 January)

### ISSUE THREAD

**Issue by ChristopheI** [sipsorcery-org/sipsorcery#660]
Hi,

There is a regression in this [commit](https://github.com/sipsorcery-org/sipsorcery/commit/a6bfce24722740997e384f332763a2f95253ab93) (2022, 17 January)

**Context:** 
Use of WebRTC
Client A: SipSorcery + SipSorceryMedia.FFmpeg + HomeMade Add On for Audio Playback (in progress)
Client B: WebClient (Edge)

**Use case:**
Client calls Client B using audio only
Client B accepts the call

**Result:**
Connection is well established but Client A hears a very noisy sound even if Client B produced no sound (Muted)
100% reproductible

Using the previous [commit](https://github.com/sipsorcery-org/sipsorcery/commit/db0be4aaa5b8fbf4551866ba396a63c7d88e270e), there is no trouble of sound

Thanks.

**Comment by sipsorcery** [comment]
I've reverted the PR while we track it down.

**Comment by sipsorcery** [comment]
[Fixed](https://github.com/sipsorcery-org/sipsorcery/pull/671#issuecomment-1021169366).
