### ISSUE TITLE
STUNClient.cs STUNAttributeTypesEnum.XORMappedAddress not handled

### ISSUE THREAD

**Issue by breeblebrax** [sipsorcery-org/sipsorcery#662]
I noticed that both stun.3cx and stun.google returned XORMappedAddress but            
public static IPEndPoint GetPublicIPEndPoint(string stunServer, int port = DEFAULT_STUN_PORT)
doesn't seem to handle the case properly.

This is the first time I have reported a bug to an open source project, so I appreciate your patience if this is not the right way 
to address this.  I did do a quick search and did not find it referenced in any other issues.

Cheers               

````
if (stunResponse.Attributes.Count > 0)
{
	foreach (STUNAttribute stunAttribute in stunResponse.Attributes)
	{
		if (stunAttribute.AttributeType == STUNAttributeTypesEnum.MappedAddress)
		{
			STUNAddressAttribute stunAddress = (STUNAddressAttribute)stunAttribute;
			publicEndPoint = new IPEndPoint(stunAddress.Address, stunAddress.Port);
			logger.LogDebug($"STUNClient Public IP={publicEndPoint.Address} Port={publicEndPoint.Port}.");
		}
/*I added to handle XORMAPPED*/
		else if(stunAttribute.AttributeType == STUNAttributeTypesEnum.XORMappedAddress)
		{
			STUNXORAddressAttribute stunAddress = (STUNXORAddressAttribute)stunAttribute;
			publicEndPoint = new IPEndPoint(stunAddress.Address, stunAddress.Port);
			logger.LogDebug($"STUNClient Public IP={publicEndPoint.Address} Port={publicEndPoint.Port}.");
		}
	}
}                               
````

**Comment by sipsorcery** [comment]
> This is the first time I have reported a bug to an open source project, so I appreciate your patience if this is not the right way
to address this. 

And, thanks for doing so. Bug reports are always appreciated.

Your suggestion looks sensible. I've added it as #665. If you're able to give it a quick review and confirm that its what you had in mind it should be good to merge.
