### ISSUE TITLE
Unable to create WindowAudioEndPoint

### ISSUE THREAD

**Issue by owlboo** [sipsorcery-org/sipsorcery#668]
I have observed the exception when unable to create the WindowAudioEndPoint when working with NAudio.

Code:
`
var userAgent = new SIPUserAgent(sipTransport, OUTBOUND_PROXY);
userAgent.ClientCallFailed += (uac, error, sipResponse) => Console.WriteLine($"Call failed {error}.");
userAgent.ClientCallFailed += (uac, error, sipResponse) => exitCts.Cancel();
userAgent.OnCallHungup += (dialog) => exitCts.Cancel();
var windowsAudio = new SIPSorceryMedia.Windows.WindowsAudioEndPoint(new SIPSorcery.Media.AudioEncoder());           
`
Exception:
`System.TypeLoadException: Could not load type 'NAudio.Wave.WaveFormat' from assembly 'NAudio, Version=2.0.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'.
   at SIPSorceryMedia.Windows.WindowsAudioEndPoint..ctor(IAudioEncoder audioEncoder, Int32 audioOutDeviceIndex, Int32 audioInDeviceIndex, Boolean disableSource, Boolean disableSink)`

When I constructed the WindowsAudioEndPoint, it's throw an exception like above.
I used NAudio to convert the audio file to PCM 16 bit. and write a service to convert in another class.

**Comment by sipsorcery** [comment]
Which operating system?

**Comment by owlboo** [comment]
Windows 10 (OS Build 19042.1466)

**Comment by sipsorcery** [comment]
Could be similar to #551.

**Comment by owlboo** [comment]
Thank you for your response.
I see both are different. It's due to my problem is when creating the WindowAudioEndPoint object at the initialized call step. If I remove the NAudio Nuget, the call is working well. If I install without any reference to the library, the issue occurs.

**Comment by jkmchinese** [comment]
I have also encountered this problem, and my current solution is: use NAudio version 1.10.0

Although the problem has been around for a long time!
