### ISSUE TITLE
How to register with different username and authId?

### ISSUE THREAD

**Issue by karas1999** [sipsorcery-org/sipsorcery#683]
Currently I'm using SIPRegistrationUserAgent to register to a 3CX server. In the server admin can set different username and authId for a user, but SIPRegistrationUserAgent only accept 1 username as parameter. If I set username and authId as the same, I can successfully register. But if I set them as different, I will always get 404 User unknown error.

In most softphones like Zoiper or Bria, it can set different username and authId in SIP account settings. 

I want to know that is it possible to use different username / authId to register in SIPSorcery? Thanks.

**Comment by sipsorcery** [comment]
You can use the [SIPRegistrationUserAgent](https://github.com/sipsorcery-org/sipsorcery/blob/2c4bef801e8176ca6ac421d64510ca65e5143aa7/src/app/SIPUserAgents/SIPRegistrationUserAgent.cs#L161) constructor that taks an `authUsername` parameter.

**Comment by sipsorcery** [comment]
Closing this issue. If you need further help feel free to re-open.
