### ISSUE TITLE
Test fails (Debug/AnyCPU)

### ISSUE THREAD

**Issue by grishinrv** [sipsorcery-org/sipsorcery#686]
SIPSorcery.Net.UnitTests.SctpDataSenderUnitTest.SmallBufferSend
   Source: SctpDataSenderUnitTest.cs line 39
   Duration: 1 sec

  Message: 
The collection was expected to contain a single element, but it contained more than one element.

  Stack Trace: 
SctpDataSenderUnitTest.SmallBufferSend() line 52
--- End of stack trace from previous location ---

**Comment by sipsorcery** [comment]
What OS and .NET version? 

The tests do get automatically run on AppVeyor and GitHub on Windows, MacOS and Ubuntu and all are currently passing.

**Comment by sipsorcery** [comment]
It will take of effort to track down Winows 8.1 issues. I'm happy to accept any PR's to fix the issue but it's not something I'll be able to spend time on investigating.
