### ISSUE TITLE
Make call with sip extension and GrandStream switch

### ISSUE THREAD

**Issue by JArmandoCl** [sipsorcery-org/sipsorcery#689]
Hi! I´m trying to make calls between a grandstream switch, i have created some extensions sip and i can connect to the server with the local ip, but when i want to make a call throws an exception:
Authentication with provided credentials fail

SIPCallDescriptor callDescriptor = new SIPCallDescriptor(sipUsername, sipPassword, callURI.ToString(), fromHeader, null, null, null, null, SIPCallDirection.Out, _sdpMimeContentType, null, null);

So i need to establish my userName, registerName and password, y tried to implement the constructor SIPRegistrationUserAgent to send tha extra parameter but it was not successful

How can i implement the 2nd overload of that method 

Thanks in advance

**Comment by sipsorcery** [comment]
You don't need to use the `SIPRegistrationUserAgent` to make a call. To place a call the only class you normally need to use is the `SIPUserAgent` and in most cases the simplest [Call](https://github.com/sipsorcery-org/sipsorcery/blob/022807091e990fd4b39536569545ea78d6fc572f/src/app/SIPUserAgents/SIPUserAgent.cs#L422) overload will work.

**Comment by JArmandoCl** [comment]
> You don't need to use the `SIPRegistrationUserAgent` to make a call. To place a call the only class you normally need to use is the `SIPUserAgent` and in most cases the simplest [Call](https://github.com/sipsorcery-org/sipsorcery/blob/022807091e990fd4b39536569545ea78d6fc572f/src/app/SIPUserAgents/SIPUserAgent.cs#L422) overload will work.

Sorry for the late response, and yes! that was the solution. Thanks for this awesome tool.
