### ISSUE TITLE
Cannot get WebRTCReceiver example to run

### ISSUE THREAD

**Issue by rcslaney** [sipsorcery-org/sipsorcery#691]
Hi,

I'm trying to do bidirectional video streaming between a C# application running on Windows 10 and Chrome (v98) on Android 10. I have cloned the latest repo, changed the "version" tag in global.json to 5, and am running the examples in Visual Studio. After doing this I have successfully been able to run video streaming examples streaming the video test pattern from C# program to the browser, but haven't been able to get any of the examples streaming video in the other direction working (Android browser-> Windows).

Running the "WebRTCReceiver" example, I get the following error in Chrome developer console on Android:

**Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='1'.**

I believe this may be because some android phones do not support H264 WebRTC (see https://stackoverflow.com/questions/36766716/how-to-enable-h264-on-android-webrtc), this is from a while ago though so I am unsure.

Next I tried changing the codec to VP8  by swapping out the relevant lines in the Program.cs file (lines 111, 112 & 150) to the alternative VP8 lines that are originally commented out. After doing this the connection establishes successfully however no feed shows in the WinForms window and the console shows the following error:

**[02:34:42 WRN] VP8 decode attempt failed, Bitstream not supported by this decoder.**

Any help on this would be greatly appreciated, let me know if there's any more details I can provide that may be of help.

**Comment by sipsorcery** [comment]
> [02:34:42 WRN] VP8 decode attempt failed, Bitstream not supported by this decoder.

That's not unusual. It can sometimes take a bit of time for a keyframe to get sent to allow the video stream to synchronise. How long did you let it run?

See [here](https://github.com/sipsorcery-org/sipsorcery/blob/022807091e990fd4b39536569545ea78d6fc572f/examples/WebRTCExamples/WebRTCtoFfplay/Program.cs#L128) for an example of a kludge to attempt to force the remote peer to send a key frame. If #385 ever gets implemented the kludge won't be needed.

**Comment by ChristopheI** [comment]
Hi @rcslaney ,

Did you find a solution to your problem ?
I have the same problem (see #712) when using FFmpeg to decode VP8 from an Android Device.

Thx

**Comment by sipsorcery** [comment]
Fixed in #1225.

Also make sure to run:

`winget install "FFmpeg (Shared)" --version 7.0`
