### ISSUE TITLE
null Ref error   in SIPSorcery.Media.AudioExtrasSource.GetPcmSampleFromReader

### ISSUE THREAD

**Issue by neilsilver** [sipsorcery-org/sipsorcery#692]
Hello! We are trying to do a blindtrasfer with a multiple call. The environment we are running is Mono. Unfortunately, have been seeing an issue , and sofar couldn't find the origin of problem.

Code has been simplified for clarity including the lock pattern that stops multiple calls being refered.
```csharp
async Task GroupCall(string homeAddress, List<string> extensions, CancellationToken tkn = default)
{
	var callList = new List<SIPUserAgent>();
	
	foreach (var destination in extensions)
	{
		Task.Run(async () =>
		{
			var call = new SIPUserAgent(SipTransport, null);
			var rtpSession = new AudioSendOnlyMediaSession();
			rtpSession.AudioExtrasSource.SetSource(AudioSourcesEnum.Music);
			callList.Add(call);
			var callResult = await call.Call(destination.Address, null, null, rtpSession);
			
			if (callResult)
			{
				CancelOtherCalls(call, callList);
				
				await TransferHome(call, homeAddress, tkn);
			}
		});
	}
	
	// ... skipped code
	
}

async Task TransferHome(SIPUserAgent call, string homeAddress, CancellationToken tkn = default)
{
	if (call == null) return;
	
	var result = await call.BlindTransfer(SIPURI.ParseSIPURI(homeAddress), TimeSpan.FromSeconds(2), tkn);
	await Task.Delay(2000, tkn);
	
	call.Hangup();
}

void CancelOtherCalls(SIPUserAgentCall call, List<SIPUserAgent> callList)
{
	foreach (var destination in callList)
	{
		if (call.CallDescriptor.To != destination.CallDescriptor.To)
		{
			call.Cancel();
			call.Close();
			call.Dispose();
		}
	}
}

```

The issue we encounter is related to the RTP session. A null Ref error on a timer callback  in SIPSorcery.Media.AudioExtrasSource.GetPcmSampleFromReader

While not suggested in the documentation We are calling the "Hangup" as the after successful blind transfer 
When the Tranfer Result is True the operation  call.IsCallActive is still true while documentation indicates it suppose to be false. 

We see the 202 response that comes back from our sip phone hardware:
Although the result of the blindtransfer returns true we dont see the BYE request being sent.

```
Response received: udp:0.0.0.0:60160<-udp:192.168.10.46:5060
SIP/2.0 202 Accepted
Via: SIP/2.0/UDP 192.168.10.147:60160;rport=60160;received=192.168.10.147;branch=z9hG4bK6b6468bce0eb4d10aeaff043dfe9083c
To: <sip:101@192.168.10.46>;tag=1EPRV5EhBMWyWRZy2Mfu3YI6mT7CsEwS
From: <sip:thisis@anonymous.invalid>;tag=FLJZVRRZBJ
Call-ID: e937b1c0298b4ed3834090fe3a317e42
CSeq: 2 REFER
Contact: "GAMES ROOM" <sip:101@192.168.10.46:5060>
Expires: 600
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Content-Length: 0
```

We mitigated this by calling call.Hangup() once we have the true response from the blindtransfer.
This Stops the Mediasession and ends the call.

This works but we occasionally we see the null ref error firing from the timer callback.

Here is the log.

     1.  # [08:41:45 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
      2. # [08:41:45 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
      3.  # [08:41:45 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
      4.  # [08:41:45 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
      5.  # [08:41:45 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
      6.  # [08:41:45 DBG] CreateBoundUdpSocket even port required, closing socket on [::]:26233 and retrying on 26234.
      7.  # [08:41:45 DBG] CreateBoundUdpSocket even port required, closing socket on [::]:10855 and retrying on 10856.
      8.  # [08:41:45 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:10857.
      9.  # [08:41:45 DBG] CreateBoundUdpSocket successfully bound on [::]:10857, dual mode True.
      10.  # [08:41:45 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:26235.
      11.  # [08:41:45 DBG] CreateBoundUdpSocket successfully bound on [::]:26235, dual mode True.
      12.  # [08:41:45 DBG] Successfully bound RTP socket [::]:10856 (dual mode True) and control socket [::]:10857 (dual mode True).
      13.  # [08:41:45 DBG] Successfully bound RTP socket [::]:26234 (dual mode True) and control socket [::]:26235 (dual mode True).
      14.  # [08:41:45 DBG] RTPChannel for [::]:26234 started.
      15.  # [08:41:45 DBG] RTPChannel for [::]:10856 started.
      16.  # [08:41:45 DBG] SIPClientUserAgent attempting to resolve 192.168.10.196:5060.
      17.  # [08:41:45 DBG] SIPClientUserAgent attempting to resolve 192.168.10.233:5060.
      18.  # [08:41:45 DBG] SIPClientUserAgent resolved 192.168.10.196:5060 to udp:192.168.10.196:5060 in 0.15ms.
      19.  # [08:41:45 DBG] SIPClientUserAgent resolved 192.168.10.233:5060 to udp:192.168.10.233:5060 in 0.13ms.
      20.  # [08:41:45 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
      21.  # [08:41:45 DBG] CreateBoundUdpSocket even port required, closing socket on [::]:23877 and retrying on 23878.
      22.  # [08:41:45 DBG] UAC commencing call to sip:105@192.168.10.196:5060.
      23.  # [08:41:46 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:23879.
      24.  # [08:41:46 DBG] UAC commencing call to sip:2245050195@192.168.10.233:5060.
      25.  # [08:41:46 DBG] CreateBoundUdpSocket successfully bound on [::]:23879, dual mode True.
      26.  # [08:41:46 DBG] Successfully bound RTP socket [::]:23878 (dual mode True) and control socket [::]:23879 (dual mode True).
      27.  # [08:41:46 DBG] RTPChannel for [::]:23878 started.
      28.  # [08:41:46 DBG] SIPClientUserAgent attempting to resolve 192.168.10.46:5060.
      29.  # [08:41:46 DBG] SIPClientUserAgent resolved 192.168.10.46:5060 to udp:192.168.10.46:5060 in 0.13ms.
      30.  # [08:41:46 DBG] UAC commencing call to sip:101@192.168.10.46:5060.
      31.  # [08:41:46 DBG] Information response 100 Trying for sip:2245050195@192.168.10.233:5060.
      32.  # [08:41:46 INF] Call attempt to sip:2245050195@192.168.10.233:5060 received a trying response INVITE 100 Trying.
      33.  # [08:41:46 DBG] Information response 180 Ringing for sip:2245050195@192.168.10.233:5060.
      34.  # [08:41:46 INF] Call attempt to sip:2245050195@192.168.10.233:5060 received a ringing response INVITE 180 Ringing.
      35.  # [08:41:46 DBG] Information response 100 Trying for sip:105@192.168.10.196:5060.
      36.  # [08:41:46 INF] Call attempt to sip:105@192.168.10.196:5060 received a trying response INVITE 100 Trying.
      37.  # [08:41:46 DBG] Information response 180 Ringing for sip:105@192.168.10.196:5060.
      38.  # [08:41:46 INF] Call attempt to sip:105@192.168.10.196:5060 received a ringing response INVITE 180 Ringing.
      39.  # [08:41:46 DBG] Information response 100 Trying for sip:101@192.168.10.46:5060.
      40.  # [08:41:46 INF] Call attempt to sip:101@192.168.10.46:5060 received a trying response INVITE 100 Trying.
      41.  # [08:41:46 DBG] Information response 183 Session Progress for sip:101@192.168.10.46:5060.
      42.  # [08:41:46 DBG] Setting audio source format to 0:PCMU.
      43.  # [08:41:46 DBG] Set remote description for early media result OK.
      44.  # [08:41:46 INF] Call attempt to sip:101@192.168.10.46:5060 received a ringing response INVITE 183 Session Progress.
      45.  # [08:41:47 DBG] Set remote audio track SSRC to 1105280207.
      46.  # [08:41:48 DBG] Response 486 Busy Here for sip:101@192.168.10.46:5060.
      47.  # [08:41:48 WRN] Call attempt was answered with failure response INVITE 486 Busy Here.
      48.  # [08:41:48 DBG] RTPChannel closing, RTP receiver on port 23878, Control receiver on port 23879. Reason: normal.
      49.  # [08:41:55 DBG] Response 200 OK for sip:105@192.168.10.196:5060.
      50.  # [08:41:55 DBG] Setting audio source format to 0:PCMU.
      51.  # [08:41:55 INF] Call attempt to sip:105@192.168.10.196:5060 was answered.
      52.  # [08:41:55 DBG] Cancelling forwarded call leg, sending CANCEL to sip:2245050195@192.168.10.233:5060.
      53.  # [08:41:55 WRN] Call attempt to sip:2245050195@192.168.10.233:5060 failed with Call cancelled by user..
      54.  # [08:41:55 DBG] RTPChannel closing, RTP receiver on port 10856, Control receiver on port 10857. Reason: call cancelled.
      55.  # [08:41:55 DBG] Set remote audio track SSRC to 431849403.
      56.  # [08:41:56 DBG] Response 487 Request Terminated for sip:2245050195@192.168.10.233:5060.
      57.  # [08:41:56 INF] Call transfer was accepted by remote server.
      58.  # [08:41:58 DBG] RTPChannel closing, RTP receiver on port 26234, Control receiver on port 26235. Reason: call hungup.
      59.  # [08:41:58 DBG] Response 200 OK for sip:105@192.168.10.196:5060.
      60.  # [08:42:19 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
      61.  # [08:42:19 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
      62.  # [08:42:19 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
      63.  # [08:42:19 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
      64.  # [08:42:19 DBG] CreateBoundUdpSocket even port required, closing socket on [::]:20037 and retrying on 20038.
      65.  # [08:42:19 DBG] CreateBoundUdpSocket successfully bound on [::]:14240, dual mode True.
      66.  # [08:42:19 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:14241.
      67.  # [08:42:19 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:20039.
      68.  # [08:42:19 DBG] CreateBoundUdpSocket successfully bound on [::]:14241, dual mode True.
      69.  # [08:42:19 DBG] CreateBoundUdpSocket successfully bound on [::]:20039, dual mode True.
      70.  # [08:42:19 DBG] Successfully bound RTP socket [::]:14240 (dual mode True) and control socket [::]:14241 (dual mode True).
      71.  # [08:42:19 DBG] Successfully bound RTP socket [::]:20038 (dual mode True) and control socket [::]:20039 (dual mode True).
      72.  # [08:42:19 DBG] RTPChannel for [::]:14240 started.
      73.  # [08:42:19 DBG] RTPChannel for [::]:20038 started.
      74.  # [08:42:19 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
      75.  # [08:42:19 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
      76.  # [08:42:19 DBG] CreateBoundUdpSocket even port required, closing socket on [::]:29039 and retrying on 29040.
      77.  # [08:42:19 DBG] SIPClientUserAgent attempting to resolve 192.168.10.196:5060.
      78.  # [08:42:19 DBG] SIPClientUserAgent attempting to resolve 192.168.10.46:5060.
      79.  # [08:42:19 DBG] SIPClientUserAgent resolved 192.168.10.196:5060 to udp:192.168.10.196:5060 in 0.16ms.
      80.  # [08:42:19 DBG] SIPClientUserAgent resolved 192.168.10.46:5060 to udp:192.168.10.46:5060 in 0.15ms.
      81.  # [08:42:19 DBG] UAC commencing call to sip:101@192.168.10.46:5060.
      82.  # [08:42:19 DBG] UAC commencing call to sip:105@192.168.10.196:5060.
      83.  # [08:42:19 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:29041.
      84.  # [08:42:19 DBG] CreateBoundUdpSocket successfully bound on [::]:29041, dual mode True.
      85.  # [08:42:19 DBG] Successfully bound RTP socket [::]:29040 (dual mode True) and control socket [::]:29041 (dual mode True).
      86.  # [08:42:19 DBG] RTPChannel for [::]:29040 started.
      87.  # [08:42:19 DBG] SIPClientUserAgent attempting to resolve 192.168.10.233:5060.
      88.  # [08:42:19 DBG] SIPClientUserAgent resolved 192.168.10.233:5060 to udp:192.168.10.233:5060 in 0.13ms.
      89.  # [08:42:19 DBG] UAC commencing call to sip:2245050195@192.168.10.233:5060.
      90.  # [08:42:19 DBG] Information response 100 Trying for sip:2245050195@192.168.10.233:5060.
      91.  # [08:42:19 INF] Call attempt to sip:2245050195@192.168.10.233:5060 received a trying response INVITE 100 Trying.
      92.  # [08:42:19 DBG] Information response 180 Ringing for sip:2245050195@192.168.10.233:5060.
      93.  # [08:42:19 INF] Call attempt to sip:2245050195@192.168.10.233:5060 received a ringing response INVITE 180 Ringing.
      94.  # [08:42:19 DBG] Information response 100 Trying for sip:105@192.168.10.196:5060.
      95.  # [08:42:19 INF] Call attempt to sip:105@192.168.10.196:5060 received a trying response INVITE 100 Trying.
      96.  # [08:42:19 DBG] Information response 180 Ringing for sip:105@192.168.10.196:5060.
      97.  # [08:42:19 INF] Call attempt to sip:105@192.168.10.196:5060 received a ringing response INVITE 180 Ringing.
      98.  # [08:42:19 DBG] Information response 100 Trying for sip:101@192.168.10.46:5060.
      99.  # [08:42:19 INF] Call attempt to sip:101@192.168.10.46:5060 received a trying response INVITE 100 Trying.
      100.  # [08:42:20 DBG] Information response 183 Session Progress for sip:101@192.168.10.46:5060.
      101.  # [08:42:20 DBG] Setting audio source format to 0:PCMU.
      102.  # [08:42:20 DBG] Set remote description for early media result OK.
      103.  # [08:42:20 INF] Call attempt to sip:101@192.168.10.46:5060 received a ringing response INVITE 183 Session Progress.
      104.  # [08:42:20 DBG] Set remote audio track SSRC to 1568999616.
      105.  # [08:42:23 DBG] Response 200 OK for sip:101@192.168.10.46:5060.
      106.  # [08:42:23 DBG] Replacing existing remote audio track for ssrc 1568999616.
      107.  # [08:42:23 DBG] Setting audio source format to 0:PCMU.
      108.  # [08:42:23 INF] Call attempt to sip:101@192.168.10.46:5060 was answered.
      109.  # [08:42:23 DBG] Cancelling forwarded call leg, sending CANCEL to sip:2245050195@192.168.10.233:5060.
      110.  # [08:42:23 WRN] Call attempt to sip:2245050195@192.168.10.233:5060 failed with Call cancelled by user..
      111.  # [08:42:23 DBG] RTPChannel closing, RTP receiver on port 29040, Control receiver on port 29041. Reason: call cancelled.
      112.  # [08:42:23 DBG] Cancelling forwarded call leg, sending CANCEL to sip:105@192.168.10.196:5060.
      113.  # [08:42:23 WRN] Call attempt to sip:105@192.168.10.196:5060 failed with Call cancelled by user..
      114.  # [08:42:23 DBG] RTPChannel closing, RTP receiver on port 14240, Control receiver on port 14241. Reason: call cancelled.
      115.  # [08:42:23 DBG] Set remote audio track SSRC to 1568999616.
      116.  # [08:42:23 DBG] Response 487 Request Terminated for sip:105@192.168.10.196:5060.
      117.  # [08:42:23 DBG] Response 487 Request Terminated for sip:2245050195@192.168.10.233:5060.
      118.  # [08:42:23 INF] Call transfer was accepted by remote server.
      119.  # [08:42:25 DBG] RTPChannel closing, RTP receiver on port 20038, Control receiver on port 20039. Reason: call hungup.
      120.  # 2022-02-22 08:42:25 # ▒p:t:▒:C:▒$H'
      121. # 2022-02-22 08:42:25 # Exception:An unhandled exception occurred:  - System.NullReferenceException: Object reference not set to an instance of an object.
                  at SIPSorcery.Media.AudioExtrasSource.GetPcmSampleFromReader (System.IO.BinaryReader binaryReader, SIPSorceryMedia.Abstractions.AudioSamplingRatesEnum inputSampleRate, System.Int32& samplesRead) [0x0009f] in <1dba3b49f2e844049096ff6b288f053c>:0
                            at SIPSorcery.Media.AudioExtrasSource.SendMusicSample(System.Object state) [0x00021] in <1dba3b49f2e844049096ff6b288f053c>:0
                                at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <a52c4a579f20475caf4d3806d4a56863>:0
               at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <a52c4a579f20475caf4d3806
        at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <a52c4a579f20475caf4d3806d4a56863>:0
                at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <a52c4a579f20475caf4d3806d4a56863>:0
      125. # 2022-02-22 08:42:25 # [08:42:25 DBG] Response 200 OK for sip:101@192.168.10.46:5060.
      127. Error: CustomAppManager_0 # 2022-02-22 08:42:25 # [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
      128. Error: CustomAppManager_0 # 2022-02-22 08:42:25 #   at SIPSorcery.Media.AudioExtrasSource.GetPcmSampleFromReader (System.IO.BinaryReader binaryReader, SIPSorceryMedia.Abstractions.AudioSamplingRatesEnum inputSampleRate, System.Int                                                                                32& samplesRead) [0x0009f] in <1dba3b49f2e844049096ff6b288f053c>:0
      129. Error: CustomAppManager_0 # 2022-02-22 08:42:25 #   at SIPSorcery.Media.AudioExtrasSource.SendMusicSample (System.Object state) [0x00021] in <1dba3b49f2e844049096ff6b288f053c>:0
      130. Error: CustomAppManager_0 # 2022-02-22 08:42:25 #   at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <a52c4a579f20475caf4d3806d4a56863>:0
      131. Error: CustomAppManager_0 # 2022-02-22 08:42:25 #   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <a52c4a579f20475caf4d3806d4a56863>:0
      132. Error: CustomAppManager_0 # 2022-02-22 08:42:25 #   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <a52c4a579f20475caf4d3806d4a56863>:0
      133. Error: CustomAppManager_0 # 2022-02-22 08:42:25 #   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <a52c4a579f20475caf4d3806d4a56863>:0

**Comment by neilsilver** [comment]
We have today mitigated by compiling a test version of the Lib with a Try/Catch in the 

SIPSorcery.Media.AudioExtrasSource.SendMusicSample() method.

This Exposes a null ref in this method.  The try Catch allows us to handle this error which running on the timer thread was causing a Fatal Exception on our environment.

We suspect that when the method is called the _musicStreamReader is Null.

We will do some more to try and find the root cause and try to solve with additional null check rather than a try catch and update.

**Comment by sipsorcery** [comment]
The PR linked just above should fix this issue.

The AudioExtrasSource class has gotten a bit out of control at this stage and should be re-written. It was originally intended to be a quick and dirty example of how to generate some audio streams but has since taken on a life of its own.
