### ISSUE TITLE
RTCRtpEncodingParameters.maxBitrate

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#702]
I might have missed this issue #346. But simply put, is there a way to set `RTCRtpEncodingParameters.maxBitrate` in `sipsorcery`?

**Comment by sipsorcery** [comment]
No, there's not.

The VP8 and H264 wrappers are prototypes at best and most parameters, including max bitrate, are left at the default for realtime streaming. If you want to dig deeper you can have a look [here](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/blob/85d11ec7c79b819f0ab76961327d2b5487ebbfdf/src/codecs/Vp8Codec.cs#L84) or [here](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/blob/f4aba3b8a706ceb7b9811f6b9c917398dd18a97e/src/Helper.cs#L9) dependng on which video lirbary you are using.

**Comment by tghanem** [comment]
So, you mean that it's a codec parameter not something controlled by `RTCPeerConnection`, right?

**Comment by sipsorcery** [comment]
Yes, needs to be set when you create teh FFmpegVideoEndPoint, or equivalent.
