### ISSUE TITLE
Several video tracks in a WebRTC communication

### ISSUE THREAD

**Issue by ChristopheI** [sipsorcery-org/sipsorcery#708]
Hi,

I would like to manage several video tracks in a WebRTC communication. I'm not the only who wants that #423 :)

I already successfully made some update to allow 2 video tracks and it's working fine: my use case was to allow the use of a webcam and a screen sharing in same time.  (see [Secondary_Video_Stream](https://github.com/ChristopheI/sipsorcery/tree/Secondary_Video_Stream))

But this was done more like using "a big hammer" than a real refactoring ... It's why I didn't made a PR.
Now I would like to do this more efficiently and allow it without limitations (not just 2 but as many as needed)

**So I'm looking for some hints / tips to implement it in a efficient way.** 

I described below what I think it's necessary to implement it (based on class/interface I have updated in my own Branch/Repository). 

Please don't hesitate if you think I'm doing badly.

**MediaStreamTrack:** (src/Net/RTP/MediaStremTrack.cs)
**SDP** (src/Net/SDP/SDP.cs)
**SDPAudioVideoMediaFormat** (src/Net/SDP/SDPAudioVideoMediaFormat.cs)
**SDPMediaAnnouncement** (src/Net/SDP/SDPMediaAnnouncement.cs)
**SDPType** (src/Net/SDP/SDPType.cs)

- Seems there is nothing to do these classes

**IMediaSession** (src/app/Media/IMediaSession.cs)

- SetMediaStreamStatus(): need to add Ssrc to specify which stream more specifically
- Is-it also necessary to add a way to list Video stream available ? see below comments about **SIPUserAgent**. If it's the case **VoIPMediaSession** and **AudioSendOnlyMediaSession** must also be changed 

**RTCPeerConnection** (src/Net/WebRTC/RTCPeerConnection.cs)

- **videoCapabilities**: Theorically each video track can have different capabilities - for simplification first video capabilities found will be used for all other tracks- Seems a correct assumption for a first release

**SecureContextCollection** (src/net/DtlSrtp/SecureContextCollection.cs)

- Need to create 2 secure Context Collection: one for audio and the other one for video. The collection for video will be based on Ssrc

**RTPSession** (src/Net/RTP/RTPSession.cs)

- **Main assumption:** Ssrc is use as UID to differentiate Video Stream
- **MediaStreamTrack VideoLocalTrack** must changed to **ConcurentDictionary<String, MediaStreamTrack> VideoLocalTracks** (by Ssrc)
- **MediaStreamTrack VideoRtcpSession** must changed to **ConcurentDictionary<String, RTCPSession> VideoRtcpSessions** (by Ssrc of the related VideoLocalTrack - is-it correct ?)
- **MediaStreamTrack VideoRemoteTrack** must changed to **ConcurentDictionary<String, MediaStreamTrack> VideoRemoteTracks** (by Ssrc)
- **IPEndPoint VideoDestinationEndPoint** must be changed to **ConcurentDictionary<String, IPEndPoint> VideoDestinationEndPoints**    
- **IPEndPoint VideoControlDestinationEndPoint** must be changed to **ConcurentDictionary<String, IPEndPoint> VideoControlDestinationEndPoints** 
- **RtpVideoFramer _rtpVideoFramer**  must changed to **ConcurentDictionary<String, RtpVideoFramer> _rtpVideoFramers** (by Ssrc)
- All code using one of the object listed previously
- **How I link a Local Track to its Remote Track ?**

**SIPUserAgent** (src/app/SIPUserAgents/SIPUserAgent.cs)

- I have no idea how to change this object. It's necessary to know the list of Video track in order to call to MediaSession.SetMediaStreamStatus(...) methods. How to know this ?
- Perhaps I need to enhance IMediaSession to offer a way to get list of Video Track for this ?

If you think to something else don't hesitate to tell me ! :)

**Comment by ChristopheI** [comment]
Update done on IMediaSession:
```
        /// <summary>
        /// Get the list of Ssrc of local video stream
        /// </summary>
        List<String> VideoLocalSsrcList { get; } // <= NEW

        /// <summary>
        /// Get the list of Ssrc of remote video stream
        /// </summary>
        List<String> VideoRemoteSsrcList { get; } // <= NEW

        /// <summary>
        /// Sets the stream status on all local audio or all local video media track.
        /// </summary>
        /// <param name="kind">The type of the media track. Must be audio or video.</param>
        /// <param name="status">The stream status for the media track.</param>
        void SetMediaStreamStatus(SDPMediaTypesEnum kind, MediaStreamStatusEnum status);  // <= Same as before but now change ALL LOCAL VIDEO if Video is used 

        /// <summary>
        /// Sets the stream status on local audio track.
        /// </summary>
        /// <param name="kind">The type of the media track. Must be audio or video.</param>
        /// <param name="status">The stream status for the media track.</param>
        void SetAudioMediaStreamStatus(MediaStreamStatusEnum status); // <= NEW

        /// <summary>
        /// Sets the stream status on local video track.
        /// </summary>
        /// <param name="Ssrc">Ssrc of the local video track</param>
        /// <param name="status">The stream status for the media track.</param>
        void SetVideoMediaStreamStatus(String Ssrc, MediaStreamStatusEnum status); // <= NEW
```

**Comment by sipsorcery** [comment]
It's been a while since I was down in the bowels fo WebRTC but I always had the idea that the hardest part of supporting multiple audio or video streams was going to be the SDP negotiation AND SDP re-negotiation. It's tempting to think that would be the easy part, since SDP is just the signalling and doesn't involve packetisation, codecs etc. Chrome, or more correctly libwebrtc, had a multi-year release cycle to swtich the SDP logic from PlanB to unified. For this task I'd be tempted to look at the SDP logic first and only then move onto the chanes required in the streaming classes, and your #711 PR will probably go a long way towards the non-SDP adjustements.

**Comment by rafcsoares** [comment]
yeah.. unified plan for SDP will be a huge improvement.

Today one of the biggest changes in unified plan is related to RemoveTrack feature.

in PlanB, when a track is removed from communication we need to remove it complely from SDP.

In unified plan we just need to change direction of the stream to inactive... so we never remove complely previous created streams

**Comment by alexdegroot** [comment]
@ChristopheI thanks for your reply.
Go nuts: Basically nothing happens. :)

There's no Audiostream upfront, so that's likely causing the challenge. I indeed don't start the renegotiation. I guess that's the part I'd assume the library to start automatically. Do you have any hint how I can manually trigger it?

**Comment by ChristopheI** [comment]
Ok I didn't know this expression: "Go nuts" 
I translated in my language like something "it's going totally crazy"

By renegociation I mean this: 

1. manage your tracks (audio and/or video) ( like you did in your snippet)
2. once done, create an SDP offer
3. send it to the remote peer
4. the remote peer will then create an SDP answer using the SDP offer
5. the remote peer send back to you the SDP answer
6. use the SDP answer

All this cannot be done in SIPSorcery because it's related to the signaling part which is specific (it' not included in WebRTC RFC)

You did already steps 2 -> 6 before your data channel between the 2 peers.

**Comment by alexdegroot** [comment]
Ah check. I guess that's the confusing and strong part of the entire signaling. Thanks!

**Comment by ChristopheI** [comment]
Now in master branch and since release v6.0.8 it's possible to have on the same PeerConnection several Audio stream and/or several Video stream.

To manage them you have access to this new objects / events:

- PeerConnection.AudioStreamList
- PeerConnection.VideoStreamList
- PeerConnection.OnAudioFormatsNegotiatedByIndex
- PeerConnection.OnVideoFormatsNegotiatedByIndex
- PeerConnection.OnVideoFrameReceivedByIndex
- PeerConnection.OnRtpPacketReceivedByIndex
- PeerConnection.OnRtpEventByIndex

**Comment by robcar** [comment]
Thanks @ChristopheI for the effort adding this functionality!

It would be very helpful if the examples could be updated with one or more examples showing this new functionality. 

I am struggling a bit trying to get my head around how to implement this myself.

I have a scenario where the SIPSorcery side is sending (only) multiple video streams/tracks to a web browser receiver but I can't get it to work properly I only get it to show one source (the first) in both streams.

Probably an example to refer to would help a lot in understanding where I am going wrong.

**Comment by rafcsoares** [comment]
@robcar its very simple... now everytime that you use

peerConnection.addTrack() internally it will generate a VideoStream or a AudioStream (that can be accessed by peerConnection.VideoStreamList and peerConnection.AudioStreamList...

Each stream contains the event that previously was present only on RTCPeerConnection (related to OnReceivePacket) 

and peerConnection now expose new events that also receive index of the streaming that received the packet.

To send packet to and specific stream use the specific instance of VideoStream

like.. peerConnection.VideoStreamList[0].SendH264Video(bytes)...

PS: im writing without access to source code.. wo ita just an idea how it works... ita very similar to native webrtc implementation of javascript 

PS2: every video stream contains one local track and on remote track... so it was implemented following UnifiedPlan SDP model.

**Comment by ChristopheI** [comment]
Very important to notice also that: 
When you add or remove a track you must negotiate with your peer a new SDP ! 
It's the only way for him to know that there is an update.

**Comment by robcar** [comment]
Thanks got it to work after some more work and your additional info.

**Comment by alexavator** [comment]
Hi there

I am trying to add second video stream. While I use 1 video stream everything work OK, but when I add second video stream (via addTrack and add info about this stream to SDP) nothing work anymore. I can`t get any video or sound from SIP. Also I captured wireshark dump, and there are video and audio in it. But sipsorcery give me nothing. 

Could anybody help me?
