### ISSUE TITLE
Can i call to standart phone number with sipsorcery?

### ISSUE THREAD

**Issue by serk1811** [sipsorcery-org/sipsorcery#709]
I want call to usual phone with SIM card. Is it pissible? And if it's can i use this library for ASP.Net web app?

I have a sip provider account with Domain, Username, Password. I'm try this example, but something wrong.(in code i hide login and pass)
`using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Serilog;
using Serilog.Extensions.Logging;
using SIPSorcery.Media;
using SIPSorcery.Net;
using SIPSorcery.SIP;
using SIPSorcery.SIP.App;
using SIPSorcery.Sys;
using SIPSorceryMedia.Abstractions;

using System;
using System.Threading.Tasks;
using Serilog;
using Serilog.Extensions.Logging;
using SIPSorcery.Media;
using SIPSorcery.SIP;
using SIPSorcery.SIP.App;
using SIPSorceryMedia.Abstractions;
using SIPSorceryMedia.Windows;

namespace demo
{

    struct SIPRegisterAccount
    {
        public string Username;
        public string Password;
        public string Domain;
        public int Expiry;

        public SIPRegisterAccount(string username, string password, string domain, int expiry)
        {
            Username = username;
            Password = password;
            Domain = domain;
            Expiry = expiry;
        }
    }

    struct SendSilenceJob
    {
        public Timer SendSilenceTimer;
        public SIPUserAgent UserAgent;

        public SendSilenceJob(Timer timer, SIPUserAgent ua)
        {
            SendSilenceTimer = timer;
            UserAgent = ua;
        }
    }

    class Program
    {
       //private static string DEFAULT_CALL_DESTINATION = "sip:*61@192.168.0.48";
        private static string DEFAULT_CALL_DESTINATION = "+79897237479@sip.zadarma.com;transport=tcp";
        private static string DEFAULT_TRANSFER_DESTINATION = "sip:*61@192.168.0.48";
        private static int SIP_LISTEN_PORT = 5060;
        private static int SIPS_LISTEN_PORT = 5061;
        private static string SIPS_CERTIFICATE_PATH = "localhost.pfx";

        private static Microsoft.Extensions.Logging.ILogger Log = NullLogger.Instance;

        /// <summary>
        /// The set of SIP accounts available for registering and/or authenticating calls.
        /// </summary>
        private static readonly List<SIPRegisterAccount> _sipAccounts = new List<SIPRegisterAccount>
        {
            new SIPRegisterAccount( "*******", "********", "sip.zadarma.com", 120)
        };

        private static SIPTransport _sipTransport;

        /// <summary>
        /// Keeps track of the current active calls. It includes both received and placed calls.
        /// </summary>
        private static ConcurrentDictionary<string, SIPUserAgent> _calls = new ConcurrentDictionary<string, SIPUserAgent>();

        /// <summary>
        /// Keeps track of the SIP account registrations.
        /// </summary>
        private static ConcurrentDictionary<string, SIPRegistrationUserAgent> _registrations = new ConcurrentDictionary<string, SIPRegistrationUserAgent>();

        static async Task Main()
        {
            Console.WriteLine("SIPSorcery SIP Call Server example.");
            Console.WriteLine("Press 'c' to place a call to the default destination.");
            Console.WriteLine("Press 'd' to send a random DTMF tone to the newest call.");
            Console.WriteLine("Press 'h' to hangup the oldest call.");
            Console.WriteLine("Press 'H' to hangup all calls.");
            Console.WriteLine("Press 'l' to list current calls.");
            Console.WriteLine("Press 'r' to list current registrations.");
            Console.WriteLine("Press 't' to transfer the newest call to the default destination.");
            Console.WriteLine("Press 'q' to quit.");

            Log = AddConsoleLogger();

            // Set up a default SIP transport.
            _sipTransport = new SIPTransport();
            _sipTransport.AddSIPChannel(new SIPUDPChannel(new IPEndPoint(IPAddress.Any, SIP_LISTEN_PORT)));
            _sipTransport.AddSIPChannel(new SIPUDPChannel(new IPEndPoint(IPAddress.IPv6Any, SIP_LISTEN_PORT)));
            _sipTransport.AddSIPChannel(new SIPTCPChannel(new IPEndPoint(IPAddress.Any, SIP_LISTEN_PORT)));
            var localhostCertificate = new X509Certificate2(SIPS_CERTIFICATE_PATH);
            _sipTransport.AddSIPChannel(new SIPTLSChannel(localhostCertificate, new IPEndPoint(IPAddress.Any, SIPS_LISTEN_PORT)));
            // If it's desired to listen on a single IP address use the equivalent of:
            //_sipTransport.AddSIPChannel(new SIPUDPChannel(new IPEndPoint(IPAddress.Parse("192.168.11.50"), SIP_LISTEN_PORT)));
            _sipTransport.EnableTraceLogs();

            _sipTransport.SIPTransportRequestReceived += OnRequest;

            // Uncomment to enable registrations.
            StartRegistrations(_sipTransport, _sipAccounts);

            CancellationTokenSource exitCts = new CancellationTokenSource();
            await Task.Run(() => OnKeyPress(exitCts.Token));

            Log.LogInformation("Exiting...");

            if (_sipTransport != null)
            {
                Log.LogInformation("Shutting down SIP transport...");
                _sipTransport.Shutdown();
            }
        }

        /// <summary>
        /// Process user key presses.
        /// </summary>
        /// <param name="exit">The cancellation token to set if the user requests to quit the application.</param>
        private static async Task OnKeyPress(CancellationToken exit)
        {
            try
            {
                while (!exit.WaitHandle.WaitOne(0))
                {
                    var keyProps = Console.ReadKey();

                    if (keyProps.KeyChar == 'c')
                    {
                        // Place an outgoing call.
                        var ua = new SIPUserAgent(_sipTransport, null);
                        ua.ClientCallTrying += (uac, resp) => Log.LogInformation($"{uac.CallDescriptor.To} Trying: {resp.StatusCode} {resp.ReasonPhrase}.");
                        ua.ClientCallRinging += (uac, resp) => Log.LogInformation($"{uac.CallDescriptor.To} Ringing: {resp.StatusCode} {resp.ReasonPhrase}.");
                        ua.ClientCallFailed += (uac, err, resp) => Log.LogWarning($"{uac.CallDescriptor.To} Failed: {err}, Status code: {resp?.StatusCode}");
                        ua.ClientCallAnswered += (uac, resp) => Log.LogInformation($"{uac.CallDescriptor.To} Answered: {resp.StatusCode} {resp.ReasonPhrase}.");
                        ua.OnDtmfTone += (key, duration) => OnDtmfTone(ua, key, duration);
                        ua.OnRtpEvent += (evt, hdr) => Log.LogDebug($"rtp event {evt.EventID}, duration {evt.Duration}, end of event {evt.EndOfEvent}, timestamp {hdr.Timestamp}, marker {hdr.MarkerBit}.");
                        ua.OnCallHungup += OnHangup;

                        var rtpSession = CreateRtpSession(ua, null);
                        var callResult = await ua.Call(DEFAULT_CALL_DESTINATION, null, null, rtpSession);

                        if (callResult)
                        {
                            await rtpSession.Start();
                            _calls.TryAdd(ua.Dialogue.CallId, ua);
                        }
                    }
                    else if (keyProps.KeyChar == 'd')
                    {
                        if (_calls.Count == 0)
                        {
                            Log.LogWarning("There are no active calls.");
                        }
                        else
                        {
                            var newestCall = _calls.OrderByDescending(x => x.Value.Dialogue.Inserted).First();
                            byte randomDtmf = (byte)Crypto.GetRandomInt(0, 15);
                            Log.LogInformation($"Sending DTMF {randomDtmf} to {newestCall.Key}.");
                            await newestCall.Value.SendDtmf(randomDtmf);
                        }
                    }
                    else if (keyProps.KeyChar == 'h')
                    {
                        if (_calls.Count == 0)
                        {
                            Log.LogWarning("There are no active calls.");
                        }
                        else
                        {
                            var oldestCall = _calls.OrderBy(x => x.Value.Dialogue.Inserted).First();
                            Log.LogInformation($"Hanging up call {oldestCall.Key}.");
                            oldestCall.Value.OnCallHungup -= OnHangup;
                            oldestCall.Value.Hangup();
                            _calls.TryRemove(oldestCall.Key, out _);
                        }
                    }
                    else if (keyProps.KeyChar == 'H')
                    {
                        if (_calls.Count == 0)
                        {
                            Log.LogWarning("There are no active calls.");
                        }
                        else
                        {
                            foreach (var call in _calls)
                            {
                                Log.LogInformation($"Hanging up call {call.Key}.");
                                call.Value.OnCallHungup -= OnHangup;
                                call.Value.Hangup();
                            }
                            _calls.Clear();
                        }
                    }
                    else if (keyProps.KeyChar == 'l')
                    {
                        if (_calls.Count == 0)
                        {
                            Log.LogInformation("There are no active calls.");
                        }
                        else
                        {
                            Log.LogInformation("Current call list:");
                            foreach (var call in _calls)
                            {
                                int duration = Convert.ToInt32(DateTimeOffset.Now.Subtract(call.Value.Dialogue.Inserted).TotalSeconds);
                                uint rtpSent = (call.Value.MediaSession as VoIPMediaSession).AudioRtcpSession.PacketsSentCount;
                                uint rtpRecv = (call.Value.MediaSession as VoIPMediaSession).AudioRtcpSession.PacketsReceivedCount;
                                Log.LogInformation($"{call.Key}: {call.Value.Dialogue.RemoteTarget} {duration}s {rtpSent}/{rtpRecv}");
                            }
                        }
                    }
                    else if (keyProps.KeyChar == 'r')
                    {
                        if (_registrations.Count == 0)
                        {
                            Log.LogInformation("There are no active registrations.");
                        }
                        else
                        {
                            Log.LogInformation("Current registration list:");
                            foreach (var registration in _registrations)
                            {
                                Log.LogInformation($"{registration.Key}: is registered {registration.Value.IsRegistered}, last attempt at {registration.Value.LastRegisterAttemptAt}");
                            }
                        }
                    }
                    else if (keyProps.KeyChar == 't')
                    {
                        if (_calls.Count == 0)
                        {
                            Log.LogWarning("There are no active calls.");
                        }
                        else
                        {
                            var newestCall = _calls.OrderByDescending(x => x.Value.Dialogue.Inserted).First();
                            Log.LogInformation($"Transferring call {newestCall.Key} to {DEFAULT_TRANSFER_DESTINATION}.");
                            bool transferResult = await newestCall.Value.BlindTransfer(SIPURI.ParseSIPURI(DEFAULT_TRANSFER_DESTINATION), TimeSpan.FromSeconds(3), exit);

                            if (transferResult)
                            {
                                Log.LogInformation($"Transferring succeeded.");

                                // The remote party will often put us on hold after the transfer.
                                await Task.Delay(1000);

                                newestCall.Value.OnCallHungup -= OnHangup;
                                newestCall.Value.Hangup();
                                _calls.TryRemove(newestCall.Key, out _);
                            }
                            else
                            {
                                Log.LogWarning($"Transfer attempt failed.");
                            }
                        }
                    }
                    else if (keyProps.KeyChar == 'q')
                    {
                        // Quit application.
                        Log.LogInformation("Quitting");
                        break;
                    }
                }
            }
            catch (Exception excp)
            {
                Log.LogError($"Exception OnKeyPress. {excp.Message}.");
            }
        }

        /// <summary>
        /// Example of how to create a basic RTP session object and hook up the event handlers.
        /// </summary>
        /// <param name="ua">The user agent the RTP session is being created for.</param>
        /// <param name="dst">THe destination specified on an incoming call. Can be used to
        /// set the audio source.</param>
        /// <returns>A new RTP session object.</returns>
        private static VoIPMediaSession CreateRtpSession(SIPUserAgent ua, string dst)
        {
            List<AudioCodecsEnum> codecs = new List<AudioCodecsEnum> { AudioCodecsEnum.PCMU, AudioCodecsEnum.PCMA, AudioCodecsEnum.G722 };

            var audioSource = AudioSourcesEnum.SineWave;
            if (string.IsNullOrEmpty(dst) || !Enum.TryParse(dst, out audioSource))
            {
                audioSource = AudioSourcesEnum.Music;
            }

            Log.LogInformation($"RTP audio session source set to {audioSource}.");

            AudioExtrasSource audioExtrasSource = new AudioExtrasSource(new AudioEncoder(), new AudioSourceOptions { AudioSource = audioSource });
            audioExtrasSource.RestrictFormats(formats => codecs.Contains(formats.Codec));
            var rtpAudioSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = audioExtrasSource });
            rtpAudioSession.AcceptRtpFromAny = true;

            // Wire up the event handler for RTP packets received from the remote party.
            rtpAudioSession.OnRtpPacketReceived += (ep, type, rtp) => OnRtpPacketReceived(ua, type, rtp);
            rtpAudioSession.OnTimeout += (mediaType) =>
            {
                if (ua?.Dialogue != null)
                {
                    Log.LogWarning($"RTP timeout on call with {ua.Dialogue.RemoteTarget}, hanging up.");
                }
                else
                {
                    Log.LogWarning($"RTP timeout on incomplete call, closing RTP session.");
                }

                ua.Hangup();
            };

            return rtpAudioSession;
        }

        /// <summary>
        /// Event handler for receiving RTP packets.
        /// </summary>
        /// <param name="ua">The SIP user agent associated with the RTP session.</param>
        /// <param name="type">The media type of the RTP packet (audio or video).</param>
        /// <param name="rtpPacket">The RTP packet received from the remote party.</param>
        private static void OnRtpPacketReceived(SIPUserAgent ua, SDPMediaTypesEnum type, RTPPacket rtpPacket)
        {
            // The raw audio data is available in rtpPacket.Payload.
        }

        /// <summary>
        /// Event handler for receiving a DTMF tone.
        /// </summary>
        /// <param name="ua">The user agent that received the DTMF tone.</param>
        /// <param name="key">The DTMF tone.</param>
        /// <param name="duration">The duration in milliseconds of the tone.</param>
        private static void OnDtmfTone(SIPUserAgent ua, byte key, int duration)
        {
            string callID = ua.Dialogue.CallId;
            Log.LogInformation($"Call {callID} received DTMF tone {key}, duration {duration}ms.");
        }

        /// <summary>
        /// Because this is a server user agent the SIP transport must start listening for client user agents.
        /// </summary>
        private static async Task OnRequest(SIPEndPoint localSIPEndPoint, SIPEndPoint remoteEndPoint, SIPRequest sipRequest)
        {
            try
            {
                if (sipRequest.Header.From != null &&
                sipRequest.Header.From.FromTag != null &&
                sipRequest.Header.To != null &&
                sipRequest.Header.To.ToTag != null)
                {
                    // This is an in-dialog request that will be handled directly by a user agent instance.
                }
                else if (sipRequest.Method == SIPMethodsEnum.INVITE)
                {
                    Log.LogInformation($"Incoming call request: {localSIPEndPoint}<-{remoteEndPoint} {sipRequest.URI}.");

                    SIPUserAgent ua = new SIPUserAgent(_sipTransport, null);
                    ua.OnCallHungup += OnHangup;
                    ua.ServerCallCancelled += (uass) => Log.LogDebug("Incoming call cancelled by remote party.");
                    ua.OnDtmfTone += (key, duration) => OnDtmfTone(ua, key, duration);
                    ua.OnRtpEvent += (evt, hdr) => Log.LogDebug($"rtp event {evt.EventID}, duration {evt.Duration}, end of event {evt.EndOfEvent}, timestamp {hdr.Timestamp}, marker {hdr.MarkerBit}.");
                    //ua.OnTransactionTraceMessage += (tx, msg) => Log.LogDebug($"uas tx {tx.TransactionId}: {msg}");
                    ua.ServerCallRingTimeout += (uasss) =>
                    {
                        Log.LogWarning($"Incoming call timed out in {uasss.ClientTransaction.TransactionState} state waiting for client ACK, terminating.");
                        ua.Hangup();
                    };

                    var uas = ua.AcceptCall(sipRequest);
                    var rtpSession = CreateRtpSession(ua, sipRequest.URI.User);

                    // Insert a brief delay to allow testing of the "Ringing" progress response.
                    // Without the delay the call gets answered before it can be sent.
                    await Task.Delay(500);

                    await ua.Answer(uas, rtpSession);

                    if (ua.IsCallActive)
                    {
                        await rtpSession.Start();
                        _calls.TryAdd(ua.Dialogue.CallId, ua);
                    }
                }
                else if (sipRequest.Method == SIPMethodsEnum.BYE)
                {
                    SIPResponse byeResponse = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.CallLegTransactionDoesNotExist, null);
                    await _sipTransport.SendResponseAsync(byeResponse);
                }
                else if (sipRequest.Method == SIPMethodsEnum.SUBSCRIBE)
                {
                    SIPResponse notAllowededResponse = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.MethodNotAllowed, null);
                    await _sipTransport.SendResponseAsync(notAllowededResponse);
                }
                else if (sipRequest.Method == SIPMethodsEnum.OPTIONS || sipRequest.Method == SIPMethodsEnum.REGISTER)
                {
                    SIPResponse optionsResponse = SIPResponse.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Ok, null);
                    await _sipTransport.SendResponseAsync(optionsResponse);
                }
            }
            catch (Exception reqExcp)
            {
                Log.LogWarning($"Exception handling {sipRequest.Method}. {reqExcp.Message}");
            }
        }

        /// <summary>
        /// Remove call from the active calls list.
        /// </summary>
        /// <param name="dialogue">The dialogue that was hungup.</param>
        private static void OnHangup(SIPDialogue dialogue)
        {
            if (dialogue != null)
            {
                string callID = dialogue.CallId;
                if (_calls.ContainsKey(callID))
                {
                    if (_calls.TryRemove(callID, out var ua))
                    {
                        // This app only uses each SIP user agent once so here the agent is 
                        // explicitly closed to prevent is responding to any new SIP requests.
                        ua.Close();
                    }
                }
            }
        }

        /// <summary>
        /// Starts a registration agent for each of the supplied SIP accounts.
        /// </summary>
        /// <param name="sipTransport">The SIP transport to use for the registrations.</param>
        /// <param name="sipAccounts">The list of SIP accounts to create a registration for.</param>
        private static void StartRegistrations(SIPTransport sipTransport, List<SIPRegisterAccount> sipAccounts)
        {
            foreach (var sipAccount in sipAccounts)
            {
                var regUserAgent = new SIPRegistrationUserAgent(sipTransport, sipAccount.Username, sipAccount.Password, sipAccount.Domain, sipAccount.Expiry);

                // Event handlers for the different stages of the registration.
                regUserAgent.RegistrationFailed += (uri, err) => Log.LogError($"{uri.ToString()}: {err}");
                regUserAgent.RegistrationTemporaryFailure += (uri, msg) => Log.LogWarning($"{uri.ToString()}: {msg}");
                regUserAgent.RegistrationRemoved += (uri) => Log.LogError($"{uri.ToString()} registration failed.");
                regUserAgent.RegistrationSuccessful += (uri) => Log.LogInformation($"{uri.ToString()} registration succeeded.");

                // Start the thread to perform the initial registration and then periodically resend it.
                regUserAgent.Start();

                _registrations.TryAdd($"{sipAccount.Username}@{sipAccount.Domain}", regUserAgent);
            }
        }

        /// <summary>
        /// Adds a console logger. Can be omitted if internal SIPSorcery debug and warning messages are not required.
        /// </summary>
        private static Microsoft.Extensions.Logging.ILogger AddConsoleLogger()
        {
            var serilogLogger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Is(Serilog.Events.LogEventLevel.Debug)
                .WriteTo.Console()
                .CreateLogger();
            var factory = new SerilogLoggerFactory(serilogLogger);
            SIPSorcery.LogFactory.Set(factory);
            return factory.CreateLogger<Program>();
        }
    }
}`

I get this: `SIPSorcery SIP Call Server example.
Press 'c' to place a call to the default destination.
Press 'd' to send a random DTMF tone to the newest call.
Press 'h' to hangup the oldest call.
Press 'H' to hangup all calls.
Press 'l' to list current calls.
Press 'r' to list current registrations.
Press 't' to transfer the newest call to the default destination.
Press 'q' to quit.
[01:03:51 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on 0.0.0.0:5060.
[01:03:51 DBG] CreateBoundUdpSocket successfully bound on 0.0.0.0:5060.
[01:03:51 INF] SIP UDP Channel created for udp:0.0.0.0:5060.
[01:03:51 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:5060.
[01:03:51 DBG] CreateBoundUdpSocket successfully bound on [::]:5060, dual mode False.
[01:03:51 INF] SIP UDP Channel created for udp:[::]:5060.
[01:03:51 INF] SIP TCP Channel created for tcp:0.0.0.0:5060.
[01:03:51 DBG] SIP TCP Channel socket on tcp:0.0.0.0:5060 accept connections thread started.
[01:03:51 INF] SIP TLS Channel created for tls:0.0.0.0:5061.
[01:03:51 DBG] SIP TLS Channel socket on tls:0.0.0.0:5061 accept connections thread started.
[01:03:51 INF] SIP TLS Channel ready for tls:0.0.0.0:5061 and certificate CN=localhost.
[01:03:51 DBG] Starting SIPRegistrationUserAgent for sip:916220@sip.zadarma.com, callback period 115s.
[01:03:51 DBG] Starting registration for sip:916220@sip.zadarma.com.
[01:03:51 DBG] SIP DNS SRV for sip:sip.zadarma.com resolved to sipms1.zadarma.com. and port 5060.
[01:03:51 DBG] Initiating registration to sip.zadarma.com at udp:37.139.38.15:5060 for sip:916220@sip.zadarma.com.
[01:03:51 DBG] Request sent: udp:192.168.0.249:5060->udp:37.139.38.15:5060 REGISTER sip:sip.zadarma.com SIP/2.0
[01:03:51 DBG] Response received: udp:0.0.0.0:5060<-udp:37.139.38.15:5060 REGISTER 401 Unauthorized
[01:03:51 DBG] Server response Unauthorised received for sip:916220@sip.zadarma.com.
[01:03:51 DBG] SIP DNS SRV for sip:sip.zadarma.com resolved to sipms1.zadarma.com. and port 5060.
[01:03:51 DBG] Request sent: udp:192.168.0.249:5060->udp:37.139.38.15:5060 REGISTER sip:sip.zadarma.com SIP/2.0
[01:03:51 DBG] Response received: udp:0.0.0.0:5060<-udp:37.139.38.15:5060 REGISTER 200 OK
[01:03:51 DBG] Server auth response Ok received for sip:916220@sip.zadarma.com.
[01:03:51 INF] sip:916220@sip.zadarma.com registration succeeded.
[01:03:51 DBG] SIPRegistrationUserAgent was successful, scheduling next registration to sip:916220@sip.zadarma.com in 115s.
c[01:03:52 INF] RTP audio session source set to Music.
[01:03:52 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[01:03:52 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
[01:03:52 DBG] CreateBoundUdpSocket even port required, closing socket on [::]:61877 and retrying on 61878.
[01:03:52 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:61879.
[01:03:52 DBG] CreateBoundUdpSocket successfully bound on [::]:61879, dual mode True.
[01:03:52 DBG] Successfully bound RTP socket [::]:61878 (dual mode True) and control socket [::]:61879 (dual mode True).
[01:03:52 DBG] RTPChannel for [::]:61878 started.
[01:03:52 DBG] SIPClientUserAgent attempting to resolve sip.zadarma.com.
[01:03:52 DBG] SIP DNS SRV for sip:+79897237479@sip.zadarma.com;transport=tcp resolved to sipms2.zadarma.com. and port 5060.
[01:03:52 DBG] SIPClientUserAgent resolved sip.zadarma.com to tcp:37.139.38.17:5060 in 9,99ms.
[01:03:52 DBG] UAC commencing call to sip:+79897237479@sip.zadarma.com:5060.
[01:03:52 DBG] Request sent: tcp:192.168.0.249:5060->tcp:37.139.38.17:5060 INVITE sip:+79897237479@sip.zadarma.com;transport=tcp SIP/2.0
[01:03:52 DBG] ConnectClientAsync SIP TCP Channel local end point of tcp:0.0.0.0:5060 selected for connection to 37.139.38.17:5060.
[01:03:52 DBG] Attempting TCP connection from tcp:0.0.0.0:5060 to 37.139.38.17:5060.
[01:03:53 DBG] ConnectAsync SIP TCP Channel connect completed result for tcp:0.0.0.0:5060->37.139.38.17:5060 Success.
[01:03:53 DBG] Response received: tcp:192.168.0.249:5060<-tcp:37.139.38.17:5060 INVITE 407 Proxy Authentication Required
[01:03:53 DBG] Request sent: tcp:192.168.0.249:5060->tcp:37.139.38.17:5060 ACK sip:+79897237479@sip.zadarma.com;transport=tcp SIP/2.0
[01:03:53 DBG] Response 407 Proxy Authentication Required for sip:+79897237479@sip.zadarma.com;transport=tcp.
[01:03:53 DBG] Forward leg failed, authentication was requested but no credentials were available.
[01:03:53 WRN] Call attempt to sip:+79897237479@sip.zadarma.com;transport=tcp failed with Authentication requested when no credentials available.
[01:03:53 WRN] sip:+79897237479@sip.zadarma.com:5060 Failed: Authentication requested when no credentials available, Status code: 407`

**Comment by serk1811** [comment]
Ohhh, thx a lot. I'm a new one in this tech. What about phonecalls with using ASP.net?

**Comment by sipsorcery** [comment]
> Ohhh, thx a lot. I'm a new one in this tech. What about phonecalls with using ASP.net?

I'm not sure what you mean. You can use a ASP.NET as a signalling server to manage call set up, an example is [signalrtc](https://github.com/sipsorcery-org/signalrtc). Using ASP.NET as a call end point to send or receive media is not really something it's designed for.
