### ISSUE TITLE
RtpVideoFramer MAX_FRAME_SIZE Constant

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#716]
In the `RtpVideoFramer ` class, there is a limit for the maximum frame size set to 64KB (or 65536). Is there any specific reason why this is the case?

The reason I'm asking is that I am encoding screen capture using VP8 and it's producing keyframes that are larger than 65536 bytes. As a result, the keyframe is being dropped, and the following RTPPackets, until the next keyframe, are all dropped. Therefore, I'm getting cuts in the video.

I have increased this limit to 1MB though and didn't notice any side effects. So, where does this limit come from and what are the side effects of increasing it?

**Comment by tghanem** [comment]
> Feel free to submit a PR bumping up the limt.

Sure, I'll be more than happy to do that.

I was also curious about a reference in the comments to [RFC 7741](https://tools.ietf.org/html/rfc7741#section-4.4). The RFC mentions a parameter for the VP8 decoder called `max-fs` (or maximum frame size). I was wondering instead of making it a constant, it should rather be negotiated through SDP. Am I thinking correctly or `max-fs` is something else?

**Comment by sipsorcery** [comment]
> I was also curious about a reference in the comments to [RFC 7741](https://tools.ietf.org/html/rfc7741#section-4.4). The RFC mentions a parameter for the VP8 decoder called max-fs (or maximum frame size). I was wondering instead of making it a constant, it should rather be negotiated through SDP. Am I thinking correctly or max-fs is something else?

I'd say your thinking is correct. Here's an example of that parameter being set in one of the unit tests containing a [FireFox SDP payload](https://github.com/sipsorcery-org/sipsorcery/blob/84f0673054abee907dd39d8d92d8017bdd717861/test/unit/net/SDP/SDPUnitTests.cs#L1192).

The parameter is being set by the receiver, the party decoding the video, though, so I'm not sure if there's much room for negotiation. It would help to ~~tell~~ ask the sender not to transmit raw frames that exceed the `w x h > sqrt(max-fs * 8)`. I can't think of any reason not to do that.

**Comment by tghanem** [comment]
For now, it was fixed by adding support to configure the maximum frame size.
