### ISSUE TITLE
Never ever call "Receive" again,when an exception threw in m_udpSocket.BeginReceiveFrom,file of "SIPUDPChannel.cs"

### ISSUE THREAD

**Issue by wonderlive-c** [sipsorcery-org/sipsorcery#719]
I found the comments is inaccurate,"the BeginReceiveMessageFrom will only throw if there is an problem with the arguments or the socket has been disposed of".When receive icmp destination port unreachable,it can cause an SocketException,this mean remote host does not listen on its port. But this is not local socket problem,we should not exit the Receive thread.

```
private void Receive()
        {
            try
            {
                EndPoint recvEndPoint = (ListeningIPAddress.AddressFamily == AddressFamily.InterNetwork) ? new IPEndPoint(IPAddress.Any, 0) : new IPEndPoint(IPAddress.IPv6Any, 0);
                m_udpSocket.BeginReceiveFrom(m_recvBuffer, 0, m_recvBuffer.Length, SocketFlags.None, ref recvEndPoint, EndReceiveFrom, null);
            }
            catch (ObjectDisposedException) { } // Thrown when socket is closed. Can be safely ignored.
            catch (Exception excp)
            {
                // From https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3056
                // the BeginReceiveMessageFrom will only throw if there is an problem with the arguments or the socket has been disposed of. In that
                // case the socket can be considered to be unusable and there's no point trying another receive.
                logger.LogError($"Exception Receive. {excp.Message}");
                logger.LogDebug($"SIPUDPChannel socket on {ListeningEndPoint} listening halted.");
                Closed = true;
            }
        }
```

please fix it. 
Here is my code, I just call "EndReceiveFrom" again when catch a SocketException, is there a better way?

```

private void Receive()
        {
            try
            {
                EndPoint recvEndPoint = (ListeningIPAddress.AddressFamily == AddressFamily.InterNetwork) ? new IPEndPoint(IPAddress.Any, 0) : new IPEndPoint(IPAddress.IPv6Any, 0);
                m_udpSocket.BeginReceiveFrom(m_recvBuffer, 0, m_recvBuffer.Length, SocketFlags.None, ref recvEndPoint, EndReceiveFrom, null);
            }
            catch (ObjectDisposedException) { } // Thrown when socket is closed. Can be safely ignored.

            catch (SocketException socketException)
            {
                //ignored.
                logger.LogError(socketException, $"SocketException Receive. {socketException.Message}");
                EndReceiveFrom(null);
            }
            catch (Exception excp) when(excp is ArgumentException || excp is ArgumentNullException || excp is ArgumentOutOfRangeException || excp is InvalidOperationException)
            {
                // From https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3056
                // the BeginReceiveMessageFrom will only throw if there is an problem with the arguments or the socket has been disposed of. In that
                // case the socket can be considered to be unusable and there's no point trying another receive.
                logger.LogError($"Exception Receive. {excp.Message}");
                logger.LogDebug($"SIPUDPChannel socket on {ListeningEndPoint} listening halted.");
                Closed = true;
            }
        }

```

**Comment by sipsorcery** [comment]
Probably related to #715. Seems the socket logic has been changed fairly substantially in .NET6 and there's some work to do this library to adjust to it.

**Comment by wonderlive-c** [comment]
> Probably related to #715. Seems the socket logic has been changed fairly substantially in .NET6 and there's some work to do this library to adjust to it.

I am using .Net5 framework，and I'v tried .NetCore3.1, Same situation.

**Comment by sipsorcery** [comment]
The socket logic has changed from when this class was written.

Previous: https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3262

Now: https://github.com/dotnet/runtime/blob/e99fb185aa10ef177d19a51fd77b7a4b75db5395/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L2460

At the time it was written I spent a lot of time trying to work out the proper way to deal with ICMP packets with UDP sockets. One issue is #150 but there was more to it than that.

Coupled with this issue and #715 there is a chunk of work to do to update both the [RTPChannel](https://github.com/sipsorcery-org/sipsorcery/blob/08499b60208ff40cff8ba97083ff25baac03bea8/src/net/RTP/RTPChannel.cs#L80) and [SIPUDPChannel](https://github.com/sipsorcery-org/sipsorcery/blob/08499b60208ff40cff8ba97083ff25baac03bea8/src/core/SIP/Channels/SIPUDPChannel.cs#L108).

> please fix it.

If only it was as easy as writing those words.
