### ISSUE TITLE
Janus Audio Bridge with SipSorcery

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#721]
Hi,
I am trying to build a test app with SipSorcery lib and Janus Audio Bridge. Steps are
Step 01. Creating Session
Step 02. Attching "janus.plugin.audiobridge"
Step 03. Sending Join message
Step 04: In Joined event,
A. Creating PeerConnection
B. Initializing Audio Capture Device
C. Sending configure Message with sdp

Step 05: Receiving "ok" message with sdp where I found "a=inactive"

Question: why getting "a=inactive"

SipSorcery creating offer as follows:
Offer
v=0
o=- 64107 0 IN IP4 127.0.0.1
s=sipsorcery
t=0 0
a=group:BUNDLE 1
m=audio 9 UDP/TLS/RTP/SAVP 0 8 9 101
c=IN IP4 0.0.0.0
a=ice-ufrag:UPNG
a=ice-pwd:KQFFNLTTMZUYHVZXEUATEFSH
a=fingerprint:sha-256 AD:AC:1A:14:3D:06:7D:A6:B2:7F:80:4B:35:EB:EB:B3:DC:0E:1F:24:92:29:C2:9F:92:27:BA:DD:51:DB:C1:C9
a=setup:actpass
a=candidate:2506 1 udp 659136 192.168.204.140 54416 typ host generation 0
a=ice-options:ice2,trickle
a=mid:1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=end-of-candidates
a=sendrecv
a=ssrc:639235144 cname:5fa3166c-ab3b-43a0-be17-aac9055a4bb7

Based on above offer, Janus is returning following answer

answer
v=0
o=- 1649843033592680 1 IN IP4 54.163.154.72
s=AudioBridge 9900
t=0 0
a=group:BUNDLE
a=ice-options:trickle
a=fingerprint:sha-256 09:E0:26:0C:FA:0D:EA:DA:70:39:97:39:60:E1:CD:68:27:9E:48:13:78:09:34:47:76:93:09:2F:B5:45:4A:26
a=msid-semantic: WMS janus
m=audio 0 UDP/TLS/RTP/SAVP 0
c=IN IP4 54.163.154.72
a=inactive
a=mid:1

After that nothing happening.

BTW: It is working with Microsoft.MixedReality.WebRTC lib.

**Comment by rafcsoares** [comment]
You must understand which plugin janus support.

Almost all SFU servers in marketing support OPUS as default audio plugin.

OpenVidu and Kurento support PCMU or OPUS.

SipSorcery does not have any implementation for OPUS but you can simple integrate it using another got repository like..

https://github.com/lostromb/concentus

you can take a look in my comment on another issue explaining how to do it

https://github.com/sipsorcery-org/sipsorcery/issues/518#issuecomment-888639894

**Comment by mail2mhossain** [comment]
Alternate Solution:
1. By default AudioBridge supports "Opus"
2. If we want to offer G.711 and G.722, then we need to add codec: "pcmu" or codec: "pcma" to join request.

**Comment by rafcsoares** [comment]
I will close, as it seems solved.
