### ISSUE TITLE
Dtls RTCCertificate Handling

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#723]
So, I was trying to provide the `RTCPeerConnection` class an `RTCCertificate` to be used for the Dtls handshake because the default behavior is to create a self-signed certificate which consumes around 700 ms (on average) which in my case is a little problematic because I'm opening many connections and it takes a while for the session to be fully connected waiting for all `RTCPeerConnection` instances to fire up.

I tried providing an `X509Certificate2` instance from the local store (and also a PFX) and I was careful to make sure that the private key is exportable and the library was failing with an exception that says

> CryptographicException: The requested operation is not supported

inside a class called `DtlsUtils` (line 290) which after more digging I found that it calls into BouncyCastle's `DotNetUtilities` class (line 100) which calls `RSA.ExportParameters(true)` method.

With a little more research, I have found that `ExportParameters(true)` is not always guaranteed to work depending on whether the key is a CAPI or Cng key (see this [CngKey.Export The requested operation is not supported [Windows]](https://github.com/dotnet/runtime/issues/26031)).

So, any ideas on how to fix this issue? And where should the fix go, sipsorcery or BouncyCastle?

**Comment by rafcsoares** [comment]
Try create a self signed certificate outside RTCPeerConnection and cache the value in a static variable.

After that.. use same certificate in all calls passing parameter to config parameter of PeerConnection

**Comment by tghanem** [comment]
@rafcsoares This does not actually solve the problem because the `RTCCertificate` class depends on `X509Certificate2` which ultimately will receive a call to `ExportParameters` and the error will occur.

My suggestion is rather to make `RTCCertificate` depend directly on the `Certificate`  and `AsymmetricKeyParameter` classes from BouncyCastle. The reasoning behind that is since `sipsorcery` needs the private key parameters to work, then having it behind `X509Certificate2` actually adds more complexity.

So, I would redefine `RTCCertificate` to look like the following:

```csharp
public class RTCCertificate
{
    public long expires
    {
        get
        {
            if (Certificate == null)
            {
                return 0;
            }
            else
            {
                return Certificate.NotAfter.GetEpoch();
            }
        }
    }

    public X509Certificate2 Certificate; //<--Removed

    public Certificate Certificate; //<-- Added

    public AsymmetricKeyParameter PrivateKey; //<-- Added

    public List<RTCDtlsFingerprint> getFingerprints()
    {
        return new List<RTCDtlsFingerprint> { DtlsUtils.Fingerprint(Certificate) };
    }
}
```

@sipsorcery - can you please comment on this?

**Comment by sipsorcery** [comment]
@tghanem sorry for taking so long to reply.

I'd be happy to go with any approach that works. It took a lot of work from @rafcsoares to be able to get DTLS working without a native library in the first place and since then there have been some more tweaks required to keep it working when the underlying dotnet crypto API's were changed.

If you put the suggested change into a PR I can review and test.

**Comment by tghanem** [comment]
Done. Please check #734.
