### ISSUE TITLE
Exception at voipMediaSession Creation

### ISSUE THREAD

**Issue by TyberiousG** [sipsorcery-org/sipsorcery#724]
`System.TypeLoadException: 'Method 'add_OnVideoSourceRawSampleFaster' in type 'SIPSorcery.Media.VideoTestPatternSource' from assembly 'SIPSorcery, Version=6.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
`

**Comment by ChristopheI** [comment]
Hi @TyberiousG ,

Could you describe a little more ?
Are you using the master branch of SIPSorcery ? 
Which dependencies are you using in your project ?

**Comment by easycaller-edossantos** [comment]
I'm having the same issue when creating the VoIPMediaSession:
`            var rtpAudioSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = audioExtrasSource })
            {
                AcceptRtpFromAny = true
            };
`

Using the following references:
    <PackageReference Include="SIPSorcery" Version="6.0.6" />
    <PackageReference Include="SIPSorceryMedia.Abstractions" Version="1.2.0" />

When downgrading SIPSorceryMedia.Abstractions to version 1.1.0, the issue doesn't happen anymore.

**Comment by TyberiousG** [comment]
> 

I'm using the latest release via Nuget, along with all the required dependencies.

**Comment by ChristopheI** [comment]
**SIPSorceryMedia.Abstractions v1.2.0** can only be used if the master branch of **SIPSorcery** is used.

For the moment, there is no **Nuget package** of **SIPSorcery** using **SIPSorceryMedia.Abstractions v1.2.0**

@sipsorcery ,
Perhaps it will be easier to create a new Nuget package (v6.0.7 ?) of SIPSorcery using last commit of the master branch

**Comment by sipsorcery** [comment]
> @sipsorcery , Perhaps it will be easier to create a new Nuget package (v6.0.7 ?) of SIPSorcery using last commit of the master branch

Done https://www.nuget.org/packages/SIPSorcery/6.0.7

**Comment by sipsorcery** [comment]
Feel free to re-open if problem still exists.
