### ISSUE TITLE
SIPUserAgent.Call overrides SDP

### ISSUE THREAD

**Issue by easycaller-edossantos** [sipsorcery-org/sipsorcery#729]
I'm using the following method from the SIPUserAgent class to start a call:
Call(SIPCallDescriptor callDescriptor, IMediaSession mediaSession, int ringTimeout = 0)

When invoking this, I'm passing SIPCallDescriptor which already specifies the SDP ContentType and SDP Content. However, my "custom" SDP is ignored, and a new SDP offer is created inside the method "InitiateCallAsync".

I think this method "InitiateCallAsync" should check if "m_callDescriptor.Content" is null, and only in that case override it with a new SDP offer.

**Comment by sipsorcery** [comment]
I've committed a fix for this. Do note that it's pretty tricky to create a custom SDP that will work with any audio/video devices/codecs you're intending to use.
