### ISSUE TITLE
Response was truncated and UseTcpFallback is disabled, unable to resolve the question

### ISSUE THREAD

**Issue by mikhaylo1** [sipsorcery-org/sipsorcery#732]
Not able to gather Ice responses from some TURN servers. Getting the error here:
![image](https://user-images.githubusercontent.com/18460856/169034785-7b648203-f9f4-4d01-a3b5-d2cb205d7736.png)

Everything works correct if I set UseTcpFallback=true as suggested in the error message 

Any particular reason disabling UseTcpFallback here https://github.com/sipsorcery-org/sipsorcery/blob/e4faf8f53fe36eca80ed3980f4cc63cb1bd5114d/src/net/STUN/STUNDns.cs#L69 

Maybe it could be safely enabled ?

**Comment by sipsorcery** [comment]
The reason I recall for disabling it was due to long timeouts when waiting for the initial connection on a TCP DNS lookup. Not so much of an issue for STUN lookups but it was problem for SIP lookups.

I'll add a new static property so it can be set.

**Comment by mikhaylo1** [comment]
please adjust the fix. The new static property would not do any affect because the setting is set in static constructor which executes before we can set the property
