### ISSUE TITLE
ICE support on SIP?

### ISSUE THREAD

**Issue by maguoloalceo** [sipsorcery-org/sipsorcery#733]
Hi,

is ICE negotiation on SIP signalling supported? I've not found any reference to this functionality on SIP, but only in the WebRTC RTCPeerConnection object.

Thanks.

**Comment by sipsorcery** [comment]
See [AsteriskIce](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/AsteriskIce/Program.cs) for an example.

**Comment by maguoloalceo** [comment]
Thank you for your prompt answer, looking at the source code from the AsteriskIce example I think I've implemented the feature, but now I'm facing a new problem because our SIP client doesn't support the UDP/TLS/RTP/SAVP media but only non secure media RTP/AVP.

Is it possible to disable the encription when ICE negotiation is enabled?

**Comment by maguoloalceo** [comment]
The problem was not the encription but instead the rtcp-mux option.
