### ISSUE TITLE
SipUserAgent disable PRACK support

### ISSUE THREAD

**Issue by henlil** [sipsorcery-org/sipsorcery#735]
Hi,

I would like to disable disable PRACK support when using the SIPUserAgent. 

I've identified the following changed needs to be done to the library, correct me if I'm wrong: 

- SipUserAgent needs a PrackSupported Property.

- SipUser agent should set SIPClientUserAgent.PrackSupported = PrackSupported when making the call. 
 
- SIPClientUserAgent should pass the inverted PrackSupported to the UACInviteTransaction when creating the invite transaction.

- UACInviteTransaction should make use of the _disablePrackSupport field and send PRACK only if enabled and RSeq>0

/Henrik

**Comment by sipsorcery** [comment]
Yes to all your points.

It's weird that the bug regarding the _disablePrackSupport on UACInviteTransaction not being used has never been picked up until now. I guess PRACK's are still not a very commonly used request.

**Comment by sipsorcery** [comment]
Seems the [Prack popery](https://github.com/sipsorcery-org/sipsorcery/blob/de91be67f8c79d6fd67bb5b18a7f9f33bd9ba6f5/src/app/SIPUserAgents/SIPUserAgent.cs#L391) for the SIPUserAgent is in place now.
