### ISSUE TITLE
When Re-joining to janus audio bridge, peer connection could not stablished

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#738]
STEP 01: Successfully joined in janus audio brigdge room and audio call is on.

STEP 02: Left from Room

STEP 03:  after joining again, getting following status

Ice State has Changed checking.
Ice State has Changed connected.
Peer connection state change to connecting.
Peer connection state change to closed.
Peer connection state to failed.

**Comment by sipsorcery** [comment]
We're not likley to be able to help you much unless you can provide some kind of log messages from your sipsorcery application. It's a fair bit of effort to attempt to replicate your scenario and unless someone else here is working with Janus and sipsorcery right at this particular point in time it's unlikely to happen.
