### ISSUE TITLE
Example for playing audio back using FFmpeg

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#739]
Currently, the way to playback RTP packets is to call `GotAudioRtp` on `WindowsAudioEndPoint` as in the `WebRTCReceiveAudio` example.

I was wondering if there is a similar example for using FFmpeg instead of `WindowsAudioEndPoint` which uses NAudio under the hood. If there isn't, how I might start putting something like this together?

Also looking into [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg), I noticed there is `FFmpegVideoEndPoint` but no `FFmpegAudioEndPoint`.

**Comment by sipsorcery** [comment]
The FFmpeg native libraries do have extensive audio support but it has not been wired up in the SIPSorceryMedia.FFmpeg library because it was more work than the SIPSorceryMedia.Windows approach with NAudio.

As Chrisophel mentioned the 3rd alternative is to use the newer SIPSorcery.SDL2 library.

**Comment by tghanem** [comment]
@ChristopheI , @sipsorcery, thank you so much! I'll take a look at [SIPSorcery.SDL2](https://github.com/sipsorcery-org/SIPSorcery.SDL2).
