### ISSUE TITLE
How to adjust the sending and receiving jitter buffer? 

### ISSUE THREAD

**Issue by karas1999** [sipsorcery-org/sipsorcery#742]
Hi. I'm using my SIPSorcery client with a SIP server. The server is transmitting the RTP stream, and we get choppy voice in both way. When I use another soft phone, the both voice are fine. 

I saw that in the trace file, the max jitter is 112 ms.  I think maybe the choppy voice is because the jitter buffer is not large enough. So I want to know if there is a way to adjust the jitter buffer for both sending and receiving? Or is there a "auto jitter buffer" feature? Thank you. 

![image](https://user-images.githubusercontent.com/12420964/171118129-fd9ca19c-ddc6-4073-919d-4cfcf45262fe.png)

Capture file attached. 
[Capture.zip](https://github.com/sipsorcery-org/sipsorcery/files/8803055/Capture.zip)

**Comment by sipsorcery** [comment]
There is no jitter buffer in this library.

The [RTPReorderBuffer](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTP/RTPReorderBuffer.cs) could probably be built upon to add one.

**Comment by karas1999** [comment]
> 

Thanks. I saw that in the web document, there is an AudioStream in RTPSession, which has an AddBuffer method, I want to try that, but I cannot find that AudioStream in the SIPSorcery package. 
My package version is 6.0.7. 

Could you help me with this? 

![image](https://user-images.githubusercontent.com/12420964/171148872-5fe337dd-60ec-4534-98c0-7801dc1a0c53.png)
