### ISSUE TITLE
TURN Implementation

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#749]
There is a class called `STUNServer` and there is another class called `MockTurnServer` in the integration tests. So, my question is which one of them contains a full TURN server implementation?

**Comment by tghanem** [comment]
So then do you suggest I use `coturn` or start a TURN implementation in sipsorcery?

**Comment by sipsorcery** [comment]
Unless you've got a very compelling reason not to I'd definitely go with coturn.

**Comment by tghanem** [comment]
Ok. I'll go with `cotrun` for now. Thank @sipsorcery .
