### ISSUE TITLE
(need the fix adjusting) Response was truncated and UseTcpFallback is disabled, unable to resolve the question

### ISSUE THREAD

**Issue by mikhaylo1** [sipsorcery-org/sipsorcery#750]
I can't reopen the old issue #732 , therefore creating a new one
It looks like the proposed fix [would not work](https://github.com/sipsorcery-org/sipsorcery/commit/9c4d0ce3428c54d2c18f0c89dc1dcebe25f64488#r75257825)  . Could you please recheck ?

**Comment by ChristopheI** [comment]
@mikhaylo1 

I added a comment. 

The best should be that you create a PR since you can test on your side this feature. 
**_lookupClient** can be created when necessary so it can use correct value from **DnsUseTcpFallback**
The static constructor is not necessary

**Comment by mikhaylo1** [comment]
@ChristopheI that is done

**Comment by ChristopheI** [comment]
Thank you !
