### ISSUE TITLE
Unable to handle unexpected exceptions when interacting with the MediaSession

### ISSUE THREAD

**Issue by JSN-C** [sipsorcery-org/sipsorcery#752]
Currently an unhandled exception can occur within a thread (not owned by the application consuming the library) which results in an unhandled exception terminating the host process.

Within the SIPUserAgent, we interact with MediaSessions as a result of a raised event or delegate, in this case (for example when starting the MediaSession) an exception could be raised on a thread which cannot be handled by the external caller.  For example where a fault arises from a media device, or for instance no media device is available (for example on a build agent). 

Ideally exceptions arising from (a thread not initiated by the host application) interacting with a media device (or lack thereof) should:

- Log an error and raise a fail event as appropriate.
- Terminate the instantiation of a call, or reject a call as appropriate.

See the implementation of the SIPUserAgent.ClientCallAnsweredHandler for one scenario where a fault arising from MediaSession.Start will crash the host process.

**Comment by sipsorcery** [comment]
The ideal solution would be to prevent the exception being thrown in that method. Otherwise it's back to the try/catch handlers polluting every method thorughout the code base.

**Comment by JSN-C** [comment]
Fair comment, thanks for responding. 

It would be nice to code defensively for this particular case, will look at the underlying implementation also.

**Comment by henlil** [comment]
I believe there should be a try catch within each "async void" method to prevent unhandled exceptions. MediaSession.Start() should of course throw the exception if there is anything wrong. I like the suggested changes, as I've seen the same behavior with unhandled exceptions.

**Comment by JSN-C** [comment]
Merged to master.
