### ISSUE TITLE
[6.0.8 issue] Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

### ISSUE THREAD

**Issue by mikhaylo1** [sipsorcery-org/sipsorcery#757]
My application stopped working after updating from 6.0.7 to 6.0.8,

The issue seems is the incorrect order of "m" lines introduced in 6.0.8

6.0.8:
**Offer from Chrome**
![image](https://user-images.githubusercontent.com/18460856/173893304-9141cb06-36d2-4d74-8eb6-55f54828b95f.png)

**Answer from Sipsorcery 6.0.8**
![image](https://user-images.githubusercontent.com/18460856/173893807-a480f3c0-dcd7-4b73-9fb4-d84dcf0eeb41.png)

With the same condition version 6.0.7 generates the correct order in SDP answer

**Comment by ChristopheI** [comment]
I'll check why this occurs. 

I don't try so much using "application" on my side ...

If you have any sample to share which reproduce the pb it will help me a lot.

**Comment by ChristopheI** [comment]
If you could provide your full SDP( the correct one) in text format, it will be great for tests purpose.

Thanks

**Comment by ChristopheI** [comment]
Could you check if, on your size, you have no more the pb with this fix:
``` csharp
// In File RTCPeerConnection.cs - Line 1218: Replace
foreach (var ann in offerSdp.Media.OrderBy(x => x.MLineIndex))
// By
foreach (var ann in offerSdp.Media.OrderBy(x => x.MLineIndex).ThenBy(x => x.MediaID))

// ----------------------------------------------------------------------------

// In File SDP.cs - Line 857: Replace
foreach (SDPMediaAnnouncement media in Media.OrderBy(x => x.MLineIndex))
// By
foreach (SDPMediaAnnouncement media in Media.OrderBy(x => x.MLineIndex).ThenBy(x => x.MediaID))

// ----------------------------------------------------------------------------

// In File SDP.cs - Replace GetIndexForMediaType method by this one
public (int, string) GetIndexForMediaType(SDPMediaTypesEnum mediaType, int mediaIndex)
{
    int fullIndex = 0;
    int mIndex = 0;
    foreach (var ann in Media)
    {
        if (ann.Media == mediaType)
        {
            if (mIndex == mediaIndex)
            {
                return (fullIndex, ann.MediaID);
            }
            mIndex++;
        }
        else
        {
            fullIndex++;
        }
    }

    return (MEDIA_INDEX_NOT_PRESENT, MEDIA_INDEX_TAG_NOT_PRESENT);
}
```

In all case, could you please provide your full SDP (text format) ? I will add a new unit test using it.

**Comment by mikhaylo1** [comment]
@ChristopheI 
> In all case, could you please provide your full SDP (text format) ? I will add a new unit test using it.

Sure. I have 2 pairs of SDP exchanges

During the first exchange I setup a DataChannel between Chrome and Sipsorcery
**First Offer from Chrome**
`{"type":"offer","sdp":"v=0\r\no=- 6660358274987668701 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:fXw4\r\na=ice-pwd:vb5CJ96xIInblnc6dTFCCpWj\r\na=ice-options:trickle\r\na=fingerprint:sha-256 2B:35:E2:AA:C0:D7:A6:A6:3C:A1:C8:CE:30:96:E6:9A:42:44:64:CE:9D:95:F6:22:DC:99:DC:BC:E3:00:B8:9B\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}`

**First answer from Sipsorcery**
`{"type":"answer","sdp":"v=0\r\no=- 70650 0 IN IP4 127.0.0.1\r\ns=sipsorcery\r\nt=0 0\r\na=group:BUNDLE 0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:SRWC\r\na=ice-pwd:JHICUJFIJRQUPKUNJMZKMQAT\r\na=fingerprint:sha-256 86:40:0B:3F:1B:45:91:FC:9F:C3:64:45:B9:24:BE:52:DE:22:2D:8C:FE:61:2E:46:66:46:E2:4E:70:F0:E7:F0\r\na=setup:active\r\na=candidate:2750 1 udp 2113937663 192.168.100.143 55547 typ host generation 0\r\na=candidate:2105 1 udp 2113940223 2a0c:5a82:1206:9500:6181:38ab:c586:f2f9 55547 typ host generation 0\r\na=candidate:2460 1 udp 2113940223 2a0c:5a82:1206:9500:cc08:e955:d6d1:40d2 55547 typ host generation 0\r\na=ice-options:ice2,trickle\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}`

**After that I setup a media with second pair of SDP exchanges. Second offer from Chrome:**
`{"type":"offer","sdp":"v=0\r\no=- 6660358274987668701 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS 03a8cc82-c386-4b9e-9f7d-bb29d00d117d\r\nm=application 61790 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 51.195.41.188\r\na=candidate:2076133753 1 udp 2113937151 7da52ae2-cbda-46a4-a41a-352694bb27cc.local 51273 typ host generation 0 network-cost 999\r\na=candidate:875361675 1 udp 2113939711 102e0cd0-cecf-4fa5-9282-1ebed8600fe4.local 51274 typ host generation 0 network-cost 999\r\na=candidate:842163049 1 udp 1677729535 86.127.230.60 51273 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:1382836467 1 udp 33562623 51.195.41.188 61790 typ relay raddr 86.127.230.60 rport 51273 generation 0 network-cost 999\r\na=candidate:2754337611 1 udp 33562367 51.75.71.217 49926 typ relay raddr 86.127.230.60 rport 51273 generation 0 network-cost 999\r\na=ice-ufrag:fXw4\r\na=ice-pwd:vb5CJ96xIInblnc6dTFCCpWj\r\na=ice-options:trickle\r\na=fingerprint:sha-256 2B:35:E2:AA:C0:D7:A6:A6:3C:A1:C8:CE:30:96:E6:9A:42:44:64:CE:9D:95:F6:22:DC:99:DC:BC:E3:00:B8:9B\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 121 125 107 108 109 124 120 123 119 35 36 41 42 114 115 116 117 118\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:fXw4\r\na=ice-pwd:vb5CJ96xIInblnc6dTFCCpWj\r\na=ice-options:trickle\r\na=fingerprint:sha-256 2B:35:E2:AA:C0:D7:A6:A6:3C:A1:C8:CE:30:96:E6:9A:42:44:64:CE:9D:95:F6:22:DC:99:DC:BC:E3:00:B8:9B\r\na=setup:actpass\r\na=mid:1\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:3gpp:video-orientation\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:03a8cc82-c386-4b9e-9f7d-bb29d00d117d 5b06be39-0752-497f-80f5-6cf3db665f14\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 H264/90000\r\na=rtcp-fb:124 goog-remb\r\na=rtcp-fb:124 transport-cc\r\na=rtcp-fb:124 ccm fir\r\na=rtcp-fb:124 nack\r\na=rtcp-fb:124 nack pli\r\na=fmtp:124 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 transport-cc\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f\r\na=rtpmap:119 rtx/90000\r\na=fmtp:119 apt=123\r\na=rtpmap:35 H264/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=fmtp:35 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:41 AV1/90000\r\na=rtcp-fb:41 goog-remb\r\na=rtcp-fb:41 transport-cc\r\na=rtcp-fb:41 ccm fir\r\na=rtcp-fb:41 nack\r\na=rtcp-fb:41 nack pli\r\na=rtpmap:42 rtx/90000\r\na=fmtp:42 apt=41\r\na=rtpmap:114 H264/90000\r\na=rtcp-fb:114 goog-remb\r\na=rtcp-fb:114 transport-cc\r\na=rtcp-fb:114 ccm fir\r\na=rtcp-fb:114 nack\r\na=rtcp-fb:114 nack pli\r\na=fmtp:114 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f\r\na=rtpmap:115 rtx/90000\r\na=fmtp:115 apt=114\r\na=rtpmap:116 red/90000\r\na=rtpmap:117 rtx/90000\r\na=fmtp:117 apt=116\r\na=rtpmap:118 ulpfec/90000\r\na=ssrc-group:FID 16371961 1091343449\r\na=ssrc:16371961 cname:DE2fEykfrhlS8lo5\r\na=ssrc:16371961 msid:03a8cc82-c386-4b9e-9f7d-bb29d00d117d 5b06be39-0752-497f-80f5-6cf3db665f14\r\na=ssrc:16371961 mslabel:03a8cc82-c386-4b9e-9f7d-bb29d00d117d\r\na=ssrc:16371961 label:5b06be39-0752-497f-80f5-6cf3db665f14\r\na=ssrc:1091343449 cname:DE2fEykfrhlS8lo5\r\na=ssrc:1091343449 msid:03a8cc82-c386-4b9e-9f7d-bb29d00d117d 5b06be39-0752-497f-80f5-6cf3db665f14\r\na=ssrc:1091343449 mslabel:03a8cc82-c386-4b9e-9f7d-bb29d00d117d\r\na=ssrc:1091343449 label:5b06be39-0752-497f-80f5-6cf3db665f14\r\n"}`

**And the second Failed answer from Sipsorcery**
`{"type":"answer","sdp":"v=0\r\no=- 70650 0 IN IP4 127.0.0.1\r\ns=sipsorcery\r\nt=0 0\r\na=group:BUNDLE 1 0\r\nm=video 9 UDP/TLS/RTP/SAVP 127\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:SRWC\r\na=ice-pwd:JHICUJFIJRQUPKUNJMZKMQAT\r\na=fingerprint:sha-256 86:40:0B:3F:1B:45:91:FC:9F:C3:64:45:B9:24:BE:52:DE:22:2D:8C:FE:61:2E:46:66:46:E2:4E:70:F0:E7:F0\r\na=setup:active\r\na=candidate:2750 1 udp 2113937663 192.168.100.143 55547 typ host generation 0\r\na=candidate:2105 1 udp 2113940223 2a0c:5a82:1206:9500:6181:38ab:c586:f2f9 55547 typ host generation 0\r\na=candidate:2460 1 udp 2113940223 2a0c:5a82:1206:9500:cc08:e955:d6d1:40d2 55547 typ host generation 0\r\na=ice-options:ice2,trickle\r\na=mid:1\r\na=rtpmap:127 H264/90000\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f;x-google-max-bitrate=1000;x-google-start-bitrate=1000\r\na=rtcp-mux\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=recvonly\r\na=ssrc:1056667677 cname:2dd303fa-0885-4df6-ac05-dac263081df3\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:SRWC\r\na=ice-pwd:JHICUJFIJRQUPKUNJMZKMQAT\r\na=fingerprint:sha-256 86:40:0B:3F:1B:45:91:FC:9F:C3:64:45:B9:24:BE:52:DE:22:2D:8C:FE:61:2E:46:66:46:E2:4E:70:F0:E7:F0\r\na=setup:active\r\na=ice-options:ice2,trickle\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}`

**Comment by mikhaylo1** [comment]
@ChristopheI 
> Could you check if, on your size, you have no more the pb with this fix:

Yes, that works. I checked with DataChannel + Video + Audio and the same but no audio. The fix resolves that issue

**second Passed answer from Sipsorcery after the fix**
`{"type":"answer","sdp":"v=0\r\no=- 78425 0 IN IP4 127.0.0.1\r\ns=sipsorcery\r\nt=0 0\r\na=group:BUNDLE 0 1\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:WEVI\r\na=ice-pwd:NKOOMELCYWFDIRHJBKCGJECE\r\na=fingerprint:sha-256 71:39:48:B3:94:B9:10:82:40:A4:62:78:E9:F5:C6:E4:B0:7C:DF:6B:7A:C7:98:68:5A:51:0B:DD:89:ED:20:72\r\na=setup:active\r\na=ice-options:ice2,trickle\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\nm=video 9 UDP/TLS/RTP/SAVP 127\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:WEVI\r\na=ice-pwd:NKOOMELCYWFDIRHJBKCGJECE\r\na=fingerprint:sha-256 71:39:48:B3:94:B9:10:82:40:A4:62:78:E9:F5:C6:E4:B0:7C:DF:6B:7A:C7:98:68:5A:51:0B:DD:89:ED:20:72\r\na=setup:active\r\na=candidate:2750 1 udp 2113937663 192.168.100.143 65174 typ host generation 0\r\na=candidate:2105 1 udp 2113940223 2a0c:5a82:1206:9500:6181:38ab:c586:f2f9 65174 typ host generation 0\r\na=candidate:2460 1 udp 2113940223 2a0c:5a82:1206:9500:cc08:e955:d6d1:40d2 65174 typ host generation 0\r\na=ice-options:ice2,trickle\r\na=mid:1\r\na=rtpmap:127 H264/90000\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f;x-google-max-bitrate=1000;x-google-start-bitrate=1000\r\na=rtcp-mux\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=recvonly\r\na=ssrc:72981441 cname:287676de-8ffb-4f8a-8961-b0161953cf62\r\n"}`

**Comment by ChristopheI** [comment]
Good news !

As soon as I can I will create a PR with this fix and a new unit test

**Comment by ChristopheI** [comment]
@mikhaylo1 

When you created the PR you had a SDP with 3 media: application, audio and video. Could you please provide me the SDP in this case too ?
