### ISSUE TITLE
Converting RawImage to Bitmap is a mirrored image

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#758]
In OnVideoSourceRawSampleFaster event of VideoSource, I am converting RawImage to Biitmap as follows:

Bitmap bmpImage = new Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, PixelFormat.Format24bppRgb, rawImage.Sample);

Getting a mirrored image.

Should I flip the image or I am missing something.

**Comment by ChristopheI** [comment]
I suppose you are talking about your own webcam output and not about video file output or neither webcam output from a Peer, isn't it ?

By habit, UI to display your own webcam output is, **by code**, mirrored so you can see you like in a mirror. But the real output of the webcam is not mirrored (i.e. the stream coming form the device). (Like you can test it here: https://webrtc.github.io/test-pages/src/single-video/)  And this is this output which is sent to the Peer. So It will be displayed not mirrored (and it's normal)

So if you want your UI to mirror your own webcam output, you have to "flip" it yourself.

It's easy:
```
bmpImage.RotateFlip(RotateFlipType.RotateNoneFlipX);
```

**Comment by mail2mhossain** [comment]
I have done the flip part in Both cases, Local & Remote. Otherwise, both images are mirrored.

**Comment by ChristopheI** [comment]
you have a different display than his one ? https://webrtc.github.io/test-pages/src/single-video/

**Comment by ChristopheI** [comment]
So there is no pb at all as I explained all details in https://github.com/sipsorcery-org/sipsorcery/issues/758#issuecomment-1157446296
