### ISSUE TITLE
Possible NullReferenceException inside SIPParameters

### ISSUE THREAD

**Issue by kuleshov-aleksei** [sipsorcery-org/sipsorcery#765]
Hello! I've noticed that there can be many NullReferenceExceptions (NRE) in `SIPParameters`.

# Explanation:

Class exposes `m_dictionary`:
```csharp
public Dictionary<string, string> m_dictionary;
```

any external class (even outside of SIPSorcery) can modify `m_dictionary` and set it to `null`
```csharp
SIPParameters parameters = new SIPParameters();
parameters.m_dictionary = null;
_ = parameters.Get("somekey"); // NRE here
```

Some methods like `public bool Has(string name)` checks if `m_dictionary` is not null. But some methods like `public void Set(string name, string value)` - don't.

Method `public string Get(string name)` has logic bug for checking for null:
`m_dictionary` can be null and then code will attempt to execute `m_dictionary.Count`, that will lead to NRE
```csharp
if (m_dictionary != null || m_dictionary.Count == 0)
{
	if (m_dictionary.ContainsKey(name))
	{
		return SIPEscape.SIPURIParameterUnescape(m_dictionary[name]);
	}
	else
	{
		return null;
	}
}
else
{
	return null;
}
```
as I think correct way is:
```csharp
if (m_dictionary != null && m_dictionary.Count > 0)
```

# Suggestions:

As I see there are two ways:
1. Make `m_dictionary` private as no code inside SIPSorcery uses it directly (potentially, this can break applications that uses  SIPParameters directly)
2. Add safety checks in all methods for handling sutiations where `m_dictionary` can be null

**Comment by sipsorcery** [comment]
> Make m_dictionary private as no code inside SIPSorcery uses it directly (potentially, this can break applications that uses SIPParameters directly)

That's what I've now done. I can't recall why I made it public, probably to serialise the parameters to a database or something. That's not the proper approach for the reasons you've mentioned so I've set it back to private.

I've fixed teh other bug as well.

Thanks for taking the time to provide the details.
