### ISSUE TITLE
add_OnVideoSourceRawSampleFaster not implemented when cloning and running WebRTCGetStarted

### ISSUE THREAD

**Issue by danjford** [sipsorcery-org/sipsorcery#767]
When cloning the repo and running the [WebRTCGetStarted](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/WebRTCGetStarted) example, if you press 'start' in the web page it causes the below exception:

`
"Method 'add_OnVideoSourceRawSampleFaster' in type 'SIPSorceryMedia.Encoders.VideoEncoderEndPoint' from assembly 'SIPSorceryMedia.Encoders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"SIPSorceryMedia.Encoders.VideoEncoderEndPoint"
`

**Comment by ChristopheI** [comment]
Samples are perhaps not all updated in each release.
Use last version of packages. 

If you use [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows): use at least [v6.0.3-pre](https://www.nuget.org/packages/SIPSorceryMedia.Windows/6.0.3-pre)

**Comment by jeremyVignelles** [comment]
After upgrading this package in WebRTCWebcamServer, it still doesn't work with :
```
Unhandled exception. System.TypeLoadException: Method 'EncodeVideoFaster' in type 'SIPSorceryMedia.Encoders.VpxVideoEncoder' from assembly 'SIPSorceryMedia.Encoders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

The WebRTCGetStarted project doesn't use that package at all, but it seems like the SIPSorcercyMedia.Encoders has been stuck to 0.0.10-pre for a while.

**Comment by Shaxzod1311** [comment]
HI
I want to try SipSorcery library to use manage WebRTC into asp net application, clearly i want to build server that handle each peerConnection in may future project.
I tried WebRTCGetStarted from examples and i got an error
Method 'add_OnVideoSourceRawSampleFaster' in type 'SIPSorceryMedia.Encoders.VideoEncoderEndPoint' from assembly 'SIPSorceryMedia.Encoders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation
My OS Windows 11.
I will be very grateful, if you help me for solving this problem

**Comment by maticcavalleri** [comment]
Having same issue as @Shaxzod1311, trying to run one of the video examples and I am getting the same error. Help appreciated.

**Comment by ekwus** [comment]
Hey, I'm having the same issue with EncodeVideoFaster missing an implementation.

I've tried targeting .net6.0 and .netcore3.1 but still having the same issue.

**Comment by lostmsu** [comment]
At the very least, the packages should be updated to include supported version ranges.

**Comment by sipsorcery** [comment]
All packages have been updated in the latest releases.
