### ISSUE TITLE
Problem with setting SSRC on MediaStream when receiving RTP packet (version 6.0.8)

### ISSUE THREAD

**Issue by anasonov1992** [sipsorcery-org/sipsorcery#770]
Hi!
I use SIPSorcery library in Mobile Xamarin app to receive RTP video stream.
And I've found an issue with RTP packets handling. Video is not displayed and I've seen the following warnings in logs:

21.06.2022 16:29:27.926  Warning      An RTP packet with SSRC 1928984433 and payload ID 99 was received that could not be matched to an audio or video stream.
21.06.2022 16:29:27.930  Warning      An RTP packet with SSRC 1926815468 and payload ID 8 was received that could not be matched to an audio or video stream.

I checked the code and found a method that logs those warnings in RTPSession:

        private void OnReceiveRTPPacket(int localPort, IPEndPoint remoteEndPoint, byte[] buffer)
        {
            if (!IsClosed)
            {
                var hdr = new RTPHeader(buffer);

                MediaStream mediaStream = GetMediaStream(hdr.SyncSource);
                
                if (mediaStream == null)
                {
                    logger.LogWarning($"An RTP packet with SSRC {hdr.SyncSource} and payload ID {hdr.PayloadType} was received that could not be matched to an audio or video stream.");
                    return;
                }

                hdr.ReceivedTime = DateTime.Now;
                if (mediaStream.MediaType == SDPMediaTypesEnum.audio)
                {
                    mediaStream.OnReceiveRTPPacket(hdr, localPort, remoteEndPoint, buffer, null);
                }
                else if (mediaStream.MediaType == SDPMediaTypesEnum.video)
                {
                    mediaStream.OnReceiveRTPPacket(hdr, localPort, remoteEndPoint, buffer, mediaStream as VideoStream);
                }
            }
        }
 
       
GetMediaStream returns null and It happens due to SSRC check in it on RemoteTrack/LocalTrack:

private MediaStream GetMediaStream(uint ssrc)

            foreach (var audioStream in AudioStreamList)
            {
                if (audioStream?.RemoteTrack?.IsSsrcMatch(ssrc) == true)
                {
                    return audioStream;
                }
                else if (audioStream?.LocalTrack?.IsSsrcMatch(ssrc) == true)
                {
                    return audioStream;
                }
            }

            foreach (var videoStream in VideoStreamList)
            {
                if (videoStream?.RemoteTrack?.IsSsrcMatch(ssrc) == true)
                {
                    return videoStream;

                }
                else if (videoStream?.LocalTrack?.IsSsrcMatch(ssrc) == true)
                {
                    return videoStream;
                }
            }

            return GetMediaStreamRemoteSDPSsrcAttributes(ssrc);
        }

        /// <summary>
        /// Checks whether a SSRC value from an RTP header or RTCP report matches
        /// a value expected for this track.
        /// </summary>
        /// <param name="ssrc">The SSRC value to check.</param>
        /// <returns>True if the SSRC value is expected for this track. False if not.</returns>
        public bool IsSsrcMatch(uint ssrc)
        {
            return ssrc == Ssrc || SdpSsrc.ContainsKey(ssrc);
        }

In my case RemoteTrack.Ssrc is 0 for video and audio streams as well. 

And I've found that RemoteTrack.Ssrc is set later - in MediaStream class OnReceiveRTPPacket method:

        public void OnReceiveRTPPacket(RTPHeader hdr, int localPort, IPEndPoint remoteEndPoint, byte[] buffer, VideoStream videoStream = null)
        {
            RTPPacket rtpPacket = null;
            if (RemoteRtpEventPayloadID != 0 && hdr.PayloadType == RemoteRtpEventPayloadID)
            {
                if (!EnsureBufferUnprotected(buffer, hdr, out rtpPacket))
                {
                    return;
                }

                RaiseOnRtpEventByIndex(remoteEndPoint, new RTPEvent(rtpPacket.Payload), rtpPacket.Header);
                return;
            }

            // Set the remote track SSRC so that RTCP reports can match the media type.
            if (RemoteTrack != null && RemoteTrack.Ssrc == 0 && DestinationEndPoint != null)
            {
                bool isValidSource = AdjustRemoteEndPoint(hdr.SyncSource, remoteEndPoint);

                if (isValidSource)
                {
                    logger.LogDebug($"Set remote track ({MediaType} - index={Index}) SSRC to {hdr.SyncSource}.");
                    RemoteTrack.Ssrc = hdr.SyncSource;
                }
            }

How can we fix this issue and set RemoteTrack.Ssrc before IsSsrcMatch check?

Thanks a lot in advance!

Tony.

**Comment by ChristopheI** [comment]
Hi,

Good news to hear that you use SIPSorcery in Xamarin ! I didn't have enough time to try it already.

MediaStream.OnReceiveRTPPacket(...) is called only when a correct MediaStream is found. 
So when GetMediaStream(hdr.SyncSource); return an object not null.

Once SDP negotiation is done, and when first RTP packet are received thanks to GetMediaStreamRemoteSDPSsrcAttributes  links between SSRC and MediaStream are created.

Do you confirm that SSRC 1928984433  and 1926815468 are values available in the SDP created by the remote ?

**Comment by anasonov1992** [comment]
Thank you for your attention!

Here is the SDP created by the remote:

v=0
o=root 677465070 677465070 IN IP4 194.28.207.15
s=Asterisk PBX 16.2.1~dfsg-2ubuntu1
c=IN IP4 194.28.207.15
b=CT:384
t=0 0
m=audio 16894 RTP/AVP 8 0
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=maxptime:150
a=sendrecv
m=video 18790 RTP/AVP 99
a=rtpmap:99 H264/90000
a=sendrecv

And as I understand, we don't get any SSRC values in SDP.
I've debugged GetMediaStreamRemoteSDPSsrcAttributes method: audioRemoteSDPSsrcAttributes and videoRemoteSDPSsrcAttributes collections are empty.

Also code that set SSRC for RemoteTrack is commented (please see 2269-2272, 2298-2301 lines) in 6.0.8 version so GetMediaStreamRemoteSDPSsrcAttributes method returns null for us as well.
https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTP/RTPSession.cs

**Comment by ChristopheI** [comment]
A correct SDP as far as I know must have a SSRC set for each media.  If it's not the case it's not possible to differentiate them easily (for example if you have 2 video streams)

Example of SDP: one audio stream and 2 video stream:
```
v=0
o=- 92761 0 IN IP4 127.0.0.1
s=sipsorcery
t=0 0
a=group:BUNDLE 0 1 2
m=audio 9 UDP/TLS/RTP/SAVP 111 101
c=IN IP4 0.0.0.0
a=ice-ufrag:FHUA
a=ice-pwd:JRESZDAEMFBDSBJKLLOMKJVO
a=fingerprint:sha-256 E0:9D:56:B3:1F:05:8E:1D:CC:12:21:59:2F:52:33:50:B2:5F:8A:7F:67:2D:41:F4:43:CC:45:C9:84:CF:8B:05
a=setup:active
a=candidate:2445 1 udp 2113937663 192.168.1.52 58671 typ host generation 0
a=candidate:4105 1 udp 8447 51.178.224.150 53802 typ relay raddr 0.0.0.0 rport 0 generation 0
a=candidate:5314 1 udp 1677730047 80.119.176.28 58671 typ srflx raddr 0.0.0.0 rport 0 generation 0
a=ice-options:ice2,trickle
a=mid:0
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:101 telephone-event/8000
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=end-of-candidates
a=sendrecv
a=ssrc:7578400 cname:3daf3fec-44ae-4421-bf6b-5775ea51396e
m=video 9 UDP/TLS/RTP/SAVP 96
c=IN IP4 0.0.0.0
a=ice-ufrag:FHUA
a=ice-pwd:JRESZDAEMFBDSBJKLLOMKJVO
a=fingerprint:sha-256 E0:9D:56:B3:1F:05:8E:1D:CC:12:21:59:2F:52:33:50:B2:5F:8A:7F:67:2D:41:F4:43:CC:45:C9:84:CF:8B:05
a=setup:active
a=ice-options:ice2,trickle
a=mid:1
a=rtpmap:96 VP8/90000
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=recvonly
a=ssrc:1024710372 cname:1a372b86-2af1-4c9c-8fc4-d6f011e27038
m=video 9 UDP/TLS/RTP/SAVP 96
c=IN IP4 0.0.0.0
a=ice-ufrag:FHUA
a=ice-pwd:JRESZDAEMFBDSBJKLLOMKJVO
a=fingerprint:sha-256 E0:9D:56:B3:1F:05:8E:1D:CC:12:21:59:2F:52:33:50:B2:5F:8A:7F:67:2D:41:F4:43:CC:45:C9:84:CF:8B:05
a=setup:active
a=ice-options:ice2,trickle
a=mid:2
a=rtpmap:96 VP8/90000
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=recvonly
a=ssrc:1581071533 cname:8542f067-5828-4519-836e-02fab268c51b
```

Since you are using Asterisk, perhaps there is a config to set to force him to indicate SSRC ?

**Comment by ChristopheI** [comment]
I'm not at all an expert about SDP  / WebRTV but reading again your SDP it looks strange to me for this reason:

- You should have something like  "a=group:BUNDLE 0 1"
- Then "a=mid:0" for audio part and "a=mid:1" for videopart

Did you successfully used a Web browser with your environment to create a WebRTC communications with Audio and Video ?

**Comment by anasonov1992** [comment]
No, I didn't test WebRTC in a Web browser but I tested RTP communication between Linphone and the mobile client with our environment and it works well without additional configurations.

Is there any way for me to configure library to work with RTP as on Linphone - without additional SSRC configuration?

**Comment by ChristopheI** [comment]
Ok I just understood you are trying to make SIP communication and not WebRTC ...

There is a method not used which permits to get MediaStream using PayloadID: **GetMediaStreamFromPayloadType**

Perhaps you coud try to use it like this:

```
        private void OnReceiveRTPPacket(int localPort, IPEndPoint remoteEndPoint, byte[] buffer)
        {
            if (!IsClosed)
            {
                var hdr = new RTPHeader(buffer);

                MediaStream mediaStream = GetMediaStream(hdr.SyncSource);

                // START: NEW LINES
                if (mediaStream == null)
                {
                    mediaStream = GetMediaStreamFromPayloadType(hdr.PayloadType);
                }
                // END: NEW LINES

                if (mediaStream == null)
                {
                    logger.LogWarning($"An RTP packet with SSRC {hdr.SyncSource} and payload ID {hdr.PayloadType} was received that could not be matched to an audio or video stream.");
                    return;
                }
                ...
        }

```

This should work because you use only ONE audio stream or/and ONE Video Stream. 
If you have more than ONE audio stream or more than ONE Video Stream you will have bad results ...

**Comment by anasonov1992** [comment]
Ok, thank you for your help!

I've not mentioned above that for now we use right that solution to test SIP communication and it works well exactly with such check by PayloadType.

Could we make that fix and update the library package somehow to avoid compiling the project sources in our app?
Maybe we could make a PR or you could update the package?

**Comment by anasonov1992** [comment]
@ChristopheI yes, I've checked the fix and it works well! Thank you a lot!

For now we can use updated sources.
Please tell me how soon can we expect NuGet package updating?

**Comment by ChristopheI** [comment]
Good news.

Not so many update since last release. So later but I can't tell you when.

**Comment by anasonov1992** [comment]
> Good news.
> 
> Not so many update since last release. So later but I can't tell you when.

It would be great for me!
So thanks again!
