### ISSUE TITLE
Defect in REGISTER Expire value

### ISSUE THREAD

**Issue by maguoloalceo** [sipsorcery-org/sipsorcery#772]
Hi,

I think I've found a defect in the value of the `Expires` header in the `REGISTER` message.

If the registrar server adds the `expires` parameter in the `Contact` field in the `OK` response, this value is used as the `Expires` header in the subsequent `REGISTER` refresh request, but if the expires value returned by the registrar server is smaller than the original `Expires` header the refresh period is reduced.

For example:

1. first `REGISTER` with `Expires` header set to 60 seconds
2. registrar server responds with an `expires` parameter in the `Contact` field in the `OK` response set to 59
3. `REGISTER` refresh sent with `Expires` header set to 59 seconds, while it should be 60 (the original value)

I've made the following modification to the `GetRegistrationRequest` method of the `SIPRegistrationUserAgent` class to fix the defect, don't know if there is a better fix:

```Diff
-            registerRequest.Header.Expires = m_expiry;
+            if (m_expiry > 0)
+            {
+                registerRequest.Header.Expires = m_originalExpiry;
+            } else
+            {
+                registerRequest.Header.Expires = 0;
+            }
```

**Comment by sipsorcery** [comment]
That's by design. The value returned by the server is the value it wants the client to use. If you use a larger value the server will discard the registration once its expiry period is reached.
