### ISSUE TITLE
First, call out failed, and then the incoming call was answered. The SIPUserAgent.OnCallHungup Event was not triggered when hanging up

### ISSUE THREAD

**Issue by danch15** [sipsorcery-org/sipsorcery#779]
1. Call out failed, the Event "private void ClientCallFailedHandler(ISIPClientUserAgent uac, string errorMessage, SIPResponse sipResponse)" was not invoke the "CallEnded" event, so the CallDescriptor is not null.
2. The other call Incoming, just answered and hangup, in the "private void CallEnded(string callId)" function, the "m_callDescriptor != null", so the m_callDescriptor.CallId != callId, so the "OnCallHungup?.Invoke(m_sipDialogue);" was not run.

How to solve this problem: 
Add this code: "CallEnded(m_callDescriptor?.CallId);" in the end of the SIPUserAgent.ClientCallFailedHandler(...) function.

private void ClientCallFailedHandler(ISIPClientUserAgent uac, string errorMessage, SIPResponse sipResponse)
{
    logger.LogWarning($"Call attempt to {uac.CallDescriptor?.Uri} failed with {errorMessage}.");

    _ringTimeout?.Dispose();

    ClientCallFailed?.Invoke(uac, errorMessage, sipResponse);
    CallEnded(m_callDescriptor?.CallId); //Add this code
}

**Comment by danch15** [comment]
Call a number then cancel immediately, and then make an incoming call by other device, then answered. The SIPUserAgent.OnCallHungup Event was not triggered when hanging up.

**Comment by sipsorcery** [comment]
The console logs, or even better SIP trace, are needed to look into this issue.
