### ISSUE TITLE
TURN TCP Protocol support. 

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery-org/sipsorcery#784]
Hello guys, i found a problem when trying to communicate with enterprise environment in Singapore.

Seems that all UDP ports are blocked inside network and the only way to bypass it ia with TURN TCP protocol.

Is anyone awared about complexity of including support for it in project? 

Useful informations in webrtc post that describe it better than me. 

https://groups.google.com/g/discuss-webrtc/c/bq2tUi_guE4/m/IgxRfjFnKSQJ

**Comment by sipsorcery** [comment]
TURN is a simple protocol. Given you managed to wire up DTLS I suspect TURN would be a walk in the park.

The only thing I'd be slightly nervous about is the potential for stalling/blocking if (or when) a TCP TURN server became unresponsive etc. Those edge cases were a rela pain with the SIP TCP channel. At the end of the day TCP does just not go well with real-time protocols.

But if UDP is completely blocked then I guess it's the only option.

**Comment by camnewnham** [comment]
I'm interested in this too. I'm not familiar with the TURN protocol or how it would be implemented, could you suggest a place to start?

**Comment by sipsorcery** [comment]
The TURN logic is mostly [here](https://github.com/sipsorcery-org/sipsorcery/blob/f4fccb11aa62bff3e0b2d38f35a947035162593e/src/net/ICE/RtpIceChannel.cs#L1900).

The STUN requests aren't too bad but the big chunk of work to support a TCP TURN client is to create an RTP channel class that supports TCP, currently it's UDP only.

**Comment by rafcsoares** [comment]
Implemented initial support to TCP ice servers..

It will only support TCP relay transports.. not ice candidates.

Ice Servers with TCP support is enough to bypass UDP restriction.

**Comment by camnewnham** [comment]
> Implemented initial support to TCP ice servers..
> 
> It will only support TCP relay transports.. not ice candidates.
> 
> Ice Servers with TCP support is enough to bypass UDP restriction.

Hi @rafcsoares 
Could you elaborate on this at all?

Does this mean a specifying an ice server with `turn:<address>:<port>?transport=tcp` will work? Or are there other changes required?

**Comment by rafcsoares** [comment]
> > Implemented initial support to TCP ice servers..
> > It will only support TCP relay transports.. not ice candidates.
> > Ice Servers with TCP support is enough to bypass UDP restriction.
> 
> Hi @rafcsoares Could you elaborate on this at all?
> 
> Does this mean a specifying an ice server with `turn:<address>:<port>?transport=tcp` will work? Or are there other changes required?

@camnewnham 
Yes... by now only one ?transport=tcp server is supported as it's not possible to reuse same TCP socket connect with different diferente IceServers.. so i limited to only one TCP server to simplify my life. 

By now the feature was implemented as beta release because we have some edge cases that could stuck video/audio when, using tcp... i will keep working on it as soon as possible.

Happy testing...

**Comment by camnewnham** [comment]
Hi @rafcsoares thanks!
I'm doing some testing at the moment.  I'm running a `coturn` instance on AWS.

It seems like the server is correctly receiving the `ALLOCATE` messages but the `SIPSorcery` client isn't getting the responses.

On the TURN side I get:
```
Oct 19 05:22:58 ip-xxx-xx-xx-xxx turnserver: 931: IPv4. tcp or tls connected to: ip-xxx-xx-xx-xxx:40583
Oct 19 05:22:58  ip-xxx-xx-xx-xxx turnserver: 931: IPv4. Local relay addr: ip-xxx-xx-xx-xxx:50159
Oct 19 05:22:58  ip-xxx-xx-xx-xxx turnserver: 931: session 000000000000000003: new, realm=<realm.com>, username=<>, lifetime=600
Oct 19 05:22:58  ip-xxx-xx-xx-xxx turnserver: 931: session 000000000000000003: realm <realm.com> user <>: incoming packet ALLOCATE processed, success
Oct 19 05:22:58  ip-xxx-xx-xx-xxx turnserver: message repeated 4 times: [ 931: session 000000000000000003: realm <realm.com> user <>: incoming packet ALLOCATE processed, success]
Oct 19 05:22:58 ip-xxx-xx-xx-xxx turnserver: 931: session 001000000000000005: realm <realm.com> user <>: incoming packet ALLOCATE processed, success
Oct 19 05:22:58 ip-xxx-xx-xx-xxx turnserver: message repeated 4 times: [ 931: session 001000000000000005: realm <realm.com> user <>: incoming packet ALLOCATE processed, success]
...
```

But on the SIPSorcery side I get `Connection attempt to ICE server turn:44.204.236.93:80?transport=tcp timed out after 25 requests.`

Any ideas?

**Comment by rafcsoares** [comment]
I will try take a look on it tomorrow.

In my tests i implemented it with coturn+aws aswell

**Comment by rafcsoares** [comment]
Well, i tested again with my coturn server + AWS setup and im sucessfully able to connect to communicate using turn TCP (iceTransport = relay and only one ice server with? transport=tcp)...

It take a lot more time to allocate to coturn in TCP mode than in UDP (probably because we have an extra step to using socket.connect)

I have no idea why you are unable to test it.. sorry :(

**Comment by camnewnham** [comment]
Ah, the error is in binding the TCP listener socket.
```
Socket error NotConnected in UdpReceiver.BeginReceiveFrom. A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
````
From here: https://github.com/sipsorcery-org/sipsorcery/blob/69b349261cf8e374340d1d9bc9ecf77701b918ef/src/net/ICE/RtpIceChannel.cs#L161

The socket doesn't seem to have an address. I haven't specified one manually for UDP, do I need to for TCP?

https://github.com/sipsorcery-org/sipsorcery/blob/69b349261cf8e374340d1d9bc9ecf77701b918ef/src/net/WebRTC/IRTCPeerConnection.cs#L322

**Comment by rafcsoares** [comment]
> Ah, the error is in binding the TCP listener socket.
> 
> ```
> Socket error NotConnected in UdpReceiver.BeginReceiveFrom. A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
> ```
> 
> From here:
> 
> https://github.com/sipsorcery-org/sipsorcery/blob/69b349261cf8e374340d1d9bc9ecf77701b918ef/src/net/ICE/RtpIceChannel.cs#L161
> 
> The socket doesn't seem to have an address. I haven't specified one manually for UDP, do I need to for TCP?
> 
> https://github.com/sipsorcery-org/sipsorcery/blob/69b349261cf8e374340d1d9bc9ecf77701b918ef/src/net/WebRTC/IRTCPeerConnection.cs#L322

Buddy, as i said, its working for me and my tests.

Im using mono for my tests.

Feel free to send PR related to possible fixes when using another platforms like Net6.0, Net5.0, etc

Sometimes we have small changes per APIs in socket that we need to handle, and as i only tested with mono i don't know if it is working for your test cases.

Its working great for me and my tests with Coturn +AWS

**Comment by rafcsoares** [comment]
@camnewnham I submitted a possible fix for your problem related to behaviour of TCP Socket on Net Platforms.

Update your project and try again
