### ISSUE TITLE
SRTP SDP processing for SIP 

### ISSUE THREAD

**Issue by palakkapoor** [sipsorcery-org/sipsorcery#795]
Hello, we've been working on a project to emulate SIP Devices using SIP Sorcery. Our project supports only SRTP SDP and not RTP. We tried to add media in our project using VoIPMediaSession class.

var voipSession = new VoIPMediaSession(winAudio.ToMediaEndPoints());
voipSession.AcceptRtpFromAny = true;

We could see the following sdp being sent over the wire and the call attempt was unsuccessful.

v=0
o=- 1431785656 0 IN IP4 127.0.0.1
s=sipsorcery
c=IN IP4 10.156.160.85
t=0 0
m=audio 59480 RTP/AVP 0 9 18 101
a=rtpmap:0 PCMU/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:117641121 cname:0b814744-d699-48f0-b022-70d9f34b2d33

However, when we hardcoded the SDP as follows, the call attempt was successful but the call did not have any media i.e. sound.

v=0
o=- 2000 2000 IN IP4 192.168.1.151
s=session
c=IN IP4 192.168.1.151
t=0 0
m=audio 6524 RTP/SAVP 9 104 103 111 18 0 8 97 118 101 13
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=mid:1
a=rtpmap:0 PCMU/8000
a=sendrecv
a=rtpmap:18 G729/8000
a=fmtp:111 bitrate=16000
a=rtpmap:8 PCMA/8000
a=rtpmap:97 RED/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:13 CN/8000
a=rtpmap:118 CN/16000
a=ptime:20
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ifCF7SQo9DOjP7rcsI1Tsqyw2S0M4MwYczcRtqMM|2^31
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:h1yAgAkEWuQqo1eGXtinqcQcAEVS5AQBQjtSwp6A|2^31
a=crypto:3 AES_256_CM_HMAC_SHA1_80 inline:HLsQ1mltT/h+hiuvpoPJD0K36pCrzlp7N5kYIoG6jztMmO7oaonR2Osc454sYQ==|2^31
a=sendrecv

Could you please guide us on how we can we send SRTP SDP  and enable media in our calls? Your response would be highly appreciated.

**Comment by sipsorcery** [comment]
SRTP has only been implemented for WebRTC. It has not been wired up for SIP.
