### ISSUE TITLE
A workaround for TURN

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#804]
I have a question that is more of WebRTC related than that about the library itself.

If I have two peers that are trying to connect. One of them is behind a normal NAT and uses `sipsorcery` and the other behind a symmetric NAT and uses the `RTCPeerConnection` API in Chrome. 

1. Is there any workaround to make the connection work? Because currently it clearly doesn't.
2. What happens when both peers are now using `sipsorcery`? Will it be the same result or the library has some workarounds for this?

**I know about TURN and I don't want to go that route and that's why I'm asking this question.**

Thanks.

**Comment by sipsorcery** [comment]
There are no additional NAT traversal mechanisms in cluded in this library over and above the ICE & TURN ones specified in the WebRTC specs.

**Comment by tghanem** [comment]
Ok. Then please allow me to drill a little deeper into this problem.

I'm trying to build a relay server in order to record the media at the server side as opposed to the peers' sides plus other session control functions. **I know we can record at the peer side of things - but that's the requirement if you will**.

I've spent time reading about TURN and it seems like I would have to decrypt the traffic between the peers, detect the negotiated SDP (somehow), then depacketize into media frames...etc.

This is far more complicated than simply each peer establishing an RTC connection with the server and there I simply do a relay of the packets using `sipsorcery.` Since both peers establish independent connections with the server, I can easily detect the media tracks that are being negotiated and which peer is adding/removing which tracks. I also will not have to decrypt the traffic, I will basically get everything I need at the server side with a small overhead of implementing the relay between the connections by simply detecting what one peer negotiates (using SDP) with the server and reflecting that to the other peer. I can even relay raw packets as you well know.

Now, this entire idea falls apart when symmetric NAT comes into play because now if I were to add a TURN server then I will add an extra hop between each peer and the server which I'm afraid will cause significant performance degradation. So basically, with a symmetric NAT configuration, it will be this:

Peer A --> Server --> TURN Server --> Peer B (when one peer is behind symmetric NAT)
Peer A --> TURN Server --> Server --> TURN Server --> Peer B (when both peers are behind symmetric NAT).

So, clearly, the TURN approach could potentially cause a significant performance hit.

And that's why I'm looking for a workaround to symmetric NAT without introducing a TURN server.

**Comment by sipsorcery** [comment]
If you're already using your server to proxy the media it's doing the same job as the TURN server.

If you server is on a public IP address then all your peers, including the ones behind symmetric NATs, will be able to establish a connection to you server without the need for a TURN relay.

**Comment by tghanem** [comment]
Ok. That's great news. However, even though it should, it actually isn't working :innocent:.

Does it have anything to do with [RTCIceTransport.role](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceTransport/role)? I mean, does the controlling ICE agent have anything to do with this? So, if I set the media server to be the _**controlled**_ agent and the peers the _**controlling**_ agents, will it work? And does `sipsorcery` has a way to configure this.

**Comment by sipsorcery** [comment]
The ICE controlling attribute is for the DTLS handshake. It's not related to NAT or media.
