### ISSUE TITLE
Is there any event to know Talking or not status?

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#807]
Is there any event to know when Talking or not Talking status? Based on Talking status want to execute some action.

private void _audioSource_OnAudioSourceEncodedSample (uint durationRtpUnits, byte[] sample)
				{
            _peerConnection.SendAudio(durationRtpUnits, sample);
        }

In the above event, want to track the talking. How could I do that?

**Comment by sipsorcery** [comment]
This library does not provide any signal analysis on audio or video streams.

To detect someone is talking you'd need to feed the received audio into a signal analysis library. I haven't done much work in that area so can't suggest anything.
