### ISSUE TITLE
Understanding the Data Channel Logs

### ISSUE THREAD

**Issue by tghanem** [sipsorcery-org/sipsorcery#808]
So, attached are two log files ([left.log](https://github.com/sipsorcery-org/sipsorcery/files/9234874/left.log) [right.log](https://github.com/sipsorcery-org/sipsorcery/files/9234875/right.log)) for two different RTC connection objects and I'm trying to make sense of them to understand what has gone wrong with the data channel. To help out, I have extracted "what seems to be or clearly is an error".

> WARN: Could not find appropriate remote track for SSRC for RTCP packet.

> WARN: RTCPCompoundPacket did not recognise packet type ID 0

I get this for many other ID values: 119, 36, 120, 43, 204, 181, 221, 53, 60, 129, 238, 160, 20, 242, 92, 86, 54, 211, 147, 89, 211, 116, 178, 218, 14, 153, 233, 237, 93, 186, 216, 174....etc. So not sure what these IDs are and what effects it has when the library can't recognize them?

> WARN : RTCP session for local ssrc 2117344949 has not had any activity for over 30 seconds.

> ERROR: Exception RTCPeerConnection.OnRTPDataReceived Serialisation for feedback report PSFB and message type unassigned not yet implemented.

> ERROR: Exception RTCPeerConnection.OnRTPDataReceived Index was outside the bounds of the array.

> ERROR: Exception RTCPeerConnection.OnRTPDataReceived The RTCP report packet did not have the required CNAME type field set correctly.

> ERROR: Exception RTCPeerConnection.OnRTPDataReceived Destination array is not long enough to copy all the items in the collection. Check array index and length. (Parameter 'value')

> ERROR: Exception RTCPeerConnection.OnRTPDataReceived Index and count must refer to a location within the buffer. (Parameter 'bytes') (from right.log)

> DEBUG: RTCP BYE received for SSRC 3981392769, reason ??88z?)?V???t?  9ynr.

> DEBUG: RTCP BYE received for SSRC 3367566472, reason ?????$???I%? ?\T?O.

> DEBUG: RTCP BYE received for SSRC 3817379013, reason .

> DEBUG: RTCP BYE received for SSRC 960815340, reason ,?????5m. (from right.log)

I have other logs, I will review them and if they contain similar errors, I will post them as well.

Thanks.

**Comment by tghanem** [comment]
@sipsorcery, were you able to look into this?

**Comment by ChristopheI** [comment]
When you have this error:
> WARN: Could not find appropriate remote track for SSRC for RTCP packet.

It means that RTP data has been received but SIPSorcery cannot make a link with any media previously defined: Audio, Video or DataChannel.

Check that the SDP send AND received with remote peer contains all media you want

**Comment by sipsorcery** [comment]
There has been a number of improvements in RTCP processing since this issue was originally created. If there is still interest and the problem still exists please feel free to re-opne.
