### ISSUE TITLE
Playing raw sound has very poor quality and cannot be understood well

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [sipsorcery-org/sipsorcery#811]
Hi,

I'm combining the CallServer sample with the PlaySounds sample. I'm setting up a call and then after the call is answered it calls a SendAudioFromStream passing on the hellowelcome8k.raw file. My SIP provider only accepts PCMA, but as I understood the hellowelcome8k.raw is encoded in neither PCMA nor PCMU, but that SIPsorcery itself is supposed to be doing the encoding. I am not sure how to troubleshoot this further. I've tried sipsorcery 6.0.7 and 6.0.9 and the result is only slightly better.

**Comment by antonkaster** [comment]
Hi! I have same problem. How do you solve it?
Thanks!

**Comment by babawarrior** [comment]
Same problem :(
