### ISSUE TITLE
UserAgent.Hangup() Sometimes couldn't Hangup an  established call.

### ISSUE THREAD

**Issue by sdwflmw** [sipsorcery-org/sipsorcery#814]
I use SIPUserAgent to make a call。But Sometimes it may HangUp fail. I can't find why and when it  occurred.  
the code below is my makecall code:

        public async Task MakeCall(string destination)
        {
            var callURI = SIPURI.ParseSIPURIRelaxed($"{destination}@{Config.SIPServerIp}:{Config.SIPServerPort}");
            var sipUsername = Config.SIPUserName;
            var sipPassword = Config.SIPPassword;
            var fromHeader = (new SIPFromHeader(Config.SIPFromName, 
                new SIPURI(sipUsername, $"{Config.SIPServerIp}:{Config.SIPServerPort}", null), null)).ToString();
            SIPCallDescriptor callDescriptor = new SIPCallDescriptor(sipUsername, sipPassword, callURI.ToString(), fromHeader, null, null, null, null, SIPCallDirection.Out, SDP.SDP_MIME_CONTENTTYPE, null, null);
            var MediaSession = CreateMediaSession();
            await UserAgent.InitiateCallAsync(callDescriptor, MediaSession);
        }

and my CreateMediaSession() method:

       private VoIPMediaSession CreateMediaSession()
        {
            var windowsAudioEndPoint = new WindowsAudioEndPoint(new AudioEncoder());
            windowsAudioEndPoint.RestrictFormats(x => x.Codec == AudioCodecsEnum.PCMA
                                               || x.Codec == AudioCodecsEnum.PCMU);
            //    || x.Codec == AudioCodecsEnum.G729

            var voipMediaSession = new VoIPMediaSession(windowsAudioEndPoint.ToMediaEndPoints());
            voipMediaSession.AcceptRtpFromAny = true;
            voipMediaSession.OnRtpPacketReceived += VoipMediaSession_OnRtpPacketReceived;
            return voipMediaSession;
        }

**Comment by sdwflmw** [comment]
my libary version is the latest version on nuget .  6.0.9 .

**Comment by sipsorcery** [comment]
I realise this response is very late. If you're still interested and able to provide the library debug messages please feel free to re-open.
