### ISSUE TITLE
the delay is too high when viewing on the browser

### ISSUE THREAD

**Issue by bzmework** [sipsorcery-org/sipsorcery#821]
After capturing the screen, the delay is too high（More than 3 seconds） when viewing on the browser. Why?
See example: SIPSorceryMedia.FFmpeg/FFmpegFileAndDevicesTest

**Comment by ChristopheI** [comment]
I don't see a big difference in settling time between using a webcam or a video file in this example.

To create the Web RTC connection, you must first join ICE servers and then establish a potential list of bindings. The remote does the same and together they choose the right way to communicate with each other.

All this can therefore take more or less time... In general, ICE servers close to you are used.

**Comment by bzmework** [comment]
When I only share my desktop in the LAN, can I remove the turn server? How to do it. thank you

**Comment by ChristopheI** [comment]
If you target only LAN and you want only to stream a screen capture, use of WebRTC is perhaps not the correct way ...

WebRTC needs a signaling server.  This [article](https://medium.com/@jaysee.zhang/webrtc-for-dummies-395e07c90562) explains it why and how you can have your own.
