### ISSUE TITLE
Blind Transfer gives 407 Proxy Authentication Required

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [sipsorcery-org/sipsorcery#823]
Hi,

I tried this on multiple SIP providers, some work but some give 407 Proxy Authentication Required.

The issue is that SIPsorcery does not try to re-authenticate when it received such a response. I'm trying different workarounds trying to get it to work, including editing the source code of SIPsorcery.

The flow I'm doing is that I'm calling from my phone to SIP, and then trying to transfer the call elsewhere.

One of the extreme workarounds I managed to get to work as an experiment was to first call the number I'm trying to transfer to, when the call is answered I hang up and then use the authentication headers to do the transfer. That somehow works.

I've spent days desperately trying multiple experiments trying to get this to work and your help will be much appreciated.

**Comment by sipsorcery** [comment]
Did you spot the [Blind Transfer Scenario](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/SIPScenarios/BlindTransferScenario) in the SIP examples folder? It might provide a useful starting point.

**Comment by MarkCiliaVincenti** [comment]
I actually fixed the issue and created a PR for it at https://github.com/sipsorcery-org/sipsorcery/pull/828
