### ISSUE TITLE
Buffering on the WebRTC

### ISSUE THREAD

**Issue by mateusz-osojca** [sipsorcery-org/sipsorcery#824]
Is there any way to switch off totally buffering on the WebRTC side? Im using the H.264 under the hood with "zerolatency" option but anyways I think that jitter is comming to play on the WebRTC side and does some buffering. Software that I write requires real time even if under certain conditions we will have bad quality or loosing frames.

**Comment by sipsorcery** [comment]
There isn't any buffering going on this library. A jitter buffer has been deliberately ommitted and left up to the application (i've personally always found them to cause as many problems as they solve).

The only exception is the optional [reorder buffer](https://github.com/sipsorcery-org/sipsorcery/blob/b5b09edb191226a7e045f25f800d03c7e1bdaa1c/src/net/RTP/MediaStream.cs#L163) which isn't used unless ypur application explicitly requests it.

For video streams the RTP packets do need to be buffered until a complete frame is received but there's no way around that and the latency is between the start and end packets on a frame should be very low.

**Comment by forlayo** [comment]
How can I enable this reader buffer ? I am using PeerConnection and adding MediaStreamTracks but I don't see how to enable this buffer.

The reason of wanting to check it with this buffer is I am on troubles of receiving video with artefacts that looks fine before sending it, and wondering if the packets aren't arriving on right order..

**Comment by forlayo** [comment]
Ok I saw it, sorry:

`pc.VideoStream.AddBuffer(TimeSpan.FromSeconds(2));`
