### ISSUE TITLE
Method 'add_OnVideoSourceRawSampleFaster' in type 'SIPSorceryMedia.Windows.WindowsVideoEndPoint' from assembly 'SIPSorceryMedia.Windows, Version=0.0.31.0, Culture=neutral, PublicKeyToken=null' does not have an implementation

### ISSUE THREAD

**Issue by Yasopp** [sipsorcery-org/sipsorcery#826]
How to solve this problem？

**Comment by mbalatha** [comment]
I'm also hitting this one.  When I run I see the message that `WebRTC Get Started and waiting for web socket connections messgae`, I used the sample html page and click button that's where I'm also getting the same error. When I debug I see that CreatePeerConnection() method is not available, here:

```
webSocketServer.AddWebSocketService<WebRTCWebSocketPeer>("/", (peer) => peer.CreatePeerConnection = () => CreatePeerConnection());
```

**Comment by ChristopheI** [comment]
You use an old version of the package [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows): use at least [v6.0.3-pre](https://www.nuget.org/packages/SIPSorceryMedia.Windows/6.0.3-pre)

**Comment by mbalatha** [comment]
I see that I'm already using 6.0.9, here:

```
<ItemGroup>
   <PackageReference Include="SIPSorcery" Version="6.0.9" />
  <PackageReference Include="SIPSorceryMedia.Encoders" Version="0.0.10-pre" />
</ItemGroup>
```

**Comment by mbalatha** [comment]
If I rollback to 6.0.6 it works, getting same error from v6.0.7 through v6.0.9.

**Comment by ChristopheI** [comment]
SIPSorcery v6.0.9 is not using [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows) v6.0.3-pre.
Specify it in your packages

**Comment by ChristopheI** [comment]
> If I rollback to 6.0.6 it works, getting same error from v6.0.7 through v6.0.9.

SIPSorcery 6.0.7 (and greater) use a new version of SIPSorceryMedia.Abstractions **with a different interfaces.**

It's why you need to upgrade some packages like [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows)

**Comment by mbalatha** [comment]
Thanks, so should we keep it at 6.0.6 since that works as 6.0.9 is not working so I'm not sure I understand as what other packages needs to be upgraded. :(
