### ISSUE TITLE
There seems to be no way of handling a received SIPNonInviteTransaction asynchronously

### ISSUE THREAD

**Issue by axelsommerfeldt** [sipsorcery-org/sipsorcery#830]
I receive a SIP (non-INVITE) request via `SIPTransport.SIPTransportRequestReceived` and would like to use `SIPNonInviteTransaction` but handle the transaction asynchronously. This leads into the problem that duplicates are not detected reliably since `SIPNonInviteTransaction` will not be put into the transaction list of the transaction engine until `SIPNonInviteTransaction.SendResponse()` is called.

Inside the constructor of `SIPNonInviteTransaction` the following code lines could be found:
```
// This transaction type can be used to represent two different things:
// - a tx that the application wants to use to send a request reliably,
// - a tx for a request that has been received from a remote end point and that duplicates need
//   to be detected for.
// This block is for the second case. The tx request has been received and the tx engine
// needs to be signalled that it is now at the request processing stage.
base.UpdateTransactionState(SIPTransactionStatesEnum.Proceeding);
```
But just setting the transaction state is not sufficient here to offer what the code comment promises, "a tx for a request that has been received from a remote end point and that duplicates need to be detected for".

Proposed solutions:
1. Add `_sipTransport.AddTransaction(this);` inside the constructor of `SIPNonInviteTransaction`, right after the code line above.
2. or offer `void SetPending() -> _sipTransport.AddTransaction(this);`
3. or split `SIPNonInviteTransaction` into `UASNonInviteTransaction` and `UACNonInviteTransaction`, and `UASNonInviteTransaction` will have `_sipTransport.AddTransaction(this);` inside the constructor.

**Comment by sipsorcery** [comment]
Slightly late reply.

The SIPTranpsort class did have the facility to add transactions at one point, the commented out code can be seen [here](https://github.com/sipsorcery-org/sipsorcery/blob/e64ae708ac1d2445721088a9d38074b1ce7b11ec/src/core/SIP/SIPTransport.cs#L1240).

The main reasons the code was removed were to make SIP transaction management simpler and stop people shooting themselves in the foot. SIP transactions, particularly INVITEs, are complex beasts and it's best to leave the tried and tested logic to deal with them alone.

Another option would be for your application to create its own instance of the SIPTransacrionEngine (its currently internal but that would be easy to change) and you could use your own instance to manage requests however you needed. When it comes time to send the transaction logic in the SIPTransport class would be unaffected.
