### ISSUE TITLE
SipServerUserAgent.Answer is missing retransmit logic for invite responses?

### ISSUE THREAD

**Issue by henlil** [sipsorcery-org/sipsorcery#835]
Hi,

I'm using the SipUserAgent class to respond to invites from the server. The happy case of course works as expected. It responds with trying, ringing and once answered it responds with an OK and the expected ack is received. But if the server does not receive the OK response (UDP) and then where will never be an ACK from the server (and things starts to go wrong with the call as it won't be considered answered by the server). Do I need to manually add logic in my code for retransmitting the OK response or is this something that should have been handled by SipSorcery (but doesn't)?

I need confirmation there is actually a problem in SipSorcery before I jump to deep into the code. But what I found so far is that the final response OK, fired by calling sipUserAgent.m_uas.Answer, has to be retransmitted until transaction is confirmed. Also this transaction has to be aborted in case of sipUserAgent.Hangup() is called (happens after a delay of WAIT_DIALOG_TIMEOUT). I think the SipUserAgent:348 Task.Delay(WAIT_DIALOG_TIMEOUT) can be replaced by making SIPServerUserAgent.Answer async and return the dialog once the Ack is received or throw a timeout exception when the retransmit of the OK response timeouts.  

I would like feedback on this.

**Comment by henlil** [comment]
I fetched the latest master and was about to dig into this problem, and to my surprise I can see that the OK response is retransmitted when running unit tests like "IncomingCallNoSdpUnitTest"! I will try to reproduce the problem live, but I'll find it hard to block the first Ok response to an invite. I'm thinking of applications like https://jagt.github.io/clumsy/ but it can't block specific packages. Any Ideas on how to test this (dropping the first OK response of an invite request) in a live system? Maybe this would involve developing a SIPUDPDebugChannel capable of dropping specific messages? I guess the easiest thing would be to use an application like clumsy, dropping random packages, and run a load test, but that wouldn't be as delicate as testing the exact scenario. Any Idea how to setup packet loss tests?

**Comment by sipsorcery** [comment]
There is defintiely response retry logic present already. If you capture the SIP exhange using WireShark you'll see 11 retries.
