### ISSUE TITLE
Error in _peerConnection.SendAudio

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#837]
My setup code is

_audioEndPoint = new SDL2AudioEndPoint(AudioOutputName, _audioEncoder);
_audioEndPoint.SetAudioSinkFormat(_audioFormat.Value);

int frameSize = _audioEncoder.GetFrameSize();
_audioSource = new SDL2AudioSource(AudioInputName, _audioEncoder, (uint)frameSize);
_audioSource.SetAudioSourceFormat(_audioFormat.Value);

MediaStreamTrack audioInputTrack = new MediaStreamTrack(_audioSource.GetAudioSourceFormats(),
MediaStreamStatusEnum.SendRecv);
_peerConnection.addTrack(audioInputTrack);

_peerConnection.OnAudioFormatsNegotiated += (audioFormats) =>
{
_audioSource.SetAudioSourceFormat(audioFormats.First());
_audioEndPoint.SetAudioSinkFormat(audioFormats.First());
};

_audioSource.OnAudioSourceEncodedSample += _audioSource_OnAudioSourceEncodedSample;
_peerConnection.OnRtpPacketReceived += _peerConnection_OnRtpPacketReceived;

private void _audioSource_OnAudioSourceEncodedSample (uint durationRtpUnits, byte[] sample)
{       
                _peerConnection.SendAudio(durationRtpUnits, sample);
 }

Sometime I am getting error from _peerConnection.SendAudio and Error is "Cannot get the audio sending format, missing either local or remote audio track.". But not always.

Would you please help me in this regard.

**Comment by ChristopheI** [comment]
Like the error said: "missing either local or remote audio track."
So you send audio sample too soon => no Audio track are available
