### ISSUE TITLE
Microphone and speaker sound problems.

### ISSUE THREAD

**Issue by pssrecom** [sipsorcery-org/sipsorcery#841]
When I simultaneously transmit the following media:
Output screen.
Output speaker sound.
Output microphone sound.

When using webrtc.html to play on the browser side, the following problems occur:
The microphone sounds overlap.
Microphone sound and speaker sound cannot be output at the same time.

How to solve it? Are there any relevant examples? thank you.

**Comment by ChristopheI** [comment]
Are you using several WebRTC audio tracks or only one ?

I you are using only one it's a normal behavior if you don't mix the 2 audio sources in one:
- You send sample from source A (Sa) with a delay of Xa seconds
- You send sample from source B (Sb) with a delay of Xb seconds

Of peer side it doesn't know that there is several audio source, so he receives an audio sample (for example Sb first) he plays it for Xb second, then there is a new samble (Sa) playd for Xa seconds. Etc ...

If you use two WebRTC audio Track, now the peer knows there is the different source. It's now up to him to decide what to do: play only Sa, or only Sb. To play both in same time it must mix same

**Comment by sipsorcery** [comment]
The OS is responsible for controlling access to the aduio devices.
