### ISSUE TITLE
missing ice entries (tcp)

### ISSUE THREAD

**Issue by ispysoftware** [sipsorcery-org/sipsorcery#842]
I'm having a problem connecting to the webrtc server over the network from (possibly incidentally) osx devices - locally it works ok.
I have existing code using googles webrtc engine and it generates more remote candidates than SIPSorcery (I have X_ICEIncludeAllInterfaceAddresses set to true)

This is the google generated candidate list (7):

```
0: {sdp_mid: '0', sdp: 'candidate:2700940188 1 udp 2122260223 192.168.0.50…812 typ host generation 0 ufrag xu4B network-id 1', sdp_mline_index: 0}
1: {sdp_mid: '0', sdp: 'candidate:1175178625 1 udp 2122194687 172.31.128.1…813 typ host generation 0 ufrag xu4B network-id 4', sdp_mline_index: 0}
2: {sdp_mid: '0', sdp: 'candidate:3205790974 1 udp 2122129151 172.27.32.1 …814 typ host generation 0 ufrag xu4B network-id 5', sdp_mline_index: 0}
3: {sdp_mid: '0', sdp: 'candidate:1458399816 1 udp 1686052607 124.187.106.… rport 59812 generation 0 ufrag xu4B network-id 1', sdp_mline_index: 0}
4: {sdp_mid: '0', sdp: 'candidate:4001296236 1 tcp 1518280447 192.168.0.50…type passive generation 0 ufrag xu4B network-id 1', sdp_mline_index: 0}
5: {sdp_mid: '0', sdp: 'candidate:143143281 1 tcp 1518214911 172.31.128.1 …type passive generation 0 ufrag xu4B network-id 4', sdp_mline_index: 0}
6: {sdp_mid: '0', sdp: 'candidate:4053237774 1 tcp 1518149375 172.27.32.1 …type passive generation 0 ufrag xu4B network-id 5', sdp_mline_index: 0}
```

the sipsorcery list is only 3:

```
0: {sdp_mid: '0', sdp: 'candidate:2488 1 udp 2113937663 192.168.0.50 56271 typ host generation 0', sdp_mline_index: 0}
1: {sdp_mid: '0', sdp: 'candidate:2468 1 udp 2113937663 172.31.128.1 56271 typ host generation 0', sdp_mline_index: 0}
2: {sdp_mid: '0', sdp: 'candidate:2577 1 udp 2113937663 172.27.32.1 56271 typ host generation 0', sdp_mline_index: 0}
```

any ideas why they're not the same? all the tcp options seem to be missing - is that a config option?

**Comment by rafcsoares** [comment]
TCP IceCandidates is not supported by SipSorcery.. and probably will never be.

There's no reason to use TCP over UDP to connect to another peer.
Use a turn server with ?transport=tcp and ?transport=udp and you will be able to bypass even the most restrictive network firewall,

**Comment by ispysoftware** [comment]
"There's no reason to use TCP over UDP to connect to another peer."

.. well, there is, TCP has error correction baked into it which means data channels transferring files or even basic json packets for example don't get corrupted.
