### ISSUE TITLE
Add support for RTCP Extended Reports packets 

### ISSUE THREAD

**Issue by vangarp** [sipsorcery-org/sipsorcery#843]
Hi,

We are using an application "StartTrinity SIPTester" for testing SIP calls. It seems to send RTCP packets of type "Extended Report" (https://www.rfc-editor.org/rfc/rfc3611.html) which have the packet type of 207 (0xCF). SIPSorcery [does not handle these packets as RTCP packets](https://github.com/sipsorcery-org/sipsorcery/blob/4db5d1ab70139a090166f1c1d600f23ec56424fe/src/net/RTP/RTPSession.cs#L1983). This results in these being treated as RTP and as a result we end up calling the AdjustRemoteEndPoint method in MediaStream to change the RTP port to be the RTCP port and that in turns means that none of the audio we send back reaches the client (because we are sending audio on the RTCP port instead of the RTP port).

SIPSorcery version 6.0.9

**Comment by vangarp** [comment]
Atleast initially I am not even looking for the full functionality of being able to handle this type RTCP packet, but more what I am looking for is that such packet to not be treated as RTP packet like it is today.

**Comment by sipsorcery** [comment]
PR's welcome.
