### ISSUE TITLE
How to realize the ip phone proxy server function similar to opensips

### ISSUE THREAD

**Issue by atorzhang** [sipsorcery-org/sipsorcery#847]
Hello, I want to realize the intranet IP phone inter-dial function, similar to opensips, I saw that the REGISTER function is implemented in the projects UserAgentServer and SIPProxy in SIPExamples, but the INVITE function dial-up receiver does not ring, how to enable the receiver to receive to the caller's request? I'm not very skilled, thanks for the answer

**Comment by atorzhang** [comment]
Similar to implement pbx system

**Comment by sipsorcery** [comment]
The [SIPCallServer](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/SIPCallServer/Program.cs) is the closest example.
