### ISSUE TITLE
Fix EndHeaderPosn in ParseSIPMessage method when HeaderString contains Chinese Text

### ISSUE THREAD

**Issue by danch15** [sipsorcery-org/sipsorcery#848]
src/core/SIP/SIPMessageBuffer.cs

Line 154-155:
    sipMessage.Body = new byte[buffer.Length - (endHeaderPosn + 4)];
    Buffer.BlockCopy(buffer, endHeaderPosn + 4, sipMessage.Body, 0, buffer.Length - (endHeaderPosn + 4));

FIX BUG:
**int endHeaderBufferPosn = sipEncoding.GetByteCount(sipMessage.FirstLine) + 2 + sipEncoding.GetByteCount(headerString);**
sipMessage.Body = new byte[buffer.Length - (**endHeaderBufferPosn** + 4)];
Buffer.BlockCopy(buffer, **endHeaderBufferPosn** + 4, sipMessage.Body, 0, buffer.Length - (**endHeaderBufferPosn** + 4));

Example:
string sipFromName = “呼叫方名字”;
sipFromName.Length == 5
Encoding.UTF8.GetByteCount(sipFromName)==10

SIP/2.0 200 Ok
Via: SIP/2.0/UDP 172.17.3.2:5060;branch=z9hG4bKd9a520e54fca43438806fbdaf46e2532;rport=5060;received=172.17.3.2
To: "被叫方名字" <sip:5030003202@172.17.2.2>;CallScope=2;CallPriority=1;tag=ENVNTODUZJ
From: "呼叫方名字" <sip:57660000@172.17.2.2>;tag=FLYTRWSZOS
Call-ID: f99d53b50a254d9194381082b21af2cc
CSeq: 1 INVITE
Contact: <sip:172.17.2.2:5060>
User-Agent: SCT_DSS V1.0
Server: sipsorcery_v6.0.6.5
Supported: replaces, norefersub, 100rel
Content-Length: 250
Content-Type: application/sdp

v=0
o=- 1307081803 2 IN IP4 172.17.2.10
s=Asterisk
c=IN IP4 172.17.2.10
t=0 0
m=audio 19722 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv

**Comment by danch15** [comment]
May be this one faster than old one:
int endHeaderBufferPosn = **sipEncoding.GetByteCount(sipMessage.FirstLine) + 2 + sipEncoding.GetByteCount(headerString);**

**Comment by sipsorcery** [comment]
Fixed in #1223.
