### ISSUE TITLE
Remote ICE candidate only supports multiplexed media

### ISSUE THREAD

**Issue by aditj95** [sipsorcery-org/sipsorcery#850]
Trying to send a video stream from Unity WebRTC to SIPSorcery.Net using the WebSocketRTCPeer from the examples.

When exchanging candidates, onIceCandidateError throws the following exception:

Remote ICE candidate only supports multiplexed media, excluding remote candidate with non-zero sdpMLineIndex of 1.

Is this something that is not supported? Or is there a configuration to get this to work?

Note: There is already a data channel that has established prior to trying to add a new track.

**Comment by sipsorcery** [comment]
That's a weird error. WebRTC only supports multiplexed media and the media id 0, media id 1 etc are used to identify sections in the SDP to describe different media types. AFAIK there's no way to combine different media types into a single media id block.

As further evidence here's an SDP payload from Chrome which also has mid:0 & mid:1 blocks.

```
v=0
o=- 4288502424376524687 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVP 0 8 9 101
c=IN IP4 0.0.0.0
a=ice-ufrag:wH33
a=ice-pwd:5//A1y8uAbXUpApvDCjcShu3
a=fingerprint:sha-256 09:F5:45:76:39:EE:DB:08:58:67:27:7D:78:58:A0:7E:95:1E:03:59:66:81:70:65:7E:84:24:B1:A9:06:83:CB
a=setup:active
a=mid:0
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=rtcp:9 IN IP4 0.0.0.0
a=ice-options:trickle
a=rtcp-mux
a=recvonly
m=video 9 UDP/TLS/RTP/SAVP 96
c=IN IP4 0.0.0.0
a=ice-ufrag:wH33
a=ice-pwd:5//A1y8uAbXUpApvDCjcShu3
a=fingerprint:sha-256 09:F5:45:76:39:EE:DB:08:58:67:27:7D:78:58:A0:7E:95:1E:03:59:66:81:70:65:7E:84:24:B1:A9:06:83:CB
a=setup:active
a=mid:1
a=rtpmap:96 VP8/90000
a=rtcp:9 IN IP4 0.0.0.0
a=ice-options:trickle
a=rtcp-mux
a=recvonly
```
