### ISSUE TITLE
Growing memory consumption on SipTcpChannel

### ISSUE THREAD

**Issue by Educsys** [sipsorcery-org/sipsorcery#856]
After 12 hours test, i detect growing memory consumption every time, when method SendOnConnected is called. After a little code analysis, I tried to fix the leak using the dictionary for SocketAsyncEventArgs used for sending, this helped solve the problem, but sometimes an exception started appearing: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance. Now I have used the approach of one SocketAsyncEventArgs per data send, after each Complete event, i call SocketAsyncEventArgs.Dispose. The memory leak test was not performed, but the periodic exception disappeared. Has this problem been noticed by someone else and is the solution correct?

**Comment by sipsorcery** [comment]
This is a known issue. I've added it to the enhancements list #1226.
