### ISSUE TITLE
Unable to send video to Android Edge browser

### ISSUE THREAD

**Issue by bzmework** [sipsorcery-org/sipsorcery#857]
When I use websocket to request videos in webrtc.html, PC Server return offer:

type: offer
sdp:
v=0
o=- 13834 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
m=audio 9 UDP/TLS/RTP/SAVP 0 101
c=IN IP4 0.0.0.0
a=ice-ufrag:LXRZ
a=ice-pwd:XWUOQRLJBIHBALMBARCXBXNH
a=fingerprint:sha-256 B4:12:53:DE:0F:1D:BD:59:F9:D6:41:A1:7D:C7:D9:D0:AB:0D:3C:9D:4D:F3:B1:25:F9:26:81:50:E3:21:3B:57
a=setup:actpass
a=candidate:2153 1 udp 2113937663 26.26.26.1 65067 typ host generation 0
a=ice-options:ice2,trickle
a=mid:0
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=end-of-candidates
a=sendonly
a=ssrc:111067377 cname:af9b7cf7-a059-4074-a52e-a43f6abff3f3

m=video 9 UDP/TLS/RTP/SAVP 100
c=IN IP4 0.0.0.0
a=ice-ufrag:LXRZ
a=ice-pwd:XWUOQRLJBIHBALMBARCXBXNH
a=fingerprint:sha-256 B4:12:53:DE:0F:1D:BD:59:F9:D6:41:A1:7D:C7:D9:D0:AB:0D:3C:9D:4D:F3:B1:25:F9:26:81:50:E3:21:3B:57
a=setup:actpass
a=ice-options:ice2,trickle
a=mid:1
a=rtpmap:100 H264/90000
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=sendonly
a=ssrc:601265584 cname:875b3ab4-836e-41da-9b30-544d6b6e0d6e

Android Edge browser answer：
type: answer
sdp:
v=0
o=- 6717018667277989459 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS

m=audio 9 UDP/TLS/RTP/SAVP 0 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:8elL
a=ice-pwd:qelEyZYMQQ+MfW1Lq/OnGJ1K
a=ice-options:trickle
a=fingerprint:sha-256 A1:E2:BA:CD:34:DF:EF:BE:45:D0:66:E2:24:B0:AD:14:AE:8F:AF:5A:85:CC:58:34:92:47:CE:4B:33:D8:22:82
a=setup:active
a=mid:0
a=recvonly
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000

m=video 0 UDP/TLS/RTP/SAVP 0
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:FpSk
a=ice-pwd:RFPq7kkaHFy8dv+8ov9Lsm91
a=ice-options:trickle
a=fingerprint:sha-256 A1:E2:BA:CD:34:DF:EF:BE:45:D0:66:E2:24:B0:AD:14:AE:8F:AF:5A:85:CC:58:34:92:47:CE:4B:33:D8:22:82
a=setup:active
a=mid:1
a=recvonly
a=rtcp-mux

Missing in answer：a=rtpmap:100 H264/90000 
PC Unable to send video to Android Edge browser （No problem on PC to PC）
What's the problem？
Thanks!

**Comment by ChristopheI** [comment]
Your Android device doesn't accept the H264 codec.

You have to propose another Video codec. VP8 or VP9 for example

**Comment by bzmework** [comment]
> thank you. After I remove the RestrictFormats restriction and support VP8 and H264, Android can use it.
I use FFmpegVideoEncoder.
However, I checked the source code of sipsorcery. In VideoStream.cs, there is only the SendVp8Frame method.

**Comment by ChristopheI** [comment]
In `VideoStream. cs` you have also [SendH264Frame](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTP/VideoStream.cs#L134)
And even [SendRtpRaw](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTP/MediaStream.cs#L355) from inheritance of `MediaStream.Cs`
