### ISSUE TITLE
Rerun WebRTCWebcamServer camera is in use

### ISSUE THREAD

**Issue by fkdfz** [sipsorcery-org/sipsorcery#858]
When i first run the WebRTCWebcamServer project, it works fine. If i stop and rerun this project, it does not work. I test the camera with other programe, the error is "WebRTC error... Could not start video source".
When i restart the computer, the first run is ok.
I use the code tag v6.0.7

**Comment by fkdfz** [comment]
I resolve this question by close html socket first. If i stop the WebRTCWebcamServer first , the method rtcpeerconnection CloseVideo and CloseAudio can`t be invoke.
I don`t know why the camera is in use after the programe is shutdown.

**Comment by sipsorcery** [comment]
Sounds like the OS is keepng the webcam device open somehow. Ending the program should kill all its processes and release all device handles.
