### ISSUE TITLE
Crash in G722Codec.cs when called with odd number of shorts

### ISSUE THREAD

**Issue by ispysoftware** [sipsorcery-org/sipsorcery#860]
Need some check in G722Codec.cs Encoder as crash at line 417

state.QmfSignalHistory[23] = inputBuffer[j++];

if inputbuffer has odd length.

**Comment by sipsorcery** [comment]
PR's welcome. The g729 codec was a copy paste from another open source implentation.

**Comment by ElDuderinoBerlin** [comment]
Have had the same bug. The C# code is a port from old C code orginally. So it's an very old bug in the original source code.
Sadly i don't know how to fix it.

**Comment by ispysoftware** [comment]
I resolved this on my version with

```
state.QmfSignalHistory[22] = inputBuffer[j++];
if (j < inputBufferCount)
{
    state.QmfSignalHistory[23] = inputBuffer[j++];
}
else
{
    //Duplicate the last sample
    state.QmfSignalHistory[23] = state.QmfSignalHistory[22];
}
```
