### ISSUE TITLE
Cannot pass message content while initiating sip call

### ISSUE THREAD

**Issue by sabinaisayeva** [sipsorcery-org/sipsorcery#862]
As per RFC we are allowed to send different headers and body with SIP invite. In this case we can pass content type as multipart/mixed and body consisting of multiple contents separated by boundary. In sip sorcery package it is possible to set content however it is overridden by sdp while placing the call. 
Example in https://datatracker.ietf.org/doc/html/rfc8787
And description in SIP RFC: https://www.rfc-editor.org/rfc/rfc3261

**Comment by sipsorcery** [comment]
If you use the [Call method](https://github.com/sipsorcery-org/sipsorcery/blob/de91be67f8c79d6fd67bb5b18a7f9f33bd9ba6f5/src/app/SIPUserAgents/SIPUserAgent.cs#L485) that takes a SIPCallDescriptor you can set the [ContentType header and the Content body](https://github.com/sipsorcery-org/sipsorcery/blob/de91be67f8c79d6fd67bb5b18a7f9f33bd9ba6f5/src/app/SIPUserAgents/SIPCallDescriptor.cs#L98).
