### ISSUE TITLE
SIPSourcery WASM support

### ISSUE THREAD

**Issue by supapo** [sipsorcery-org/sipsorcery#869]
Does SIPSourcery support in blazor app as WASM?
I want to make a hybrid app, based on blazor, that runs on web, desktops and mobiles
Also, in .Net 7, there is the ability to [compile C# code to WASM](https://devblogs.microsoft.com/dotnet/use-net-7-from-any-javascript-app-in-net-7/) and run it from the JS. this means that this library is able to compete the SIP.js and JSSIP libraries because it can be very fast with native AOT!

**Comment by sipsorcery** [comment]
This library has no pinvoke or native dependencies so you should be able to compile to WASM without any mods reqd.

**Comment by CoderNate** [comment]
In case anyone else wonders about this, I attempted to use SipSorcery in an app running inside Wasmtime but seems that isn't currently possible.  There's some support for sockets (see [this](https://github.com/dotnet/runtime/issues/98957)) but stuff inside of System.Security.Cryptography throws `System.PlatformNotSupportedException` in .NET 10.0:
```
wasmtime-v47.0.3-x86_64-linux/wasmtime --dir . --wasi http --wasi inherit-network dotnet.wasm wasi_dotnet_test

Unhandled Exception:
System.AggregateException: One or more errors occurred. (The type initializer for 'SIPSorcery.Sys.Crypto' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'SIPSorcery.Sys.Crypto' threw an exception.
 ---> System.PlatformNotSupportedException: System.Security.Cryptography is not supported on this platform.
   at System.Security.Cryptography.RandomNumberGenerator..ctor()
   at System.Security.Cryptography.RNGCryptoServiceProvider..ctor()
   at SIPSorcery.Sys.Crypto..cctor()
   --- End of inner exception stack trace ---
   at SIPSorcery.Net.RTPSession..ctor(RtpSessionConfig config)
   at SIPSorcery.Net.RTPSession..ctor(Boolean isMediaMultiplexed, Boolean isRtcpMultiplexed, Boolean isSecure, IPAddress bindAddress, Int32 bindPort, PortRange portRange)
   at SIPSorcery.Net.RTCPeerConnection..ctor(RTCConfiguration configuration, Int32 bindPort, PortRange portRange, Boolean videoAsPrimary)
   at WasiMainWrapper.MainAsync(String[] args)
```
Quite possibly there are other reasons it wouldn't work but that's the first thing I hit.  Also, when trying to compile to WASM it uses native AOT and if you try to use `<PublishTrimmed>true</PublishTrimmed>` it looks like there are some ILLink errors from `Common.Logging.LogManager` and `TinyJson.JSONParser`.

**Comment by sipsorcery** [comment]
`SIPSorcery.Sys.Crypto` is mainly used to get pseudo-random values for various protocols. It doesn't do anything particularly exotic. If it breaks on the WASM runimte I'd expect the BouncyCastle crypto primitives would be the next break. That's where all the heavy duty cryptographic work happens.
