### ISSUE TITLE
RFC 7714 (AES-GCM AEAD support)

### ISSUE THREAD

**Issue by augustocb23** [sipsorcery-org/sipsorcery#871]
Hi all,
I'm currently working on a project and I need to secure the connection using a cryptography with 256-bit key. Reading the specifications, I found that original SRTP only require 128-bit algorithms ([RFC 3711](https://www.rfc-editor.org/rfc/rfc3711)), but a new specification ([RFC 7714](https://www.rfc-editor.org/rfc/rfc7714.html)) includes the support for AES-GCM algorithms, that supports 128 or 256-bit keys.

There are any plans to implement these specifications?

**Comment by richardblynd** [comment]
We are working on an implementation in the SIPSorcery library to support 128-bit and 256-bit AES-GCM encryption.
At the moment we are in the testing phase and I believe that soon we will be able to submit a PR.
