### ISSUE TITLE
Call transfer queue

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [sipsorcery-org/sipsorcery#874]
I'm trying to create a queue for call transfers. The problem is that when we do a blind or attended transfer, the SIP server sends us a BYE on the original call so we have no means of knowing when the call ended so as to try to transfer the next call in the queue. Is there a means for us to do that? Perhaps using conference and just 'listening in' (i.e. no audio mixing) just to know when the other parties hung up?

Because otherwise the only solution I can think of is polling the phone to see if it's busy or not, and if it's not try to do an attended transfer with who is next in the queue.

**Comment by sipsorcery** [comment]
You can use SIP subscriptions to get NOTIFY requests about events on remote SIP user agents. It will depend on the remote device supporting subscriptions but it's a failry common scenario.
