### ISSUE TITLE
H264 bad video after passing through network; issue with packetization/depacketization apparently..

### ISSUE THREAD

**Issue by forlayo** [sipsorcery-org/sipsorcery#877]
I am trying to fix an issue that comes from sending the Android camera using SipSorcery, after several tests I ended up recording the stream in raw h264 just before sending it and just when receiving it at the other side. And the issue is still there so I would say that something is not going well on network transmission.

As a proof of this I've recorded the h264 stream just before calling [OnVideoSourceEncodedSample](https://file.io/HWyPEiGcAFxI) on video source and recorded same on the other party on [OnVideoFrameReceived.](https://file.io/pZjfZHcgd80r)

As you an see on file recorded at [OnVideoSourceEncodedSample](https://file.io/HWyPEiGcAFxI) video looks pretty fine, but at receiving side at [OnVideoFrameReceived.](https://file.io/pZjfZHcgd80r) it looks with artefacts, specially on movement.

Note: You can play these raw h264 files with ffplay, vlc or Elmedia Player.

Comparing ([using h264streamanalysis tool](https://sourceforge.net/projects/h264streamanalysis/)) the stream we can see that there are errors, on received stream at NAL 98 (for example) the type is not correct, neither the size and it's followed by an invalid frame as wel..

![image (5)](https://user-images.githubusercontent.com/1199238/205315747-7c321d70-5b03-4a2d-89f5-255181b10ef4.png)

**Comment by forlayo** [comment]
This could be related with https://github.com/sipsorcery-org/sipsorcery/issues/378 I think..

**Comment by forlayo** [comment]
I am checking with latest version of master, just wondering if the changes to rtp mtu to 1200 fixes my issue.  But it's still happening..

**Comment by forlayo** [comment]
Could it be an issue related to packet loss ? Just basing my answer as the receiving side is somehow corrupt and the effect is like this one (more or less) -> [http://www.mediapro.cc/rtp抗丢包传输方案/](http://www.mediapro.cc/rtp%E6%8A%97%E4%B8%A2%E5%8C%85%E4%BC%A0%E8%BE%93%E6%96%B9%E6%A1%88/)

If so.. I think I am on a big issue as this library doesn't have any mechanism for packet loss right ?

**Comment by forlayo** [comment]
I saw on a bit old Microsoft example a full implementation of FEC using XOR, just in case this helps -> https://github.com/conferencexp/conferencexp/blob/master/MSR.LST.Net.Rtp/fec.cs#L47

**Comment by sipsorcery** [comment]
There is no proper RTCP feedback mechanism in the sipsorcery library and minimal work has been done to wire up the video encoders to trigger key frames in the event of packet loss. I'm adding this issue to the list of enhancements. It's a BIG job to sort this out.
