### ISSUE TITLE
SIP Proxy with Asterisk

### ISSUE THREAD

**Issue by asadcr** [sipsorcery-org/sipsorcery#880]
Hi, i came Across [305](https://github.com/sipsorcery-org/sipsorcery/issues/305) which mentions `SIPProxy` to work with Asterisk. My goal is to build similar. 

A Simple SIP Proxy that can exchange messages between SoftPhone and Asterisk. And Intercept INVITE Responses to support [PUSH Notifications](https://www.rfc-editor.org/rfc/rfc8599). I only want to utilize simple SIP forwarding and no RTP. RTP Should be handled directly.  

The given examples does not use `SIPRegistrationUserAgent` for registration to Asterisk. Also how can i implement the INVITE packet implementation so it can send out the coming request from Asterisk to SoftPhone or Vice Versa. 
I am using LinPhone as SoftPhone now.

**Comment by sipsorcery** [comment]
The closest example is the [SIPProxy](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/SIPExamples/SIPProxy) one.
