### ISSUE TITLE
Data Channels Stuck on "Closing" state

### ISSUE THREAD

**Issue by alt95** [sipsorcery-org/sipsorcery#882]
Seems like a very simple issue but haven't been able to get anything to work.

Setup:
Server using SipSorcery
Webpage running JavaScript

Makes connection and creates data channel(s) to send/receive data with no problems.

When `dataChannel.close()` is called on the web page, the server never fires onClose. The data channel on the web page also does not fire `RTCDataChannel.onclosing` or `RTCDataChannel.onclose `events.

When looking at chrome internals, the data channel is forever stuck on the "closing" readyState.

Note: `peerConnection.close()` does close the channels, but I want to leave the connection open and only close the data channel.

**Comment by ChristopheI** [comment]
pb fixed here #1058 and her #1059
