### ISSUE TITLE
Question about best architecture for building SIP server

### ISSUE THREAD

**Issue by estewui** [sipsorcery-org/sipsorcery#883]
Hi, I want to use your library for building a SIP server. Main goal is to have a centralized app, where I will initialize VOIP calls to clients and after the client accepts the call, the call will be transferred to the free consultant (for now it will be around 20 consultants). 

What would be the correct way of doing that? 
First idea that popped inside my head is to build two separate apps:
- server, which will set up calls with the clients and transfer them using UserAgent.BlindTransfer
- client app, which will be running on every consultant's computer, responsible for SIP registration and connection with audio/microphone

These 2 apps could communicate over WebSockets or HTTP. Is it possible to have only one server app that somehow connects computers of all consultants without the need of running client application on every computer or not? I have a working example of setting up calls and transferring them, but all takes place on my local computer, I just don't know which direction should I take to achieve the goals without having too many issues.

I would really appreciate the tip what's the best way to build this simple SIP server.

Thanks,
Stanisław

**Comment by sipsorcery** [comment]
I relalise this answer is a bit late but if you need to handle the call media this is not the right library for you. Managed dev environments like dotnet don't play well with high performance media. You'd be better off with a native dev env like C++ or Rust.
