### ISSUE TITLE
CPU usage rises high when PeerConnection close() method has been called

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#886]
I am using sipsorcery with SIPSorceryMedia.SDL2. After successful call, when I terminate the call, I call-

1. _peerConnection.close()
2. It fired OnPeerConnectionClose event [Custom Event based on RTCPeerConnectionState.closed]
3. In this event, I am closing _audioSource.CloseAudio() & _audioEndPoint.CloseAudioSink()
4. _audioSource = null;_audioEndPoint = null; _audioEncoder = null; _peerConnection = null;

After every call, CPU usage is going higher and higher.

BUT, IF I DO NOT CALL _peerConnection.close(), and manually call _audioSource.CloseAudio() & _audioEndPoint.CloseAudioSink()
THEN CPU usage is near about zero(0). And working fine in debug/release mode from source code.

But when I am using the exe, then 30% of CPU is always blocked after first and subsequent call.

**Comment by jp-fournier-dev** [comment]
I am investigating an issue similar to this, when WebRtc calls are closed, there's a rise in CPU usage. With profiling, it seems like threads with the prefix "rtcsctprecv-" are using up CPU time. 

Seems like those are created by the `RTCSctpTransport` class which is created inside of the RTCPeerConnection. Keep you posted on this if I find anything more and a fix

**Comment by jp-fournier-dev** [comment]
Doing this change on the RTCPeerConnection fixes the issue. I will create a PR fix.

![image](https://user-images.githubusercontent.com/7319702/214897415-a88f0b5e-3858-4cc5-8ff0-32d0509f0b5d.png)
The additional check would end up not closing the SCTP transport correctly and the receive loop thread would go on as fast as possible. The check is also done inside the close method of transport, so I don't think it is necessary

**Comment by jp-fournier-dev** [comment]
#887 should fix the issue

**Comment by mail2mhossain** [comment]
Has this fix been released?
