### ISSUE TITLE
IVideoEncoder implementation missing methods

### ISSUE THREAD

**Issue by maximusmp** [sipsorcery-org/sipsorcery#888]
Hi,

I am using SIPSorcery for a videocall application using the WebRTC protocol.

I installed the SIPSorcery package (version 6.0.11) using NuGet, and I noticed that it installs the reference to SIPSorceryMedia.Abstractions v1.2.0.
Now, the IVideoEncoder interface in this package contains two methods, EncodeVideoFaster and DecodeVideoFaster, that are not implemented in class VpxVideoEncoder of library SIPSorceryMedia.Encoders (v0.0.10-pre). For this reason, when I try to use this class, I get a System.TypeLoadException.
I'm using the classes as suggested in WebRTCWebcamServer class of WebRTCExamples.

Do you have an idea on how to safely overcome this issue?

Thank you!
Massimiliano

**Comment by sipsorcery** [comment]
Should be fixed if you use the latest nuget packages. They seem to have gotten out of sync at some point.
