### ISSUE TITLE
 at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.SocketReceiveFromResult>.GetResult(Int16 token)    at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)

### ISSUE THREAD

**Issue by wobushiafa** [sipsorcery-org/sipsorcery#890]
The following is done when the form opens and closes   

 protected override async Task OnActivateAsync(CancellationToken cancellationToken)
    {
        _pc = new RTCPeerConnection();

        _videoEP = new FFmpegVideoEndPoint();
        _videoEP.RestrictFormats(d => d.Codec == VideoCodecsEnum.H264);
        _videoEP.SetVideoSourceFormat(new VideoFormat(VideoCodecsEnum.H264, VideoFormat.DYNAMIC_ID_MAX));
        _videoEP.OnVideoSinkDecodedSampleFaster += OnUpdateImage;

        _videoTrack = new MediaStreamTrack(SDPMediaTypesEnum.video,
                false,
                new List<SDPAudioVideoMediaFormat>
                    {
                        new SDPAudioVideoMediaFormat(new VideoFormat(VideoCodecsEnum.H264,102))
                    },
                MediaStreamStatusEnum.RecvOnly);
        _pc.addTrack(_videoTrack);
        var sdp = _pc.createOffer();
        var response = await _webRTCRerpository.ExchangeSDP(_url, sdp.sdp, "admin", MD5Helper.MakeSign("admin"));
        _pc.setRemoteDescription(new RTCSessionDescriptionInit { type = RTCSdpType.answer, sdp = response.Sdp });
    }

    protected override async Task OnDeactivateAsync(bool close, CancellationToken cancellationToken)
    {
        _videoEP.OnVideoSinkDecodedSampleFaster -= OnUpdateImage;
        _pc.OnVideoFrameReceived -= _videoEP.GotVideoFrame;
        _pc.OnVideoFormatsNegotiated -= (formats) => _videoEP.SetVideoSinkFormat(formats.First());
        await _videoEP.PauseVideo();
        await _videoEP.CloseVideo();
        _pc.removeTrack(_videoTrack);
        _pc.Dispose();

        _videoEP = null;
        _pc = null;
        DisplayImage = null;
        await base.OnDeactivateAsync(close, cancellationToken);
    }

**Comment by ChristopheI** [comment]
A form can be activated / deactivated very quickly ...
You try to do things which can take a very long time (at least you call async methods ...)
You must think in a different way to manage this
