### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by buldo** [sipsorcery-org/sipsorcery#894]
Hello.
I making library that is heavily based on sipsorcery source code.
Actually I copied and refactoried a bit part of code that listens RTP stream and provides encoded video frames.
Can you describe what should I put in my license file?

**Comment by sipsorcery** [comment]
You can use any license you want. The sipsorcery MIT license does not impose any restrictions on how you use the card. An attribution would be nice though.

**Comment by buldo** [comment]
Thank you for answer
