### ISSUE TITLE
No RTCP Packets Sent

### ISSUE THREAD

**Issue by jerro-org** [sipsorcery-org/sipsorcery#899]
The event `OnReportReadyToSend` that should trigger sending RTCP packets and is defined here:
https://github.com/sipsorcery-org/sipsorcery/blob/019050c99e02a293da861a2bb4394c807c79f420/src/net/RTCP/RTCPSession.cs#L169
is not assigned anywhere in the sipsorcery library. Has this been forgotten or is an application supposed to do it itself like this:
`_mediaSession.AudioRtcpSession.OnReportReadyToSend += (_, p) => _mediaSession.AudioStream.SendRtcpReport(p);`

**Comment by sipsorcery** [comment]
It's called on the base RTCPSession. one example being when the [session is closed](https://github.com/sipsorcery-org/sipsorcery/blob/32d6dcf87e89b0048dcc103222d7bea3deae5d8b/src/net/RTCP/RTCPSession.cs#L208).
