### ISSUE TITLE
How to configure STUN Client?

### ISSUE THREAD

**Issue by shushil** [sipsorcery-org/sipsorcery#904]
Hello, 
I am new to this SipSorcery and this STUN stuff. Sorry in advance if I miss interpret something.
I am trying to connect to STUN server on the sip.us "https://support.sip.us/hc/en-us/articles/214706803-Interconnecting-with-SIP-US-The-Basics". 
So I am using one SIPTransport object for placing outgoing call and also listening on incoming SIP call using SIPRegistrationUserAgent.

When using STUN connection as suggested on this "[https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/Softphone/Signalling/STUNClient.cs" based on previous](https://github.com/sipsorcery-org/sipsorcery/issues/203)"
I am updating SIPTransport.ContactHost information and calling IMediaSession.CreateOffer on the outgoing calls. So, I am getting registration timeout error and my call are not going through.

So, my questions are: 
1> Should I user different SIPTransport object for outgoing calls and SIPRegistrationuserAgent?
2> Do I need to add SIPChannel when using STUN? what should be the channel IpEndpoint? should it be one i get using "STUNClient.GetPublicIPEndPoint" this call?
3> When using STUN when creating SIPRegistrationuserAgent should I use SIP credentials and server info or should i use STUN server credentials and server info i got from "STUNClient.GetPublicIPEndPoint"?

Again, Sorry if I have misunderstood anything.
Thank you very much.

**Comment by sipsorcery** [comment]
I realise this answer is somewhat late.

SIP and STUN are very different protocols. The way they interact is if your SIP device is behind a NAT you will often use a STUN client to determine what your public IP address is. You then let the SIP stack know what the public IP address is so it can use it in the SIP headers.

The explanation in #203 and the code it links to are still valid.
