### ISSUE TITLE
Proxy support for `RTCPeerConnection`

### ISSUE THREAD

**Issue by lostmsu** [sipsorcery-org/sipsorcery#906]

**Comment by sipsorcery** [comment]
Do you mean a SOCKs proxy? How would this work? WebRTC is designed to connect peers directly not via any intermediaries.

**Comment by lostmsu** [comment]
I guess there's already a mechanism similar to SOCKS: TURN. The reason for suggesting SOCKS is that TURN is less ubiquitous.
