### ISSUE TITLE
Audio quality distortion (static noise etc).

### ISSUE THREAD

**Issue by xBasov** [sipsorcery-org/sipsorcery#908]
Update to SipSorcery ver 6.0.12 ruined audio quality. (Worked in 6.0.11).

When making a regular call from soft phone made by SipSorcery to SipSorcery everything works as regular, however making or receving call through other soft phone (Zoiper, Jitsi) the call quality is awful. (Calls through Asterisk).

**Comment by jsmhlz** [comment]
Can second this issue, on some SIP trunks this is happening. 
I can see that the transcoding going on under the hood is transcoding to a codec that hasn't been negotiated. For example, our trunk negotiates PCMA and in wireshark I can see PCMA RTP packets going in both directions. The raw audio bytes actually in the RTP packet is PCMU

**Comment by sipsorcery** [comment]
Should be fixed in #1216.
