### ISSUE TITLE
SIPProxy

### ISSUE THREAD

**Issue by DavidTzur1** [sipsorcery-org/sipsorcery#909]
Hi,
I try to build SIPProxy for IMS and i use the SIPProxy Example.
I add to the SIPTransportRequestReceived logic 
...
else if (sipRequest.Method == SIPMethodsEnum.UPDATE)
{
     logger.LogDebug("UPDATE")
}

...

The problem is i don't get the UPDATE request
Attach pcap - line 14 is update

Br,
David Tzur
        
[UPDate.zip](https://github.com/sipsorcery-org/sipsorcery/files/11090167/UPDate.zip)

**Comment by DavidTzur1** [comment]
Hi,
Checking the code in the SIPTransport class, I see that for request with   header  Required return badRequireResp.
I only use as proxy .
Why the response is badRequireResp ?

Br.
David Tzur

**Comment by sipsorcery** [comment]
If your application is operating as a SIP Proxy it shouldn't have a problem forwarding UPDATE requests. Are you bale to provide a SIP trace of the traffic into and out of the proxy?

The SIP peer the UPDATE request is being forwarded to might be rejeccting it. It's not a very common or well supported method.

**Comment by DavidTzur1** [comment]
[UPDate.zip](https://github.com/sipsorcery-org/sipsorcery/files/11157575/UPDate.zip)

Add Trace

Br,
David Tzur

**Comment by DavidTzur1** [comment]
Hi,

This is code from the SIPHeader.cs(line 1762)  it Causes the code in SIPTransport class return error

 #region Require.
                        else if (headerNameLower == SIPHeaders.SIP_HEADER_REQUIRE.ToLower())
                        {
                            sipHeader.Require = headerValue;

                            **if (!String.IsNullOrEmpty(sipHeader.Require))
                            {
                                sipHeader.RequiredExtensions = SIPExtensionHeaders.ParseSIPExtensions(sipHeader.Require, out 
                                   sipHeader.UnknownRequireExtension);
                            }**
                        }

**Comment by sipsorcery** [comment]
Only just getting around to looking at this now.

The failure response was because the UPDATE request has a `Require: timer` header. This library does not support the required extension (RFC 4028, "Session Timers in the Session Initiation Protocol (SIP).
