### ISSUE TITLE
sip call doesn't work via softphone 404 NOT FOUND

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [sipsorcery-org/sipsorcery#910]
goodmorning,
i am trying to user softphone ,when i try to call via sip an internal i receive 404 not found
i have check that credentials are correct,if i try to call via anonymous it works
can you help me?
the sip server is a yeastar that use asterisk
thanks

this is the log
UAC commencing call to sip:1002@192.168.0.150:5060.
[10:45:50 DBG] Request Sent udp:192.168.0.47:5060<-udp:192.168.0.150:5060: INVITE sip:1002@192.168.0.150 SIP/2.0.
[10:45:50 DBG] Response Received udp:0.0.0.0:5060<-udp:192.168.0.150:5060: INVITE 401 Unauthorized.
[10:45:50 DBG] Request Sent udp:192.168.0.47:5060<-udp:192.168.0.150:5060: ACK sip:1002@192.168.0.150 SIP/2.0.
[10:45:50 DBG] Response 401 Unauthorized for sip:1002@192.168.0.150.
[10:45:50 DBG] Request Sent udp:192.168.0.47:5060<-udp:192.168.0.150:5060: INVITE sip:1002@192.168.0.150 SIP/2.0.
[10:45:50 DBG] Response Received udp:0.0.0.0:5060<-udp:192.168.0.150:5060: INVITE 404 Not Found.
[10:45:50 DBG] Request Sent udp:192.168.0.47:5060<-udp:192.168.0.150:5060: ACK sip:1002@192.168.0.150 SIP/2.0.
[10:45:50 DBG] Response 404 Not Found for sip:1002@192.168.0.150.
[10:45:50 WRN] Call attempt was answered with failure response INVITE 404 Not Found.
[10:45:50 DBG] Call failed: Not Found.

**Comment by andreameneguzzoinfol** [comment]
this is the log via wireshark
`Frame 1995: 956 bytes on wire (7648 bits), 956 bytes captured (7648 bits) on interface \Device\NPF_{3ADCF5FF-CB9B-4BAA-866F-E18670D92A2E}, id 0
Ethernet II, Src: HP_19:aa:ce (7c:4d:8f:19:aa:ce), Dst: XiamenYe_f9:fa:65 (f4:b5:49:f9:fa:65)
Internet Protocol Version 4, Src: 192.168.0.47, Dst: 192.168.0.150
User Datagram Protocol, Src Port: 5060, Dst Port: 5060
Session Initiation Protocol (INVITE)
    Request-Line: INVITE sip:1002@192.168.0.150 SIP/2.0
        Method: INVITE
        Request-URI: sip:1002@192.168.0.150
        [Resent Packet: False]
    Message Header
        Via: SIP/2.0/UDP 192.168.0.47:5060;branch=z9hG4bK0f2a1f3a54a44bd29fb9301d23ac4b16;rport
        To: <sip:1002@192.168.0.150>
        From: "client" <sip:1000@192.168.0.150>;tag=MOLNOOXDFS
        Call-ID: 5d519307c6cf41ccb9938b9dd9933279
        [Generated Call-ID: 5d519307c6cf41ccb9938b9dd9933279]
        CSeq: 1 INVITE
        Contact: <sip:1000@192.168.0.47:5060>
        Max-Forwards: 70
        User-Agent: sipsorcery_v6.0.6.0
        Supported: replaces, norefersub, 100rel
        Content-Length: 456
        Content-Type: application/sdp
    Message Body



Frame 1998: 577 bytes on wire (4616 bits), 577 bytes captured (4616 bits) on interface \Device\NPF_{3ADCF5FF-CB9B-4BAA-866F-E18670D92A2E}, id 0
Ethernet II, Src: XiamenYe_f9:fa:65 (f4:b5:49:f9:fa:65), Dst: HP_19:aa:ce (7c:4d:8f:19:aa:ce)
Internet Protocol Version 4, Src: 192.168.0.150, Dst: 192.168.0.47
User Datagram Protocol, Src Port: 5060, Dst Port: 5060
Session Initiation Protocol (401)
    Status-Line: SIP/2.0 401 Unauthorized
        Status-Code: 401
        [Resent Packet: False]
        [Request Frame: 1995]
        [Response Time (ms): 11]
    Message Header
        Via: SIP/2.0/UDP 192.168.0.47:5060;rport=5060;received=192.168.0.47;branch=z9hG4bK0f2a1f3a54a44bd29fb9301d23ac4b16
        Call-ID: 5d519307c6cf41ccb9938b9dd9933279
        [Generated Call-ID: 5d519307c6cf41ccb9938b9dd9933279]
        From: "client" <sip:1000@192.168.0.150>;tag=MOLNOOXDFS
        To: <sip:1002@192.168.0.150>;tag=z9hG4bK0f2a1f3a54a44bd29fb9301d23ac4b16
        CSeq: 1 INVITE
        WWW-Authenticate: Digest  realm="YSAsterisk",nonce="1680081381/0f984019576b4f6c270ec774e227abda",opaque="4fee36413b477249",algorithm=md5,qop="auth"
        Server: Yeastar S20-30.15.0.115
        Content-Length:  0


Frame 2006: 392 bytes on wire (3136 bits), 392 bytes captured (3136 bits) on interface \Device\NPF_{3ADCF5FF-CB9B-4BAA-866F-E18670D92A2E}, id 0
Ethernet II, Src: HP_19:aa:ce (7c:4d:8f:19:aa:ce), Dst: XiamenYe_f9:fa:65 (f4:b5:49:f9:fa:65)
Internet Protocol Version 4, Src: 192.168.0.47, Dst: 192.168.0.150
User Datagram Protocol, Src Port: 5060, Dst Port: 5060
Session Initiation Protocol (ACK)
    Request-Line: ACK sip:1002@192.168.0.150 SIP/2.0
        Method: ACK
        Request-URI: sip:1002@192.168.0.150
        [Resent Packet: False]
        [Request Frame: 1995]
        [Response Time (ms): 92]
    Message Header
        Via: SIP/2.0/UDP 192.168.0.47:5060;branch=z9hG4bK0f2a1f3a54a44bd29fb9301d23ac4b16;rport
        To: <sip:1002@192.168.0.150>;tag=z9hG4bK0f2a1f3a54a44bd29fb9301d23ac4b16
        From: "client" <sip:1000@192.168.0.150>;tag=MOLNOOXDFS
        Call-ID: 5d519307c6cf41ccb9938b9dd9933279
        [Generated Call-ID: 5d519307c6cf41ccb9938b9dd9933279]
        CSeq: 1 ACK
        Max-Forwards: 70
        Content-Length: 0


Frame 2018: 1220 bytes on wire (9760 bits), 1220 bytes captured (9760 bits) on interface \Device\NPF_{3ADCF5FF-CB9B-4BAA-866F-E18670D92A2E}, id 0
Ethernet II, Src: HP_19:aa:ce (7c:4d:8f:19:aa:ce), Dst: XiamenYe_f9:fa:65 (f4:b5:49:f9:fa:65)
Internet Protocol Version 4, Src: 192.168.0.47, Dst: 192.168.0.150
User Datagram Protocol, Src Port: 5060, Dst Port: 5060
Session Initiation Protocol (INVITE)
    Request-Line: INVITE sip:1002@192.168.0.150 SIP/2.0
        Method: INVITE
        Request-URI: sip:1002@192.168.0.150
        [Resent Packet: False]
    Message Header
        Via: SIP/2.0/UDP 192.168.0.47:5060;branch=z9hG4bKb96f9ed4b3a24d8da6a494598ee7c4b7;rport
        To: <sip:1002@192.168.0.150>
        From: "client" <sip:1000@192.168.0.150>;tag=MOLNOOXDFS
        Call-ID: 5d519307c6cf41ccb9938b9dd9933279
        [Generated Call-ID: 5d519307c6cf41ccb9938b9dd9933279]
        CSeq: 2 INVITE
        Contact: <sip:1000@192.168.0.47:5060>
        Max-Forwards: 70
        User-Agent: sipsorcery_v6.0.6.0
         [truncated]Authorization: Digest username="1000",realm="YSAsterisk",nonce="1680081381/0f984019576b4f6c270ec774e227abda",uri="sip:1002@192.168.0.150",response="68a4721322c748810af5302bcdbb585f",cnonce="1554473777",nc=00000001,qop=auth,opa
        Supported: replaces, norefersub, 100rel
        Content-Length: 456
        Content-Type: application/sdp
    Message Body



Frame 2022: 422 bytes on wire (3376 bits), 422 bytes captured (3376 bits) on interface \Device\NPF_{3ADCF5FF-CB9B-4BAA-866F-E18670D92A2E}, id 0
Ethernet II, Src: XiamenYe_f9:fa:65 (f4:b5:49:f9:fa:65), Dst: HP_19:aa:ce (7c:4d:8f:19:aa:ce)
Internet Protocol Version 4, Src: 192.168.0.150, Dst: 192.168.0.47
User Datagram Protocol, Src Port: 5060, Dst Port: 5060
Session Initiation Protocol (404)
    Status-Line: SIP/2.0 404 Not Found
        Status-Code: 404
        [Resent Packet: False]
        [Request Frame: 2018]
        [Response Time (ms): 32]
    Message Header
        Via: SIP/2.0/UDP 192.168.0.47:5060;rport=5060;received=192.168.0.47;branch=z9hG4bKb96f9ed4b3a24d8da6a494598ee7c4b7
        Call-ID: 5d519307c6cf41ccb9938b9dd9933279
        [Generated Call-ID: 5d519307c6cf41ccb9938b9dd9933279]
        From: "client" <sip:1000@192.168.0.150>;tag=MOLNOOXDFS
        To: <sip:1002@192.168.0.150>;tag=d9c4520a-f639-4054-853f-2ebb1b5c55ca
        CSeq: 2 INVITE
        Server: Yeastar S20-30.15.0.115
        Content-Length:  0
`

**Comment by mjalil** [comment]
> Hi, Here, I have the same problem with the Softphone example solution. Could you let me know if your issue has been resolved? Any help? [@andreameneguzzoinfol](https://github.com/andreameneguzzoinfol)

I found the solution to the problem with the Yeastar SIP server. It can be found at #445 in [this comment](https://github.com/sipsorcery-org/sipsorcery/issues/445#issuecomment-800938885)

To fix the problem, add a `sendUsernameInContactHeader: true` to the arguments of the constructor of `SIPRegistrationUserAgent` in [line 130](https://github.com/sipsorcery-org/sipsorcery/blob/0f60bc39b4753c6f3c827074302443e9edd33aac/examples/Softphone/Softphone.xaml.cs#L130)

I will also open a PR to fix the codebase
