### ISSUE TITLE
Transmitting in-band RTP events and audio packets on a media stream

### ISSUE THREAD

**Issue by CNH01** [sipsorcery-org/sipsorcery#914]
Hi, 

Thanks for all your work on sipsorcery. 

**Summary**
I noticed that SendDtmfEvent was moved out of RTPSession.cs and into AudioStream.cs since v6.0.8. With this change, I think it has been made possible to transmit duplicate RTP events with inconsistent timestamps - which violates [RFC4733](https://www.rfc-editor.org/rfc/rfc4733#section-2.5.1.2) (granted SipSorcery only claims to support [RFC2833](https://www.rfc-editor.org/rfc/rfc2833#section-3.6), but I've also heard 4733 being referred to as 2833.. this issue seems worthwhile to fix anyway - as SendDTMF is important for SIP clients and a fix looks easy). 

_Note this issue is similar to https://github.com/sipsorcery-org/sipsorcery/discussions/588._

**Context**
To recap, in AudioStream.cs SendDtmfEvent is currently (v6.0.12) wrapped with a Boolean flag rtpEventInProgress as a kind of "lock" on the media stream. If a thread enters SendAudioFrame or SendDtmfEvent while rtpEventInProgress = true then the payload or event is dropped. That's fine (more or less). 

**Reproduction steps & Impact**
However, issues can occur if a thread enters SendAudioFrame and a second thread enters SendDtmfEvent before the first thread finishes. This can cause: 
- RTP packets (an audio frame) to be sent in-between the burst of RTP event (DTMF) packets
- The timestamp for duplicate RTP event packets to be incremented (which can reasonably lead to double DTMF digit detection on the recipient's side). 

**Suggestions**
I would like to propose two hardening approaches, I'm happy to make a pull request for these if you agree, I just thought I should post here first to talk it through: 

1. Wrap SendAudioFrame with a new Boolean try {audioFrameInProgress = true; ...} finally {audioFrameInProgress = false;} and check this value upon entering SendDtmfEvent (set the lock rtpEventInProgress = true then wait up to 50ms(? maybe dependent on the negotiated SDP) for audioFrameInProgress to be false). This should prevent RTP events from starting to be sent while an audio frame is finished being sent. 
2. In SendDtmfEvent, before sending any RTP events, store the current timestamp on the local media stream track 
var currentTimestamp = LocalTrack.Timestamp;
and use this as the timestamp in SendRtpRaw. This should ensure that timestamps are always consistent for duplicate RTP events. If currentTimeStamp != LocalTrack.Timestamp on exiting SendDtmfEvent then log a warning (to help future debuggers)? 

There are probably many more elegant approaches (semaphores? locks? mutexes?). Complications with locks arise because SendAudioFrame and SendDtmfEvent are asynchronous and sorry I'm not an expert on semaphores or mutexes. I have suggested a fairly simple approach but they seem to work, testing locally.

**Comment by sipsorcery** [comment]
Sorry for the delayed response. DTMF does not get a lot of love these days.

More than happy to take a PR if you're still interested. Your approach sounds sensible.
