### ISSUE TITLE
RtspToWeb/FFmpegToWebrtc .  Demux rtsp by ffmpeg . Restream

### ISSUE THREAD

**Issue by Dmise** [sipsorcery-org/sipsorcery#917]
Hello, want to finalize my project and add to examples folder of the SipSorcery lib (say to contribute). Suppose there are people who faced with troubles with multiple track in one RTCPeerConnection. 

first of all want to get advise how to Mux two RTP (audio + video), that I get by ffmpeg process. into one RTCPeerConnetion
(now I see only video stream and for some reason audio frames have not catched. row 91 FFmpegListener.cs newer reached)

sequence of my doings
1) Create demuxer  (configure ffmpeg process,  in a word start such a process
`ffmepg -re -i {0} -an -vcodec {1} -ssrc {2} -f rtp rtp://{3}:{4} -vn -acodec {5} -ssrc {6} -f rtp rtp://{3}:{7} -sdp_file {8}`
2) Run demuxer (works fine. In CLI i see frames, sdp file is created)
3) Create FFmpegListner.cs (it should listen audio and video RTP, and Invoke event when catch a frame)
for each rtp stream I create RTPSession (audio + video)
4) Configure each RTPSession.  (think my mistake is here. when read sdp. exact when use RTPSession.SetRemoteDescription).
4.1) read general sdp from file. (get SIPSorcery.Net.SDP)
4.2) to get SDP for video RTPSession, remove audio announcment from general SDP.
4.3)  to get SDP for audio RTPSession, remove video announcment from general SDP.

5) Create WebScoektSignalingServer.  (its responsible for signaling process)
here made according to the sample from the library (FFmpegToWebrtc). Seems its works : sdp sending to webbrowser 
6) Configure RTCPeerConnection (not sure I do it right way)

Below the sdp file content ##### stream.sdp
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
t=0 0
a=tool:libavformat 59.35.100
m=video 5202 RTP/AVP 96
c=IN IP4 127.0.0.1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
m=audio 5204 RTP/AVP 8
c=IN IP4 127.0.0.1
b=AS:64
```

link to the projet:
https://github.com/Dmise/RtspToWeb

**Comment by ChristopheI** [comment]
Hi,
In the SDP generated It's strange for audio, there is no line with "a=rtpmap:8 PCMA/8000"
Also could you share the result of "sdpAudio" and "sdpVideo" ?

**Comment by Dmise** [comment]
## question 1
I've googled and  `a=rtpmap:8 PCMA/8000`  mean G.711 codec, its exist `G.711 alaw`, and `G.711 mulaw`. Clear.
My ip camera can give both of them. Select G.711alaw and make few examples.

1) example 1
camera output: G.711alaw
ffmpeg arguments:
ffmpeg -re -i rtsp://admin:HelloWorld4@192.168.1.64:554/ISAPI/Streaming/Channels/101 -an -vcodec copy -f rtp rtp://127.0.0.1:5020 -vn -acodec copy -f rtp rtp://127.0.0.1:5022 -sdp_file A:\temp\sdp\exp1.sdp

###### exp1.sdp
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
t=0 0
a=tool:libavformat 59.35.100
m=video 5020 RTP/AVP 96
c=IN IP4 127.0.0.1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z01AKI2NQDwBE/LgLcBAQFAAAD6AAAw1DoYAPDQAAX14LvLjQwAeGgAAvrwXeXCg,aO44gA==; profile-level-id=4D4028
m=audio 5022 RTP/AVP 8
c=IN IP4 127.0.0.1
b=AS:64
```


2) example 2
camera output: G.711alaw
ffmpeg arguments:
ffmpeg -re -i rtsp://admin:HelloWorld4@192.168.1.64:554/ISAPI/Streaming/Channels/101 -vn -acodec copy -f rtp rtp://127.0.0.1:5022 -sdp_file A:\temp\sdp\exp2.sdp

###### exp2.sdp
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 59.35.100
m=audio 5022 RTP/AVP 8
b=AS:64
```

3) example 3
camera output: G.711alaw
ffmpeg arguments:
ffmpeg -re -i rtsp://admin:HelloWorld4@192.168.1.64:554/ISAPI/Streaming/Channels/101 -vn -acodec pcm_alaw -f rtp rtp://127.0.0.1:5022 -sdp_file A:\temp\sdp\exp3.sdp

###### exp3.sdp
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 59.35.100
m=audio 5022 RTP/AVP 8
b=AS:64
```
Result: I do not know how to get `a=rtpmap:8 PCMA/8000` raw using ffmpeg comands.

---

## question 2

I want to point that these are not two separate files. Each of SDP created from single sdp file created by ffmpeg process.
They created in this way. (not sure that its good idea have only one sdp file and create two SIPSorcery.Net.SDP classes from it)

```
// create sdpVideo
var sdpVideo = SDP.ParseSDPDescription(File.ReadAllText(_dc.sdpPath));            
var videoAnn = sdpVideo.Media.Find(x => x.Media == SDPMediaTypesEnum.video);
var audioAnn = sdpVideo.Media.Find(x => x.Media == SDPMediaTypesEnum.audio);
sdpVideo.Media.Remove(audioAnn);
// cretae sdpAudio
var sdpAudio = SDP.ParseSDPDescription(File.ReadAllText(_dc.sdpPath));
sdpAudio.Media.Remove(videoAnn);
```

in this example the ffmpeg command is 
`ffmpeg -re -i rtsp://admin:HelloWorld4@192.168.1.64:554/ISAPI/Streaming/Channels/101 -an -vcodec h264 -f rtp rtp://127.0.0.1:5202 -vn -acodec pcm_alaw -f rtp rtp://127.0.0.1:5022 -sdp_file A:\temp\sdp\exp4.sdp`

values catched while debuging.
sdpAudio:
```
{v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
t=0 0
a=tool:libavformat 59.35.100
m=video 5202 RTP/AVP 96
c=IN IP4 127.0.0.1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=sendrecv
m=audio 5204 RTP/AVP 8
c=IN IP4 127.0.0.1
b=AS:64
a=rtpmap:8 PCMA/8000
a=sendrecv
}
```

sdpVideo:
```
{v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
t=0 0
a=tool:libavformat 59.35.100
m=video 5202 RTP/AVP 96
c=IN IP4 127.0.0.1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=sendrecv
}
```
###### exp4.sdp
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
t=0 0
a=tool:libavformat 59.35.100
m=video 5202 RTP/AVP 96
c=IN IP4 127.0.0.1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
m=audio 5204 RTP/AVP 8
c=IN IP4 127.0.0.1
b=AS:64
```

**Result:**  
Running webrtc_tester.html I see only video. Event _audioRTP.OnRtpPacketReceived does not Invoking.

**Comment by Dmise** [comment]
I've decided this issue. Want to share my example with the community.

Here is [pull request](https://github.com/sipsorcery-org/sipsorcery/pull/922]) to my example. Hope it will added to main branch.

**Comment by jimm98y** [comment]
I've tried to do something similar, but I did not want to have any ffmpeg dependencies as I don't think they are necessary. My project is here if somebody wants to take a look: https://github.com/jimm98y/SharpRTSPtoWebRTC
