### ISSUE TITLE
Username with domain different to SIP-domain BUG

### ISSUE THREAD

**Issue by maddinthegreat** [sipsorcery-org/sipsorcery#918]
Hi,

there is a bug when users have a username with a domain appended to it domain like:

User: 490312345657@1und1.de 
SIP server: sip.1und1.de

then you'll get:

Registration failed with BadRequest for sip:490312345657@1und1.de@sip.1und1.de.

by using:

`new SIPRegisterAccount( "490312345657@1und1.de", "pw123456#", "sip.1und1.de", 120)`

Should be fixed.

Regards
Martin

**Comment by sipsorcery** [comment]
The '@' character in the username is not valid according to the SIP spec and even if it was it'd be asking for trouble to use it.
