### ISSUE TITLE
Reduce video bitrate on high packet loss

### ISSUE THREAD

**Issue by ghost** [sipsorcery-org/sipsorcery#923]
Hi,

I use SipSorcery to receive video from chrome.
If I simulate packet loss or bandwidth limitations on the network I expected that chrome reduces the sender bitrate.

In chrome webrtc-internals I can see the packet loss and high roundtriptime for the receiver.

![Screenshot 2023-04-24 090957](https://user-images.githubusercontent.com/88649311/233926298-8232c156-82fc-4db3-836b-55a224aa8322.png)

However the target bitrate for sending video remains the same.

![Screenshot 2023-04-24 090943](https://user-images.githubusercontent.com/88649311/233926230-17dee843-2476-4200-916d-40e85d5ca9fd.png)

I've added the video track as follows.
```cs
var track = new MediaStreamTrack(new VideoFormat(VideoCodecsEnum.H264, 108));
_peerConnection.addTrack(track);
```

Is it possible to tell the browser to dynamically reduce the video bitrate?

**Comment by sipsorcery** [comment]
In theory yes and a bit of work has been done on [RTCPFeedback](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTCP/RTCPFeedback.cs) packets but it hasn't gotten as far as writing the hooks so a video source can can make use of it to adjust the bit rate.
