### ISSUE TITLE
Need help with WebSocket connection

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#926]
@sipsorcery I was going through [FFmpegFileAndDevicesTest](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/tree/master/test/FFmpegFileAndDevicesTest). In this code a websocket server is being created and the PeerConnection is added to the websocket. Is there any way to connect to an external websocket server instead of creating one. The code is 

	static void Main()
        {
            Console.WriteLine("WebRTC MP4 Source Demo");

            logger = AddConsoleLogger();

            // Initialise FFmpeg librairies
            SIPSorceryMedia.FFmpeg.FFmpegInit.Initialise(SIPSorceryMedia.FFmpeg.FfmpegLogLevelEnum.AV_LOG_FATAL, LIB_PATH);

            // Start web socket.
            Console.WriteLine("Starting web socket server...");
            var webSocketServer = new WebSocketServer(IPAddress.Parse("127.0.0.1"), WEBSOCKET_PORT);
            // var webSocketServer = new WebSocketServer("ws://localhost:8081");
            webSocketServer.AddWebSocketService<WebRTCWebSocketPeer>("/", (peer) => peer.CreatePeerConnection = CreatePeerConnection);
            webSocketServer.Start();

            Console.WriteLine($"Waiting for web socket connections on {webSocketServer.Address}:{webSocketServer.Port}...");
            Console.WriteLine("Press ctrl-c to exit.");

            // Ctrl-c will gracefully exit the call at any point.
            ManualResetEvent exitMe = new ManualResetEvent(false);
            Console.CancelKeyPress += delegate (object sender, ConsoleCancelEventArgs e)
            {
                e.Cancel = true;
                exitMe.Set();
            };

            // Wait for a signal saying the call failed, was cancelled with ctrl-c or completed.
            exitMe.WaitOne();
        }

**Comment by ChristopheI** [comment]
Sure it's possible. But the examples are written to be as simple as possible
And it's already difficult to update them each time the project is updated/improved

**Comment by nodminger** [comment]
I have created an external websocket and modified nosignalling code to work with it.
