### ISSUE TITLE
Is there support to set stats like latency, jitter, packet loss, etc. in SIPSorcery?

### ISSUE THREAD

**Issue by akamilkhan** [sipsorcery-org/sipsorcery#932]
Is there support to set stats like latency, jitter, packet loss, etc. in SIPSorcery?

There is this webrtc API (https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats) that can provide low-level statistics, is this API or something similar implemented in SIPSorcery?

**Comment by ChristopheI** [comment]
Unfortunately no.
