### ISSUE TITLE
Equals throws InvalidCastException

### ISSUE THREAD

**Issue by weihog** [sipsorcery-org/sipsorcery#934]
I tried to use a Json serializer to log objects at certain stages in my code and InvalidCastException is thrown from some Equals methods when comparing objects of different types.

To reproduce use Newtonsoft.Json to serialize SIPRequest.
`
JsonConvert.SerializeObject(new SIPRequst(SIPMethodsEnum.REGISTER, "sip:127.0.0.1:5060"));
`

I identified that this problem exisits in:
STUNUri
SIPURI
SIPEventDialogStateEvent
SIPParameters

A better implementation for this exists in SIPEndPoint.

**Comment by sipsorcery** [comment]
PR's welcome.
