### ISSUE TITLE
Test PlaceCallUsingSDPDescriptorWithWrongContentFailsUnitTest passes when it should not

### ISSUE THREAD

**Issue by kuleshov-aleksei** [sipsorcery-org/sipsorcery#936]
Hello! There is a test [PlaceCallUsingSDPDescriptorWithWrongContentFailsUnitTest](https://github.com/sipsorcery-org/sipsorcery/blob/master/test/integration/app/SIPUserAgentUnitTest.cs#L469) in [SIPUserAgentUnitTest.cs](https://github.com/sipsorcery-org/sipsorcery/blob/master/test/integration/app/SIPUserAgentUnitTest.cs) which passes with following logs:

```
Standard Output: 
13:02:25.6204 [Debug]  --> MoveNext
13:02:25.6208 [Information]  SIP UDP Channel created for udp:127.0.0.1:56393.
13:02:25.6211 [Debug] ["MoveNext"] Attempting call to sip:127.0.0.1:56393.
13:02:25.6218 [Information]  SIP UDP Channel created for udp:0.0.0.0:56396.
13:02:25.6227 [Debug] ["MoveNext"] Request received: INVITE sip:127.0.0.1:56393 SIP/2.0
13:02:25.6235 [Debug] ["MoveNext"] Server agent answer result True.
13:02:25.6733 [Debug] ["MoveNext"] Client agent answer result True.
```

But test exepects `false` result: `Assert.False(callResult);`

Seems like something was changed under the hood

**Comment by sipsorcery** [comment]
Checked test. Is working correctly, may have been a temporary break. 

SDP of "wrongcontent" is generating a failure response of NoRemoteMedia.
