### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by jcorert** [sipsorcery-org/sipsorcery#940]
Be great if support for running clients behind a HTTP proxy could be added. A lot of organisations are still running HTTP proxies for outbound communication. Had a few issues with not being able to get TURN clients to work for example, because of this.

I'm assuming it would be would be possible to use something like HttpWebResponse.GetResponseStream to setup a data stream through a HTTP proxy using HTTP CONNECT, then treat it like a standard TCP stream, leaving .NET to manage the underlying connection.

**Comment by sipsorcery** [comment]
To proxy which protocol? SIP could in theory use a HTTP proxy but all the WebRTC connections are UDP only.
