### ISSUE TITLE
trying to buy license

### ISSUE THREAD

**Issue by AmparoGuiase** [sipsorcery-org/sipsorcery#941]
https://www.sipsorcery.com/mainsite/Purchase?purchaseType=Professional

Hi guys, how are you?

I'm trying to buy a license and the site is giving an error.
Does anyone know why?

Thanks
![Imagem do WhatsApp de 2023-05-26 à(s) 15 14 05](https://github.com/sipsorcery-org/sipsorcery/assets/76967356/98935198-f65a-4cc5-972a-19faa6ed79df)

**Comment by AmparoGuiase** [comment]
![image](https://github.com/sipsorcery-org/sipsorcery/assets/76967356/43ca1e59-0aff-4c79-8546-14021fbcc4b0)

https://www.sipsorcery.com/mainsite/Purchase/Payment?purchaseType=Professional&customerID=71fcd358-80f7-48c7-8c6a-50827ec8b254

**Comment by sipsorcery** [comment]
I've emailed you out of band. Closing as not related to this repo.

**Comment by AmparoGuiase** [comment]
Sorry, but could you tell me which email you sent it to? please?
because I didn't receive
