### ISSUE TITLE
Initial RTP packet's timestamp should be random (RFC 3550)

### ISSUE THREAD

**Issue by CNH01** [sipsorcery-org/sipsorcery#943]
As per RFC 3550, the initial timestamp on an RTP stream should be random. However, according to .\net\RTP\MediaStreamTrack.cs, the timestamp of the initial RTP packet always defaults to zero. 

> Sequence Number
> The initial value of the sequence number SHOULD be random (unpredictable) to make known-plaintext attacks on encryption more difficult
> 
> Timestamp
> The initial value of the timestamp SHOULD be random, as for the sequence number

https://datatracker.ietf.org/doc/html/rfc3550

A simple fix is to instantiate MediaStreamTrack.Timestamp as a random number: 
Timestamp = Convert.ToUInt32(Crypto.GetRandomInt(0, Int16.MaxValue));
Similar to how Ssrc and m_seqNum are currently instantiated:
https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/RTP/MediaStreamTrack.cs#L175 

Happy to open a pull request for this, please let me know any feedback.

**Comment by ChristopheI** [comment]
Don't hesitate to create a PR.
Thanks

**Comment by sipsorcery** [comment]
The RTP timestamp does [get intialised](https://github.com/sipsorcery-org/sipsorcery/blob/de91be67f8c79d6fd67bb5b18a7f9f33bd9ba6f5/src/net/RTP/RTPHeader.cs#L60) to a pseudo-random value.
