### ISSUE TITLE
Life-Cycle Methods on IAudioSink not called

### ISSUE THREAD

**Issue by 2steuer** [sipsorcery-org/sipsorcery#947]
Hi,
I'm currently playing around with SipSorcery and apart from the astonishing work done here, I've come accross an inssue which is bothering me and I'm seeking advice to maybe create a pull request for this...

The VoIPMediaSession() does only call the Life-Cycle Methods (StartAudio, CloseAudio, ...) only on the Audio **source**, but not on the Audio **sink**, which is totally fine when both are one class.

My current use case is a bit different, as the source and sink are two very different classes (and thus, objects), which do not necessarily know about each other. 

Should I add the calls to the IAudioSink Life-Cycle Methods or rather use a different Class than VoIPMediaSession? I'm quite new here and do not yet have a complete overview over SipSorcery. I can provide with sample code in my repository, if needed.

Thanks!

**Comment by sipsorcery** [comment]
I realise this is a bit of a late reply but the reason there are no such methods on the audio sink is that it's typically a speaker device and you don't start or stop speakers. Instead you just send your audio to it and that's it. Generally mutliple apps can use a speaker without issues, other than the audio overlap.

Audio sources on the other hand are typically microphones and need to be told when to start sampling their input and when to stop. Normally only one device at a time can access a microphone.
