### ISSUE TITLE
OnDtmfTone triggered multiple times

### ISSUE THREAD

**Issue by Maurotb** [sipsorcery-org/sipsorcery#950]
HI,
when I call my program from a mobile phone,
OnDtmfTone is triggered 7 times.
When i call my program from deskphone, OnDtmfTone is correctly triggered 1 times.

Example from deskphone

received DTMF tone 1, duration 400ms

example from mobile:

received DTMF tone 1, duration 160ms
received DTMF tone 1, duration 320ms
received DTMF tone 1, duration 480ms
received DTMF tone 1, duration 640ms
received DTMF tone 1, duration 800ms
received DTMF tone 1, duration 960ms
received DTMF tone 1, duration 1120ms

Analyzing wireshark, I see that deskphone calls come with

N.5 rtpevent packages
N.1 rtp event end packet

from mobile phone they arrive with

N.7 rtpevent packets (which correspond to the number of events generated)
N.3 RTP packages EVENT END

Is there a problem when multiple event ends arrive? How can I solve the problem? Thank you

**Comment by Maurotb** [comment]
After some debug, i see _rtpEventSsrc is always 0 in call from mobile.
This cause the problem.... 
This variable is set by rtpHeader.SyncSource, there is a problem in parsing header?

**Comment by Maurotb** [comment]
Solvet putting un sipuseragent.cs
private uint _rtpEventSsrc = 4294967295; instead of 0,
and changing this

      private void OnRemoteRtpEvent(IPEndPoint remoteEP, RTPEvent rtpEvent, RTPHeader rtpHeader)
        {
            OnRtpEvent?.Invoke(rtpEvent, rtpHeader);

            if (OnDtmfTone != null)
            {
                if (_rtpEventSsrc == 4294967295)  
                {
                    if (rtpEvent.EndOfEvent && rtpHeader.MarkerBit == 1)
                    {
                        // Full event is contained in a single RTP packet.
                        //logger.LogDebug($"RTP event {rtpEvent.EventID}.");

                        OnDtmfTone.Invoke(rtpEvent.EventID, rtpEvent.Duration);
                    }
                    else if (!rtpEvent.EndOfEvent)
                    {
                        //logger.LogDebug($"RTP event {rtpEvent.EventID}.");
                        _rtpEventSsrc = rtpHeader.SyncSource;

                        OnDtmfTone.Invoke(rtpEvent.EventID, rtpEvent.Duration);
                    }
                }

**Comment by sipsorcery** [comment]
The fix of hardcoding the SSRC value won't work. That's a pseudo random value and is expected to change for every RTP session.

The cause of the issue here is why the RTP packet received on the mobile app have `syncsource 0`. That's whats breaking the DTMF method's ability to collate mutliple RTP packets into a single DTMF event.
