### ISSUE TITLE
Cannot register to 3CX V18

### ISSUE THREAD

**Issue by Paolo113** [sipsorcery-org/sipsorcery#952]
SIPRegistrationUserAgent allow only Username and Password.
3CX require Username, Login and Password.

How can I pass the right credential?

**Comment by palybok** [comment]
For 3cx you need this: 
`new SIPRegistrationUserAgent(new SIPTransport(), null, new SIPURI("my_3cx_extension", "my_3cx_domain", null), "my_3cx_login", "my_3cx_password", null, "my_3cx_domain", new SIPURI("my_3cx_extension", "my_3cx_domain", null), 3600, null, 60, 300, 3, true );`
