### ISSUE TITLE
SIPRegistrationUserAgent with Custom Headers (Authorization Bearer Token)

### ISSUE THREAD

**Issue by iniamudhan** [sipsorcery-org/sipsorcery#955]
I'm trying to register using SIPRegistrationUserAgent with a custom header to use the Bearer token. 

But the request received on the server has `Authorization: Digest realm=""`. And on the response it gives `WW-Authenticate: Digest realm="example.com", nonce="r1+****+xeTEz**fiinD***A", qop="auth"`

I'm expecting to just send the token added. What could be the fix?

```
userAgent = new SIPRegistrationUserAgent(
      _sipTransport,
      null,
      new SIPURI(_phoneNumber, _server, null, SIPSchemesEnum.sip),
      _phoneNumber,
      null,
      null,
      _server,
      new SIPURI(SIPSchemesEnum.sip, IPAddress.Any, 0),
      120,
      new[] { "Authorization: Bearer asdfsd.afdsf.*****asdfa" }
    );
```

**Comment by sipsorcery** [comment]
If you have any docs on the SIP Registrar server that support bearer tokens feel free to post them but I'v never come across one.

SIP authentication uses digests and typically created with a usernae and password. Bearer tokens are used mainly for HTTP authentication.
