### ISSUE TITLE
Slow Parse times

### ISSUE THREAD

**Issue by CoderJoeW** [sipsorcery-org/sipsorcery#961]
Running locally testing the performance of SIPRequest.ParseSIPRequest

I pass in the following string

INVITE sip:1112223333@1.1.1.1:5060;transport=udp SIP/2.0
Via: SIP/2.0/UDP 5.5.5.5:5080;branch=z9hG4bKFQamuarZ;rport
From: <sip:2223332233@1.1.1.1>;tag=542A74E5-64AD7CDB00025F8D-5BA54700
To: <sip:1112223333@1.1.1.1>
CSeq: 10 INVITE
Call-ID: adsadsaseasaasdasadsawsd
Route: <sip:2.2.2.2:5060;received=sip:1.1.1.1:5060%3blr%3btransport%3dudp;lr>
Max-Forwards: 70
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, SUBSCRIBE, NOTIFY, PUBLISH, MESSAGE
Supported: replaces
Content-Type: application/sdp
Contact: <sip:5.5.5.5:5080;transport=udp>
Content-Length: 322

The execution time ranges wildly between 26-106ms

This may be fine for some cases but I am building a live network monitoring tool and 26ms on the low end of things is still just going to be way to slow.

Here to find out what I can do to get around this

**Comment by CoderJoeW** [comment]
https://stackoverflow.com/questions/76665506/sipsorcery-slow-parsing-times

**Comment by mahald** [comment]
SIP Sorcery is a powerful tool that handles all the parsing tasks for you, thereby saving you significant time in development. It provides an existing, well-designed solution, thus eliminating the need to reinvent the wheel.

One common pitfall in software development is premature optimization, which often leads to unnecessary complexity and an extended development timeline. By utilizing tools like SIP Sorcery, you can avoid this pitfall, thereby accelerating your development process.

The critical question to ask when considering a solution is: "Is it fast enough for my specific use case?" From my experience, I can attest that SIP Sorcery has served me well. I've been able to process between 6-8k messages per second using 4 Intel Silver 2.2 GHz CPU cores.

However, it's important to note that in many scenarios, the limiting factor isn't the parsing speed of the tool, but rather the capacity of the network stack traffic. In other words, the bottleneck often arises from network traffic handling, not the computational capabilities of the CPUs or the efficiency of the SIP Sorcery tool.

Therefore, I recommend considering SIP Sorcery for your project, provided it satisfies your speed and performance requirements. It strikes an excellent balance between accelerating the development process and delivering strong runtime performance.

**Comment by ChristopheI** [comment]
@CoderJoeW, 
Don' t hesitate to propose a PR. 
It seems you have made a major improvement about this
Thx

**Comment by sipsorcery** [comment]
I suspect the test results are a bit misleading. Doing a single parse test is not a good appraoch as there can be other things going on like dotnet intialising etc. Plus it used to be the case that the .Net Framework timer could never time anything under ~25ms so if it took 1ms the timer would still report 25ms.

A better test is to do 10k parse operations, run it 3 times and take the average.

```
using SIPSorcery.SIP;
using System.Diagnostics;

var reqStr = @"INVITE sip:1112223333@1.1.1.1:5060;transport=udp SIP/2.0
Via: SIP/2.0/UDP 5.5.5.5:5080;branch=z9hG4bKFQamuarZ;rport
From: sip:2223332233@1.1.1.1;tag=542A74E5-64AD7CDB00025F8D-5BA54700
To: sip:1112223333@1.1.1.1
CSeq: 10 INVITE
Call-ID: adsadsaseasaasdasadsawsd
Route: sip:2.2.2.2:5060;received=sip:1.1.1.1:5060%3blr%3btransport%3dudp;lr
Max-Forwards: 70
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, SUBSCRIBE, NOTIFY, PUBLISH, MESSAGE
Supported: replaces
Content-Type: application/sdp
Contact: sip:5.5.5.5:5080;transport=udp
Content-Length: 322";

var sw = new Stopwatch();
sw.Start();

for (int i = 0; i < 10000; i++)
{
    var req = SIPRequest.ParseSIPRequest(reqStr);
}

sw.Stop();
Console.WriteLine($"Total duration {sw.ElapsedMilliseconds} ms.");
Console.WriteLine($"Avg duration for single parse {sw.ElapsedMilliseconds/10000} ms.");`
```

Results:

```
c:\dev\SIPParseTest>dotnet run
Total duration 679 ms.
Avg duration for single parse 0 ms.

c:\dev\SIPParseTest>dotnet run
Total duration 640 ms.
Avg duration for single parse 0 ms.

c:\dev\SIPParseTest>dotnet run
Total duration 682 ms.
Avg duration for single parse 0 ms.
```

Parsing a SIP message involves string and regex operations. Something is very wrong if it's taking anywhere near 100ms. Circa 1ms is more like it,
