### ISSUE TITLE
Settings for latency focused Datachannel

### ISSUE THREAD

**Issue by akamilkhan** [sipsorcery-org/sipsorcery#964]
Hello, 

I am using data channel to communicate data which is latency critical. What settings to use to get the best possible latency and jitter?

**Comment by camnewnham** [comment]
What settings are you referring to? Semi-reliable WebRTC datachannels are not currently supported, so your options are minimal.

**Comment by sipsorcery** [comment]
Unless it's for a game where the user need near-realtime feedback jitter doesn't really make sense to worry about for the data channel.

And as far as latency goes the data channel uses UDP under the hood so it's as good as it gets.
