### ISSUE TITLE
RTPHeader Extension infinite loop

### ISSUE THREAD

**Issue by mmjc23** [sipsorcery-org/sipsorcery#966]
Good morning

I encountered a problem while using your library with a probably non-standard RTP stream.

While decoding the RTP stream, the library tries to get the RTP Header Extensions (Class: `RTPHeader` - Method: `GetHeaderExtension`) but it stays forever in the while loop because `i` is never incremented.

The byte array of ExtensionPayload of the received RTP stream is as follows
`00-00-00-00-00-09-9E-1C-00-00-00-00-00-00-00-71-00-00-00-00-00-00-00-00-13-03-00-00-00-00-00-00`

I solved it by adding `return extensions`, immediately after `var extensions = new List<RTPHeaderExtensionData>();` in `GetHeaderExtension` method.

Can you think of any other solutions to this problem?
This problem occurred after upgrading to library 6.0.12; with the 6.0.3 library, this didn't happen (probably, because the 6.0.3 library didn't try to get the Header Extension from the RTP stream).

Thank you in advance and congratulations for the excellent work.

**Comment by pedoc** [comment]
Can you share the complete RTP packet?

**Comment by pedoc** [comment]
> This is what Wireshark shows me for the first RTP packet received:

I checked the data you shared, we don't know this extension currently, but there is a bug in the previous processing logic, and it eventually leads to an infinite loop

This issue has been fixed in #967

**Comment by mmjc23** [comment]
Thank you very much pedoc
Best regards.
