### ISSUE TITLE
Is it possible to increase video quality in VP8?

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#968]

**Comment by nodminger** [comment]
It can be done by increasing the quality form Sipsorcery.FFmpeg source code.

**Comment by lukedukeus** [comment]
@nodminger Can you explain how you were able to increase the quality / what you changed?

**Comment by nodminger** [comment]
I don't have access to the source now. I think in VideoEncoder.cs or VideoDecoder.cs, there will be some arguments. You can use them to give custom number(I mean quality), Then lesser the number, more the quality will be. You might also need to increase the buffersize.
