### ISSUE TITLE
Simulcast support

### ISSUE THREAD

**Issue by tasnimjubaier** [sipsorcery-org/sipsorcery#971]
Our project requires support for simulcast transmission between devices (PWA, IOS, Android). Is there any support for this currently? Will there be any release addressing this in the near future?

**Comment by mail2mhossain** [comment]
Is the simulcast logic implemented in the SipSorcery library?

**Comment by ChristopheI** [comment]
Simulcast is not supported.
Don't hesitate to participate to this project
