### ISSUE TITLE
Receiving Substreams from Simulcast-Enabled Devices Without Simulcast Implementation 

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#976]
We are currently utilizing Janus as our media server.

Our setup involves joining a video room with an SDP generated by SipSorcery. When another device transmits video with simulcast enabled, we receive one of the following streams (either 1 or 2) once the WebRTC connection is established:

```json
{
   "janus": "event",
   "session_id": 4591975740462470,
   "sender": 3564487309735126,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "event",
         "room": 222528007479603,
         "mid": "0",
         "substream": 2
      }
   }
}
```

Is it possible in SipSorcery to retrieve this substream without having to implement simulcast on our end in SipSorcery?

**Comment by ChristopheI** [comment]
Simulcast is not supported.
PR  welcome
