### ISSUE TITLE
What is the alternative to ontrack?

### ISSUE THREAD

**Issue by tylerlong** [sipsorcery-org/sipsorcery#983]
I used to write WebRTC code in JavaScript. There is an `ontrack` event. Example: https://github.com/sipsorcery-org/sipsorcery/blob/2e28a633ff675915d3e593cab338580f01a76122/examples/WebRTCExamples/FfmpegToWebRTC/webrtc.html#L27

But the C# code doesn't support `ontrack` event:
https://github.com/sipsorcery-org/sipsorcery/blob/2e28a633ff675915d3e593cab338580f01a76122/src/net/WebRTC/IRTCPeerConnection.cs#L411-L420

What is the alternative then? My goal is to get the new track from remote and get audio out of it.

**Comment by ChristopheI** [comment]
in RTPSession,you have the event `OnRtpPacketReceivedByIndex`, You can then do something like that
``` cs
        private void RtcPeerConnection_OnRtpPacketReceivedByIndex(int index, System.Net.IPEndPoint remoteEndPoint, SDPMediaTypesEnum mediaType, RTPPacket rtpPacket)
        {
            lock (lockDisposed)
            {
                if (disposed)
                    return;

                // Check if we have received AUDIO
                if (mediaType == SDPMediaTypesEnum.audio)
                {
                    (Boolean newTrack, var audioStreamTrack) = GetOrCreateRemoteAudioStreamTrack(index);
                    audioStreamTrack?.GotRTPacket(rtpPacket.GetBytes());
                }
                // Check if we have received VIDEO
                else if (mediaType == SDPMediaTypesEnum.video)
                {
                    (Boolean newTrack, var videoStreamTrack) = GetOrCreateRemoteVideoStreamTrack(index);
                    videoStreamTrack?.GotRTPacket(rtpPacket.GetBytes());
                }
            }
        }
```

Implement your own logic in `GetOrCreateRemoteAudioStreamTrack / GetOrCreateRemoteVideoStreamTrack` to know if it's a new track or not and then raise your `ontrack` event
