### ISSUE TITLE
Getting `profile-level-id` in `OnVideoFormatsNegotiated`

### ISSUE THREAD

**Issue by lostmsu** [sipsorcery-org/sipsorcery#985]
I am having issues with Firefox peer, probably because it only supports baseline H.264 profile.

I could tune down my encoder to provide that, but the issue is that on the SIPSorcery side `OnVideoFormatsNegotiated` does not include H.264 profile information from the SDP.

If that's not supported yet, I could probably contribute a simple workaround if somebody points me where to start.

**Comment by ChristopheI** [comment]
You can provide profile information like this:
new VideoFormat(VideoCodecsEnum.H264, Rainbow.Medias.Helper.H264_FORMATID, VideoFormat.DEFAULT_CLOCK_RATE, "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"),

And use this VideoFormat in the negotation.
So you can ensure to have only the profile you want

Could you share the profile you want to use ?
I'm trying to support H264 but I cannot have a correct video (input or output) ... 
In output (from sIPSorcery) nothing is display in Chorme/Edge/Firefox ...
In input, I have big artefact ... Perhaps it's related to https://github.com/sipsorcery-org/sipsorcery/commit/6608c1debf09b48960a9b744b429ed489295d650 ?
