### ISSUE TITLE
`NullReferenceException` in `GotStunResponse`

### ISSUE THREAD

**Issue by lostmsu** [sipsorcery-org/sipsorcery#987]
I just added https://www.metered.ca/tools/openrelay/ to get TURN (might be unrelated to the issue though, but that's the only recent change).

The app started crashing with `NullReferenceException` in `GotStunResponse` seemingly caused by `null` `IceServer` in local candidate.

![image](https://github.com/sipsorcery-org/sipsorcery/assets/239520/cd3c8206-9d2e-48ee-96ee-5900bbe76cd8)

A big issue is that there does not seem a way for the app to handle that error.

**Comment by ChristopheI** [comment]
Difficult to reproduce ... 
Could you on your side ? and could you suggest a fix for this ?
Thx

**Comment by lostmsu** [comment]
Turned out it had to do with mDNS resolution failure. E.g. if you set an mDNS resolver and return `null` from it, and this bit of code is hit, then you get the above exception.

The service I linked has a free tier - you can get your TURN server.

In my app I worked it around by never returning `null` from my custom mDNS resolver, and instead returning `IPAddress.None`.

**Comment by sipsorcery** [comment]
I've added a null check for LocalCandidate.IceServer in #1213.
