### ISSUE TITLE
No Incoming Call event from 3cX

### ISSUE THREAD

**Issue by olorunfemidavis** [sipsorcery-org/sipsorcery#989]
Hi @sipsorcery,

I migrated away from another service and integrated Sip Sorcery. 
I am unable to receive incoming calls from extensions and from external. 
Registration is successful and I am able to make an out-going call to external number or to another extension. 

What I have done:
* I set listeners to SIPUDPChannel, SIPTransport Manager (from sample) and also SIPCLient=> muser (also from sample).
* I set the firewall to allow the app to communicate. 
* I used the STUN snippet from the code to get the public IP address. 
I added this public Ip address as the ContactURl in the registration model. 
`var contactURl = SIPURL.ParseSIPURI($"sip:{publicIPAdress4}");
`

Can you please provide a checklist of things to do in order to receive incoming calls?
This can be network or code configurations. 

Also, there is no single event in these:

 ```
 // Wire up the transport layer so incoming SIP requests have somewhere to go.
                SIPTransport.SIPTransportRequestReceived += SIPTransportRequestReceived;

                // Log all SIP packets received to a log file.
                SIPTransport.SIPRequestInTraceEvent += SIPRequestInTraceEvent;
                SIPTransport.SIPRequestOutTraceEvent += SIPRequestOutTraceEvent;
                SIPTransport.SIPResponseInTraceEvent += SIPResponseInTraceEvent;
                SIPTransport.SIPResponseOutTraceEvent += SIPResponseOutTraceEvent;
```

On 3cX Activity Log, I can see the call log as CM503003 408 request Timeout/INVITE from local

**Comment by sipsorcery** [comment]
You're better off not doing the below if your using a server on the Internet

`var contactURl = SIPURL.ParseSIPURI($"sip:{publicIPAdress4}");`

If your contact has a public IP address the server may assume that's your real IP address. If you leave it as a private address the server will know you're behind a NAT and use the source socket which will take account of the port number. WIth your approach where you set the public IP address the port number is assumed to be 5060 but your NAT is likely to be rewriting that to something different.
