### ISSUE TITLE
Not receiving RTP events or reports

### ISSUE THREAD

**Issue by tjma2001** [sipsorcery-org/sipsorcery#991]
I am streaming from my server to the browser using webrtc and FFMPEG. I am trying to figure out if I am getting packet loss indicators from the browser and then trigger a keyframe from my encoding function.

Problem is that I am not getting any callbacks triggered on (peerConnection.OnReceiveReport, peerConnection.OnRtpEvent, peerConnection.OnRtpPacketReceived). I even tried the examples and it doesn't seem to get triggered there either. 

This was fairly easy to do in rust, with the same frontend codebase, so I am certain there must be something here that I can do as well. Has this functionality been disabled? 

![image](https://github.com/sipsorcery-org/sipsorcery/assets/8049309/66d522e4-baef-4ad6-be66-fc57d26ffe05)

**Comment by sipsorcery** [comment]
The RTCP support in this library is incomplete. SIP doesn't use RTCP much whereas WebRTC goes crazy with it.

The RTCP report types supported are [here](https://github.com/sipsorcery-org/sipsorcery/blob/c4d13be8b401c5c06ea179ac248c0bfc9eb6325e/src/net/RTP/RTPSession.cs#L2023).

```
// Only call OnReceiveRTCPPacket for supported RTCPCompoundPacket types
if (buffer[1] == (byte)RTCPReportTypesEnum.SR ||
    buffer[1] == (byte)RTCPReportTypesEnum.RR ||
    buffer[1] == (byte)RTCPReportTypesEnum.SDES ||
    buffer[1] == (byte)RTCPReportTypesEnum.BYE ||
    buffer[1] == (byte)RTCPReportTypesEnum.PSFB ||
    buffer[1] == (byte)RTCPReportTypesEnum.RTPFB)
{
    OnReceiveRTCPPacket(localPort, remoteEndPoint, buffer);
}
```

If the RTCP control packet you're looking for is not one of those then you should still get a warning log message.

RTP events are typically DTMF tones. They're hardly ever used in WebRTC given data channels are a much better way to transmit any kind fo data.
