### ISSUE TITLE
RTP Sequence number cannot be auto generated in all cases.

### ISSUE THREAD

**Issue by moorecj** [sipsorcery-org/sipsorcery#996]
I have run into an issue implementing a webrtc media server where the RTP sequence number must be past along inside the media server. 

A simple example of my setup is this:
remote publisher  --- (webrtc connection 1) ---> media server (Sipsorcery) ---(webrtc connection 2)---> remote consumer

I have found  that auto generating sequence numbers causes remote consumers that are connected to the server to not be aware of packets that are dropped from the remote publishers to the media server.  

As a result  packets that are not actually sequential get marked as sequential and this causes distortion on the consuming client side.

I have created a pull request to try and address this issue.
https://github.com/sipsorcery-org/sipsorcery/pull/995

**Comment by sipsorcery** [comment]
PR was merged.
