### ISSUE TITLE
Registration with SIPWebSocketChannel

### ISSUE THREAD

**Issue by kovenko** [sipsorcery-org/sipsorcery#999]
Hi!
JsSip + Asterisk works.
How to have Registration with SIPWebSocketChannel?

const int SipWebsocketListenPort = 4324;
const string Username = "77_3";
const string Password = "12345";
const string Domain = "wss://77_3@domain.com:4324/ws";
const int Expiry = 120;
SIPTransport _sipTransport;

_sipTransport = new SIPTransport();
_sipTransport.AddSIPChannel(new SIPWebSocketChannel(IPAddress.Any, SipWebsocketListenPort));
var regUserAgent = new SIPRegistrationUserAgent(_sipTransport, Username, Password, Domain, Expiry);
regUserAgent.Start();

Could not resolve wss://77_3@domain.com/ws.

**Comment by sipsorcery** [comment]
When specifying SIP URIs you don't use the HTTP URI format and //. Your URI should be:

`wss:77_3@domain.com:4324`
